### ISSUE TITLE
[Feature] C.H.I.P. support

### ISSUE THREAD

**Issue by juaningan** [mKeRix/room-assistant#1]
Hi,

I guess that C.H.I.P computer is perfect target for this because lowcost, size and BT + Wifi integrated.

I've tried to install but fails when run with:

```
root@chip:~/room-assistant# npm start

> room-assistant@0.1.0 start /root/room-assistant
> node index.js

module.js:457
    throw err;
    ^

Error: Cannot find module '../build/Release/binding.node'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/room-assistant/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm ERR! Linux 4.4.11-ntc
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! room-assistant@0.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the room-assistant@0.1.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the room-assistant package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs room-assistant
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls room-assistant
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/room-assistant/npm-debug.log
```

Maybe because arch armv7l

**Comment by mKeRix** [comment]
I don't have a C.H.I.P. device to test here currently sadly, but this seems to be related directly to the Bluetooth lib. I found another ticket on Github where people discuss this (even if it's for a different lib, it works using the same Linux native package):

https://github.com/sandeepmistry/bleno/issues/140

Maybe check if bluetooth-hci-socket is installed correctly and delete the node_mdules to pull the dependencies again. If I can get the C.H.I.P. to ship to Germany I'll try to debug this further!

**Comment by mabeltron** [comment]
Had a similar problem with a Raspberry Pi Zero W. The raspbian node package only installs 0.10 and the nodesource package doesn't work with an arm6 processor so I installed the arm6 binary, linked node, nodejs and npm into /usr/bin, deleted the contents of roomassistant/node-modules and ran npm install again.

**Comment by mKeRix** [comment]
Thanks for the hint @mabeltron - great findings. I'll close this ticket as I presume this was the issue, if anyone still needs assistance you are free to comment.
