### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by hwikene** [mKeRix/room-assistant#104]
Hi! i am running Home assistant (0.105.5) on Docker on a NUC. 
When i start the room-assistant i get this ```[Nest] 6   - 02/21/2020, 10:14:08 PM   [ClusterService] Command failed: dig +short @231.0.0.333 -p 5353 -4 localhost.
 +14461ms``` What is this error?

i also get these in the log when staring addon: 
```*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>```

**Comment by mKeRix** [comment]
room-assistant uses MDNS for the auto discovery mechanism, which is handled by Avahi on Linux. The warning you can safely ignore, they won’t cause on impact on the functionality. 

As for the dig errors: it seems like the discovery picked up a packet from localhost which it‘s not able to resolve. I think you can also just ignore this for now as it shouldn’t cause any issues (and if it does let me know). I will make sure to handle these cases better in the next version.

**Comment by hwikene** [comment]
Thanks for quck answer.. i am new to this MQTT and am wondering if i am missing something? how do i see if the room-assistant is running ok? does there apper a new entity in Home Assistant? Or do i need to add someting in a config file?
all i have is this in config: 
```
global:
  instanceName: henning
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
bluetoothLowEnergy:
  whitelist:
    - "my bluetooth MAC"
  maxDistance: 7
  tagOverrides:
    "same here":
      name: Cool BLE Tag
      measuredPower: -61```

**Comment by mKeRix** [comment]
Do you have it running as Hass.io add-on or straight up Docker? room-assistant communicates with Home Assistant over MQTT. For Hass.io it can setup the credentials automatically, on other platforms you have to set the options for the Home Assistant Integration.

Once you have setup this MQTT connection for room-assistant and Home Assistant (here with auto discovery enabled), you should see the entities appear automatically. They will be shown under MQTT on the Integrations page of Home Assistant!

**Comment by hwikene** [comment]
I am running MQTT as a integration and this is my config: 
```global:
  instanceName: test
  integrations:
    - bluetoothClassic
    - homeAssistant
bluetoothClassic:
  minRssi: -20
  addresses:
    - 04-F1-3E-5D-D6-B2
homeAssistant:
  mqtturl: 'mqtt://localhost:1883'
  mqttOptions:
    username: username
    password: password```

I have installed Ubuntu server on my NUC and then Docker and HA and get this log and nothing show in my MQTT intergration: 
```[22:14:27] INFO: Setting up Home Assistant configuration
[22:14:27] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
[Nest] 6   - 02/22/2020, 10:14:30 PM   [NestFactory] Starting Nest application...
[Nest] 6   - 02/22/2020, 10:14:30 PM   [InstanceLoader] AppModule dependencies initialized +496ms
[Nest] 6   - 02/22/2020, 10:14:30 PM   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 6   - 02/22/2020, 10:14:30 PM   [InstanceLoader] NestEmitterModule dependencies initialized +1ms
[Nest] 6   - 02/22/2020, 10:14:30 PM   [InstanceLoader] IntegrationsModule dependencies initialized +1ms
[Nest] 6   - 02/22/2020, 10:14:30 PM   [InstanceLoader] DiscoveryModule dependencies initialized +18ms
[Nest] 6   - 02/22/2020, 10:14:30 PM   [InstanceLoader] HomeAssistantModule dependencies initialized +2ms
[Nest] 6   - 02/22/2020, 10:14:30 PM   [InstanceLoader] ClusterModule dependencies initialized +2ms
[Nest] 6   - 02/22/2020, 10:14:30 PM   [InstanceLoader] ScheduleModule dependencies initialized +1ms
[Nest] 6   - 02/22/2020, 10:14:30 PM   [InstanceLoader] BluetoothClassicModule dependencies initialized +3ms
[Nest] 6   - 02/22/2020, 10:14:30 PM   [InstanceLoader] EntitiesModule dependencies initialized +1ms
[Nest] 6   - 02/22/2020, 10:14:31 PM   [RoutesResolver] EntitiesController {/entities}: +22ms
[Nest] 6   - 02/22/2020, 10:14:31 PM   [RouterExplorer] Mapped {/, GET} route +12ms
[Nest] 6   - 02/22/2020, 10:14:31 PM   [HomeAssistantService] Successfully connected to MQTT broker at mqtt://core-mosquitto:1883
[Nest] 6   - 02/22/2020, 10:14:31 PM   [ClusterService] Starting mDNS advertisements and discovery
[Nest] 6   - 02/22/2020, 10:14:31 PM   [NestApplication] Nest application successfully started +6ms
[Nest] 6   - 02/22/2020, 10:14:32 PM   [ClusterService] henning has been elected as leader
[Nest] 6   - 02/22/2020, 10:14:32 PM   [EntitiesService] Refreshing entity states
[Nest] 6   - 02/22/2020, 10:14:48 PM   [ClusterService] Command failed: dig +short @224.0.0.251 -p 5353 -4 localhost.
 +15425ms```

**Comment by mKeRix** [comment]
I think the Bluetooth address should be 04:F1:3E:5D:D6:B2. Otherwise your logs and config look good to me.

**Comment by hwikene** [comment]
Strange... nothing shows in the MQTT integration after i change to ":" isted of "-" and the log dont change:
```
[22:55:00] INFO: Setting up Home Assistant configuration
[22:55:00] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
[Nest] 6   - 02/22/2020, 10:55:02 PM   [NestFactory] Starting Nest application...
[Nest] 6   - 02/22/2020, 10:55:03 PM   [InstanceLoader] AppModule dependencies initialized +385ms
[Nest] 6   - 02/22/2020, 10:55:03 PM   [InstanceLoader] ConfigModule dependencies initialized +2ms
[Nest] 6   - 02/22/2020, 10:55:03 PM   [InstanceLoader] NestEmitterModule dependencies initialized +3ms
[Nest] 6   - 02/22/2020, 10:55:03 PM   [InstanceLoader] IntegrationsModule dependencies initialized +1ms
[Nest] 6   - 02/22/2020, 10:55:03 PM   [InstanceLoader] DiscoveryModule dependencies initialized +19ms
[Nest] 6   - 02/22/2020, 10:55:03 PM   [InstanceLoader] HomeAssistantModule dependencies initialized +2ms
[Nest] 6   - 02/22/2020, 10:55:03 PM   [InstanceLoader] ClusterModule dependencies initialized +2ms
[Nest] 6   - 02/22/2020, 10:55:03 PM   [InstanceLoader] ScheduleModule dependencies initialized +2ms
[Nest] 6   - 02/22/2020, 10:55:03 PM   [InstanceLoader] BluetoothClassicModule dependencies initialized +3ms
[Nest] 6   - 02/22/2020, 10:55:03 PM   [InstanceLoader] EntitiesModule dependencies initialized +2ms
[Nest] 6   - 02/22/2020, 10:55:03 PM   [RoutesResolver] EntitiesController {/entities}: +22ms
[Nest] 6   - 02/22/2020, 10:55:03 PM   [RouterExplorer] Mapped {/, GET} route +11ms
[Nest] 6   - 02/22/2020, 10:55:03 PM   [HomeAssistantService] Successfully connected to MQTT broker at mqtt://core-mosquitto:1883
[Nest] 6   - 02/22/2020, 10:55:03 PM   [ClusterService] Starting mDNS advertisements and discovery
[Nest] 6   - 02/22/2020, 10:55:03 PM   [NestApplication] Nest application successfully started +3ms
[Nest] 6   - 02/22/2020, 10:55:05 PM   [ClusterService] henning has been elected as leader
[Nest] 6   - 02/22/2020, 10:55:05 PM   [EntitiesService] Refreshing entity states
[Nest] 6   - 02/22/2020, 10:55:20 PM   [ClusterService] Command failed: dig +short @224.0.0.251 -p 5353 -4 localhost.
 +14788ms
```

**Comment by mKeRix** [comment]
Ok, then let’s check if room-assistant is trying to configure something. In Home Assistant go to Developer Tools in the sidebar, then go to the MQTT tab and subscribe to the following topic: homeassistant/sensor/+/+/config

Do you see any messages here?

**Comment by hwikene** [comment]
Nope.. no message

**Comment by mKeRix** [comment]
You can start room-assistant with the -v option to get more detailed output of what is happening, maybe that will help show the issue. For Docker that would be `docker run mkerix/room-assistant --digResolver -v`, for docker-compose:

```
version: '3'
services:
  room-assistant:
    [...]
    command: --digResolver -v
```

In the background it's just running `hcitool cc 04:F1:3E:5D:D6:B2 && hcitool rssi 04:F1:3E:5D:D6:B2`. You can also try executing this manually in the shell to see the results. Also make sure that this is the Bluetooth MAC address, in the iPhone settings for example there are multiple MACs listed - not sure which kind of device you want to track.

**Comment by hwikene** [comment]
But i am running it from the room-assistant addon. I have nothing else then Home Assistant innstalled on my Docker.

**Comment by mKeRix** [comment]
Oh sorry, didn't realize it was Hass.io. Do you have access to the host SSH? You should be able to run `hcitool cc 04:F1:3E:5D:D6:B2 && hcitool rssi 04:F1:3E:5D:D6:B2` from there.

**Comment by hwikene** [comment]
Got it to work... it was my mqtt that was fault in my issues. Now i have this in my HA and this is my config. I have now gone in and out of the room and cant get it to change from "Unavailable" to "home" or "not_home".   
```
global:
  instanceName: test
  integrations:
    - bluetoothClassic
    - homeAssistant
bluetoothClassic:
  minRssi: 20
  addresses:
    - '40:9C:28:03:01:CC'
```
<img width="503" alt="Skjermbilde 2020-02-23 kl  21 38 06" src="https://user-images.githubusercontent.com/17985923/75119620-d3f5e200-5684-11ea-9d7b-fd268f3107c7.png">

**Comment by mKeRix** [comment]
Those are both [inquire switches](https://www.room-assistant.io/integrations/bluetooth-classic.html#inquiries-switch), not actual devices. You should see a sensor appear with either the MAC address or the name of the Bluetooth device, that should carry the state. I see you set `minRssi` to 20 - I'm pretty sure you meant to put `minRssi: -20`. Try changing the config like that and see if you get a new entity that works correctly.

**Comment by hwikene** [comment]
I get this message in my log:```
`(node:6) UnhandledPromiseRejectionWarning: Error: Entity with id bluetooth-classic-40-9c-28-03-01-cc already exists!
    at EntitiesService.add (/usr/lib/node_modules/room-assistant/dist/entities/entities.service.js:43:19)
    at BluetoothClassicService.createSensor (/usr/lib/node_modules/room-assistant/dist/integrations/bluetooth-classic/bluetooth-classic.service.js:187:45)
    at async BluetoothClassicService.handleNewRssi (/usr/lib/node_modules/room-assistant/dist/integrations/bluetooth-classic/bluetooth-classic.service.js:86:22)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code ```

**Comment by hwikene** [comment]
Sorry for all spam! found the sensor and it works perfect!!
