### ISSUE TITLE
Not detecting TPlink BLE ?

### ISSUE THREAD

**Issue by atv2016** [mKeRix/room-assistant#1052]
I keep getting these messages, even after adding a BLE dongle from TPlink which is recognised by Linux and connected to the VM:

2/2/2022, 12:42:15 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://core-mosquitto:1883
2/2/2022, 12:42:15 PM - error - ClusterService: Failed to start mdns discovery (dns service error: unknown)
2/2/2022, 12:42:15 PM - info - NestApplication: Nest application successfully started
bleno warning: adapter does not support Bluetooth Low Energy (BLE, Bluetooth Smart).
               Try to run with environment variable:
               [sudo] BLENO_HCI_DEVICE_ID=x node ...
noble warning: adapter does not support Bluetooth Low Energy (BLE, Bluetooth Smart).
               Try to run with environment variable:
               [sudo] NOBLE_HCI_DEVICE_ID=x node ...
2/2/2022, 12:42:16 PM - info - ClusterService: changeme has been elected as leader
2/2/2022, 12:42:16 PM - info - HomeAssistantService: Refreshing entity states

I'll try a different BLE usb dongle, but anything else i can do or any tips

**Comment by atv2016** [comment]
Used different dongle, works fine now. closing.

**Comment by townsmcp** [comment]
@atv2016 which dongle did you go for in the end? Any chance of a link please?
