### ISSUE TITLE
iPhone bluetooth hangs

### ISSUE THREAD

**Issue by andriuskr** [mKeRix/room-assistant#1059]
Started using Room assistant with 7 Raspberry devices, using Bluetooth and BLE services.
Now each morning i have problems with bluetooth on phone. Airpods Pro; Powerbeats Pro headphones and Tesla Bluetooth does not connecting to phone, until i reboot iPhone 12 Pro Max. 
Next morning the same. 

**Environment**
 - room-assistant version: [e.g. 2.0.0]
 - hardware: Raspberry Pi 3,  Raspberry Pi Zero W, Raspberry Pi Zero W 2
 - OS: [e.g. Linux, Windows, macOS]

**Comment by mKeRix** [comment]
Are you using both BT Classic and BLE for the same iPhone? For iPhones I'd recommend to only use BLE with the companion app. I haven't seen any connection trouble with any of our household devices with this setup so far.
