### ISSUE TITLE
error upgrading to 2.0.0 from beta on pi zero

### ISSUE THREAD

**Issue by Alfiegerner** [mKeRix/room-assistant#106]
Hi,

I've been running 2.0.0@beta_6 very successfully and now looking to upgrade to final 2 version.

Running `sudo npm i --global --unsafe-perm room-assistant` on my pi 3s worked fine, but on my pi zeros I am getting the following:

```
pi@pizero_living_room:~ $ sudo npm i --global --unsafe-perm room-assistant
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /usr/local/lib/node_modules/.staging/room-assistant-5fd42786/node_modules/@abandonware/noble
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/room-assistant-5fd42786/node_modules/@abandonware/noble' -> '/usr/local/lib/node_modules/.staging/@abandonware/noble-7a2f9ccc'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-22T03_23_33_368Z-debug.log
```

Clean install works fine.

Not very familiar with Node / npm - could you suggest anything to avoid full re-installs?

Thanks

**Comment by Alfiegerner** [comment]
Looking through the log it looked like 

`sudo npm i --global --unsafe-perm room-assistant`

was attempting to install version 1.1.

I modified the install command to 

`sudo npm i --global --unsafe-perm room-assistant@2.0.0`

and all okay.  Solved.

**Comment by mKeRix** [comment]
As the 1.x versions are not [published on npm](https://www.npmjs.com/package/room-assistant) maybe something was off in the cache or there was a folder called room-assistant with the old version somewhere nearby. Glad to hear you figured out a fix quickly though!
