### ISSUE TITLE
Cluster seems to create an error

### ISSUE THREAD

**Issue by Jens-Wymeersch** [mKeRix/room-assistant#1071]
**Describe the bug**
Basically, I've defined 4 RAs (2 Home Assistant entries and 2 RPIs). 

**To reproduce**
I followed the documentation related to installation and setup of the RA cluster.

**Relevant logs**

2/20/2022, 8:55:02 PM - error - undefined: "global.cluster" is not allowed [Value: {"port":6425,"autoDiscovery":false,"peerAddresses":["XX.YY.ZZ.OO:6425","XX.YY.ZZ.PP:6425","XX.YY.ZZ.QQ:6425"]}]

**Relevant configuration**
Paste the relevant parts of your configuration below.

```global:
   instanceName: Name
   cluster:
     port: 6425
     autoDiscovery: false
     peerAddresses:
        - XX.YY.ZZ.OO:6425
        - XX.YY.ZZ.PP:6425
        - XX.YY.ZZ.QQ:6425
   integrations:
     - homeAssistant
     - bluetoothClassic
     - bluetoothLowEnergy
homeAssistant:
   mqttUrl: 'mqtt://XX.YY.ZZ.VV:1883'
   mqttOptions:
     username: username
     password: pw
bluetoothClassic:
   minRssi: -20
   hciDeviceId: 0
   addresses:
    - 'AA:BB:CC:DD:EE:FF' 

bluetoothLowEnergy:
  timeout: 15
  allowlist:
    - 'dddddddd' # Niki Tile
```

**Expected behavior**
I would like to see the devices in my house to be located near each beacon. 

**Environment**
 - room-assistant version: [e.g. 2.0.0]
 - installation type: NodeJS, Hassio
 - hardware: 3 RPIs and 1 i5 intel (VBox)
 - OS: Linux 

**Additional context**

**Comment by Segar85** [comment]
I believe you have placed the Cluster under the Global. Please move your Cluster outside of Global like this below. It will fix the error. 

global:
  instanceName: Bedroom
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy

cluster:
  autoDiscovery: true
  port: 6425
  peerAddresses:
    - 192.168.10.10:6425
    - 192.168.10.11:6425
