### ISSUE TITLE
Apple Watch BLE tracking

### ISSUE THREAD

**Issue by wtangofoxtrot** [mKeRix/room-assistant#1075]
Is there any way to track apple watches via BLE ? I know the iOs devices require the companion apps and I've tried BT classic but it kills my apple watch 6's battery by 1/3rd so avoiding it.

**Comment by mehdic** [comment]
I need this as well. I dont know how, but espresence does excellent BLE tracking for the apple watch. Is there a way to replicate that functionality here?

**Comment by townsmcp** [comment]
Room Assistant can only track on BT Classic for Apple Watch.

ESPresense might appear to be working on BLE however as soon as you have more than 1 watch of the same model tracking goes out the window as it doesn’t track against a specific device, just against a model

**Comment by mKeRix** [comment]
As @townsmcp mentioned, the ESPresense project just does fingerprinting of public device properties and won't give you a real unique id for devices like the Apple Watch. With the current watchOS version, there does not seem to be a good way to uniquely track Apple Watches. Best you can do from what I've read so far is doing some statistical estimates based on the data, however that isn't really perfect either.

That being said, the room-assistant code could theoretically be extended to support the same fingerprinting mechanism. It would allow those that do not have different models in their household to support their use case. I'm just not sure if we should implement this: the big caveat is that as soon as someone else with the same Watch model walks in/by, the readings will be off and wrong. I'd be interested to hear your opinions on this topic.

**Comment by mehdic** [comment]
Well , in my case, i have an iphone and an apple watch, while my wife has an android and a galaxy watch, so this would be great for me and the people in my situation.

I think this would be a interesting extension for people who would like to track their apple watches. You would just have to document that well so people dont get confused( especially new people coming to the project).

i believe the espresence differentiates between apple watch models as well, so would difertiate a model 7 and a model 6, etc..

**Comment by wtangofoxtrot** [comment]
I agree with @mehdic, My partner and I usually upgrade in steps so we have an apple watch 6 & 7 in the house so tracking devices by a fingerprint would be pretty useful.

**Comment by townsmcp** [comment]
I disagree for Apple Watch users. From what I’ve read on ESPresence, the most recent watches have the same identifiers between versions so ESPresence can’t distinguish between watch 6 and 7 devices. That’s one of the reasons I stayed away from ESPresence being as my wife and I have Watch 6 and the kids have Watch 4 and 5. As much as Bluetooth Classic uses more battery, it works to determine actual devices. I’m sure a fair few households would be in similar positions.

@mKeRix really silly question, can the iOS app not be ported/recompiled to watchOS for BLE tracking? Sorry if I sound stupid on this as I have no idea how much effort is needed to port an iOS app to watchOS

**Comment by wtangofoxtrot** [comment]
@townsmcp thats a bummer but GTK, an applewatch companion app would be nice. I did do BT classic originally but i found the battery life of our watches decreased by 1/3rd which we decided wasnt worth it.

**Comment by mehdic** [comment]
> I disagree for Apple Watch users. From what I’ve read on ESPresence, the most recent watches have the same identifiers between versions so ESPresence can’t distinguish between watch 6 and 7 devices. That’s one of the reasons I stayed away from ESPresence being as my wife and I have Watch 6 and the kids have Watch 4 and 5. As much as Bluetooth Classic uses more battery, it works to determine actual devices. I’m sure a fair few households would be in similar positions.
> 
> 

Well, giving is the choice to use ble tracking for apple watches, doesnt make it mandatory for you or anyone else to use, you can keep using room assistant as you already do, and we would have an extra tracking option that we dont currently have. Its a win / win situation if it is implemented.

**Comment by steuerzentrale** [comment]
I share the same opinion like mehdic, would be really nice to give the user the choice to use BLE for Apple Watches. anyway, I recently installed room assistant and would like to say thank you! it works really nice and is in my opinion the best presence-detection so far.

**Comment by DTTerastar** [comment]
Has anyone every seen an Apple Watch app that directly lets you connect to a BLE device?  I'm searching for an app...

**Comment by bughaver** [comment]
ESPresence can now track all apple devices individually using BLE!

**Comment by wtangofoxtrot** [comment]
still relevant though with the ios app now being unusable unless its always in the foreground this most likely wont be of much use as well

**Comment by lolorc** [comment]
let's add a "irk" section the the bluetoothLowEnergy config section.
something like:

```
bluetoothLowEnergy:
  irk:
   - device1: "IRK1"
   - device2: "IRK2"
```
for every ble addr received: loop through the list of irk and check them as it is done here:
 - https://github.com/ESPresense/ESPresense/blob/e9b13889b1917b7569f3a406560fe80438307bec/lib/BleFingerprint/BleFingerprint.cpp#L135
  - https://gist.github.com/dgrnbrg/9f51c58c96ab3ce8e3d689a77def4ab7#file-irk_tracker-py-L104

atm I'm doing this with an iphone and a python script subscribed to "room-assistant/sensor/#", I get the address from the topic (ex: room-assistant/sensor/ble-001122334455/attributes) I use my irk list to match the address and then publish the payload to a topic my home-assistant is subscribed to.
I'm not used to typescript but I'm pretty sure it's not a big deal to add this feature to room-assistant :-)
(getting the irk is another subject, it's easier with an iphone than a watch)

**Comment by wtangofoxtrot** [comment]
Curious is there a pr tracking this implementation as it’s marked as done which is awesome !
