### ISSUE TITLE
BLE with iOS not working after a few hours.

### ISSUE THREAD

**Issue by DjBac** [mKeRix/room-assistant#1077]
**Describe the bug**
BLE tracking on iOS with the companion app seems to work well, but for instance, if I leave home and come back the next day, then for it to start working I need to re-open the companion app. Is there a setting I could change to avoid this?

**To reproduce**
Steps required to reproduce the issue.

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
```

**Expected behavior**

**Environment**
 - room-assistant version: [v2.19.1
 - installation type: Raspaberry pi Zero W cluster
 - hardware: Raspaberry pi Zero W cluster
 - OS: [e.g. Linux, Windows, macOS]

**Additional context**

**Comment by mKeRix** [comment]
You could try two quick fixes that have helped others in the past: 

1. Turn off auto toggle visibility in the companion app (this feature may be re-written with a more stable approach in the future).
2. Upgrade your room-assistant instances to the beta version.

Other than that, the only required settings are the iOS permissions. I haven't had my iPhone drop from tracking for a few months now.

**Comment by DjBac** [comment]
What would be the best way to upgrade to the beta version (I run it on Zero Ws and Zero 2 Ws)?

**Comment by vistalba** [comment]
> * Turn off auto toggle visibility in the companion app (this feature may be re-written with a more stable approach in the future).

Hi @mKeRix 
Noticed also that BLE with iOS doesn't work well with the companion app.
I now disabled "auto toggle visibility" and will see how it works.
Any idea how to rewrite this function?
As I understood when this is disabled, iOS is always advertising and can also be tracked by others.
This fature should make sure to only advertise when iOS is reciving a BLE message from room-assistant before?
May it could be an idea to define a location (by maps) and just advertise when in a defined range e.g. 500 meters.
