### ISSUE TITLE
Configuration via environment variables

### ISSUE THREAD

**Issue by mateuszdrab** [mKeRix/room-assistant#1094]
I am trying to deploy room assistant as a daemonset on my RPIs via Kubernetes.

I understand that it was possible to configure previous version on RA via env variables - perfect for K8s.
However, it looks like the feature is now removed and the only option is to supply a YAML/JSON file via an environment variable or in the file system. 
This means, supplying separate file for each instance because there is no easy way to override the room name and the default is the hostname, which isn't appropriate for my use case.

Is is possible to at least provide an environment variable based configuration of the room name?

The yaml is uniform for all nodes, except the room name and I could have the environment variable populated from the label of the kubernetes node which bears the desired room name.

Thanks

**Comment by mKeRix** [comment]
room-assistant utilizes [node-config](https://github.com/node-config/node-config) under the hood for its configuration interface in the current version, which does not expose these flat environment variable configurations anymore as you suggested. I think your use case is a valid one though - and while I don't think that exposing all options via env variables is possible anymore due to the complex structure, some basic options can be [made available](https://github.com/node-config/node-config/wiki/Environment-Variables#custom-environment-variables).

I'll take a look at configuring this for a few basic options, such as the room name.

**Comment by mateuszdrab** [comment]
Perfect, looks like quite an easy addition based on the fact node config supports it already.
I think apart from the room name, I'd also recommend exposing the mqtt connection broker details, at least the username and password so that they can also be injected from Kubernetes' native secrets.
I think pretty much the rest of the config should in fact stay unform across nodes.

**Comment by mKeRix** [comment]
I whipped up a quick PR that implements these environment variables. Seems to work fine on my dev machine, but I want to make sure it works on a real world installation before merging & releasing.

**Comment by mateuszdrab** [comment]
That was quick!
I'm about to try, building the container on the pi is taking forever...

**Comment by mateuszdrab** [comment]
Hmm, so is it supposed to work when loading the config from the file but the hostname from the variable?

**Comment by mKeRix** [comment]
I've now tested this successfully on a real world npm installation, as well as my dev machine. In all cases the custom env variable took precedence, even when configuring an instance name both via `RA_GLOBAL_INSTANCE_NAME` and `NODE_CONFIG`. I'll check again by building the Docker image locally to try and reproduce your issue.

**Comment by mKeRix** [comment]
My Docker test was also successful - maybe something is off in your custom image build? I can put out a new release with these changes soon, so you can test it again with the official build.

**Comment by mateuszdrab** [comment]
Yeah, please do. I keep getting the same result locally.

**Comment by mateuszdrab** [comment]
@mKeRix any update on the new release builds?

Thanks

**Comment by mKeRix** [comment]
I'll put out new releases later today!

**Comment by mateuszdrab** [comment]
@mKeRix Thanks! The feature works fine and I've been able to feed in the MQTT creds from a secret plus the instance name from the K8s node label :)
