### ISSUE TITLE
BLE Crashes

### ISSUE THREAD

**Issue by abmantis** [mKeRix/room-assistant#11]
When using BLE, sometimes it crashes (randomly?), with the following:

```
buffer.js:817
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:817:11)
    at Buffer.readInt8 (buffer.js:943:5)
    at Hci.processLeAdvertisingReport (/room-assistant/node_modules/noble/lib/hci-socket/hci.js:643:21)
    at Hci.processLeMetaEvent (/room-assistant/node_modules/noble/lib/hci-socket/hci.js:608:10)
    at Hci.onSocketData (/room-assistant/node_modules/noble/lib/hci-socket/hci.js:479:12)
    at emitOne (events.js:96:13)
    at BluetoothHciSocket.emit (events.js:188:7)
```

**Comment by mKeRix** [comment]
Hey there,

this seems to be a problem with the library used for the BLE scanning. Personally I haven't run into this issue yet. I did find a couple tickets with similar errors [here](https://github.com/sandeepmistry/noble/issues?utf8=%E2%9C%93&q=is%3Aissue%20index%20out%20of%20range%20).

Do you use any custom BLE devices by any chance?

**Comment by abmantis** [comment]
I'm using a Xiaomi Mi Band only.

**Comment by mKeRix** [comment]
So after further analysis I haven't found a way to properly catch this error on our end, this is something that needs to be done by the library we depend on. There seems to be something off with the received BLE advertisements (not necessarily by your device, could be anything really).

I would recommend to run the service using forever as described in the "running as a service" section of the README, but in case you don't want to I added an option that tries to catch these errors without crashing the app:
```json
{
  "app": {
    "unsafe": true
  }
}
```

Give this a whirl - and if you're unhappy with it feel free to reopen this issue.
