### ISSUE TITLE
Device Tracking keeps falling off

### ISSUE THREAD

**Issue by phoniclynx** [mKeRix/room-assistant#1104]
### Discussed in https://github.com/mKeRix/room-assistant/discussions/1103

<div type='discussions-op-text'>

<sup>Originally posted by **phoniclynx** March 13, 2022</sup>
I have been playing around with room-assistant and I've got a few devices with a few quirks and it almost destroys the advantage of using the software for me.

I have 4 devices I am trying to track: Samsung Active 2 Watch. Samsung Active 4 Watch, Tile square and Tile Credit Card. Each seems to have its oddities, and I can't work my way around it.

First my setup. I have 3 devices. Raspberry Pi 4 running Home Assistant Core, Raspberry Pi 3b+, Raspberry Pi 4 all in different rooms and set up as a cluster.

Each device has its sittings appropriate to them:
```
global:
  instanceName: LivingRoom [MyRoom, Kitchen]
  integrations:
    - bluetoothLowEnergy
    - homeAssistant
homeAssistant:
  mqttUrl: mqtt://192.x.x.x:1883
  mqttOptions:
    username: ro....t
    password: 5.....E
  discoveryPrefix: homeassistant

cluster:
  port: 6425
  weight: 100 [75/50]
  maxDistance: 3 #<-- seems to give me an error here
  peerAddresses:
#    - 192.168.x.x:6425
    - 192.168.x.x:6425
    - 192.168.x.x:6425
    - 192.168.x.x:6425
```

All devices have a list of devices as such:
```
bluetoothLowEnergy:
  timeout: 60
  hciDeviceId: 0
  allowlist:
    - c0f542750688
    - 'Galaxy Watch4 (CBAA)'
    - 6a1d37636939
    - 9d41000035d6f4ddba60e7bd8dc491c0-20492-23783
    - 9d41000035d6f4ddba60e7bd8dc491c0-48300-7158
  tagOverrides:
    6a1d37636939:
      name: Denises Watch
    Galaxy Watch4 (CBAA):
      name: Denises Watch Name
    c0f542750688:
      name: Nats Watch
    9d41000035d6f4ddba60e7bd8dc491c0-20492-23783:
      name: Nats Tile Keys
      measuredPower: -42
    9d41000035d6f4ddba60e7bd8dc491c0-48300-7158:
      name: Nats Tile Credit Card
````

[Galaxy Watch 4]
I have found it really hard to find the MAC address for the Watch as the MAC would continuously be different, but it would occasionally display its name at the beginning (captured from logs when could find it):
```
info - BluetoothLowEnergyService: Discovered nearby BLE peripheral Galaxy Watch4 (CBAA) with ID 4c40b0b5fbd7 and RSSI -86
info - BluetoothLowEnergyService: Discovered nearby BLE peripheral Galaxy Watch4 (CBAA) with ID 5001dc6757ce and RSSI -93
info - BluetoothLowEnergyService: Discovered nearby BLE peripheral Galaxy Watch4 (CBAA) with ID 693bca9cba46 and RSSI -89
info - BluetoothLowEnergyService: Discovered nearby BLE peripheral Galaxy Watch4 (CBAA) with ID 4184ef613f87 and RSSI -77
````
It didn't seem to matter how I put it into the config file it wouldn't be picked up. I tried with single quotes, double quotes, no quotes and the software couldn't pick it up as a device. I couldn't use the MAC address as there wasn't a consistent address to use.

[Galaxy Watch 2]
This is an older version of the above watch. It doesn't seem to have the cycling of the MAC address but the address where the name shows up is sometimes different from the one that is listed above in the config files:
```
info - BluetoothLowEnergyService: Discovered nearby BLE peripheral Galaxy Watch Active2(0344) LE with ID c0f542750688 and RSSI -56
info - BluetoothLowEnergyService: Discovered nearby BLE peripheral Galaxy Watch Active2(0344) LE with ID c0f542750688 and RSSI -61
````
Using this MAC address, however, I can seem to track it. But it has a different quirk. If I turn the watch to Airport Mode and back on it will show up in the logs as above. It then connects to the mobile phone and then it disappears from the logs and presence system. It doesn't update the distance and then after a very short while it displays as "not_home". If I turn off the Bluetooth of the mobile phone the devices mostly seem to work as I expect and they can be picked up by the various Clusters. As soon as I turn the Bluetooth back on room-assistant can't seem to see the watch any more.

[Tile Tags] - both
These seem to have a very similar issue. They seem to react in the same way as the Galaxy Watch 2 where if you have it connected to the Tile App on the mobile it just disappears from room-assistant. The caveat of these devices is that it only seems to show up when you press the button on the Tile itself, which is normally used to locate the mobile phone through the Tile app. If you remove the app or turn off Bluetootn then connect it in one location move it to another far away location in the same cluster group / different raspberry pi, it doesn't update. No distance update and no room presence updates.
```
[Tile Keys]
info - BluetoothLowEnergyService: Discovered nearby BLE peripheral 9d41000035d6f4ddba60e7bd8dc491c0-20492-23783 with ID 9d41000035d6f4ddba60e7bd8dc491c0-20492-23783 and RSSI -82
info - BluetoothLowEnergyService: Discovered nearby BLE peripheral 9d41000035d6f4ddba60e7bd8dc491c0-20492-23783 with ID 9d41000035d6f4ddba60e7bd8dc491c0-20492-23783 and RSSI -64
info - BluetoothLowEnergyService: Discovered nearby BLE peripheral 9d41000035d6f4ddba60e7bd8dc491c0-20492-23783 with ID 9d41000035d6f4ddba60e7bd8dc491c0-20492-23783 and RSSI -51
```
```
[Tile Credit Card]
info - BluetoothLowEnergyService: Discovered nearby BLE peripheral 9d41000035d6f4ddba60e7bd8dc491c0-48300-7158 with ID 9d41000035d6f4ddba60e7bd8dc491c0-48300-7158 and RSSI -60
info - BluetoothLowEnergyService: Discovered nearby BLE peripheral 9d41000035d6f4ddba60e7bd8dc491c0-48300-7158 with ID 9d41000035d6f4ddba60e7bd8dc491c0-48300-7158 and RSSI -60
info - BluetoothLowEnergyService: Discovered nearby BLE peripheral 9d41000035d6f4ddba60e7bd8dc491c0-48300-7158 with ID 9d41000035d6f4ddba60e7bd8dc491c0-48300-7158 and RSSI -55

```

Unfortunately, this means they are all not very useful to me. The Tile app does update the Tile and communicates with the Tile inside the app and can tell me where it is and how far away it is, but room-assistant doesn't keep in contact with the Tile after it's initial discovery.

How can I fix these issues?
</div>

**Comment by mKeRix** [comment]
Unfortunately, I don't own any of these devices, so I can't test this, but my guesses would be:

- Galaxy Watch 4 -> With a rotating MAC address you'll either have to get it to send iBeacon signals (there is a [thread on reddit](https://www.reddit.com/r/homeassistant/comments/r5xfpf/using_galaxy_watch_4_as_a_beacon_in_espresense/) for this specific model) or to use [Bluetooth Classic](https://www.room-assistant.io/integrations/bluetooth-classic.html) mode. With Bluetooth Classic, you will have to enter the permanent, real Bluetooth MAC address as shown in your watch settings. The random ones room-assistant sees will not work for that setup either.
- Galaxy Watch 2 -> Some devices stop advertising as soon as there is an active connection. Sometimes this also a setting that you can toggle. If not, you could probably get the same solutions mentioned above working here as well.
- Tile tags -> I believe other users have reported that you will need to use these without pairing them to your phone, otherwise they shut off advertisements when connected as you reported.

**Comment by phoniclynx** [comment]
I found an app that broadcasts an iBeacon for the Galaxy Watch 2 that broadcasts all the time. However, now I have the issue of the application constantly just dropping off all the time.. It connects it to see it.. I don't move for 10 mins.. but within 2 mins it says it is no longer there or "not_home"

**Comment by phoniclynx** [comment]
I have posted a bit more info here: https://github.com/mKeRix/room-assistant/discussions/1103

**Comment by phoniclynx** [comment]
Bump
