### ISSUE TITLE
Document MQTT payload for Classic BT Inquiries Switch

### ISSUE THREAD

**Issue by Matsuo3rd** [mKeRix/room-assistant#1111]
**Describe the bug**
How can a non-HA users (eg. openHab) find BT Classic Inquiries Switch MQTT payload?

**Expected behavior**
Please document what is the expected payload for a MQTT command switching ON and OFF the BT Classic Inquiries Switch present at Topic "room-assistant/entity/WYZ/switch/bluetooth-classic-inquiries-switch"

Would also be great if someone could document it in this comment. Thanks.

**Comment by mKeRix** [comment]
Are you using room-assistant with the pure `mqtt` integration or the `homeAssistant` integration + the compatibility layer in OpenHAB? The former actually doesn't support inputs yet, so this would be an enhancement request. For the latter, it expects a payload of `on` or `off` in the `room-assistant/switch/<YOUR-ENTITY>/command` topic.

**Comment by Matsuo3rd** [comment]
Answering my own question after looking at the source code.
See: [https://github.com/mKeRix/room-assistant/issues/151](https://github.com/mKeRix/room-assistant/issues/151)

1. Home-Assistant Integration is mandatory for the BT Classic Inquiry Switch to operate
2. Look at "home assistant/switch/+/+/config" topic to fetch switch command_topic value (use MQTT Explorer)
3. Use following MQTT command in order to toggle OFF switch (replace topic with your own command_topic in step number 2)
mosquitto_pub -h 127.0.0.1 -t room-assistant/switch/front-door-bluetooth-classic-inquiries-switch/command  -m "off"
