### ISSUE TITLE
Website have incorrect content-type on various pages

### ISSUE THREAD

**Issue by kvisle** [mKeRix/room-assistant#112]
```
~$ curl -sI https://www.room-assistant.io/integrations/bluetooth-classic | grep content-type
content-type: application/octet-stream
```

This causes my browser to download the web page in stead of viewing it.

**Comment by mKeRix** [comment]
Thanks for the hint, didn’t notice this on Chrome and Safari when testing. I guess this is caused by the clean URLs plugin, GitHub pages seems to set the MIME type based on the extension. Will take care of it!
