### ISSUE TITLE
MQTT messages continuing long after switch turned off

### ISSUE THREAD

**Issue by gmalbert** [mKeRix/room-assistant#113]
**Describe the bug**
After turning off the switch in HA, the mqtt messages continue and don't stop. There's no way to stop the mqtt messages other than stopping the service. 
**To reproduce**
Steps required to reproduce the issue.

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
```

**Expected behavior**
In 2.0 beta up to and including 5, the HA switch stopped RA from continuing to check whether the devices are still around. This was the expected behavior and (I believe) the reason for the HA switch in the first place. However, as of beta 6, even turning off the switch does not stop the messages from continuing until the service is actually stopped.

There is a good argument that showing not_home should not mean that RA should stop searching. However, there are valid use cases (like being gone for the day) in which it would be helpful to turn off the continual checks until a certain time or trigger.
**Environment**
 - room-assistant version: [e.g. 2.0.0]
 - installation type: [e.g. NodeJS, Docker, Hass.io]
 - hardware: [e.g. Raspberry Pi Zero W, NUC]
 - OS: [e.g. Linux, Windows, macOS]
Node JS on Raspberry pi zero w. The issue occurs on betas 6 and above, including the full 2.0.0 release on both NUC and the raspberry pi zero w.
**Additional context**

I had referenced this issue just before RA went to the 2.0.0 release, so I'm reposting here since the previous issue had been closed upon release. [https://github.com/mKeRix/room-assistant/issues/102#issuecomment-589779775](url)

**Comment by mKeRix** [comment]
Thanks for bringing this to my attention again! It got lost under all the other topics. I will restore the old behavior in the sense that the `last_updated_at` will not be set anymore after the sensor has gone `not_home` asap.

**Comment by gmalbert** [comment]
@mKeRix working perfectly. Thank you for the quick update!
