### ISSUE TITLE
Track room-assistant companion app via ESPHome

### ISSUE THREAD

**Issue by scout1256** [mKeRix/room-assistant#1137]
Which kind of uuid does room-assistant companion app use?

I'm trying to use ESPHome to track iPhone's room-assistant, using
(https://esphome.io/components/binary_sensor/ble_presence.html).
I tried service uuid and ibeacon uuid neither work.
pls help!!

**Comment by michaelblight** [comment]
I too am struggling to work this out. With the companion app installed on my phone, and nRF Connect installed on my iPad, the iPad can see 'room-assistant-companion', but it doesn't list the UUID to confirm it's the room-assistant Device ID. With Locate Beacon installed on the iPad, and adding the Device ID, that app does not find it.

In ESPHome, if I log beacon data, I can see one with Apple's manufacturer code, but I don't know what it is. If I turn off bluetooth on my iPhone and iPad, and take the batteries out of my two Air Tags, it's still broadcasting. But the point is, when bluetooth is on and enabled for my iPhone and iPad, I'm not logging any more than that one unknown beacon.

**Comment by michaelblight** [comment]
Looking at lines 155 and 510 of [bluetooth-low-energy.service.ts](https://github.com/mKeRix/room-assistant/blob/85981ee3b031be3bf870e43f45fc4726275eb06c/src/integrations/bluetooth-low-energy/bluetooth-low-energy.service.ts), room-assistant looks for any iBeacon, and then reads COMPANION_APP_SERVICE_UUID, COMPANION_APP_CHARACTERISTIC_UUID (defined on lines 34-35) to get the Device ID as shown in the app.

I've not seen any ESPHome code that reads data without connecting, and writing is seriously testing me.

I might be mistaken, but it looks to me like the room-assistant companion provides a BLE beacon, but not an "iBeacon". According to Apple:
> Q: Can I use an iOS device to issue iBeacon advertisements while my app is in the
> background?
> A: No. For an iOS device to issue iBeacon advertisements , the app requesting this functionality
> must be frontmost, with the screen turned on and the device unlocked.

However the room-assistant companion app clearly works in the background.
