### ISSUE TITLE
HA entity is not created...complete silence over mqtt

### ISSUE THREAD

**Issue by dedepene** [mKeRix/room-assistant#115]
**Describe the bug**
Room-assistant is not sending out mqtt updates. Apparently, it does register my iBeacon but it then doesn't create an entity and never updates status over mqtt :( What am I doing wrong?
**To reproduce**
Steps required to reproduce the issue.

**Relevant configuration**
Paste the relevant parts of your configuration below.

```global:
  instanceName: the-office
  integrations:
    - bluetoothLowEnergy
    - homeAssistant

homeAssistant:
  mqttUrl: mqtt://192.168.1.195:1883
  mqttOptions:
    username: xxxxxxx
    password: xxxxxxx

bluetoothLowEnergy:
  whitelist:
    - a50693a4e24fb1afcfc6eb07647825-5-6
    - 5548a6779994
    - e2c56db5dffb48d2b060d0f5a71096e0-0-0
  channel: 'room_presence'
  onlyIBeacon: true

```

**Expected behavior**
expected to update entity.

**Environment**
 - room-assistant version: 2.0.0
 - installation type: [e.g. NodeJS, Docker, Hass.io]
 - hardware: Raspberry Pi Zero W
 - OS: [e.g. Linux, Windows, macOS]

**Additional context**
```
root@raspberrypi:/home/pi/room-assistant# /opt/nodejs/bin/room-assistant --verbose
[Nest] 574   - 2020-02-27 11:25:20   [ClusterService] Cannot find module '../build/Release/dns_sd_bindings'
Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/nodejs/lib/node_modules/room-assistant/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
[Nest] 574   - 2020-02-27 11:25:24   [NestFactory] Starting Nest application... +3878ms
[Nest] 574   - 2020-02-27 11:25:28   [InstanceLoader] AppModule dependencies initialized +3244ms
[Nest] 574   - 2020-02-27 11:25:28   [InstanceLoader] ConfigModule dependencies initialized +15ms
[Nest] 574   - 2020-02-27 11:25:28   [InstanceLoader] NestEmitterModule dependencies initialized +13ms
[Nest] 574   - 2020-02-27 11:25:28   [InstanceLoader] IntegrationsModule dependencies initialized +13ms
[Nest] 574   - 2020-02-27 11:25:28   [InstanceLoader] DiscoveryModule dependencies initialized +92ms
[Nest] 574   - 2020-02-27 11:25:28   [InstanceLoader] HomeAssistantModule dependencies initialized +16ms
[Nest] 574   - 2020-02-27 11:25:28   [InstanceLoader] ClusterModule dependencies initialized +13ms
[Nest] 574   - 2020-02-27 11:25:28   [InstanceLoader] ScheduleModule dependencies initialized +15ms
[Nest] 574   - 2020-02-27 11:25:28   [InstanceLoader] BluetoothLowEnergyModule dependencies initialized +22ms
[Nest] 574   - 2020-02-27 11:25:28   [InstanceLoader] EntitiesModule dependencies initialized +12ms
[Nest] 574   - 2020-02-27 11:25:28   [RoutesResolver] EntitiesController {/entities}: +148ms
[Nest] 574   - 2020-02-27 11:25:28   [RouterExplorer] Mapped {/, GET} route +84ms
[Nest] 574   - 2020-02-27 11:25:29   [HomeAssistantService] Successfully connected to MQTT broker at mqtt://192.168.1.195:1883
[Nest] 574   - 2020-02-27 11:25:30   [ClusterService] Dependency "mdns" was not found, automatic discovery has been disabled. You will have to provide the addresses of other room-assistant nodes manually in the config.
[Nest] 574   - 2020-02-27 11:25:30   [NestApplication] Nest application successfully started +22ms
[Nest] 574   - 2020-02-27 11:25:30   [ClusterService] the-office has been elected as leader
[Nest] 574   - 2020-02-27 11:25:30   [EntitiesService] Refreshing entity states
[Nest] 574   - 2020-02-27 11:25:33   [BluetoothLowEnergyService] Discovered new BLE peripheral fda50693a4e24fb1afcfc6eb07647825-5-6 with ID fda50693a4e24fb1afcfc6eb07647825-5-6 and RSSI -47
[Nest] 574   - 2020-02-27 12:20:13   [BluetoothLowEnergyService] Discovered new BLE peripheral 50765cb7d9ea4e2199a4fa879613a492-59716-24897 with ID 50765cb7d9ea4e2199a4fa879613a492-59716-24897 and RSSI -90

```

**Comment by Gio76** [comment]
**Describe the bug**
Same issue for me. When I first installed the addon everything worked fine but only for a few hours. My smartphone and Apple Watch at first appeared in the MQTT integration but after deleting and reinstalling the Room-Assistant addon, they completely disappeared.

**Relevant configuration**

```
global:
  instanceName: office
  integrations:
    - homeAssistant
    - bluetoothClassic
bluetoothClassic:
  minRssi: -20
  addresses:
    - '38:C9:XX:XX:XX:XX'
    - '3C:2E:XX:XX:XX:XX'
```

**Expected behaviour**
Expected devices to update every 6 seconds

**Environment**
- room-assistant version: 2.0.1
- installation type: Docker, Hass.io
- hardware: Macbook Pro
- OS: Ubuntu Mate

**Comment by mKeRix** [comment]
@dedepene From the logs I can't see any of the devices you have in your whitelist being discovered by room-assistant. Are the IDs correct as noted in the config? Does executing "sudo hcitool lescan" (while room-assistant is not running) list your iBeacons?

@Gio76 I think your bug is unrelated, as it it's about Bluetooth Classic and not BLE. Did you try rebooting your host machine? Could anything else be using the Bluetooth adapter? What do the logs say?

**Comment by dedepene** [comment]
> @dedepene From the logs I can't see any of the devices you have in your whitelist being discovered by room-assistant. Are the IDs correct as noted in the config? Does executing "sudo hcitool lescan" (while room-assistant is not running) list your iBeacons?
> 
Duh! My bad. And I did copy into my config from the list of discovered devices - must have copied the wrong entry! Thanks!

**Comment by Gio76** [comment]
> @Gio76 I think your bug is unrelated, as it it's about Bluetooth Classic and not BLE. Did you try rebooting your host machine? Could anything else be using the Bluetooth adapter? What do the logs say?

@mKeRix My apologies for 'highjacking' this ticket. Next tie I'll open a new one. Rebooting the actual host machine did solve the problem... let's see how long that lasts. I am running room-assistant as a hassio addon so I am unable to see any specific logs

**Comment by mKeRix** [comment]
@Gio76 You can't see the verbose logs unfortunately, but you should still be able to see the normal add-on logs at the bottom of the add-on page. :)

**Comment by Gio76** [comment]
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:50:01] INFO: Setting up Home Assistant configuration
[15:50:01] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
[Nest] 176   - 02/28/2020, 3:50:02 PM   [IntegrationsModule] Loading integrations: home-assistant, bluetooth-classic
[Nest] 176   - 02/28/2020, 3:50:02 PM   [NestFactory] Starting Nest application... +128ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] AppModule dependencies initialized +88ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] NestEmitterModule dependencies initialized +0ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] IntegrationsModule dependencies initialized +0ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] DiscoveryModule dependencies initialized +5ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] HomeAssistantModule dependencies initialized +1ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] ClusterModule dependencies initialized +0ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] BluetoothClassicModule dependencies initialized +1ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] EntitiesModule dependencies initialized +0ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [RoutesResolver] EntitiesController {/entities}: +6ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [RouterExplorer] Mapped {/, GET} route +3ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [HomeAssistantService] Successfully connected to MQTT broker at mqtt://core-mosquitto:1883
[Nest] 176   - 02/28/2020, 3:50:02 PM   [ConfigService] Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
[Nest] 176   - 02/28/2020, 3:50:02 PM   [ClusterService] Starting mDNS advertisements and discovery
[Nest] 176   - 02/28/2020, 3:50:02 PM   [NestApplication] Nest application successfully started +1ms
[Nest] 176   - 02/28/2020, 3:50:04 PM   [ClusterService] office has been elected as leader
[Nest] 176   - 02/28/2020, 3:50:04 PM   [EntitiesService] Refreshing entity states
[Nest] 176   - 02/28/2020, 3:50:18 PM   [ClusterService] Command failed: dig +short @224.0.0.251 -p 5353 -4 localhost.
 +14180ms`

**Comment by Gio76** [comment]
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:50:01] INFO: Setting up Home Assistant configuration
[15:50:01] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
[Nest] 176   - 02/28/2020, 3:50:02 PM   [IntegrationsModule] Loading integrations: home-assistant, bluetooth-classic
[Nest] 176   - 02/28/2020, 3:50:02 PM   [NestFactory] Starting Nest application... +128ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] AppModule dependencies initialized +88ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] NestEmitterModule dependencies initialized +0ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] IntegrationsModule dependencies initialized +0ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] DiscoveryModule dependencies initialized +5ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] HomeAssistantModule dependencies initialized +1ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] ClusterModule dependencies initialized +0ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] BluetoothClassicModule dependencies initialized +1ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [InstanceLoader] EntitiesModule dependencies initialized +0ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [RoutesResolver] EntitiesController {/entities}: +6ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [RouterExplorer] Mapped {/, GET} route +3ms
[Nest] 176   - 02/28/2020, 3:50:02 PM   [HomeAssistantService] Successfully connected to MQTT broker at mqtt://core-mosquitto:1883
[Nest] 176   - 02/28/2020, 3:50:02 PM   [ConfigService] Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
[Nest] 176   - 02/28/2020, 3:50:02 PM   [ClusterService] Starting mDNS advertisements and discovery
[Nest] 176   - 02/28/2020, 3:50:02 PM   [NestApplication] Nest application successfully started +1ms
[Nest] 176   - 02/28/2020, 3:50:04 PM   [ClusterService] office has been elected as leader
[Nest] 176   - 02/28/2020, 3:50:04 PM   [EntitiesService] Refreshing entity states
[Nest] 176   - 02/28/2020, 3:50:18 PM   [ClusterService] Command failed: dig +short @224.0.0.251 -p 5353 -4 localhost.
 +14180ms
```

**Comment by Gio76** [comment]
The above logs have always been the same...both when the entities worked and didn't work.
