### ISSUE TITLE
Devices are not registering as closest to the correct node

### ISSUE THREAD

**Issue by dcgrove** [mKeRix/room-assistant#116]
**Describe the bug**
Devices are not registering as closest to the correct nodes. Detection seems to degrade over time. Devices will be registered to a node that is across the house, while sitting three feet from a node.

**To reproduce**
Start room-assistant on all nodes, let time pass.

**Relevant configuration**
All configs for the three rPi's can be found at link.

[link to configs](https://www.dropbox.com/sh/ivoy3qmwiyfrk6n/AADQ4DHrEQogUwE6FHhnuBcIa?dl=0)

**Expected behavior**
Devices are registered to the closest node. 

**Environment**
 - room-assistant version: 2.0
 - installation type: Node
 - hardware: Office - Pi3b+, MBR: Pi3B+, FamLR: Pi zero W
 - OS: Raspbian Buster. Only other software installed is tmux

**Additional context**
I have piped the output of running in verbose mode all day to the log files in the dropbox link above.  I am also getting these two errors pretty consistently.
`
[Nest] 24576   - 02/27/2020, 9:10:26 PM   [BluetoothClassicService] Command failed: hcitool cc "88:64:40:7B:60:89" && hcitool rssi "88:64:40:7B:60:89"
Can't create connection: Input/output error
Not connected.

[Nest] 872   - 02/27/2020, 9:11:09 PM   [BluetoothClassicService] spawn ENOMEM
`

The first error has happened on all three nodes, the second error has now been happening on the pizero and the Pi3B+ in the office. 

Htop from OfficePi:
![image](https://user-images.githubusercontent.com/22239966/75507216-103b8200-59a6-11ea-8e3f-8f8121d388e1.png)

Htop from FamLR Pi zero:
![image](https://user-images.githubusercontent.com/22239966/75507242-277a6f80-59a6-11ea-8d2f-fe05cb6493f3.png)

Rebooting the officepi node resolved the issue of the device not registering correctly

**Comment by mKeRix** [comment]
Something is quite weird here - the room-assistant process should definitely not be using 63% of memory. On my Pi 3 it uses around 5% as comparison. Plus, the `hcitool cc "undefined"` should not happen.

How reliable is your network between the nodes? I can see that the devices are often dropping out of the cluster and being re-added. I think this may add to your problem of the devices not being registered correctly. Based on the logs I would first try two things (as mentioned under [cluster troubleshooting](https://www.room-assistant.io/guide/cluster.html#troubleshooting)): set the `quorum` to `2` and manually configure all `peerAddresses`.

**Comment by dcgrove** [comment]
Thanks, I will set up the cluster options today and see if that helps.  Here is the Wi-Fi connection info for both nodes.  The office node is hardwired.  The first screenshot is the famLR node and the second is the MBR node.  Both are connecting to UniFi Ac-lite access points. 

![943C3E80-1FD9-4ED4-9A1D-DEE798DB4B6D](https://user-images.githubusercontent.com/22239966/75550513-b19ef400-59f7-11ea-9d6e-6d68ccc7b398.png)
![A3524EDA-9FB3-4D83-912A-2F6BBC049D42](https://user-images.githubusercontent.com/22239966/75550518-b2d02100-59f7-11ea-87c3-2315e19688c6.png)

**Comment by dcgrove** [comment]
Good morning, it appears that across my three nodes, the famLR node is the only one that is correctly registering this morning after making the config changes you recommended yesterday. Please see the snippets of console output showing the errors I am getting on the officePi and MBRpi nodes below. All console output and config files can be found at the dropbox link below.

MBRpi
`[Nest] 9696   - 02/29/2020, 7:10:32 AM   [BluetoothClassicService] Querying for RSSI of E4:50:EB:0C:DA:91 using hcitool
[Nest] 9696   - 02/29/2020, 7:10:32 AM   [BluetoothClassicService] Received RSSI of -28.7 for 88:64:40:7B:60:89 from Kitchen
[Nest] 9696   - 02/29/2020, 7:10:36 AM   [BluetoothClassicService] Querying for RSSI of 88:64:40:7B:60:89 using hcitool
[Nest] 9696   - 02/29/2020, 7:10:38 AM   [BluetoothClassicService] Query of E4:50:EB:0C:DA:91 took too long, resetting hci0
[Nest] 9696   - 02/29/2020, 7:10:38 AM   [BluetoothClassicService] Command failed: hciconfig hci0 reset
Can't down device hci0: Operation not permitted (1)
 +92ms
[Nest] 9696   - 02/29/2020, 7:10:42 AM   [BluetoothClassicService] Query of 88:64:40:7B:60:89 took too long, resetting hci0
[Nest] 9696   - 02/29/2020, 7:10:42 AM   [BluetoothClassicService] Command failed: hciconfig hci0 reset
Can't down device hci0: Operation not permitted (1)
 +92ms
[Nest] 9696   - 02/29/2020, 7:10:42 AM   [BluetoothClassicService] Querying for RSSI of E4:E4:AB:D9:AB:09 using hcitool
`
OfficePi
` E4:E4:AB:D9:AB:09 using hcitool
[Nest] 1016   - 02/29/2020, 7:13:48 AM   [BluetoothClassicService] spawn ENOMEM
[Nest] 1016   - 02/29/2020, 7:13:49 AM   [BluetoothClassicService] Received RSSI of -27.6 for F0:C3:71:2B:8A:74 from Kitchen
[Nest] 1016   - 02/29/2020, 7:13:54 AM   [BluetoothClassicService] Querying for RSSI of C8:3C:85:67:9E:86 using hcitool
[Nest] 1016   - 02/29/2020, 7:13:54 AM   [BluetoothClassicService] spawn ENOMEM
[Nest] 1016   - 02/29/2020, 7:14:00 AM   [BluetoothClassicService] Querying for RSSI of F0:C3:71:2B:8A:74 using hcitool
[Nest] 1016   - 02/29/2020, 7:14:00 AM   [BluetoothClassicService] spawn ENOMEM
[Nest] 1016   - 02/29/2020, 7:14:01 AM   [BluetoothClassicService] Received RSSI of -27.6 for 88:64:40:7B:60:89 from Kitchen
[Nest] 1016   - 02/29/2020, 7:14:06 AM   [BluetoothClassicService] Querying for RSSI of E4:50:EB:0C:DA:91 using hcitool
[Nest] 1016   - 02/29/2020, 7:14:06 AM   [BluetoothClassicService] spawn ENOMEM
[Nest] 1016   - 02/29/2020, 7:14:12 AM   [BluetoothClassicService] Querying for RSSI of 88:64:40:7B:60:89 using hcitool
[Nest] 1016   - 02/29/2020, 7:14:12 AM   [BluetoothClassicService] spawn ENOMEM
`
![image](https://user-images.githubusercontent.com/22239966/75608218-360a7900-5ac3-11ea-8568-9f45cef130af.png)


https://www.dropbox.com/sh/ivoy3qmwiyfrk6n/AADQ4DHrEQogUwE6FHhnuBcIa?dl=0

**Comment by mKeRix** [comment]
Could you try running running the following command on all of your Pis to give room-assistant the permission to reset your HCI device?

```shell
sudo setcap cap_net_admin+eip $(eval readlink -f `which hciconfig`)
```

As far as the ENOMEM errors on your Office Pi go I'm still not sure. If it keeps happening even after the above fix I will have to take a deep look at what could be leaking memory.

**Comment by dcgrove** [comment]
Hello, I am getting the ENOMEM error on the officepi and Famlr node this morning. The MBRpi node was running along fine. I have run the command above that you suggested and rebooted all three nodes for a fresh start. Do you need the console output to troubleshoot? I am running room-assistant in a tmux window, do you think the memory leak could be caused by that? I can open ssh-terminals from my server and leave them open to eliminate tmux from the equation if you think it would be helpful.

**Comment by mKeRix** [comment]
I don't think it's related to tmux, at least I can't think of a reason why it would be. I will try to write a special build for you to help catch this memory leak, it might take a few days though.

In the mean time: If you setup room-assistant [as a service](https://www.room-assistant.io/guide/quickstart-pi-zero-w.html#making-sure-it-always-runs) you can periodically restart it with cron. To do this run `sudo crontab -e` and something like this to the file:

```
0 3 * * * systemctl restart room-assistant
```

This would restart it everyday at 3am. Additional plus: you can look at the past logs of room-assistant easily with `journalctl -u room-assistant.service`.

**Comment by Alfiegerner** [comment]
In case I can be of any help, I've been seeing the hcitool scan for 'undefined' too.

I haven't observed the out of memory error, but that maybe because I already reboot the each PI every night.  If you me help replicating I can turn off the nightly reboot.

**Comment by dcgrove** [comment]
@mKeRix any luck on that build to capture the memory leak?

**Comment by mKeRix** [comment]
@dcgrove Unfortunately was busy with other stuff so far, will try to work on it tomorrow!

**Comment by mKeRix** [comment]
I built a special version that will create a heap-dump file and exit when it sees ENOMEM. It would be great if you could install that on at least one of your affected Pis, run it and wait for an ENOMEM. The name of the dump will be logged, you can find it in the working directory. Then just add it to your Dropbox for inspection and let me know. You download it from here:

[room-assistant-2.1.1.tar.gz](https://github.com/mKeRix/room-assistant/files/4314409/room-assistant-2.1.1.tar.gz)

Once it's on your Pi you can install it with: `sudo npm i --global --unsafe-perm room-assistant-2.1.1.tar.gz`

**Comment by dcgrove** [comment]
@mKeRix Thank you for this! I have it installed on all three of my pi's. I will let you know when it produces the logs.

**Comment by dcgrove** [comment]
Good morning, the heap-dump files for all three rpi's are in the dropbox folder. Thanks for putting the effort into this!

**Comment by mKeRix** [comment]
Thanks for providing the heap dumps - I just looked over them. Unfortunately they all seem quite normal to me, at least from the first look. The memory size that was occupied according to the dump was between 15 and 26 MB, which shouldn't even be able to bring down a Pi W. Can I ask how you installed NodeJS on your Pis? Through the methods that are also shown in the quickstart guides (i.e. [NodeSource](https://github.com/nodesource/distributions/blob/master/README.md) or the [Pi Zero install script](https://github.com/sdesalas/node-pi-zero)) or something different? What does `node -v` say?

**Comment by dcgrove** [comment]
Hello, I used the instructions in the quickstart guides to install Node. I have turned off the Pi3b+ and Pi Zero that were connected via wifi as it was causing serious issues with the stability of my network. Currently the only nodes I have running are the officepi (pi3b+ connected via ethernet) and the Hassio addon. The office pi shows node V12.16.1 is installed.

**Comment by dcgrove** [comment]
Good morning, I got another set of errors this morning as I had an ssh terminal open overnight when the system crashed. Not sure if this helpful or not.

`pi@officepi:~ $
Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.786771] Internal error: Oops: 17 [#1] SMP ARM

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790116] Process kworker/u9:0 (pid: 3727, stack limit = 0xdb9b9375)

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790122] Stack: (0xaca59d70 to 0xaca5a000)

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790132] 9d60:                                     af0060bc 00000000 80d04d48 7f628214

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790144] 9d80: 7f652014 00000016 aca59dc4 aca59d98 805cf53c 8084a414 00000016 00000000

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790156] 9da0: 00000000 7ddf4f2d af0060bc af006188 b6352000 b6352000 aca59de4 aca59dc8

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790167] 9dc0: 7f62837c 805cf4d8 00000000 af0060bc af0060bc af006000 aca59e04 aca59de8

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790179] 9de0: 7f60d440 7f62833c af006000 b6352000 80d04d48 00000000 aca59e24 aca59e08

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790191] 9e00: 7f60d5f0 7f60d398 b6352000 b9140900 80d04d48 00000000 aca59ec4 aca59e28

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790203] 9e20: 7f616574 7f60d554 00000002 00000001 ba376400 8085d710 b96c6900 b6352000

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790215] 9e40: 00000001 00000016 b6352008 00000000 b6352000 003527d8 b6350000 00000000

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790227] 9e60: 00000000 aca59e70 8020336c 80204570 40000013 b63527d8 b63527e4 b6352000

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790239] 9e80: aca59ea4 aca59e90 808635c4 80203328 b63527d8 7ddf4f2d aca59ec4 ad6a4b80

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790251] 9ea0: b6352700 b9140900 b6352000 b63527d8 b6352704 00000001 aca59efc aca59ec8

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790263] 9ec0: 7f606e8c 7f614cf4 b6352704 00000001 aca59efc ad6a4b80 b6352700 b9f83800

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790275] 9ee0: b549f700 00000000 b6352704 00000001 aca59f34 aca59f00 8013c44c 7f606d2c

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790287] 9f00: 40000093 b9f83800 b9f83800 b9f83800 ad6a4b94 b9f83800 b9f83818 80d03d00

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790299] 9f20: 00000088 ad6a4b80 aca59f7c aca59f38 8013c790 8013c2e8 aca59f5c 00000000

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790311] 9f40: 80d03d00 80d03d00 80d8ef7a aca58038 aca59f7c af165f40 ad409e00 00000000

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790323] 9f60: ad6a4b80 8013c734 af165f5c ac883e74 aca59fac aca59f80 80142ac4 8013c740

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790334] 9f80: 801043d8 ad409e00 8014298c 00000000 00000000 00000000 00000000 00000000

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790346] 9fa0: 00000000 aca59fb0 801010ac 80142998 00000000 00000000 00000000 00000000

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790356] 9fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.790367] 9fe0: 00000000 00000000 00000000 00000000 00000013 00000000 00000000 00000000

Message from syslogd@officepi at Mar 16 22:38:20 ...
 kernel:[100922.791790] Code: e24cb004 e8900088 e1a04000 e1a00003 (e5938010)

`

**Comment by mKeRix** [comment]
See raspberrypi/linux#2794. A German thread about this issue also suggests that it may be solved by using a better power supply.

I don't really know what else to try. The heap dumps show normal memory usage by room-assistant and I can't reproduce it at all using my 4 Pi Zero Ws setup with Ansible (which more or less equals the quickstart guide).
