### ISSUE TITLE
Pi Zero W service restarting constantly

### ISSUE THREAD

**Issue by kreene1987** [mKeRix/room-assistant#1181]
I've had room-assistant set up for 2 years and just recently on an update the room-assistant.service is starting for the timeout (120 seconds) and runs great (BLE/Bluetooth devices detected and showing proper state) but then the service restarts and says:

'''
room assistant.service failed due to timeout
'''

The room-assistant program (via cd ~/room-assistant, then room-assistant) runs perfectly for days, but I'd really like to get back to having the service automatically start when power is lost or any random occurrence.

I am assuming this is something related to the room-assistant program not triggering the service to the "started" state, but not sure what might be happening.

Currently running without the service and fine, but thought I'd ask while I had some time!

**Comment by kreene1987** [comment]
Just to add detail, I set up the service file EXACTLY per the documentation, tested a longer timeout, but it still restarts, just at the longer timeout interval.

I am running the nodejs 16.15.0 and room-assistant 2.20.0.

**Comment by kreene1987** [comment]
'''
>
Jun 04 18:52:57 mbedroom room-assistant[5664]: 04/06/2022, 18:52:57 - info - BluetoothLowEnergyService: Discovered n>
Jun 04 18:53:10 mbedroom systemd[1]: room-assistant.service: start operation timed out. Terminating.
Jun 04 18:53:10 mbedroom systemd[1]: room-assistant.service: Failed with result 'timeout'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit room-assistant.service has entered the 'failed' state with result 'timeout'.
Jun 04 18:53:10 mbedroom systemd[1]: Failed to start room-assistant service.
░░ Subject: A start job for unit room-assistant.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit room-assistant.service has finished with a failure.
░░
░░ The job identifier is 851 and the job result is failed.
Jun 04 18:53:10 mbedroom systemd[1]: room-assistant.service: Consumed 49.071s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit room-assistant.service completed and consumed the indicated resources.
Jun 04 18:53:11 mbedroom sudo[5661]: pam_unix(sudo:session): session closed for user root
Jun 04 18:53:21 mbedroom systemd[1]: room-assistant.service: Scheduled restart job, restart counter is at 1.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ Automatic restarting of the unit room-assistant.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Jun 04 18:53:21 mbedroom systemd[1]: Stopped room-assistant service.
░░ Subject: A stop job for unit room-assistant.service has finished
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A stop job for unit room-assistant.service has finished.
░░
░░ The job identifier is 916 and the job result is done.
Jun 04 18:53:21 mbedroom systemd[1]: room-assistant.service: Consumed 49.071s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit room-assistant.service completed and consumed the indicated resources.
Jun 04 18:53:21 mbedroom systemd[1]: Starting room-assistant service...
░░ Subject: A start job for unit room-assistant.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit room-assistant.service has begun execution.
░░
░░ The job identifier is 916.
'''

**Comment by adirburke** [comment]
Did you fix this ? 

I have the exact same problem

**Comment by adirburke** [comment]
I fixed this but setting the StartTimeOut to infinity  

From `TimeoutStartSec=120` to `TimeoutStartSec=0`

**Comment by kreene1987** [comment]
This kind of works (I mean it works, sure) but it's in a "starting" state forever basically.

I'm probably looking to move to ESPresence or a different solution as @mKeRix seems to have moved on to other priorities (no heartburn!)

**Comment by adirburke** [comment]
Yeah I just dropped a few $$ on six Pis for the house so Im gonna keep trying to get it to work. 
My Typescript is not amazing but shouldnt take long to pick up the basics

Its werid that this bug only displayed on 2 out of the 6 devices, the other 4 seem to get through the starting state
