### ISSUE TITLE
MQTT messages fail to send

### ISSUE THREAD

**Issue by Blink515** [mKeRix/room-assistant#120]
I have been using the older 1.X version of room assistant without issue for many months and decided to give version 2.X a shot (I wiped the SD card and started fresh).  I can see room assistant connect to the MQTT server but I've only gotten it to send messages once.  I thought it had something to do with using the verbose flag because that's the first time it worked but after stopping and starting room assistant again it no longer sent messages to the broker.  Most recent log is below

`pi@RA-Office:~/room-assistant $ room-assistant -v
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
[Nest] 445   - 02/29/2020, 4:49:22 AM   [IntegrationsModule] Loading integrations: home-assistant, bluetooth-low-energy
[Nest] 445   - 02/29/2020, 4:49:25 AM   [NestFactory] Starting Nest application... +2679ms
[Nest] 445   - 02/29/2020, 4:49:29 AM   [InstanceLoader] AppModule dependencies initialized +3461ms
[Nest] 445   - 02/29/2020, 4:49:29 AM   [InstanceLoader] ConfigModule dependencies initialized +16ms
[Nest] 445   - 02/29/2020, 4:49:29 AM   [InstanceLoader] NestEmitterModule dependencies initialized +15ms
[Nest] 445   - 02/29/2020, 4:49:29 AM   [InstanceLoader] IntegrationsModule dependencies initialized +15ms
[Nest] 445   - 02/29/2020, 4:49:29 AM   [InstanceLoader] DiscoveryModule dependencies initialized +106ms
[Nest] 445   - 02/29/2020, 4:49:29 AM   [InstanceLoader] HomeAssistantModule dependencies initialized +19ms
[Nest] 445   - 02/29/2020, 4:49:29 AM   [InstanceLoader] ClusterModule dependencies initialized +16ms
[Nest] 445   - 02/29/2020, 4:49:29 AM   [InstanceLoader] ScheduleModule dependencies initialized +18ms
[Nest] 445   - 02/29/2020, 4:49:29 AM   [InstanceLoader] BluetoothLowEnergyModule dependencies initialized +25ms
[Nest] 445   - 02/29/2020, 4:49:29 AM   [InstanceLoader] EntitiesModule dependencies initialized +17ms
[Nest] 445   - 02/29/2020, 4:49:29 AM   [RoutesResolver] EntitiesController {/entities}: +136ms
[Nest] 445   - 02/29/2020, 4:49:29 AM   [RouterExplorer] Mapped {/, GET} route +78ms
[Nest] 445   - 02/29/2020, 4:49:30 AM   [BluetoothLowEnergyService] Discovered new BLE peripheral 50798dbcf046 with ID 50798dbcf046 and RSSI -37
[Nest] 445   - 02/29/2020, 4:49:30 AM   [BluetoothLowEnergyService] Discovered new BLE peripheral 5050904df73e with ID 5050904df73e and RSSI -53
[Nest] 445   - 02/29/2020, 4:49:30 AM   [BluetoothLowEnergyService] Discovered new BLE peripheral nut with ID c53e5f59c30b and RSSI -74
[Nest] 445   - 02/29/2020, 4:49:30 AM   [EntitiesService] Adding new entity ble-c53e5f59c30b
[Nest] 445   - 02/29/2020, 4:49:30 AM   [BluetoothLowEnergyService] Discovered new BLE peripheral 450b6cb9431c with ID 450b6cb9431c and RSSI -84
[Nest] 445   - 02/29/2020, 4:49:31 AM   [BluetoothLowEnergyService] Discovered new BLE peripheral 4fa61296eb82 with ID 4fa61296eb82 and RSSI -88
[Nest] 445   - 02/29/2020, 4:49:31 AM   [HomeAssistantService] Successfully connected to MQTT broker at mqtt://192.168.1.67:1883
[Nest] 445   - 02/29/2020, 4:49:31 AM   [ConfigService] Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml
[Nest] 445   - 02/29/2020, 4:49:31 AM   [ClusterService] Starting mDNS advertisements and discovery
[Nest] 445   - 02/29/2020, 4:49:31 AM   [NestApplication] Nest application successfully started +26ms
[Nest] 445   - 02/29/2020, 4:49:31 AM   [ClusterService] office has been elected as leader
[Nest] 445   - 02/29/2020, 4:49:31 AM   [EntitiesService] Refreshing entity states
[Nest] 445   - 02/29/2020, 4:49:31 AM   [BluetoothLowEnergyService] Discovered new BLE peripheral 47a8914f6149 with ID 47a8914f6149 and RSSI -85
[Nest] 445   - 02/29/2020, 4:49:33 AM   [BluetoothLowEnergyService] Discovered new BLE peripheral UCKP with ID 1ae829494533 and RSSI -95
[Nest] 445   - 02/29/2020, 4:49:33 AM   [BluetoothLowEnergyService] Discovered new BLE peripheral c47c8d660ddb with ID c47c8d660ddb and RSSI -93
[Nest] 445   - 02/29/2020, 4:49:34 AM   [BluetoothLowEnergyService] Discovered new BLE peripheral 770a7436d751 with ID 770a7436d751 and RSSI -94
[Nest] 445   - 02/29/2020, 4:49:36 AM   [BluetoothLowEnergyService] Discovered new BLE peripheral c00000009086 with ID c00000009086 and RSSI -93
[Nest] 445   - 02/29/2020, 4:49:37 AM   [BluetoothLowEnergyService] Discovered new BLE peripheral c2f7db340335 with ID c2f7db340335 and RSSI -92`

**Comment by mKeRix** [comment]
Does the whitelist contain at least one of the ids that are listed as discovered in the logs? Is the entity created locally by room-assistant? You can check the latter by going to `<pi-ip>:6415/entities` in your browser. This endpoint lists all entities room-assistant manages on the local device in JSON format.

**Comment by Blink515** [comment]
The whitelist contains 2 entities.  The entity is created when looking at the entities endpoint but it's unfortunately not showing the device as being home even though I have it sitting on the same desk as the pi.  I have pasted the JSON data below.
`

0 |  
-- | --
attributes |  
lastUpdatedAt | "2020-02-29T16:32:08.609Z"
id | "ble-c53e5f59c30b"
name | "Charger Keys Room Presence"
distributed | true
distances | {}
timeout | 5
state | "not_home"

`

**Comment by mKeRix** [comment]
Ok, so for one it seems like the BLE tag is actually discovered before MQTT is connected and therefore the discovery message is just lost. That's a bug that I'll try to fix asap.

As for the device being `not_home`: do you have a `maxDistance` configured? It's weird that the entity does not have any attributes - it should at least have a `last_updated_at` attribute with a timestamp.

**Comment by Blink515** [comment]
I have `maxDistance` set to 5 and I can see the distance updating in the JSON now but still no MQTT messages being sent other than the one time it worked last night.

**Comment by Blink515** [comment]
This is the most recent JSON.

`{"attributes":{"distance":3.4,"lastUpdatedAt":"2020-02-29T17:34:51.499Z"},"id":"ble-c53e5f59c30b","name":"Charger Keys Room Presence","distributed":true,"distances":{},"timeout":5,"state":"office"}`

**Comment by mKeRix** [comment]
Could you update your installation to the release above and give that a shot? I believe it should fix this. Otherwise we can re-open this issue.

**Comment by Blink515** [comment]
I just updated and things are working great now.  Thank you!
