### ISSUE TITLE
Is room-assistant no longer maintained?

### ISSUE THREAD

**Issue by bachoo786** [mKeRix/room-assistant#1200]
Hi All

Do we know if @mKeRix has stopped maintaining room-assistant? It seems like no ones issues are answered nor any changes are implemented in the actual software/code.

Thanks.

**Comment by mKeRix** [comment]
Hey! I’m still around, but currently don’t have the time to invest a lot in maintaining this project. If someone would be interested in picking up maintainership of this project do let me know - I’m happy to help you get started.

I hope to be able to spend more time on home automation and room-assistant again in the future.

**Comment by adirburke** [comment]
@mKeRix I would love to help, but I need a crash course in Bluetooth. Havent done any programming with it

**Comment by bachooo786** [comment]
> Hey! I’m still around, but currently don’t have the time to invest a lot in maintaining this project. If someone would be interested in picking up maintainership of this project do let me know - I’m happy to help you get started.
> 
> I hope to be able to spend more time on home automation and room-assistant again in the future.

I wish we find your replacement but it seems like no one is available. 

I think you will find most of the roomassistant users experience the same recurring issue which is: RA will be running fine for weeks and then all of a sudden on a fresh raspberry pi install : 
`
BluetoothService: Did not detect any low energy advertisements in a while, resetting`

Is there anyway you can help please?

**Comment by townsmcp** [comment]
@bachooo786 i have got round this by adding a cron to each RPI to reboot over night. 5 minute time difference between each and the main RPI that I want as the cluster leader goes last

**Comment by legovaer** [comment]
@mKeRix I would be happy to help you with maintaining this addon!

**Comment by FormBurden** [comment]
Hi there @mKeRix, might I suggest on the front page of possibly putting "Looking for more maintainers" or something similar. Because you would need look in the archives to see that this issue is happening. And I'm sure lots of folks do not do that, and miss it. Just a suggestion! :)

**Comment by itkfilelor** [comment]
> > Hey! I’m still around, but currently don’t have the time to invest a lot in maintaining this project. If someone would be interested in picking up maintainership of this project do let me know - I’m happy to help you get started.
> > I hope to be able to spend more time on home automation and room-assistant again in the future.
> 
> I wish we find your replacement but it seems like no one is available.
> 
> I think you will find most of the roomassistant users experience the same recurring issue which is: RA will be running fine for weeks and then all of a sudden on a fresh raspberry pi install : ` BluetoothService: Did not detect any low energy advertisements in a while, resetting`
> 
> Is there anyway you can help please?

Try these commands.


sudo setcap cap_net_raw+eip $(eval readlink -f \`which node\`)
sudo setcap cap_net_raw+eip $(eval readlink -f \`which hcitool\`)
sudo setcap cap_net_admin+eip $(eval readlink -f \`which hciconfig\`)
sudo systemctl restart room-assistant
