### ISSUE TITLE
Add tag.Name to BLE white list

### ISSUE THREAD

**Issue by jbucky86** [mKeRix/room-assistant#121]
For use with iPhones. As you can change the name with the "nFR conect app"

**Comment by mKeRix** [comment]
So I just wrote a clean version to solve this and then tried the nRF connect app - for me it only advertises with the configured name when the app is running. That would match my previous knowledge of iOS Bluetooth. Do I need to set something elsewhere as well?

I'll keep the changeset in a branch, but if there is no actual use case for this then I'd rather not merge this into the production code to keep the code simpler.
