### ISSUE TITLE
BLE device whitelist: kebab-style MACs or just 12 characters?

### ISSUE THREAD

**Issue by mikeage** [mKeRix/room-assistant#122]
**Describe the bug**
The documentation says:

> For regular BLE devices this is the MAC address in kebab-case, for example `77-50-fb-4d-ab-70`

but when running 2.1.1, it seems like it's just a 12 character string (e.g., `7750fb4dab70`).

Is this a bug in the docs, or did something accidentally change in the code?

**To reproduce**
n/a

**Relevant logs**
n/a

**Relevant configuration**
n/a

**Expected behavior**
n/a

**Environment**
 - room-assistant version: 2.1.1
 - installation type: nodejs npm install -g
 - hardware: raspberry pi 3 
 - OS: raspbian stretch

**Additional context**
n/a

**Comment by mKeRix** [comment]
Was a mistake in the documentation - thanks for reporting, it's fixed now. :)
