### ISSUE TITLE
Expose detailed status to HomeAssistant

### ISSUE THREAD

**Issue by CoMPaTech** [mKeRix/room-assistant#127]
**Is your feature request related to a problem? Please describe.**
Unless I overlooked it in my dev window (I've got a generous lot of entities), I didn't spot a status for room_assistant itself (I do see my bluetooth devices). As sometimes the PI0w's are unavailable (wifi intermission) or out of memory, or maybe just unplugged one to vacuum (heaven forbids), I'm not sure if tracking is accurate. While I could set-up monitoring in various ways, exposing a list of active nodes will surely help spotting issues easily.

**Describe the solution you'd like**
Add a room_assistant device with attributes describing each cluster node. Not yet looked at your code but adding a `sensor.room_assistant` or something similar with some attributes like:

```
device |  state | attributes
sensor.room_assistant | [on/off] | last change # last mqtt message?
 | | nodes: ["livingroom","kitchen"] # i.e. the nodenames in a list, actively updated
 | | leader: ["kitchen"]
```

**Describe alternatives you've considered**
Adding 'tracked by node' to each tracked device, but that will be cluttering (though useful when debugging, but you can just subscribe to mqtt for that)

Adding nodes as separate sensors, but not sure (besides showing things) if it would be useful in the long run (i.e. sensor.ra_kitchen with attributes like `devices_tracked: 3`, `last_updated`

**Additional context**

**Comment by mKeRix** [comment]
Good idea! Should be useful for understanding the tracking history and some issues. Building on your suggestion above and my understanding of how Home Assistant entities should be used nowadays I would think adding two sensors makes sense: `sensor.room_assistant_cluster_size` with the count as state and the nodes in the attributes and `sensor.room_assistant_cluster_leader` with the current leader as state.

**Comment by CoMPaTech** [comment]
That indeed sounds great!

**Comment by Alfiegerner** [comment]
Great idea, this would definitely be very useful disgusting issues - I had an situation where my quorum wasn't reached due to varied reasons and I couldn't figure it out.

**Comment by mKeRix** [comment]
Quick side note: the sensors I suggested above are now registered per instance, i.e. you will have two new sensors for each instance in your cluster. Decided to go that route because it's much easier to find split cluster issues this way.
