### ISSUE TITLE
Room Assistant randomly shutting down on Hass.io

### ISSUE THREAD

**Issue by Alex9premium** [mKeRix/room-assistant#128]
**Describe the bug**
Room Assistant randomly shuts off.

**To reproduce**
Steps required to reproduce the issue.

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:02:00] INFO: Setting up Home Assistant configuration
[19:02:00] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
[Nest] 177   - 03/04/2020, 7:02:04 PM   [IntegrationsModule] Loading integrations: home-assistant, bluetooth-low-energy
[Nest] 177   - 03/04/2020, 7:02:05 PM   [NestFactory] Starting Nest application... +813ms
[Nest] 177   - 03/04/2020, 7:02:05 PM   [InstanceLoader] AppModule dependencies initialized +907ms
[Nest] 177   - 03/04/2020, 7:02:05 PM   [InstanceLoader] ConfigModule dependencies initialized +2ms
[Nest] 177   - 03/04/2020, 7:02:05 PM   [InstanceLoader] NestEmitterModule dependencies initialized +1ms
[Nest] 177   - 03/04/2020, 7:02:05 PM   [InstanceLoader] IntegrationsModule dependencies initialized +2ms
[Nest] 177   - 03/04/2020, 7:02:05 PM   [InstanceLoader] DiscoveryModule dependencies initialized +20ms
[Nest] 177   - 03/04/2020, 7:02:05 PM   [InstanceLoader] HomeAssistantModule dependencies initialized +2ms
[Nest] 177   - 03/04/2020, 7:02:05 PM   [InstanceLoader] ClusterModule dependencies initialized +2ms
[Nest] 177   - 03/04/2020, 7:02:05 PM   [InstanceLoader] ScheduleModule dependencies initialized +3ms
[Nest] 177   - 03/04/2020, 7:02:05 PM   [InstanceLoader] BluetoothLowEnergyModule dependencies initialized +3ms
[Nest] 177   - 03/04/2020, 7:02:05 PM   [InstanceLoader] EntitiesModule dependencies initialized +2ms
[Nest] 177   - 03/04/2020, 7:02:06 PM   [RoutesResolver] EntitiesController {/entities}: +25ms
[Nest] 177   - 03/04/2020, 7:02:06 PM   [RouterExplorer] Mapped {/, GET} route +12ms
[Nest] 177   - 03/04/2020, 7:02:06 PM   [HomeAssistantService] Successfully connected to MQTT broker at mqtt://core-mosquitto:1883
[Nest] 177   - 03/04/2020, 7:02:06 PM   [ConfigService] Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
[Nest] 177   - 03/04/2020, 7:02:06 PM   [ClusterService] Starting mDNS advertisements and discovery
[Nest] 177   - 03/04/2020, 7:02:06 PM   [NestApplication] Nest application successfully started +3ms
[Nest] 177   - 03/04/2020, 7:02:06 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral 3c950981fd5e with ID 3c950981fd5e and RSSI -69
[Nest] 177   - 03/04/2020, 7:02:06 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral 338d0dd68a44 with ID 338d0dd68a44 and RSSI -68
[Nest] 177   - 03/04/2020, 7:02:06 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral 22227f874d9a with ID 22227f874d9a and RSSI -77
[Nest] 177   - 03/04/2020, 7:02:08 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral Amazfit Cor with ID d01f2d9bf9dd and RSSI -85
[Nest] 177   - 03/04/2020, 7:02:08 PM   [BluetoothLowEnergyService] Discovered new BLE peripheral Mi Smart Band 4 with ID e398749862f3 and RSSI -82
[cmd] /room-assistant/entrypoint.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
internal/buffer.js:72
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 2. Received 3
    at boundsError (internal/buffer.js:72:9)
    at Uint8Array.readUInt8 (internal/buffer.js:238:5)
    at Hci.onSocketData (/usr/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:469:36)
    at BluetoothHciSocket.emit (events.js:223:5) {
  code: 'ERR_OUT_OF_RANGE'
}
[s6-finish] sending all processes the TERM signal.
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```global:
  instanceName: Living room
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  peerAddresses:
    - '192.168.64.4:6425'
  weight: 5
bluetoothLowEnergy:
  whitelist:
    - e398749862f3
  timeout: 25
```

**Expected behavior**
It should run normally.

**Environment**
 - room-assistant version: 2.1.1
 - installation type: Hass.io
 - hardware: Raspberry Pi 4
 - OS: Linux

**Additional context**
 This only happens on Hass.io because my other instance on a normal NodeJS manual installation runs fine without problems. Both are Raspberry Pi 4s.

**Comment by mKeRix** [comment]
Unfortunately an issue with the underlying library, see abandonware/noble#15. As the stack never even touches room-assistant code I'm not sure how I could catch and handle this better. Somebody is trying to write a new library with the same functionality [here](https://github.com/LukasBombach/sblendid/), but the current releases don't have Linux support yet.

I can do some research on workarounds for this issue in the future though!

**Comment by THATDONFC** [comment]
Does this mean room-assistant can't be run on a machine that is running Home Assistant (hassio)?

**Comment by mKeRix** [comment]
@THATDONFC It can - the BLE integration might just be a bit flaky on Hass.io at the moment.

**Comment by clutwo** [comment]
Just to add to this... this error is NOT restricted to Hass.io. 

I have room-assistant currently running on three machines with BLE integration:

One is a Raspberry Pi 3B+ with Raspbian connected over LAN with Home Assistant (not hass.io) installed on it with Docker + Room Assistant as an additional docker container. No problem here.

The second on is an Odroid N2 with CoreElec, also connected by LAN , also with a room-assistant docker container running.  No Problem.

The third one is a Raspberry Pi 3B+, running over WIFI, running Volumio server for speakers. 
Room-Assistant again running in a docker image. On this machine, i get this problem constantly. 

Since those are all the same docker images, I'm not sure what the problem here could be. Maybe it is just a faulty Bluetooth device. I have to add that the wifi reception can be quite bad for the third machine, and drops sometimes, maybe there is some kind of bluetooth interference here also.

**Comment by asknoone** [comment]
Hi people,

I'm running an older version of Room Assistant but have this issue too. For the HASSIO users out there...

I've created a sensor to monitor the add-on state and then an automation to restart the add-on if it stops. I've been running this for around 2 years now and very few problems with presence detection.

You need to create a long lived api token to pull the data out of the API to get the state of the add-on using a REST sensor. There are probably multiple other ways of doing this too.

I hope this helps some of you guys.

```
# Sensor - Get status of the Room Assistant Add-on so can restart it if it has stopped running
  - platform: rest
    name: Room Assistant Addon Status
    resource: 'http://{haipaddress}:8123/api/hassio/addons/6e66619d_room_assistant/info'
    headers:
      Authorization: !secret rest_api_token
      Content-Type: 'application/json'
    value_template: '{{value_json.data.state}}'

# Automation to restart Room Assistant if it has stopped
- alias: Restart Room Assistant
  trigger:
    platform: state
    entity_id: sensor.room_assistant_addon_status
    to: 'stopped'
  action:
  - service: hassio.addon_start
    data:
      addon: 6e66619d_room_assistant

```

**Comment by clutwo** [comment]
I'm now pretty sure that this is the reason: [https://www.raspberrypi.org/documentation/configuration/uart.md](url)

Namely, my Volumio instance puts Bluetooth on the miniUART port so it can better utilize the GPIO pins for the soundboards like HifiBerry that are supposed to be used with Volumio (Network Music Player). 

I'm guessing HassOS does the same, so it can better utilize the GPIO pins for stuff like Z-Wave or Zigbee boards ( haven't checked this though).

The particular deficiencies of the mini UART compared to the PL011 are :

No break detection
No framing errors detection
No parity bit
No receive timeout interrupt
No DCD, DSR, DTR or RI signals

These deficiencies and the room-assistant ble error messages lead me to believe, that this is the reason. I haven't had time to try to change it back on my Volumio, but I will report back here in case I manage to do it.

**Comment by mKeRix** [comment]
I think this issue can be circumvented quite nicely by the Home Assistant Supervisor Watchdog now, which you can just enable for the add-on. This seems like a cleaner solution than building a somewhat hacky catch-all errors solution around the application itself.
