### ISSUE TITLE
Cluster example setup

### ISSUE THREAD

**Issue by MTrab** [mKeRix/room-assistant#130]
**Is your feature request related to a problem? Please describe.**
I'm trying to setup a cluster, with a master node on Home Assistant, running in a VM (hence no bluetooth device) and nodes based on RPi running room-assistant in Docker.

**Describe the solution you'd like**
I can not find an example on configs for master and nodes anywhere.
I have tried, using the current docs, but have failed as it seems to be incorrectly configured,
Master is not receiving anything from the nodes
The nodes is not scanning for bluetooth devices and hence are not reporting anything

**Comment by Nin-D-Tendo** [comment]
I've just set up my room-assistant with multiple pi zeros and don't see a problem. 
I set the same name for the whitelisted ble devices across the nodes and set them all up to the same mqtt server. In HA I get 1 entity per device with states according to closest node.
By default they should auto discover, so I didn't add 'cluster' to config on any device.
Hope it helped somehow

**Comment by mKeRix** [comment]
If you're not actually running any integrations on your "master" node then you won't need that instance. room-assistant is capable of just picking a leader from the nodes doing the work. Keep in mind that the leader also needs to have the `bluetoothClassic` integration enabled for it to run anything, and it will use the config of the leader for the list of addresses. Try things without your master.

**Comment by MTrab** [comment]
Just fired up my one Pi again.
Unfortunately it doesn't find my Android phone (which I actually already was expecting, as NONE of the other Bluetooth solutions I have looked at could find it)

This is what I get from the Pi:

```
sudo docker run --net="host" -v /docker/room-assistant/config:/room-assistant/config -v /var/run/dbus:/var/run/dbus --name="room-assistant" mkerix/room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
[Nest] 1   - 03/09/2020, 7:24:06 PM   [IntegrationsModule] Loading integrations: home-assistant, bluetooth-classic
[Nest] 1   - 03/09/2020, 7:24:07 PM   [NestFactory] Starting Nest application... +755ms
[Nest] 1   - 03/09/2020, 7:24:08 PM   [InstanceLoader] AppModule dependencies initialized +479ms
[Nest] 1   - 03/09/2020, 7:24:08 PM   [InstanceLoader] ConfigModule dependencies initialized +3ms
[Nest] 1   - 03/09/2020, 7:24:08 PM   [InstanceLoader] NestEmitterModule dependencies initialized +2ms
[Nest] 1   - 03/09/2020, 7:24:08 PM   [InstanceLoader] IntegrationsModule dependencies initialized +2ms
[Nest] 1   - 03/09/2020, 7:24:08 PM   [InstanceLoader] DiscoveryModule dependencies initialized +20ms
[Nest] 1   - 03/09/2020, 7:24:08 PM   [InstanceLoader] HomeAssistantModule dependencies initialized +3ms
[Nest] 1   - 03/09/2020, 7:24:08 PM   [InstanceLoader] ClusterModule dependencies initialized +2ms
[Nest] 1   - 03/09/2020, 7:24:08 PM   [InstanceLoader] ScheduleModule dependencies initialized +3ms
[Nest] 1   - 03/09/2020, 7:24:08 PM   [InstanceLoader] BluetoothClassicModule dependencies initialized +4ms
[Nest] 1   - 03/09/2020, 7:24:08 PM   [InstanceLoader] EntitiesModule dependencies initialized +2ms
[Nest] 1   - 03/09/2020, 7:24:08 PM   [RoutesResolver] EntitiesController {/entities}: +30ms
[Nest] 1   - 03/09/2020, 7:24:08 PM   [RouterExplorer] Mapped {/, GET} route +13ms
[Nest] 1   - 03/09/2020, 7:24:08 PM   [HomeAssistantService] Successfully connected to MQTT broker at mqtt://10.254.254.109:1883
[Nest] 1   - 03/09/2020, 7:24:08 PM   [ConfigService] Loading configuration from /usr/local/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml
[Nest] 1   - 03/09/2020, 7:24:08 PM   [ClusterService] Starting mDNS advertisements and discovery
[Nest] 1   - 03/09/2020, 7:24:08 PM   [NestApplication] Nest application successfully started +4ms
[Nest] 1   - 03/09/2020, 7:24:10 PM   [ClusterService] bryggers has been elected as leader
[Nest] 1   - 03/09/2020, 7:24:10 PM   [EntitiesService] Refreshing entity states
```

local.yml:
```
global:
  instanceName: bryggers
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://MY_IP:1883'
  mqttOptions:
    username: MY_USER
    password: MY_PASS
bluetoothClassic:
  addresses:
    - aa:bb:cc:dd:ee:ff
```

**Comment by mKeRix** [comment]
I don't have an Android to test with, but I suspect it also heavily depends on the device and installed variant anyway. The options and log look correct, in theory you could append `-v` to your docker run command (after the image) to get debug logging and see what room-assistant does in more detail. Maybe your phone turns off Bluetooth if nothing is connected, or if it's in energy save mode? Have you used Bluetooth peripherals with it before (e.g. headphones)?

**Comment by MTrab** [comment]
Will try with -v.

And yes, have Android smartwatch connected, 3 different headsets and a car ;)

**Comment by MTrab** [comment]
Okay - this might be an issue ;)

```
[Nest] 1   - 03/09/2020, 7:53:16 PM   [BluetoothClassicService] Command failed: hcitool -i hci0 cc "aa:bb:cc:dd:ee:ff" && hcitool -i hci0 rssi "aa:bb:cc:dd:ee:ff"
Can't create connection: I/O error
Get connection info failed: No such file or directory

```

**Comment by mKeRix** [comment]
The error you saw is generated when the device doesn't respond, which would be normal when it's not home for example (also the reason why it's only logged to debug). #114 also contains some other reports of this when you scroll down. Does running `hcitool -I hci0 cc --role=s "xx:xx:xx:xx:xx:xx" && hcitool -i hci0 rssi "xx:xx:xx:xx:xx:xx"` give you other output by any chance? Are you running it with root (or have you set the appropriate permissions as shown in the docs)?

**Comment by MTrab** [comment]
Running the command (as root) gives same error as the Docker.

Permissions you say?! Which permissions might that be? Can't find anything related to permissions in the docs.

**Comment by MTrab** [comment]
Rebooted the Pi and now it seems to work.
I have no idea what the difference was.

**Comment by mKeRix** [comment]
Sorry, forgot you ran it as Docker - don't worry about permissions, those don't matter for Docker installs. Glad it randomly started working - sometimes these things are weird.
