### ISSUE TITLE
ble disconnected randomly

### ISSUE THREAD

**Issue by Nin-D-Tendo** [mKeRix/room-assistant#131]
Have set up 2 instances on rasperry pi zero w and 1 on raspberry 4 and integrated all in HA.
Whitelisted 2x Mi Band 3 with their respective id.

The nodes report the band "jumping" from one room to another and even disconnect.

e.g band is in bedroom with an node nearby
HA states that sensor.foo_band is in bedroom
then sensor.foo_band is in entryway for a while
afterwards back to bedroom.
Sometimes it drops out entirely setting sensor.foo_band to not_home

I should note that the distance is not correct even after multiple tries of calibration.

Is there a workaround? I'm new to Home Assistant and just deployed room-assistant, but I think an update interval might help to reduce this problem.

**Comment by mKeRix** [comment]
There is no updateInterval option at the moment, but two options to combat these issues are increasing `timeout` and setting a `maxDistance` for the entryway. The estimated distance works the best for iBeacons, other devices should still work okay-ish within the same room though. As soon as there is a wall in-between the measuring Pi and the BLE peripheral the distance will be wrong though, by the nature of the detection method.

**Comment by Nin-D-Tendo** [comment]
I managed to get this somwhat more accurate, but as you mentioned a wall will have great impact on distance ( and signal I guess ).
The odd thing now is that even though seperated by a wall "entryway" picks up the mi Band over time even though I sit right next to the bedroom instance.
Is this issue related to the mi Band or might it be some misconfiguration.
Thanks in advance!

**Comment by mKeRix** [comment]
I don't think it's an issue with the Mi Band, it's probably something going wrong in the detection process. Does the node in the bedroom drop off the cluster/network occasionally by any chance? You would see that in the logs. If the node is not in the cluster it won't send the measurements, which would lead to further away nodes suddenly being considered as the closest ones.

**Comment by Nin-D-Tendo** [comment]
checking the logs, bedroom instance has output as expected,entryway is within hass.io, so I don't know how to check,in the home assistant logs, I can see that whilst sleeping the mi band goes through the wall to the entryway quite alot while the bedroom instance logs dont show any error or drop ( I used journalctl -u room-assistant.service  for logs). Another strange thing is that the bathroom instance which ran for 3 days straight only has a log dating back to today 5 pm ( 11pm right now).

**Comment by mKeRix** [comment]
For Hass.io you can just go to the integration detail page and look at the logs on the bottom (just regular logs here though, no verbose). It may be possible that the Pi 4 antenna is just a bit better than the Pi Ws, which could cause the tool to think that you're closer to there than you actually are. I suppose you could limit this problem by setting an even tighter `maxDistance` on that instance though.

**Comment by Nin-D-Tendo** [comment]
might having different `measuredPower` be the source of the problem?
I tried calibrating my mi Bands and used the measured RSSI value as the value for `measuredPower` in BLE options. 
While trying to set the maxDistance today, I noticed that even though the band was lying in the entryway ( approx. 3 meters from pi4 ) the pi zero in my bedroom picked it up across a concrete wall. 
Some sort of visualisation:
( mi band --- entryway instance ---- || ---- bedroom instance )
entryway has a measuredPower of -56
bedroom has measuredPower of -76

**Comment by mKeRix** [comment]
The distance estimation is based on the `measuredPower`, so that might be a cause, yeah. A lower `measuredPower` value leads to room-assistant considering bad signal strengths as closer to the instance than to other instances. Maybe try raising the bedroom `measuredPower` value a bit? I think the Pi 4, 3B+ and Zero W all use the same Bluetooth chipset (but maybe slightly different antennas), so the `measuredPower` shouldn't drift too far apart.

**Comment by Nin-D-Tendo** [comment]
I will close the issue, because for now it is working somehow.
Thanks for great support!
