### ISSUE TITLE
Stuck on installing on raspzero

### ISSUE THREAD

**Issue by Mikomie** [mKeRix/room-assistant#1318]
Hi

i've been trying to install RA on an raspzero but i'm stuck on "tar@2.2.2" dependency

i'm getting:
`npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive secu
(##################) ⠙ reify:mathjs: http fetch GET 200 https://registry.npmjs.org/mathjs/-/mathjs-10.6.4.tgz 28842`

and it stays there for an eternity

thanks in advance
H

**Comment by doughoyt** [comment]
Many of the dependencies have to be 'built' and on the Pi 0 that can take a while.

I just completed the install and it took about 58 minutes:
``npm timing npm Completed in 3480097ms``

Add the "--timing" parameter to the npm install command to watch the progress in more detail.
