### ISSUE TITLE
Issues with Ansible

### ISSUE THREAD

**Issue by Blink515** [mKeRix/room-assistant#133]
I'm really interested in using Ansible to keep all of my room-assistant machines updated easily but I am running into an error at step 3 of your Ansible documentation.  Any suggestions?

``` 
@RA-TV:~/ansible-playbooks $ ansible-galaxy install -r requirements.yml
- downloading role 'roles', owned by 
 [WARNING]: - roles was NOT installed successfully: Content has no field named
'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list. ```

**Comment by mKeRix** [comment]
As mentioned in mKeRix/ansible-playbooks#1 that is likely related to an outdated ansible version. In which way did you install it? The [official docs](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html) list a few different ways.

**Comment by Blink515** [comment]
My bad, I installed directly through apt but it appears the version is outdated.  I just added the Ansible apt source, upgraded and got it to run successfully.
