### ISSUE TITLE
Multicast packets being used?

### ISSUE THREAD

**Issue by gmalbert** [mKeRix/room-assistant#137]
This is a question rather than a bug or a feature request. I've been having issues with my router since early February (which also coincided with the installation of a new modem). But, it's also when I started to download and install the RA beta. 

I finally heard from Synology (the company that makes my router), and the developer said that my ongoing issues with access points disconnecting may be caused by my Home Assistant machine that "kept sending a lot of multicast packets on the local network". 

I'm just wondering if RA works by sending a lot of multicast packets. I'm not technical enough to understand the architecture, so I figured I'd go right to the source. Apologies for the round-about question, but I'm trying to get to the root of the issue.

**Comment by mKeRix** [comment]
room-assistant uses [Avahi](https://en.wikipedia.org/wiki/Avahi_(software)) (Linux version of Apple Bonjour), which is based on multicast DNS. It shouldn't send abnormal amounts of packages in theory - it just contacts the avahi-daemon running on the host and lets it do the job. There is also some smart caching and some other things involved to reduce the amounts of multicast packets required. If you want to try, you can just set the `cluster.autoDiscovery` option to false - that will stop room-assistant from sending multicast datagrams through Avahi entirely.
