### ISSUE TITLE
Display RSSi values from all nodes for each device

### ISSUE THREAD

**Issue by dcgrove** [mKeRix/room-assistant#140]
**Is your feature request related to a problem? Please describe.**
With multiple nodes that are relatively close together, it would be helpful to be able to see a display of all rssi values that each node receives for each device in order to tune the minRssi bluetooth classic attribute

**Describe the solution you'd like**
A home assistant sensor in the format of sensor.nodename_device_rssivalue would be easiest to display.

**Describe alternatives you've considered**
Any method of displaying all RSSI values for a particular device.

**Comment by mKeRix** [comment]
I'm torn on this one - in previous versions quite a few people were unhappy with the amount of messages that are sent via MQTT. This would re-introduce this concern and also make those messages all update separate entities in Home Assistant. I think I would only add this as an option, not a default. For now I'm not really seeing the benefit of keeping this data in Home Assistant though - for tuning purposes you can just run room-assistant with `-v` and see all received values in the logs. Outside of this setup/tuning process I believe you won't really need those RSSI values.

**Comment by dcgrove** [comment]
I agree that it would only be necessary temporarily while tuning.  The problem with running it in verbose is that the rssi readings scroll through fairly quickly so comparing the reading from a couple of devices is difficult.

**Comment by mKeRix** [comment]
Fair enough. Maybe this is a nice feature for a room-assistant Web UI in the future?

**Comment by lawhazl** [comment]
I have to say I love this add-on, its been so easy to get up and running on a HASS I'm running on a dedicated raspberrypi zero w.

One thing I have noticed is that the RSSI value that you limit devices as being sensed as home or away seems to be a blanket rule for all devices.

However I've noticed my iPhone has a far stronger signal strength compared to my Apple Watch when they are basically in the same spot and distance from the Pi.

What I would like to see is the ability to set each MAC address with its own RSSI setting so you can fine tune each device.

What do you think?

**Comment by mKeRix** [comment]
@lawhazl I've been seeing the same for my installation as well actually, I think that's a great idea. I've copied your idea over into a new issue so that we can track it separately from this one. :)

**Comment by gadric** [comment]
Has this been fixed only for BLE Or also for Bluetooth Classic?

**Comment by mKeRix** [comment]
It has only been added for BLE, because BT Classic does not do any calculation on the RSSI data. As mentioned in the docs, to get the RSSI for BT Classic measurements just calculate `distance * -1`.

**Comment by gadric** [comment]
Thanks for the answer. I was actually asking with regard to have rssi value of each node. I have 1room assistant node in my office and 1 in my sleeping room. I would like to have kind of room presence depending on the rssi value of both nodes. 

Is that possible?

**Comment by mKeRix** [comment]
Through the [API](https://www.room-assistant.io/guide/api.html), yes. You can setup some REST HTTP calls in whatever automation engine you use to achieve what you want.

**Comment by gadric** [comment]
Thanks! That sounds good. I will check this.
