### ISSUE TITLE
can't create connection: Input/output error

### ISSUE THREAD

**Issue by dfmckay** [mKeRix/room-assistant#148]
**Describe the bug**
getting 'Can't create connection: Input/output error
Get connection info failed: No such file or directory' errors constantly from a new install using the guide. I have also noticed that my network gets bogged down (TPlink plugs go unavailable while room-assistant is running) and comes back soon after I kill room-assistant.

**To reproduce**
I followed the guide for the pi zero w verbatim except I used the new raspberry pi imager

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```[Nest] 1063   - 03/15/2020, 2:57:57 AM   [BluetoothClassicService] Querying for RSSI of cc:21:19:af:f2:7a using hcitool
[Nest] 1063   - 03/15/2020, 2:57:58 AM   [BluetoothClassicService] Received RSSI of 0 for cc:21:19:af:f2:7a from diningroom
[Nest] 1063   - 03/15/2020, 2:57:58 AM   [HomeAssistantService] Sending new attributes {"distance":0,"lastUpdatedAt":"2020-03-15T02:57:58.681Z"} for room-assistant-bluetooth-classic-cc-21-19-af-f2-7a
[Nest] 1063   - 03/15/2020, 2:58:03 AM   [BluetoothClassicService] Querying for RSSI of c0:d3:c0:23:de:f0 using hcitool
[Nest] 1063   - 03/15/2020, 2:58:08 AM   [BluetoothClassicService] Command failed: hcitool -i hci0 cc "c0:d3:c0:23:de:f0" && hcitool -i hci0 rssi "c0:d3:c0:23:de:f0"
Can't create connection: Input/output error
Get connection info failed: No such file or directory
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```global:
  instanceName: diningroom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://xxxx:1883'
  mqttOptions:
    username: xxxx
    password: xxxx
bluetoothClassic:
  minRssi: -20
  hciDeviceId: 0
  addresses:
    - 'ff:ff:ff:ff:ff:ff'
    - 'ff:ff:ff:ff:ff:ff'
```

**Expected behavior**

**Environment**
 - room-assistant version:  2.1.1
 - installation type: NodeJS
 - hardware: Raspberry Pi Zero W
 - OS: raspbian.

**Additional context**

**Comment by dcgrove** [comment]
I am see issues with my wifi when I have two of my wireless Pi's running also.

**Comment by dfmckay** [comment]
Closing it out. the issues were that the can't create connection errors are normal, they display when it can't get a connection to the bluetooth device. For some reason my Gear S3 watch doesn't play well. When I commented out the device the wifi resumed normal function. Also I didn't have a discovery setting under my home assistant mqtt settings which is why I didn't see them there.
