### ISSUE TITLE
Some devices are not sending updates

### ISSUE THREAD

**Issue by Misak** [mKeRix/room-assistant#152]
**Describe the bug**
I have devices that are working fine (like mobile phones), but then I have bluetooth trackers (NUT), or my bluetooth watch and room-assistant can't see them at all.

**To reproduce**
Add mac address of ble tracker and wait for mqtt message.

**Relevant logs**
no relevant logs found

**Relevant configuration**
Paste the relevant parts of your configuration below.

```global:
  instanceName: Doma
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://10.1.1.20:1883'
  mqttOptions:
    username: mqtt
    password: mqtt123
bluetoothClassic:
  minRssi: -20
  hciDeviceId: 0
  addresses:
    - 'D2:FB:D2:DF:XX:YY'
```

**Expected behavior**
Send sensor status to mqtt.
I tried to scan with hcitool and wont write anything, but it is discoverable:

```
root@ganymed:~# mac='D2:FB:D2:DF:XX:YY' ; hcitool cc $mac && hcitool rssi $mac
Can't create connection: Input/output error
Read RSSI failed: Input/output error

root@ganymed:~# hcitool lescan
LE Scan ...
D2:FB:D2:DF:XX:YY nut

```

**Environment**
 - room-assistant version: 2.1.1
 - installation type: Hass.io
 - hardware: RPI3
 - OS: Linux

**Additional context**
Is it even possible? Am I missing something?
Thank you!

**Comment by dcgrove** [comment]
BLE devices must be used with the BLE addon, however, you cannot use the bluetooth classic and BLE addon on the same device without two separate bluetooth antennas.

**Comment by mKeRix** [comment]
Exactly - some devices only support BLE, like Tile devices. For these you would need to use the `bluetoothLowEnergy` integration. Generally you can find info about the supported protocols in their respective data sheets.
