### ISSUE TITLE
please add armv6 docker image

### ISSUE THREAD

**Issue by djaydev** [mKeRix/room-assistant#155]
**Is your feature request related to a problem? Please describe.**
Related problem is not able to run docker image on armv6

**Describe the solution you'd like**
The building and availability of a docker image for armv6 on Docker Hub.

**Describe alternatives you've considered**
I'm sorry I can't think of an alternative

**Additional context**
I have a sample Dockerfile that can be used to allow devices such as raspberry-pi to run room-assistant in docker.  The base image used in the Dockerfile is officially maintained similar to the current docker images used by the project.  I've successfully tested the docker image built with the Dockerfile below with a raspberry pi.

[Dockerfile.txt](https://github.com/mKeRix/room-assistant/files/4363178/Dockerfile.txt)

```
FROM arm32v6/node:12-alpine as build
ARG ROOM_ASSISTANT_VERSION=latest

RUN apk add --no-cache python make g++ libusb-dev eudev-dev avahi-dev
RUN npm install -g --unsafe-perm room-assistant@$ROOM_ASSISTANT_VERSION

FROM arm32v6/node:12-alpine

WORKDIR /room-assistant

RUN apk add --no-cache bluez bluez-deprecated libusb avahi-dev bind-tools dmidecode \
    && setcap cap_net_raw+eip $(eval readlink -f `which node`) \
    && setcap cap_net_raw+eip $(eval readlink -f `which hcitool`) \
    && setcap cap_net_admin+eip $(eval readlink -f `which hciconfig`) \
    && ln -s /usr/local/lib/node_modules/room-assistant/bin/room-assistant.js /usr/local/bin/room-assistant
COPY --from=build /usr/local/lib/node_modules/room-assistant /usr/local/lib/node_modules/room-assistant

ENTRYPOINT ["room-assistant"]
CMD ["--digResolver"]
```

**Comment by mKeRix** [comment]
Can I ask which Raspberry Pi you are trying to run this on with Docker? room-assistant is packaged as multi arch images with support for armv7 - which includes all recent Pi generations except the Zero line.

**Comment by djaydev** [comment]
Can I ask which Raspberry Pi you are trying to run this on with Docker? 
Raspberry Pi W Zero

Thanks for confirming armv7 availability.  I also noticed x86 (32 and 64 bit), arm64 support as well.

**Comment by dragonb2** [comment]
Unfortunately armv6 does not work for PI Zeros, it apparently needs to be "arm".

For example, "arm32v6/bash" and "portainer/portainer" work, however your versions marked with armv6 do not.

**Comment by mKeRix** [comment]
@dragonb2 Which version of Docker are you on? I haven't tried it on the Pi Zero, but in theory arm/v6 should work fine from a technical standpoint. As I'm using docker buildx to build the images I don't have just arm available unfortunately.

**Comment by akonradi** [comment]
I'm unable to run the latest image on a Pi Zero; it exits every time with status code 139. Here's my `docker version` output:
```
Client: Docker Engine - Community
 Version:           19.03.10
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9424aea
 Built:             Thu May 28 22:24:06 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.10
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9424aea
  Built:            Thu May 28 22:18:05 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by mKeRix** [comment]
@akonradi Are you seeing the same issues with the image for 2.7.1 (or lower)? Status code 139 points to a segmentation fault and I have no clue what might be causing it.
