### ISSUE TITLE
How to make room-assistant send all the detected devices to home-assistant in each response?

### ISSUE THREAD

**Issue by Atul141** [mKeRix/room-assistant#16]
Hi,
Firstly, thanks a lot for the wonderful library. 

I want to detect all BLE devices in the raspberry pi's range and analyse it's signal strength.

1) Unfortunately room-assistant is publishing only the latest device, as a result, I am able to see only one device in home-assistant's panel. Is there a way to send all the devices info as Json objects in the response each time?

2) How to tap the response that room-assistant sends to the home-assistant, programmatically, so that I could deploy automated scripts for some computation?

 And the location is a public place, so I don't know about the MAC address of the devices that may come in.

**Comment by Atul141** [comment]
I added a piece of code in my program t to do that.

Thanks.

**Comment by mKeRix** [comment]
If you feel others could benefit from your addition feel free to add a pull request making this an option for the tool. Glad you could solve the issue yourself. :)
