### ISSUE TITLE
Docker install RaspberryPi 4 image is mkerix/room-assistant:latest-arm32

### ISSUE THREAD

**Issue by faspina** [mKeRix/room-assistant#163]
**Describe the bug**
npm ERR! Failed at the room-assistant@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-30T21_52_14_535Z-debug.log
> room-assistant@1.0.1 start /room-assistant
> bin/room-assistant-runner.js
sh: bin/room-assistant-runner.js: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! room-assistant@1.0.1 start: `bin/room-assistant-runner.js`
npm ERR! Exit status 126

**To reproduce**
new docker-compose install 

**Relevant logs**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle room-assistant@1.0.1~prestart: room-assistant@1.0.1
6 info lifecycle room-assistant@1.0.1~start: room-assistant@1.0.1
7 verbose lifecycle room-assistant@1.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle room-assistant@1.0.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/room-assistant/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle room-assistant@1.0.1~start: CWD: /room-assistant
10 silly lifecycle room-assistant@1.0.1~start: Args: [ '-c', 'bin/room-assistant-runner.js' ]
11 silly lifecycle room-assistant@1.0.1~start: Returned: code: 126  signal: null
12 info lifecycle room-assistant@1.0.1~start: Failed to exec start script
13 verbose stack Error: room-assistant@1.0.1 start: `bin/room-assistant-runner.js`
13 verbose stack Exit status 126
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid room-assistant@1.0.1
15 verbose cwd /room-assistant
16 verbose Linux 4.19.97-v7l+
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 126
22 error room-assistant@1.0.1 start: `bin/room-assistant-runner.js`
22 error Exit status 126
23 error Failed at the room-assistant@1.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 126, true ]

```text
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
```

**Expected behavior**

**Environment**
 - room-assistant version: [e.g. 2.0.0]
 - installation type: Docker
 - hardware: RPI 4
 - OS:  Raspian Buster

**Additional context**
docker-compose.yaml is 

version: "3.0"
services:
  room-assistant:
    image: mkerix/room-assistant:latest-arm32
    container_name: room-assistant
    restart: always
    network_mode: host
    privileged: true
    environment:
      SERVICES: 'mqtt,ble,shell'
      ROOM: 'home'
      AUTO_DISCOVERY: 'true'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/room-assistant
      - ./log:/root/.npm/_logs

**Comment by mKeRix** [comment]
room-assistant v1.x is not supported anymore, please switch to room-assistant 2.x. That should also solve the problem above, as the image is built differently. Refer to the [upgrade guide](https://www.room-assistant.io/guide/upgrading.html#major-upgrades) for more detailed information.
