### ISSUE TITLE
Getting error message stating "RSSI update for empty address requested"

### ISSUE THREAD

**Issue by dcgrove** [mKeRix/room-assistant#166]
**Describe the bug**
Getting error message stating "RSSI update for empty address requested"

**To reproduce**
Unknown steps to reproduce. Errors are occurring on a fresh pizero with latest version of room-assistant

**Relevant logs**
```6   - 04/10/2020, 7:27:51 PM   [BluetoothClassicService] RSSI update for empty address requested +40002ms
[Nest] 2296   - 04/10/2020, 7:28:31 PM   [BluetoothClassicService] RSSI update for empty address requested +39999ms
[Nest] 2296   - 04/10/2020, 7:29:11 PM   [BluetoothClassicService] RSSI update for empty address requested +40003ms
[Nest] 2296   - 04/10/2020, 7:29:35 PM   [ClusterService] getaddrinfo -3008 +23967ms
[Nest] 2296   - 04/10/2020, 7:29:51 PM   [BluetoothClassicService] RSSI update for empty address requested +16105ms
[Nest] 2296   - 04/10/2020, 7:30:31 PM   [BluetoothClassicService] RSSI update for empty address requested +39931ms
[Nest] 2296   - 04/10/2020, 7:31:11 PM   [BluetoothClassicService] RSSI update for empty address requested +40000ms
[Nest] 2296   - 04/10/2020, 7:31:51 PM   [BluetoothClassicService] RSSI update for empty address requested +40005ms
[Nest] 2296   - 04/10/2020, 7:32:31 PM   [BluetoothClassicService] RSSI update for empty address requested +40004ms
[Nest] 2296   - 04/10/2020, 7:33:11 PM   [BluetoothClassicService] RSSI update for empty address requested +40004ms
[Nest] 2296   - 04/10/2020, 7:33:51 PM   [BluetoothClassicService] RSSI update for empty address requested +40002ms

```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```global:
  instanceName: Master Bedroom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.240:1883'
  mqttOptions:
    username: clayton
    password: XXXXXXX
bluetoothClassic:
  minRssi: -10
  addresses:
    - F0:C3:71:2B:8A:74
    - E4:50:EB:0C:DA:91
    - 88:64:40:7B:60:89
    - E4:E4:AB:D9:AB:09
  interval: 10

```

**Expected behavior**
No errors regarding empty addresses.

**Environment**
 - room-assistant version: 2.3
 - installation type: Nodejs
 - hardware: Pi Zero
 - OS: Raspbian Lite

**Comment by mKeRix** [comment]
That message is the safeguard to prevent #136 - does it impact the functionality of your room-assistant cluster in any way? I couldn't reproduce the issue as part of the other ticket, which is why I opted for this simple solution. If it doesn't impact the functionality you can just ignore the messages.

**Comment by ghzgod** [comment]
I am also receiving this issue on multiple devices.

`Jul 26 15:59:51 roomassistantpi room-assistant[236]: 7/26/2020, 3:59:51 PM - error - BluetoothClassicService: RSSI update for empty address requested
Jul 26 16:01:06 roomassistantpi room-assistant[236]: 7/26/2020, 4:01:06 PM - error - BluetoothClassicService: RSSI update for empty address requested
Jul 26 16:02:21 roomassistantpi room-assistant[236]: 7/26/2020, 4:02:21 PM - error - BluetoothClassicService: RSSI update for empty address requested`

**Comment by andrelung** [comment]
Also receiving this on some nodes (not all). I came across this issue, because one of my nodes seems not to recognize my phone. It feels like the iPhone is invisible to my pi4. Has anyone seen similar behaviour? My other are working as expected.

```Aug 09 19:52:38 printerpi room-assistant[9359]: 09/08/2020, 19:52:38 - error - BluetoothClassicService: RSSI update for empty address requested
Aug 09 19:52:44 printerpi room-assistant[9359]: 09/08/2020, 19:52:44 - error - BluetoothClassicService: RSSI update for empty address requested
Aug 09 19:53:14 printerpi room-assistant[9359]: 09/08/2020, 19:53:14 - error - BluetoothClassicService: RSSI update for empty address requested
Aug 09 19:53:20 printerpi room-assistant[9359]: 09/08/2020, 19:53:20 - error - BluetoothClassicService: RSSI update for empty address requested
Aug 09 19:53:50 printerpi room-assistant[9359]: 09/08/2020, 19:53:50 - error - BluetoothClassicService: RSSI update for empty address requested
Aug 09 19:53:56 printerpi room-assistant[9359]: 09/08/2020, 19:53:56 - error - BluetoothClassicService: RSSI update for empty address requested
Aug 09 19:54:26 printerpi room-assistant[9359]: 09/08/2020, 19:54:26 - error - BluetoothClassicService: RSSI update for empty address requested
Aug 09 19:54:32 printerpi room-assistant[9359]: 09/08/2020, 19:54:32 - error - BluetoothClassicService: RSSI update for empty address requested
Aug 09 19:55:02 printerpi room-assistant[9359]: 09/08/2020, 19:55:02 - error - BluetoothClassicService: RSSI update for empty address requested
Aug 09 19:55:08 printerpi room-assistant[9359]: 09/08/2020, 19:55:08 - error - BluetoothClassicService: RSSI update for empty address requested```

**Comment by lwYeo** [comment]
I'm getting the same issue but randomly on random Pi Zero W on random days, and the affected instance was not able to see my phone. However, a restart seem to fix it, but I don't want to be manually restarting it every time it happens.
Maybe implementing a watchdog with an option to either restart the daemon or PI would help.

**Comment by mKeRix** [comment]
I added some more logging for debugging this in the latest version, let's track the issue at #288.
