### ISSUE TITLE
State of Bluetooth device is not correct 

### ISSUE THREAD

**Issue by delta010** [mKeRix/room-assistant#167]
**Describe the bug**

the state of the my all Bluetooth devices when it is in my home, home assistant show "raspberrypi" rather than the room name 

![Screenshot at 2020-04-12 09-39-05](https://user-images.githubusercontent.com/29528880/79060572-4443db80-7ca4-11ea-94a9-6e0887d43f28.png)

**To reproduce**
Steps required to reproduce the issue.

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```Apr 11 17:06:29 raspberrypi room-assistant[230]: [Nest] 230   - 04/11/2020, 5:06:29 PM   [InstanceLoader] BluetoothClassicModule dependencies initialized +24ms
Apr 11 17:06:29 raspberrypi room-assistant[230]: [Nest] 230   - 04/11/2020, 5:06:29 PM   [InstanceLoader] EntitiesModule dependencies initialized +17ms
Apr 11 17:06:29 raspberrypi room-assistant[230]: [Nest] 230   - 04/11/2020, 5:06:29 PM   [RoutesResolver] EntitiesController {/entities}: +136ms
Apr 11 17:06:29 raspberrypi room-assistant[230]: [Nest] 230   - 04/11/2020, 5:06:29 PM   [RouterExplorer] Mapped {/, GET} route +78ms
Apr 11 17:06:30 raspberrypi room-assistant[230]: [Nest] 230   - 04/11/2020, 5:06:30 PM   [HomeAssistantService] Successfully connected to MQTT broker at mqtt://192.168.1.5:1883
Apr 11 17:06:30 raspberrypi room-assistant[230]: [Nest] 230   - 04/11/2020, 5:06:30 PM   [ConfigService] Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dist
Apr 11 17:06:31 raspberrypi room-assistant[230]: [Nest] 230   - 04/11/2020, 5:06:31 PM   [ClusterService] Starting mDNS advertisements and discovery
Apr 11 17:06:31 raspberrypi room-assistant[230]: [Nest] 230   - 04/11/2020, 5:06:31 PM   [NestApplication] Nest application successfully started +27ms
Apr 11 17:06:31 raspberrypi room-assistant[230]: [Nest] 230   - 04/11/2020, 5:06:31 PM   [ClusterService] raspberrypi has been elected as leader
Apr 11 17:06:31 raspberrypi room-assistant[230]: [Nest] 230   - 04/11/2020, 5:06:31 PM   [EntitiesService] Refreshing entity states

```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://hassio.local:1883'
  mqttOptions:
    username: youruser
    password: yourpass
bluetoothClassic:
  addresses:
    - 00:AA:XX

```

**Expected behavior**

I expected to happen it should show a room name rather than raspberrypi

**Environment**
 - room-assistant version: 2.3.0
 - installation type:  NodeJS
 - hardware: Raspberry Pi Zero W
 - OS:  Rasbian 

**Additional context**

**Comment by mKeRix** [comment]
You either need to set the `instanceName` in your config ([docs](https://www.room-assistant.io/guide/configuration.html#core-settings)) or change the hostname of your Raspberry Pi to whatever you want the name to be (can be done with `raspi-config` under Networking Options, don't forget to reboot after changing).
