### ISSUE TITLE
minRssi setting per device

### ISSUE THREAD

**Issue by mKeRix** [mKeRix/room-assistant#168]
**Is your feature request related to a problem? Please describe.**
Different device types lead to different RSSI readings at the same distance with Bluetooth Classic. This makes the blanket `minRssi` setting too generic when using e.g. an iPhone and Apple Watch in the same setup.

**Describe the solution you'd like**
`minRssi` should be allowed to be set per device, with a configurable default value for everything that is not specifically configured.

**Additional context**
Feature request by @lawhazl in #140.

**Comment by lawhazl** [comment]
This is fantastic, I'll get testing this straight away

**Comment by readeral** [comment]
This is super awesome
