### ISSUE TITLE
Link motion sensor to prevent false positive

### ISSUE THREAD

**Issue by meauxt** [mKeRix/room-assistant#169]
**Is your feature request related to a problem? Please describe.**
in multiroom on multi level setup there issue where you multiple nodes will be close to you due the multi level home... 

**Describe the solution you'd like**
if we can link a motion sensor from homeassistant for example that will prevent switching to a room without a motion being trigger in defined seconds ( maybe last 10 second or depends how often the ble will advertise ) 
so each room will have a motion sensor link to it and room-assistant wont switch to that room unless there is a motion( since PIR reliable in capturing motion)
**Additional context**

**Comment by meauxt** [comment]
@mKeRix I would love to hear what you think about this if it's ideal to added or have maybe a better solution ?

**Comment by mKeRix** [comment]
I think this approach might lead to problems when you have multiple people in your house, as then multiple motion sensors might be triggered at the same time. From a technical standpoint it's possible, but would also complicate the integrations quite a bit imo.

To solve the multi-story issue I had an idea that I posted about on [reddit](https://www.reddit.com/r/homeassistant/comments/fwydue/monitor_vs_roomassistant/fmspji2/?context=3) - that assumes you have multiple nodes per level though. Not sure how well it'd work, as I don't have a multi-story home to test and collect data in.

**Comment by meauxt** [comment]
@mKeRix I agree it's will add more complication. but it will only target false positive ( if we trying to switch to a room that doesn't have motion then we would ignore it) so we gonna still have the issue if there is some motion we can get random trigger( room switching)

i tried solution mention ( same wall, same distance from floor, not same distance from floor,..) unfortunately did not get any better results.
i will be more than happy to help in collecting data and support/ help implementing a solution :) 
currently i did order AMG8833 to see is if that can help to if it i used it in main room ( kitchen , livingroom) but i guess in room-assistant we are just getting the raw value of it correct? we are don't have any logic around it

**Comment by mKeRix** [comment]
room-assistant doesn't support the AMG8833 yet, so you'll need something else to control that. If you want you can extend the software though - essentially all you would need to write are the parts that get the temperature data from the sensor in a 8x8 matrix, everything else is already provided to you in the thermopile folder. You can take a look at the code for d6t and gridEye if you want to give that a shot. :)

**Comment by meauxt** [comment]
Got it! I thought its same 😅 i will take a look as soon as i receive the sensor!

**Comment by mKeRix** [comment]
You know what - you're right, it's the same. I forgot that the technical name of the Grid-EYE is AMG8833. 😅 You should be able to hook it up to i2c and just fire up the `gridEye` integration to get presence data.

**Comment by meauxt** [comment]
Awesome! And about the first part of my comment do think the multilevel improvement something you will be able to tackle or take a look in the near future?

**Comment by mKeRix** [comment]
Yeah, it's on the shortlist of things that I want to work on. I'll probably put out a beta version that includes some sort of feature in this direction, collect feedback from people and then iterate or release.
