### ISSUE TITLE
wget returns 404

### ISSUE THREAD

**Issue by SylvainGa** [mKeRix/room-assistant#174]
**Describe the bug**
Installation of NodeJS through 

wget -O - https://raw.githubusercontent.com/sdesalas/node-pi-zero/master/install-node-v.lts.sh | bash

fails

**To reproduce**
run the commands

**Relevant logs**
No logs

**Relevant configuration**
No config yet

**Expected behavior**
The installation of NodeJS

**Environment**
 - room-assistant version: Not there yet
 - installation type: Trying to install NodeJS,
 - hardware: Raspberry Pi Zero W
 - OS: up to date Rasbian-lite

**Additional context**
This is the output when trying to install NodeJS

```--2020-04-18 17:23:07--  https://raw.githubusercontent.com/sdesalas/node-pi-zero/master/install-node-v.lts.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1944 (1.9K) [text/plain]
Saving to: ‘STDOUT’

-                                            100%[==============================================================================================>]   1.90K  --.-KB/s    in 0.02s

2020-04-18 17:23:08 (82.5 KB/s) - written to stdout [1944/1944]

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 35  168k   35 61062    0     0  64343      0  0:00:02 --:--:--  0:00:02 64275
curl: (23) Failed writing body (511 != 4229)
--2020-04-18 17:23:09--  https://nodejs.org/dist/latest-dubnium/node-v10.20.0-linux-armv6l.tar.gz
Resolving nodejs.org (nodejs.org)... 104.20.22.46, 104.20.23.46, 2606:4700:10::6814:162e, ...
Connecting to nodejs.org (nodejs.org)|104.20.22.46|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-18 17:23:10 ERROR 404: Not Found.

tar (child): node-v10.20.0-linux-armv6l.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove 'node-v10.20.0-linux-armv6l.tar.gz': No such file or directory
mv: cannot stat 'node-v10.20.0-linux-armv6l': No such file or directory
unlink: cannot unlink '/usr/bin/node': No such file or directory
unlink: cannot unlink '/usr/sbin/node': No such file or directory
unlink: cannot unlink '/sbin/node': No such file or directory
unlink: cannot unlink '/usr/local/bin/node': No such file or directory
unlink: cannot unlink '/usr/bin/npm': No such file or directory
unlink: cannot unlink '/usr/sbin/npm': No such file or directory
unlink: cannot unlink '/sbin/npm': No such file or directory
unlink: cannot unlink '/usr/local/bin/npm': No such file or directory
```

The file there is node-v10.20.1-linux-armv6l.tar.gz but the script doesn't pick it up and tries to install node-v10.20.0-linux-armv6l.tar.gz instead, which is not there hence why it fails.

I doubt I'll close this one minutes after opening it lol.

**Comment by SylvainGa** [comment]
Actually, this is more an issue with sdesalas repos so yeah, I'll close this one as well :-/

**Comment by mKeRix** [comment]
We might need to switch to a different install procedure for the Pi Zero - I'll have to do some research if there are other scripts that are still maintained. Sorry for the annoying issue, it's a recent change. There is quick workaround mentioned in mKeRix/ansible-playbooks#4 in the mean time.

**Comment by mKeRix** [comment]
Just checked the install repo and saw that @sdesalas updated the lts script an hour ago - hopefully that resolves the issue? Unfortunately I can't test it right at this moment.

**Comment by SylvainGa** [comment]
Nope, still got the 404 error :-(

**Comment by mKeRix** [comment]
Thanks for the direct link to the issue, I'll watch it for updates!

**Comment by SylvainGa** [comment]
It has been fixed apparently. Haven't tried it myself yet.

**Comment by SylvainGa** [comment]
Confirmed it's working. Thought I had another problem because I got
```
unlink: cannot unlink '/usr/bin/node': No such file or directory
unlink: cannot unlink '/usr/sbin/node': No such file or directory
unlink: cannot unlink '/sbin/node': No such file or directory
unlink: cannot unlink '/usr/local/bin/node': No such file or directory
unlink: cannot unlink '/usr/bin/npm': No such file or directory
unlink: cannot unlink '/usr/sbin/npm': No such file or directory
unlink: cannot unlink '/sbin/npm': No such file or directory
unlink: cannot unlink '/usr/local/bin/npm': No such file or directory
```
At the end of the script but then realized it's "normal" because the files aren't there to start with on a fresh installation.

**Comment by Mikomie** [comment]
Hi @SylvainGa 
i've also got the same "issue", should I just ignore this or will it result in issues with the install further on?
Ty
`node-v14.17.0-linux-armv 100%[==================================>]  30.77M  2.01MB/s    in 16s

2021-05-31 08:29:20 (1.91 MB/s) - ‘node-v14.17.0-linux-armv6l.tar.gz’ saved [32261575/32261575]

unlink: cannot unlink '/usr/bin/node': No such file or directory
unlink: cannot unlink '/usr/sbin/node': No such file or directory
unlink: cannot unlink '/sbin/node': No such file or directory
unlink: cannot unlink '/usr/local/bin/node': No such file or directory
unlink: cannot unlink '/usr/bin/npm': No such file or directory
unlink: cannot unlink '/usr/sbin/npm': No such file or directory
unlink: cannot unlink '/sbin/npm': No such file or directory
unlink: cannot unlink '/usr/local/bin/npm': No such file or directory
ln: failed to create symbolic link '/sbin/node': File exists
ln: failed to create symbolic link '/sbin/npm': File exists`

**Comment by k41zen** [comment]
I get the same issue too. Just blown away an old PI to see if a reinstall fixes it and am faced with this error.

**Comment by mKeRix** [comment]
@k41zen can you open a new issue with the command that you executed and the log messages that you saw?
