### ISSUE TITLE
Integration for Xiaomi Mi temperature humidity sensors

### ISSUE THREAD

**Issue by alan-strohm** [mKeRix/room-assistant#176]
**Is your feature request related to a problem? Please describe.**
I have an [E-Ink clock / LYWSD02MMC](https://item.mi.com/product/9542.html) in the same room as the rasberry pi which I am using for presence detection.  I'd like to use room assistant to report the temperature / humidity readings back to home assistant.

**Describe the solution you'd like**
I have a working patch that I'm willing to turn into a pull request.  I'm creating this feature request to reach agreement on the high level strategy before I spend time writing tests and cleaning things up.

The patch is largely based on the [homebridge-mi-hygrothermograph](https://github.com/hannseman/homebridge-mi-hygrothermograph) repos.   We listen for BLE advertisements from a configured list of devices and then attempt to parse the readings out of the service data.

There has been [some discussion](https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/84) on the homebridge repos about splitting it out into a lighter library.  I plan on reaching out to the maintainer about whether it's worth a separate package just for the parser or if we should copy it into this repos.

I use the EntityService to create a separate Sensor for each device + type of reading (temperature, humidity, battery, etc) that I see.  I then update the state on each new reading.

I tell noble to start / stop scanning on power state changes.  I've been running my new integration in parallel with the existing BLE integration and so far haven't had any problems.

**Describe alternatives you've considered**
I could run a different service on the device to listen for readings and publish them to MQTT.  I'm not sure if there any benefits to making sure everything goes through one instance of noble.

**Comment by mKeRix** [comment]
I think you can actually only have one instance of noble running at the same time, as it blocks other Bluetooth calls when it's doing something. Generally your approach sounds good to me from the high-level view.

My suggestion for continuing here would be: just create a PR based on what you have in the patch so far. That way I can already give some feedback and provide support where possible before you dive deeper into the other things.
