### ISSUE TITLE
RSSI Values on API for Known BT Classic and BLE Devices

### ISSUE THREAD

**Issue by paulrbeers** [mKeRix/room-assistant#177]
**Is your feature request related to a problem? Please describe.**
It's somewhat difficult/time consuming to dial in RSSI values for both BLE and BT Classic since every device is different

**Describe the solution you'd like**
Now that I am aware of the API, could we get the measured RSSI value?  Currently there is the distance calculated, but I'd love to be able to see the RSSI values so I can tweak the settings

**Describe alternatives you've considered**
Manually logging into each node (I have 10? now), stopping the room-assistant service and using HCITool for BT Classic and manually starting/stopping room-assistant to get the BLE values

**Additional context**
No I don't want to know all devices out there, just the ones I've spelled out in my local.yml file.

**Comment by mKeRix** [comment]
Great idea, that would certainly help for tuning the values! :)

**Comment by mKeRix** [comment]
This has been added in 2.8.0! :tada:
