### ISSUE TITLE
Add more information to attributes / JSON

### ISSUE THREAD

**Issue by ragenhe** [mKeRix/room-assistant#182]
I have setup a TIG stack and would like as much detail as possible for each device in the attributes topic in JSON format.

With this detail, a person could really hone in on each device / location / rssi value for optimal setup.

Thanks for considering.

**Comment by mKeRix** [comment]
I'm hesitant with adding new attributes to the entities, especially if they change a lot and do not provide a clear benefit. In the past I've had people complain that room-assistant sends too many updates over MQTT. At the moment I've brought the messages down to a good level and adding new attributes would also add more messages. With that said, I'm open to exposing more information via the (still unofficial) API of room-assistant (`http://<ip>:6415/entities`).

What kind of information are you looking for?

**Comment by ragenhe** [comment]
I was hoping to be able to grab more (or possibly all) information via the current attributes topic.  It is in JSON but only contains distance.  Adding RSSI, Instance, device, etc would complete the info needed to map out the values via (T)elegraf / (I)nflux / (G)rafana.  Those currently using distance from that topic wouldn't necessarily be negatively affected.

**Comment by ragenhe** [comment]
I think the data available via the api will suffice. I’m closing this now.
