### ISSUE TITLE
MQTT device tracker discovery in HA

### ISSUE THREAD

**Issue by jaburges** [mKeRix/room-assistant#183]
**Is your feature request related to a problem? Please describe.**
right now only sensors and switches are used. HA has a shameful lack of device_tracker template, or using binary_sensor for persons (making it very hard to use Room-Assistant to create a bluetooth mesh for presence)

**Describe the solution you'd like**
use the device_tracker MQTT template and have room-assistant send:
home if any room is detected
not_home if not_home is the payload

**Describe alternatives you've considered**
device_tracker doesnt allow for sensors, or binary sensors, it HAS to pull from MQTT (lame)
binary_sensor cant be used in `persons` (also lame)
device_tracker doesnt have a template option (even more lame)

**Additional context**
Room-Assistant is epic, and would love to natively bring in a device tracker to work around the HA limitations. Thanks

**Comment by basroovers** [comment]
You could use the `device_tracker.see` service as a work-around. I have an automation in node-red running where I pass the location to the `device_tracker.see` service, which I then use a a device_tracker in de person entity.

Documentation on the see service can be found here: https://www.home-assistant.io/integrations/device_tracker/#device_trackersee-service

**Comment by mKeRix** [comment]
Home Assistant doesn't support auto discovery for the MQTT device tracker unfortunately, but that doesn't stop us from at least providing the data and a sample configuration snippet. Should be simple enough. :)
