### ISSUE TITLE
Ansible Playbook upgrade not working

### ISSUE THREAD

**Issue by ragenhe** [mKeRix/room-assistant#190]
Running command listed in ansible playbook guide is not upgrading room-assistant.

I ran npm command with success on each pi and that method did work.

**Comment by mKeRix** [comment]
Yeah, I'm not sure if something changed there or I somehow got it wrong when I initially ran that command. At the moment I have to set `room_assistant_version: x.x.x` to the newest version in the `vars` for it to upgrade. I'll update the README/guide.

**Comment by mKeRix** [comment]
Updated the docs on the website!
