### ISSUE TITLE
HomeAssistantService: Couldn't connect to server

### ISSUE THREAD

**Issue by austwhite** [mKeRix/room-assistant#191]
**Describe the bug**
Trying to run room-assisant on a Raspberry Pi3, setup following exact instructions on webpage.
I am getting HomeAssistantService: Couldn't connect to server.
This is the only error I get.  Everything else is green.
I am sure this is something I am doing wrong, but I can't work it out.  The username and password I am using in the the mqttOptions is correctly setup in Home Assistant.

**To reproduce**
Every time I start room-assistant this happens

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```global:
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://homeassistant.local:1883'
  mqttOptions:
    username: ********
    password: *******
bluetoothClassic:
  addresses:
    - xx:xx:xx:xx:xx:xx
```
edit:  I also tried the IP address of the home assistant instance.
**Expected behavior**
Successful connection to MQTT.

**Environment**
 - room-assistant version: [2.5.0]
 - installation type: [NodeJS]
 - hardware: [e.g. Raspberry Pi 3]
 - OS: [Raspbian]

**Additional context**

**Comment by mKeRix** [comment]
Are you running the Mosquitto add-on for Home Assistant OS/Supervised? In that case make sure the logs of that are looking fine and the port is mapped correctly. Generally you can try `telnet homeassistant.local 1883` to see if there is something listening on that port.

**Comment by austwhite** [comment]
Hi @mKeRix
I am using the Mosquitto plugin for Home Assistant.
I am using Home Assistant 109.6 and Mosquitto Plugin version 5.1, which I believe is latest version.  I use Authentication, using HA users for Authentication.  I have a couple of other MQTT devices connecting up fine at this stage.
I have tried a clean install of Raspbian Buster light, only adding the core components need for room-assistant to work
I get green info messages for all steps excent the HomeAssistantService, which gives the red "error" and "Couldnt connect to server".
There is no error in the Home Assistant log.  There does not seem to be any entries in the Mosquitto log the Raspberry Pi, which has a static IP set.  It is as though there is no connection attempt to the server from the Pi.   
I will try the telnet in and let you know shortly how that goes.

**Comment by austwhite** [comment]
Ok.  Telnet gave this:
Note:  I do have my mqttURL set to mqtt://192.168.0.11:1883
pi@livingroom:~/room-assistant $ telnet 192.168.0.11 1883
Trying 192.168.0.11...
Connected to 192.168.0.11.
Escape character is '^]'.

**Comment by mKeRix** [comment]
Ok, well it's most likely not network issues then, especially if you already have other clients connected. Does your password contain special characters by any chance? In that case make sure they are escaped properly in the yaml.

From the Pi you can also verify that MQTT works with the `mosquitto_sub` command (part of the `mosquitto-clients` package). Unfortunately the MQTT library that we use doesn't give more detailed output on why the connection fails.

**Comment by austwhite** [comment]
No special characters in the password.  Just numbers and letters.
I'll give Mosquitto sub a go and let you know soon.

**Comment by austwhite** [comment]
I have no idea what I did this time.  I managed to mess up something on the pi and did a third clean install and this time it just worked, following the web page exactly like I did before.

I honestly have no idea what I did, but now it is working I will close this ticket off.   Darn computers.   
Thanks for trying to help me troubleshoot the issue.

**Comment by Taxy7** [comment]
hello,

i need help....im experience same error as "austwhite"...ive tryed all possible variatons.....please can you try to assist me on this problem ? 

im running  Hassio on Rpi4, booting from SSD, 


11/7/2020, 11:53:41 AM - error - HomeAssistantService: Couldn't connect to server

global:
  instanceName: Living Room
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.2:1883'
  mqttOptions:
    password: ********
    username: *******
bluetoothClassic:
  minRssi: -20
  addresses:
    - 'AE:*:*:*:*0:3f'

In Mosquito log im getting :  New connection from 192.168.1.2 on port 1883.
1604746932: Socket error on client <unknown>, disconnecting.


Thank you

**Comment by mKeRix** [comment]
@Taxy7 Could you post that config in a code block? Just so that we can see if the indentation is correct. The Mosquitto log you posted could be a lot of things, but the most likely one is something being wrong with the authentication.

**Comment by Taxy7** [comment]
hello mKeRix thank you for trying to help>)  What config do you mean from mosquitto or from room assistant?

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:44:24] INFO: Setting up Home Assistant configuration
[11:44:24] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
11/13/2020, 11:44:27 AM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-classic
11/13/2020, 11:44:28 AM - info - NestFactory: Starting Nest application...
11/13/2020, 11:44:29 AM - info - InstanceLoader: AppModule dependencies initialized
11/13/2020, 11:44:29 AM - info - InstanceLoader: ConfigModule dependencies initialized
11/13/2020, 11:44:29 AM - info - InstanceLoader: NestEmitterModule dependencies initialized
11/13/2020, 11:44:29 AM - info - InstanceLoader: IntegrationsModule dependencies initialized
11/13/2020, 11:44:29 AM - info - InstanceLoader: HttpModule dependencies initialized
11/13/2020, 11:44:29 AM - info - InstanceLoader: DiscoveryModule dependencies initialized
11/13/2020, 11:44:29 AM - info - InstanceLoader: ClusterModule dependencies initialized
11/13/2020, 11:44:29 AM - info - InstanceLoader: TerminusModule dependencies initialized
11/13/2020, 11:44:29 AM - info - InstanceLoader: BluetoothModule dependencies initialized
11/13/2020, 11:44:29 AM - info - InstanceLoader: ScheduleModule dependencies initialized
11/13/2020, 11:44:29 AM - info - InstanceLoader: EntitiesModule dependencies initialized
11/13/2020, 11:44:29 AM - info - InstanceLoader: HomeAssistantModule dependencies initialized
11/13/2020, 11:44:29 AM - info - InstanceLoader: BluetoothClassicModule dependencies initialized
11/13/2020, 11:44:29 AM - info - InstanceLoader: StatusModule dependencies initialized
11/13/2020, 11:44:29 AM - info - RoutesResolver: EntitiesController {/entities}:
11/13/2020, 11:44:29 AM - info - RouterExplorer: Mapped {/entities, GET} route
11/13/2020, 11:44:29 AM - info - RoutesResolver: StatusController {/status}:
11/13/2020, 11:44:29 AM - info - RouterExplorer: Mapped {/status, GET} route
11/13/2020, 11:45:00 AM - error - HomeAssistantService: Couldn't connect to server
11/13/2020, 11:45:00 AM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
11/13/2020, 11:45:00 AM - info - ClusterService: Starting mDNS advertisements and discovery
11/13/2020, 11:45:00 AM - info - NestApplication: Nest application successfully started

**Comment by Taxy7** [comment]
I removerd from configuration this lines

"homeAssistant:
  mqttUrl: 'mqtt://<mqtt-ip>:1883'
  mqttOptions:
    username: youruser
    password: yourpass"

and result:

11/13/2020, 12:27:27 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://core-mosquitto:1883
11/13/2020, 12:27:27 PM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-


I getting in in Integrations mqtt new device Living Room 

but just dies Entities: 
Living Room Cluster Leader
living-room
Living Room Cluster Size
1 instances 

but no my smartphone

**Comment by mKeRix** [comment]
I meant the config you posted in your original comment in this issue. Either way, when you see those sensors that means it has connected successfully. If your smartphone does not show up as an entity that just means room-assistant has not been able to detect the device yet. Maybe double check that BT is on and you're using the BT (not the WiFi!) MAC in the configuration.
