### ISSUE TITLE
Error installation pi Zero W

### ISSUE THREAD

**Issue by barthelemyguillaume** [mKeRix/room-assistant#198]
Hello,

I have an error when I try to install room-assistant on an Raspberry Pi Zero W (Buster).

With this command 
`wget -O - https://raw.githubusercontent.com/sdesalas/node-pi-zero/master/install-node-v.lts.sh | bash`

I have this result
`unlink: cannot unlink '/usr/bin/node': No such file or directory
unlink: cannot unlink '/usr/sbin/node': No such file or directory
unlink: cannot unlink '/sbin/node': No such file or directory
unlink: cannot unlink '/usr/local/bin/node': No such file or directory
unlink: cannot unlink '/usr/bin/npm': No such file or directory
unlink: cannot unlink '/usr/sbin/npm': No such file or directory
unlink: cannot unlink '/sbin/npm': No such file or directory
unlink: cannot unlink '/usr/local/bin/npm': No such file or directory`

**Comment by mKeRix** [comment]
That's normal and nothing to worry about - the start of the script tries to uninstall previous node versions before installing. If you didn't have anything installed it will log these messages, but still continue on fine. If you're seeing other issues with the script it would be best to open an issue at [sdesalas/node-pi-zero](https://github.com/sdesalas/node-pi-zero), as the install script as maintained there (not by me).
