### ISSUE TITLE
Recommended Micro SD Card class

### ISSUE THREAD

**Issue by Royal2000H** [mKeRix/room-assistant#200]
Under the Quick Starts for Raspberry Pi Zero W and Pi 3/4, the guides mention:

> Micro SD Card (ideally Application Class 2 or better)

In my research, A2 is actually not only not preferable but may be worse than A1 in Raspberry Pis (and most devices) since they don't support the required hardware to make use of the added features in A2. When they don't have this added hardware, they often have worse performance than A1. Worse yet, they're often significantly more expensive than A1.

I figured I would mention this as the current guides steer people toward A2 cards.

Sources: [1](https://android.stackexchange.com/questions/214545/should-i-get-a1-or-a2-specd-micro-sd-card-for-my-phone) [2](https://www.raspberrypi.org/forums/viewtopic.php?t=239154) [3](https://www.jeffgeerling.com/blog/2019/a2-class-microsd-cards-offer-no-better-performance-raspberry-pi) [4](https://www.jeffgeerling.com/blog/2019/raspberry-pi-microsd-follow-sd-association-fools-me-twice) [5](https://github.com/ThomasKaiser/Knowledge/blob/master/articles/A1_and_A2_rated_SD_cards.md)

**Comment by mKeRix** [comment]
Thanks for the hint and all the sources you linked! When I wrote the guide I lifted the A2 recommendation from the Home Assistant Getting Started guide I think. I will update the recommendation to A1 in the room-assistant docs.

**Comment by Royal2000H** [comment]
Good point, I don't think I ever noticed it in the HA guides. Only noticed it in RA because I just bought some Pi Zeros to try to set up this week and then did a bunch of research. I'll make sure to submit the same thing over on their Github.
