### ISSUE TITLE
ERROR [supervisor.docker] Can't create container from <room_assistant>: 404 Client Error: Not Found ("No such image: mkerix/room-assistant-armhf:2.7.1")

### ISSUE THREAD

**Issue by dabozz88** [mKeRix/room-assistant#202]
**Describe the bug**
room-assistant on Hass.io not loading

**Comment by mKeRix** [comment]
I just verified that I could pull exactly the image you specified in the title (by copy-pasting). You can also view that it's available on [Docker Hub](https://hub.docker.com/repository/docker/mkerix/room-assistant-armhf/tags?page=1). Did this problem appear when upgrading or installing? Do you have trouble installing other add-ons too?

**Comment by dabozz88** [comment]
I have the add-on set to auto update. 

I will try uninstalling and reinstalling, and I suspect that will work. That was next on my to-do. Just a busy day today.

**Comment by mKeRix** [comment]
Ah - in that case I suspect that the auto-update triggered between the time the new version was committed to GitHub and the time it was done building and uploaded to Docker Hub. The timeframe in which that could've happened is about [13min after the commit](https://github.com/mKeRix/hassio-repo/runs/712116994?check_suite_focus=true).

**Comment by dabozz88** [comment]
Yep, reinstalling fixed it. 

13 minutes of unluckiness? With the rest of the good luck I've had today, I'll take it. 

Sorry for the trouble, didn't know about the additional docker stuff. Still learning some of this stuff.

**Comment by mKeRix** [comment]
No problem, glad you could fix it. :)
