### ISSUE TITLE
Add per instance BLE calibration value

### ISSUE THREAD

**Issue by marrold** [mKeRix/room-assistant#204]
**Is your feature request related to a problem? Please describe.**

I am using 3x instances of room-assistant with the BLE detection. They're frequently reported as being in the wrong location.

I have tested the device at ~1M away from each instance, and one reports the RSSI as 10 dBm stronger that the other instances. Weirdly, it's an identical Pi, in an identical case, so I assume this is some internal calibration thing with the Pi itself. 

**Describe the solution you'd like**

I think a good solution would be a per instance calibration value. In my case it would be `-10` 

This would also help users using Pi's in different cases etc which may report different RSSI values

**Describe alternatives you've considered**

I could use Tag Overrides but it gets a bit messy.

I've checked if it's possible to calibrate BLE at an OS level, but I couldn't find anything. 

Thanks!

**Comment by mKeRix** [comment]
Yeah, afaik the BLE output cannot be configured on the OS level, not on the Pis at least. Could you provide some more details on why you think using `tagOverrides` would get messy? To me it seems like this feature would solve your issue.

**Comment by marrold** [comment]
I will try to get more accurate results with #203 and let you know. 

I think if one Pi is consistently 10dBm higher it's just cleaner to have a "global" setting for the instance.

**Comment by marrold** [comment]
I think this one can be closed, thanks!
