### ISSUE TITLE
Automatic reconnect to MQTT Broker on broker restart

### ISSUE THREAD

**Issue by georgeinva2004** [mKeRix/room-assistant#208]
**Is your feature request related to a problem? Please describe.**
room-assistant nodes do not appear to automatically reconnect to my MQTT broker when the broker is restarted.

**Describe the solution you'd like**
Detection of a broker disconnect and periodic reconnect attempts

**Describe alternatives you've considered**
N/A

**Additional context**
Love the work!!!!!  I hope I didn't miss something obvious before I made this request.

**Comment by mKeRix** [comment]
In theory room-assistant should already try to reconnect to the MQTT at a 1 second interval - this is part of the library we use and documented [here](https://www.npmjs.com/package/mqtt#enabling-reconnection-with-reconnectperiod-option). I haven't run into issues with this before - but I also didn't explicitly test this to be fair.

I'll try restarting my MQTT server in a bunch of different ways and will observe the room-assistant behavior when I have some time. That way I can make sure everything works as intended. :)

**Comment by georgeinva2004** [comment]
Yeah, it could just be me.  My last test was to restart my broker while MQTT.fx was connected.  As expected MQTT.fx disconnected and I had to manually reconnect. I then subscribed to room-assistant/# and I didn't see any activity.  I had to restart each of the nodes before I saw any activity related to room-assistant.   If it helps, the log file on the room-assistant nodes didn't note a disconnect.

**Comment by mKeRix** [comment]
I just tested it with my Mosquitto add-on instance - all of my nodes reconnected shortly after restarting the add-on. I tried it with the normal restart button and by hitting stop, waiting for a little while and then starting again. Maybe it was a one-time issue?

**Comment by georgeinva2004** [comment]
Probably.  What do you think about having nodes that detect a reconnect with the broker report their state to the broker.  Maybe reusing the cluster-state messages.   That would ensure that all subscribers get to a known state after a broker restart.

**Comment by mKeRix** [comment]
Good point! We should at least make sure that the state is in sync after a reconnect. Could you open a short follow up issue with this suggestion?
