### ISSUE TITLE
SIGSEGV when running with Docker on a Pi Zero

### ISSUE THREAD

**Issue by ensjens** [mKeRix/room-assistant#210]
I'm unable to run the latest image on a Pi Zero; it exits every time with status code 139. Here's my `docker version` output:
```
Client: Docker Engine - Community
 Version:           19.03.10
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9424aea
 Built:             Thu May 28 22:24:06 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.10
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9424aea
  Built:            Thu May 28 22:18:05 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

_Originally posted by @akonradi in https://github.com/mKeRix/room-assistant/issues/155#issuecomment-637089527_

**Comment by ensjens** [comment]
I have this same issue on a Pi Zero W
exits with status code 139

tried it with room-assistant:2.6.0, 2.7.1 and 2.8.1 and got the same error.
docker log remains empty

**Comment by RomRider** [comment]
That's because Docker select the image for arm7 and raspberry pi zero is arm6.
You'll need to use the digest of the image unfortunately.

It's unrelated to room-assistant but related to https://github.com/moby/moby/issues/37647

**Comment by mKeRix** [comment]
Thanks for the heads up @RomRider!

**Comment by sstratoti** [comment]
Just want to add a quick comment.
By using docker-compose version 2.4, you can specify the platform to pull, so you don't have to specify a digest.

Example:

```
version: '2.4'
services:
  room-assistant:
    image: mkerix/room-assistant
    platform: linux/arm/v6
```
By doing this, it'll pull the arm/v6 version.
HTH someone else, cause I was banging my head all afternoon...
@mKeRix  - you might want to put a note about this in the docker-compose section of the docs?

**Comment by eifinger** [comment]
And for those of you who like me found this issue and tried @sstratoti solution but it still didn't work:
It might be that docker will still use the pulled image. Execute `docker system prune -a` to remove all images and then try to run `docker-compose` with the platform added.
