### ISSUE TITLE
Unable to leave room

### ISSUE THREAD

**Issue by v-sante** [mKeRix/room-assistant#212]
**Describe the bug**

I have set up tracking of Apple Watch on RPB3+ installed as add-on in HA.  It reads it fine.

I have had to set timeout cycles to 10 to get it to not randomly report not_home.   This seems to me to be a serious ongoing problem but I can see it has been raised before.

My issue is with minRSSI.  I have set it to -1 (having tried more reasonable figures one might expect for minRSSI (e.g. -45 for a short distance).  I have tried it both on the RP bluetooth adapter and on a separate USB dongle put into the RP. No difference.

However, I'm never actually out of the room until I think I'm completely out of range of the RP bluetooth (e.g. 20+ metres away).  I'm looking at the MQTT distance measures and they all are reported, always around 0-2 in the room where the RP is and 4+ outside.  So I can't understand why its not changing the state to "not_home".

**To reproduce**

Not sure - not an apparent bug I've seen others report.  Situation as above

**Relevant logs and config**

```MQTT:

Received 2:49:43 PM
QoS: 0
Payload: distance: 4.3
last_updated_at: '2020-06-04T13:49:43.318Z'

Received 2:19:50 PM
QoS: 0
Payload: Office```

YAML:

```global:
  instanceName: Office
  integrations:
    - homeAssistant
    - bluetoothClassic
bluetoothClassic:
  device: 1
  timeoutCycles: 10
  minRSSI: -1
  addresses:
    - 'xx:xx:xx:xx:xx:xx'
```

**Expected behavior**
Should update to "not_home" when at some distance from the RP.

**Environment**
 - room-assistant version:2.8.1
 - installation type: HA add-on
 - hardware:: RP3B+ with and without dongle
 - OS: HA

**Additional context**
Only registers as not home where it can get no distance measurement at all

**Comment by v-sante** [comment]
> **Describe the bug**
> 
> I have set up tracking of Apple Watch on RPB3+ installed as add-on in HA. It reads it fine.
> 
> I have had to set timeout cycles to 10 to get it to not randomly report not_home. This seems to me to be a serious ongoing problem but I can see it has been raised before.
> 
> My issue is with minRSSI. I have set it to -1 (having tried more reasonable figures one might expect for minRSSI (e.g. -45 for a short distance). I have tried it both on the RP bluetooth adapter and on a separate USB dongle put into the RP. No difference.
> 
> However, I'm never actually out of the room until I think I'm completely out of range of the RP bluetooth (e.g. 20+ metres away). I'm looking at the MQTT distance measures and they all are reported, always around 0-2 in the room where the RP is and 4+ outside. So I can't understand why its not changing the state to "not_home".
> 
> **To reproduce**
> 
> Not sure - not an apparent bug I've seen others report. Situation as above
> 
> **Relevant logs**
> 
> MQTT
> 
> ```
> QoS: 0
> Payload: distance: 4.3
> last_updated_at: '2020-06-04T13:49:43.318Z'
> 
> Received 2:19:50 PM
> QoS: 0
> Payload: Office```
> 
> **Relevant configuration**
> Paste the relevant parts of your configuration below.
> 
> ```global:
>   instanceName: Office
>   integrations:
>     - homeAssistant
>     - bluetoothClassic
> bluetoothClassic:
>   device: 1
>   timeoutCycles: 10
>   minRSSI: -1
>   addresses:
>     - 'xx:xx:xx:xx:xx:xx'
> ```
> 
> **Expected behavior**
> Should update to "not_home" when at some distance from the RP.
> 
> **Environment**
> 
> * room-assistant version:2.8.1
> * installation type: HA add-on
> * hardware:: RP3B+ with and without dongle
> * OS: HA
> 
> **Additional context**
> Only registers as not home where it can get no distance measurement at all

**Comment by v-sante** [comment]
Just to say I gave up on trying to get it to work sensibly and instead extracted the MQTT distance data into Node-Red and wrote my own rules on what distances should qualify as which room.

It seems to me you should be able to acheive trilaterlation in Node-Red with just 3 Pis, by going into the relevant rooms and observing the data and allowing a little margin/smoothing.

**Comment by mKeRix** [comment]
The capitalization in your config has a small mistake, it should be `minRssi` and not `minRSSI` (see the [docs](https://www.room-assistant.io/integrations/bluetooth-classic.html#settings)). Other than that you can also check what's happening in more detail with the entities endpoint of the [API](https://www.room-assistant.io/guide/api.html).

There is an open feature request for triangulation at #17 - I still have some doubts in regards to the data quality, but it's worth a shot.
