### ISSUE TITLE
Easier cluster configuration

### ISSUE THREAD

**Issue by danpowell88** [mKeRix/room-assistant#213]
Having a pi in every room is great but when I need to make a config change I need to log into 6+ pis and update them.

It would be great if we could just post the config yaml to a mqtt topic and the pis load their configuration from that (they would of course at a minimum need a mqtt connection in their config)

Or is there another easier way to configure and maintain the clusters?

**Comment by gbdavidx** [comment]
https://kubernetes.io/

**Comment by georgeinva2004** [comment]
You might want to check this out.  

[https://github.com/mKeRix/ansible-playbooks](url)

**Comment by danpowell88** [comment]
> You might want to check this out.
> 
> [https://github.com/mKeRix/ansible-playbooks](url)

Ah Excellent, I dont suppose theres an easy way to define all the IPs and have them include all but the current pis ips in the cluster config, unless it doesnt matter if its there?

**Comment by georgeinva2004** [comment]
I'm not exactly sure what your asking. There's a hosts.yml file used by the room assistant ansible playbook that defines the the IPs you want to include.    The setup is pretty cool. I'm mainly using it now to add bluetooth addresses without editing the configuration files in all my pis.

**Comment by mKeRix** [comment]
As @georgeinva2004 stated, Ansible is the tool of choice for what you're trying to achieve. I purposefully did not build this feature into room-assistant as there are already other tools that can do deployment much better than I could.

There is also a [quickstart guide](https://www.room-assistant.io/guide/quickstart-ansible.html) available on the website if you're interested.

**Comment by mKeRix** [comment]
>  I dont suppose theres an easy way to define all the IPs and have them include all but the current pis ips in the cluster config, unless it doesnt matter if its there?

Oh and, it doesn't matter if the current IP is in the configured IPs - it will just be ignored. I have all configured under `room_assistant_global_config`. :)
