### ISSUE TITLE
BLE does not find my 2 galaxy S9's

### ISSUE THREAD

**Issue by huuub** [mKeRix/room-assistant#216]
If I enable BLE, which I hope is more accurate then the classic I can't find my 2 phones (both are samasung galaxy s9). 
Why is that?

**Comment by mKeRix** [comment]
Most phones do not broadcast on BLE constantly by default - and if they do, they usually use randomized addresses (BLE privacy feature). Usually you would want to stick to BT Classic for phones. On Android you can use an app to turn your phone into a BLE beacon though, which would make it discoverable for the BLE integration as well.
