### ISSUE TITLE
Apple Watch isn't being scanned from certain node(s) in cluster

### ISSUE THREAD

**Issue by yetdog** [mKeRix/room-assistant#223]
**Describe the bug**
This has worked up to this point, but after upgrading to 2.8.2 (not sure if it's version related or just transient), my "Office" RA node doesn't scan for my Apple Watch. The rest of the nodes see it.

**To reproduce**
Run Room-assistant

**Relevant logs**

```2020-06-18T16:50:40-07:00 officePi room-assistant[237]: 6/18/2020, 4:50:40 PM - debug - BluetoothClassicService: Received RSSI of -14.4 for <my iPhone Mac> from Office
2020-06-18T16:50:53-07:00 officePi room-assistant[237]: 6/18/2020, 4:50:53 PM - debug - BluetoothClassicService: Received RSSI of 0 for <Wife's iPhone Mac> from Office


When manually running a scan against Apple Watch MAC:
root@officePi:/home/pi/room-assistant/config# hcitool -i hci0 cc "<Apple Watch MAC>" && hcitool -i hci0 rssi "<Apple Watch MAC>"
RSSI return value: 1
```

^^^Point being that my Apple Watch does not show up in the logs, but responds properly when manually scanning. The watch MAC is in the relevant config files, as I have deployed using ansible playbooks.

**Relevant configuration**
Paste the relevant parts of your configuration below.

```root@officePi:/home/pi/room-assistant/config# cat local.yml 
bluetoothClassic:
    minRssi: -8
global:
    instanceName: Office
    integrations:
    - homeAssistant
    - bluetoothClassic

root@officePi:/home/pi/room-assistant/config# cat officePi.yml 
bluetoothClassic:
    addresses:
    - <my iphone MAC>
    - <apple watch MAC>
    - <wife's iphone MAC>
    interval: 6
global:
    integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
    mqttOptions:
        password: <mqtt password>
        username: <mqtt user>
    mqttUrl: <MQTT URL>
```

**Expected behavior**
I would expect the Office node (where I'm sitting) to scan/report presence of my watch as I wear it.

**Environment**
 - room-assistant version: 2.8.2
 - installation type: NodeJS / Ansible Playbook
 - hardware: Pi 0W
 - OS: Raspbian

**Comment by mKeRix** [comment]
The leader node determines which addresses are scanned by which node (in a round robin fashion). Is the Watch MAC also present in the configuration of the leader? Ideally `bluetoothClassic.addresses` should be the same across all nodes.

If it's already in there, have you tried restarting the leader/all nodes?

**Comment by yetdog** [comment]
Thanks for the response @mKeRix - I ended up downgrading to 2.6.0 (via ansible) and it fixed things. I hadn't restarted ALL nodes so I'm going to bring things back up to the latest version and confirm all looks good.

**Comment by yetdog** [comment]
Restarting all nodes seemed to do the trick, even at the latest version. Thanks.

Side note - let me know if i need to open a new ticket - but is there a reason I have two clusters, (across 5 nodes, all 5 nodes members of both clusters?)

I have:
- kitchen-status-cluster-leader
- kitchen-status-cluster-size
- bedroom-status-cluster-leader
- bedroom-status-cluster-size

**Comment by mKeRix** [comment]
If all 5 nodes are listed in the clusters, then you only have 1 cluster. room-assistant registers these cluster sensors per node (if you have the `homeAssistant` integration enabled on all of them you will see these 5 times in HA). This is done to help people find split clusters and other oddities in their setup. So no worries. :)
