### ISSUE TITLE
Room Assistant via Ansible returns "Failed to connect to the host via ssh"

### ISSUE THREAD

**Issue by circa1741** [mKeRix/room-assistant#225]
**Describe the bug**

I am trying to use Ansible to install room-assistant to a Raspberry Pi Zero W.

When executing "ansible-playbook -i hosts.yml -u pi room-assistant.yml" (no quotes), i get:

<ipaddress> (255, '', "Warning: Permanently added 'ipaddress' (ECDSA) to the list of known hosts.\r\npi@ipaddress: Permission denied (publickey,password).\r\n")
fatal: [ipaddress]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'ipaddress' (ECDSA) to the list of known hosts.\r\npi@ipaddress: Permission denied (publickey,password).",
    "unreachable": true
}

**To reproduce**

1. Complete step #s 1-7 as per the Raspberry Pi Zero W : Installing Raspbian Quickstart in the room-assistant guide.
2. Install Ansible as per the Ansible documentation appropriate for your environment.
3. Complete step #s 2-4 as per the Ansible Quickstart in the room-assistant guide.
3. Now, execute the playbook with:
ansible-playbook -i hosts.yml -u pi room-assistant.yml -vvv
(see step # 5 as per the Ansible Quickstart in the room-assistant guide)

**Relevant logs**

ansible-playbook 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/opsadm/ansible-playbooks/hosts.yml as it did not pass its verify_file() method
script declined parsing /home/opsadm/ansible-playbooks/hosts.yml as it did not pass its verify_file() method
Parsed /home/opsadm/ansible-playbooks/hosts.yml inventory source with yaml plugin
statically imported: /home/opsadm/ansible-playbooks/roles/nodejs/tasks/armv6.yml
statically imported: /home/opsadm/ansible-playbooks/roles/geerlingguy.nodejs/tasks/setup-RedHat.yml
statically imported: /home/opsadm/ansible-playbooks/roles/geerlingguy.nodejs/tasks/setup-Debian.yml

PLAYBOOK: room-assistant.yml ****************************************************************
1 plays in room-assistant.yml

PLAY [all] **********************************************************************************

TASK [Gathering Facts] **********************************************************************
task path: /home/opsadm/ansible-playbooks/room-assistant.yml:2
<ipaddress> ESTABLISH SSH CONNECTION FOR USER: pi
<ipaddress> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="pi"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/43b56f0c0f ipaddress '/bin/sh -c '"'"'echo ~pi && sleep 0'"'"''
The authenticity of host 'ipaddress (ipaddress)' can't be established.
ECDSA key fingerprint is SHA256:WZzKulDgzdcbA8bDqQyHNVxFidPyOevzTFMmzDuojqc.
Are you sure you want to continue connecting (yes/no)? yes
<ipaddress> (255, '', "Warning: Permanently added 'ipaddress' (ECDSA) to the list of known hosts.\r\npi@ipaddress: Permission denied (publickey,password).\r\n")
fatal: [ipaddress]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'ipaddress' (ECDSA) to the list of known hosts.\r\npi@ipaddress: Permission denied (publickey,password).",
    "unreachable": true
}

PLAY RECAP **********************************************************************************
ipaddress              : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

**Relevant configuration**

see attached file
[hosts.yml.txt](https://github.com/mKeRix/room-assistant/files/4841130/hosts.yml.txt)

**Expected behavior**
Should successfully install the required dependencies and room-assistant as a service on ip address of pi zero w as per **Relevant configuration** section above.

**Environment**
 - room-assistant version: unsuccessfully installed via Ansible
 - installation type: Hassio on laptop with Proxmox VM
 - hardware: Raspberry Pi Zero W
 - OS: Debian Buster

**Additional context**
I used sudo when executing:
ansible-playbook -i hosts.yml -u pi room-assistant.yml -vvv

**Comment by circa1741** [comment]
I got past this issue by adding ansible_user and ansible_password as per the example in https://github.com/mKeRix/ansible-playbooks#options.

Thanks

**Comment by cjramseyer** [comment]
This also requires sshpass to be installed on your linux box.  I seemed to have gotten this working using this method.  Please include these steps in the instructions
