### ISSUE TITLE
ESPHome Nodes to the clusture

### ISSUE THREAD

**Issue by haddood** [mKeRix/room-assistant#226]
**Is your feature request related to a problem? Please describe.**
having raspberrypi  in every room is a bit over kill. 

**Describe the solution you'd like**
have ESPHome (or just ESP32s) Nodes ...  in theory even ESP8266 can be used based on wifi signal strength 

**Additional context**
already having multiple ESP32s around the house with sensors, the do report wifi and bluetooth signals strength ... it will be ideal if we can add an ESPhome module so the report to the main leader that is an addon on raspberry pi that runs HASS

**Comment by mKeRix** [comment]
While this would certainly be cool to have, it's not something that I plan to look at as part of this project. It would require significant effort (and maintenance) in a language and other project that I'm not really comfortable in. I'm happy to help out anyone that wants to write the integration in ESPHome with my knowledge on the communication needed for room-assistant though.
