### ISSUE TITLE
error - BluetoothClassicService: Command failed:

### ISSUE THREAD

**Issue by n1rvn** [mKeRix/room-assistant#228]
**error - BluetoothClassicService: Command failed: hcitool -i hci0 cc "MAC" && hcitool -i hci0 rssi "MAC"
Invalid device: No such device**

**My Configuration**

global:
  instanceName: livingroom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://MY_MQTT_BROKER:1883'
  mqttOptions:
    username: MY_USER
    password: MY_PASS
bluetoothClassic:
  minRssi: -20
  hciDeviceId: 0
  addresses:
    - 'MAC'

**Environment**
 - room-assistant version: 2.8.2
 - installation type: Hass.io
 - hardware: VBox
 - OS: macOS

**Full Log**

```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:17:47] INFO: Setting up Home Assistant configuration
[18:17:47] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
7/5/2020, 6:17:50 PM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-classic
7/5/2020, 6:17:50 PM - info - NestFactory: Starting Nest application...
7/5/2020, 6:17:50 PM - info - InstanceLoader: AppModule dependencies initialized
7/5/2020, 6:17:50 PM - info - InstanceLoader: ConfigModule dependencies initialized
7/5/2020, 6:17:50 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
7/5/2020, 6:17:50 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
7/5/2020, 6:17:50 PM - info - InstanceLoader: HttpModule dependencies initialized
7/5/2020, 6:17:50 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
7/5/2020, 6:17:50 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized
7/5/2020, 6:17:50 PM - info - InstanceLoader: ClusterModule dependencies initialized
7/5/2020, 6:17:50 PM - info - InstanceLoader: TerminusModule dependencies initialized
7/5/2020, 6:17:50 PM - info - InstanceLoader: ScheduleModule dependencies initialized
7/5/2020, 6:17:50 PM - info - InstanceLoader: EntitiesModule dependencies initialized
7/5/2020, 6:17:50 PM - info - InstanceLoader: BluetoothClassicModule dependencies initialized
7/5/2020, 6:17:50 PM - info - InstanceLoader: StatusModule dependencies initialized
7/5/2020, 6:17:51 PM - info - RoutesResolver: EntitiesController {/entities}:
7/5/2020, 6:17:51 PM - info - RouterExplorer: Mapped {/entities, GET} route
7/5/2020, 6:17:51 PM - info - RoutesResolver: StatusController {/status}:
7/5/2020, 6:17:51 PM - info - RouterExplorer: Mapped {/status, GET} route
7/5/2020, 6:17:51 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://MY_MQQT
7/5/2020, 6:17:51 PM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
7/5/2020, 6:17:51 PM - info - ClusterService: Starting mDNS advertisements and discovery
7/5/2020, 6:17:51 PM - info - NestApplication: Nest application successfully started
7/5/2020, 6:17:53 PM - info - ClusterService: livingroom has been elected as leader
7/5/2020, 6:17:53 PM - info - EntitiesService: Refreshing entity states
7/5/2020, 6:17:57 PM - error - BluetoothClassicService: Command failed: hcitool -i hci0 cc "MAC" && hcitool -i hci0 rssi "MAC"
Invalid device: No such device 
```

**Comment by mKeRix** [comment]
As the error states, the Bluetooth device `hci0` (which is used by default) does not exist on your machine. If you have SSH available (e.g. via the SSH add-on) you can go in there and type `hciconfig` to see available devices. You can then use the `hciDeviceId` option to use the correct device.

If there are no HCI devices listed make sure that you have setup your VM correctly for passing on the Bluetooth interface.

**Comment by n1rvn** [comment]
i get
-bash: hciconfig: command not found home
when running the hciconfig command, is there any other way to check my Bluetooth device name?

**Comment by Colorado4Wheeler** [comment]
I'm having this exact problem, except I do have an hci0.  On my HA system using the add-on, everything works great, but on an identical Pi I get the same errors as above:

```
Jan 24 16:07:23 raspberrypi room-assistant[16258]: 1/24/2021, 16:07:23 - error - BluetoothService: Command failed: hcitool -i hci0 cc "d4:a3:3d:f0:sa:12" && hcitool -i hci0 rssi "d4:a3:3d:f0:sa:12"
Jan 24 16:07:23 raspberrypi room-assistant[16258]: Can't create connection: Operation not permitted
Jan 24 16:07:23 raspberrypi room-assistant[16258]: Get connection info failed: No such file or directory
```

And when I type hciconfig:

```
pi@raspberrypi:~/room-assistant/config $ hciconfig
hci0:	Type: Primary  Bus: UART
	BD Address: DC:A6:32:DC:41:C2  ACL MTU: 1021:8  SCO MTU: 64:1
	UP RUNNING 
	RX bytes:1640 acl:0 sco:0 events:100 errors:0
	TX bytes:2590 acl:0 sco:0 commands:100 errors:0
```

**Comment by n1rvn** [comment]
I'm not an expert but did you try switching it to hci1?

The method mentioned above to see the ID I don't believe worked for me

**Comment by Colorado4Wheeler** [comment]
No, that didn't work, but I didn't expect it to since my HA Pi is an identical Pi 4B and it works there on hci0.  Good recommendation, though.

**Comment by mKeRix** [comment]
@Colorado4Wheeler Is your problem installation running it directly on NodeJS? Did you run the commands stated [here](https://www.room-assistant.io/integrations/bluetooth-low-energy.html#requirements)?

**Comment by Colorado4Wheeler** [comment]
No, I did not!  I was running classic so I just ran the instructions [here](https://www.room-assistant.io/integrations/bluetooth-classic.html#requirements) and restarted RA and it fixed it!  Thank you for that!  I'll do the same for BLE.

**Comment by kjell5317** [comment]
I've got the same issue while running Bluetooth classic and BLE on the same RPI 4 with an additional external Bluetooth adapter.

## My configuration:

`global:
  instanceName: name
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://<IP>:1883'
  mqttOptions:
    username: mqtt
    password: password

bluetoothLowEnergy:
  hciDeviceId: 0
  allowlist:
  - 'uuid'

bluetoothClassic:
 hciDeviceId: 1
 addresses:
   - 'mac'`

The command `hciconfig` doesn't work and `ls -la /dev` doesn't show anything starting with hci. But `bluetoothctl` followed by `list` shows 2 Bluetooth controllers with their MAC address, but I don't know how to resolve the hciDeviceId or what to do with their names.

## My environment:

room assistant:  2.18.4
home-assistant OS: 6.1

**Comment by mKeRix** [comment]
@kjell5317 Home Assistant OS is a bit special with this stuff - I honestly don't know if USB adapters will work in the current state of the add-on, never tried. I'd recommend you open a new issue for this and I'll see if I can try some stuff with my OS installation.
