### ISSUE TITLE
Feature request: extending mqtt output with timestamp, raw data, major, minor, MAC+UUID

### ISSUE THREAD

**Issue by gruijter** [mKeRix/room-assistant#25]
Hello Heiko,

First of all: Great work, thanks!

I want to use it to for presence detection  in my house and maybe indoor tracking, also for occasional visitors. I have now set it up on a rpi3 for the 'ble' tracker, because I think that will catch the most devices (iBeacons, ble tags, Eddystone, whatever ...)

However, to be able to better do what I want to achieve I could really need some additional information in the mqtt messages:
-id: I would like to always have the mac address here (and this is how I now configured room-assistant)
-raw data: don't know what I want to do with this yet, but I think it can be very useful
-timestamp: timestamp of moment of reception of the signal (epoch format)
-iBeacon uuid: could you please add this as a separate property?
-iBeacon major/minor: don't know what I want to do with this yet, but I think it can be very useful
-Eddystone namespace: don't know what I want to do with this yet, but I think it can be very useful
-Eddystone instance_id: don't know what I want to do with this yet, but I think it can be very useful

Would it be possible to add these properties in a next release please?

Much appreciated!

**Comment by gruijter** [comment]
Any feedback on this? See also my post #15 concerning filtering out unwanted mac adresses of iBeacons

Thx!

**Comment by mKeRix** [comment]
Woops, I wanted to reply to this at least a week ago and it totally slipped my mind - sorry!

So...

- ID/MAC: so you want a new field to contains the MAC address regardless of the config option for id?
- Raw data: as in the full information of the BLE advertisement?
- Timestamp: I can generate one in the receiving function and publish it to the MQTT, if that is alright.
- iBeacon stuff: this can be done with the iBeacon component, I will check your other ticket as it is probably related.
- Eddystone stuff: noted, but placing this on low priority for now.

Overall a solid list of suggestions, most of which should be easy to integrate.
