### ISSUE TITLE
forever-service fails due to swig no longer available.....

### ISSUE THREAD

**Issue by dd3uk** [mKeRix/room-assistant#26]
Hi,

everything went well until the last step of the setup about making it a service. the forever service app install seemed to say it wasn't valid anymore and then the final step won't work.... Im no linux expert, I can follow instructions but could do with some advice on how to finalise the install (and maybe the instructions need revising too for others) thanks :)Hi,

npm WARN deprecated swig@1.4.2: This package is no longer maintained

**Comment by PeteBa** [comment]
@dd3uk , not sure about forever service but I use the built-in systemd on my raspberry pi to automate the start-up and monitoring of the service as follows:

1) Use "nano" or your favourite editor to create the systemd service file:

```peter@RPZ:~ $ sudo nano /etc/systemd/system/room-assistant.service```

2) Populate the service file with the following (changing WorkingDirectory as required):
```
[Unit]
Description=Room Assistant service

[Service]
ExecStart=/usr/bin/npm start
WorkingDirectory=/home/peter/room-assistant
StandardOutput=null
StandardError=journal
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

3) You can then use the following commands to enable and start the service:

```
peter@RPZ:~ $ sudo systemctl enable room-assistant.service
peter@RPZ:~ $ sudo systemctl start room-assistant.service
```

4) And finally, the following to make sure it is running as expected:

```peter@RPZ:~ $ systemctl status room-assistant.service```

**Comment by dd3uk** [comment]
thank you peter... that all works perfectly 👍

**Comment by mKeRix** [comment]
For distros with systemd this is probably an even better solution - thanks @PeteBa! I will include that in the README as the new recommend method. :)
