### ISSUE TITLE
can room-assistant track any smart device that is bluetooth compatible?

### ISSUE THREAD

**Issue by gbdavidx** [mKeRix/room-assistant#260]
Not really a bug but a question...
For example, instead of relying on a watch to wear all time (though i dont mind it if this is the only option), I wanted to know if it could track glasses such as these https://vueglasses.com/collections/eyeglasses/products/eyeglasses-trendy?variant=34099542392876 with bluetooth 4.2.  These would be on my face 24/7 except when im asleep

**Comment by andrelung** [comment]
The glasses need to somehow advertise the bluetooth or answer connection requests. I own a Withings Steel HR, which seems not to do this and I recently purchased a Mi Band, which doesn't do it either. However, my laptop does answer, so at least I can track my laptop.
So... it completely depends on the implementation of the device.

**Comment by gbdavidx** [comment]
can it connect by "pairing"?

**Comment by mKeRix** [comment]
As mentioned, this really is up to a bunch of different factors and will often times require trials & error. Maybe you could also ask the manufacturer for some details on their Bluetooth implementation before buying, but I don't know how knowledgeable the support will be on this topic.

Generally you can make a few assumptions:
- BLE-only devices will in most cases not be trackable unless they are specifically marketed as beacon (some exceptions apply, such as some version of the Mi Band)
- Devices with Bluetooth Classic have a good chance of working if they can also be connected to peripherals (e.g. headphones)
  - Sometimes it is enough if they are just connectable to a phone as well - but caution, as sometimes these devices will block all connection requests if already paired to a phone

I googled the glasses that you mentioned here and - according to their Kickstarter - they support the A2DP profile, which allows them to send audio to another device. Given that information I think that they could work with room-assistant as well, but I can't provide any guarantees unfortunately.
