### ISSUE TITLE
Packet loss/poor network perf on every wifi device on AVM mesh network

### ISSUE THREAD

**Issue by mgiako** [mKeRix/room-assistant#266]
About the known slowdown issue using bluetooth classic integration on Raspberry Pis reported here:
https://www.room-assistant.io/integrations/bluetooth-classic.html#slow-unresponsive-device-over-ssh, and in issue #178

I found that the slowdown affects not only the device (pi3 / pi0) that runs room assistant but my whole wifi network.

I have an AVM Fritz mesh network, and the slowdown every n seconds (depending on the interval parameter) affects any other device connected to the mesh network.

If I open (on my LAN cabled pc) some ping windows, one on the device running room assistant, and the others on any other wifi device, I see that every slowdown / timeout of the room assistant device corresponds to an equal slowdown of the other wifi devices.
This causes slowdowns and malfunctions to my home automation devices (sonoff and shelly devices) and to the navigation with my mobile phone.
The only solution I have found so far is to use the ethernet port of the raspberry devices instead of the wifi.

Since I had 3 Pi zero with room assistant on the three floors of my house, for now I'm using a pi3b+ with lan cable, and I plan to buy 3 ethernet hats for the pi zeros. 
And of course I am pulling the lan cables on the three floors.

Has anyone else had this issue?

N.B. the slowness is noticeable only when one of the searched devices is not reachable

**Comment by mKeRix** [comment]
This tricky issue arises from the way that the scans work - Bluetooth connection attempt (as used by room-assistant) are very aggressive. Depending on the surrounding factors this may also impact the 2.4 GHz network in general. As it stands right now there are two steps I could recommend to alleviate this issue:

- move most of your other devices to a 5 GHz network, as that will not be impacted
- increase the interval (and live with the slower reaction times)

I also had the idea to limit the time that scans will take when the device is not present which could help with this too, but I haven't actually gotten around to trying that yet. Before investing in the ethernet hats maybe wait another day and I'll get back to you on this.

Out of interest, does the ethernet cable make all devices responsive again or just the Pi itself (which is what I would've expected)?

**Comment by mgiako** [comment]
Hi, thanks for the quick reply.
I can definitely wait before buying ethernet hats, and I'm really interested in a possible solution that limits the scan time of devices that are not present.
If you could do that I would be delighted to test this innovation.
However, from my tests, when the raspberry pi3 uses the ethernet connection the pings to all the devices on the network return perfectly normal.
From what you know, does the wifi / bluetooth chip also handle the ethernet interface?

**Comment by mKeRix** [comment]
Afaik the ethernet connection does not go over the shared wireless chip. I think it shares the bandwidth with it, but that's unrelated.

Just for reference the related ticket for the idea I mentioned above is #179. I just put a new beta release ([2.9.0-beta.1](https://github.com/mKeRix/room-assistant/releases/tag/v2.9.0-beta.1)) that contains this feature. By default the scan time is now limited to 2s, if it takes longer it will be aborted. This should take some strain off the chip and the network. You can customize the value by setting `bluetoothClassic.scanTimeLimit` to however many seconds you want. Could you install the beta and report back if it improved your situation?

You can install it with `sudo npm i --global --unsafe-perm room-assistant@2.9.0-beta.1` (or by setting the version in Ansible/using the relevant Docker image tag/using the beta Hass.io add-on).

**Comment by mgiako** [comment]
I'm testing th new beta now.... stand by...

**Comment by mgiako** [comment]
At a first test it seems to me that nothing changes.
After dinner I will do other tests.
How can I check the installed version?

**Comment by mKeRix** [comment]
Typing `room-assistant -h` will echo out the version. Note that you will probably need to install it across all your Pis to see changes. 

I did some tests on my local instance and according to `hcidump` the scan is killed correctly, but since my setup doesn't suffer from the interference so much it's hard to test the real effects here sadly.

**Comment by mgiako** [comment]
ok from left to right:
first pi0, second pi0 (both running latest beta.2) and another wifi device. No other room assistant devices running
There are two bluetooth iphones as target, both phones have disabled bluetooth to simulate their absence
This is the config of both pi0 (apart from Instance name and weight that are different)

```
global:
  instanceName: studio
  integrations:
    - homeAssistant
    - bluetoothClassic
cluster:
  weight: 10
homeAssistant:
  mqttUrl: 'mqtt://192.168.0.50:1883'
  mqttOptions:
    username: *****
    password: *******
bluetoothClassic:
  interval: 10
  timeoutCycles: 2
  addresses:
    - 'D4:A3:3D:9E:4F:B8'
    - '18:65:90:A7:B0:9C'
```


first image: both pi with room assistant service stopped
![image](https://user-images.githubusercontent.com/44270368/90342243-e3882f00-e006-11ea-8739-c747b16098e3.png)
second image: both pi0 with room assistant running. Note the higher milliseconds in every device
![image](https://user-images.githubusercontent.com/44270368/90343198-6f518980-e00e-11ea-868e-d80abd290058.png)
third image: same as the second but both phones have bluetooth enabled. There is high milliseconds anyway, is similar to the second image.
![image](https://user-images.githubusercontent.com/44270368/90343387-361a1900-e010-11ea-9151-132e76b9620e.png)

my conclusions: the situation is much better now. With the regular version there are many ping timeouts that now are (almost completely) gone.
I think this is a very good improvement.

However, having tried room assistant with wired devices, I don't think I'll go back. This is a photo of two wired devices (on the left) and the same wifi device. In the worst case scenario, both phones bluetooth disabled.
![image](https://user-images.githubusercontent.com/44270368/90343556-e63c5180-e011-11ea-88f2-5d459b99785e.png)
Everything is perfect!!

So, I'll try to use cabled devices from now.
Thanks for the big improvement anyway.

Now I have a little issue with room assistant on my homeassistant NUC, but since is not related to wifi I'll open a new issue.

**Comment by mKeRix** [comment]
Yeah, can't beat wired. If your home allows for it and you're fine with the added costs it certainly is great. :) Thanks for the detailed insights that you posted!
