### ISSUE TITLE
Debug mode available??

### ISSUE THREAD

**Issue by brian32768** [mKeRix/room-assistant#267]
I have a room-assistant instance running in Docker and I can see it appears in Home Assistant as a "cluster of 1".
I saw the Docker log file for room-assistant but have no idea what's going on now--- is it scanning? It's connected so it's alive. Does it see my BLE devices? No idea. Help! :-)

I tried connecting to its API port but don't know what to say so it just says 404 to me. Is there a call I can make to test it?
```
statusCode | 404
-- | --
message | "Cannot GET /"
error | "Not Found"
```

What I am asking for is a verbose mode to put out messages to the log to help me in the set up phase.

If there is one already, then this is a request for documentation how to turn it on.

I look forward to not being a room-assistant newb.

**Comment by mKeRix** [comment]
For some reason the search on the docs website did not seem to index this (so you can't find it easily), but there is a command line switch for the debug output: https://www.room-assistant.io/guide/cli.html

When running via Docker you can enable it by adding it as the `command` together with the default `--digResolver`. When launching directly it would be something like `docker run mkerix/room-assistant --digResolver --verbose`, with docker-compose:

```yaml
version: '3'
services:
  room-assistant:
    image: mkerix/room-assistant
    command: --digResolver --verbose
```
