### ISSUE TITLE
Using home assistant add-on the distance is never higher than 1

### ISSUE THREAD

**Issue by mgiako** [mKeRix/room-assistant#268]
Using bluetooth classic integration, the distance of all my bluetooth devices from my NUC (where I have installed room assistant as add-on of home assistant) is always from 0.1 to 1, even if they are very far (but never out of range).

![image](https://user-images.githubusercontent.com/44270368/90344282-8c8b5580-e018-11ea-80bf-9b2e462b8c66.png)

If I use a raspberry (pi zero or pi3b+) with room assistant installed on NodeJS, the distance goes from 2 up to 30

![image](https://user-images.githubusercontent.com/44270368/90344295-a75dca00-e018-11ea-8077-f25d48ca6b84.png)

For this reason if I use both of this devices in a cluster, even though my phone is closer to the raspberry,
since the reported distance is shorter (1) on the NUC, than the raspberry (4-5) room assistant places me closer to the NUC.

I tried to install home assistant and room assistant add-on on the raspberry too.
The distance is always 1 also in this case.
So I think the problem is homeassistant and not the NUC.

Has anyone else noted this issue?
What do you think about it?

**Comment by mKeRix** [comment]
Hm, I haven't heard of anyone with this issue on the add-on yet... what is really interesting is that you see the same behavior on the Pis. I can check if I can reproduce it on my NUC with the add-on.

Generally the values may not be invalid either: the distance is the inverse of the RSSI on Bluetooth Classic, and the RSSI value is what the Bluetooth controller returns. This isn't standardized in any way afaik. If these are actual correct values it might be a good idea to introduce a scaling option that you could use to tune the instances to be similar - so in your case e.g. multiplying by a factor of 20 to match values somewhat.

**Comment by mgiako** [comment]
ok, but what interests me is not really the reported distance, but the fact that room assistant says I'm in the studio (room assistant on homeassistant/nuc) even though I'm physically "sopra" (upstairs) near a raspberry pi3b+ running roomassistant on NodeJS.
How does room assistant decide which cluster member I am closest to?
Not based on the reported distance?

**Comment by jpgimenez** [comment]
I'm facing same issue, I think that the problem is hcitool on nuc always reporting RSSI -1
my phone close to the nuc:
```
$ hcitool -i hci0 cc "xxx" && hcitool -i hci0 rssi "xxx"
RSSI return value: -1
```
my wife's phone on other room:
```
$ hcitool -i hci0 cc "xxx" && hcitool -i hci0 rssi "xxx"
RSSI return value: -1
```
the same with the kitchen raspberry report good values, -16, -22

**Comment by jpgimenez** [comment]
I say hcitool but is probably a kernel module issue, I tried same distro than the nuc on a laptop, other kernel module, and the RSSI is properly displayed... my nuc's bluetooth is:
```
Bus 001 Device 004: ID 8087:0a2a Intel Corp. Bluetooth wireless interface
```

**Comment by jpgimenez** [comment]
maybe related to this https://github.com/mKeRix/room-assistant/issues/187

**Comment by mKeRix** [comment]
@mgiako I totally missed your last message, sorry about that. Yeah, room-assistant uses a (slightly filtered) version of the reported distance to decide the room presence. Hence the idea of introducing some kind of scaling. If you could set a scaling factor of 20 in your studio instance you should be able to run both instances at the same time and get correct results.

@jpgimenez That seems related to the internals of your machine - are the Bluetooth drivers up-to-date and working correctly? Can you get good values using `bluetoothctl` instead? The latter would be quite interesting, as that would prioritize the migration for me. Haven't heard of a case like that before.

**Comment by jpgimenez** [comment]
> @jpgimenez That seems related to the internals of your machine - are the Bluetooth drivers up-to-date and working correctly? Can you get good values using `bluetoothctl` instead? The latter would be quite interesting, as that would prioritize the migration for me. Haven't heard of a case like that before.

not sure how to use `bluetoothctl` to control my phone RSSI, but it seems to be reporting RSSI for some devices...

[CHG] Device 7E:AA:2F:59:88:03 RSSI: -61
[CHG] Device 7E:AA:2F:59:88:03 RSSI: -58
[CHG] Device 6D:BB:7A:CA:11:5F RSSI: -74

**Comment by mKeRix** [comment]
Unfortunately I also don't know the right commands to replicate the current hcitool behavior with bluetoothctl atm, but that's interesting nonetheless. The CHG logs you posted are from devices that are currently discoverable afaik. Thanks for checking that!

**Comment by jpgimenez** [comment]
doesn't have nodejs a native implementation for bluetooth?
IMO, spawning a process is not always the better idea and could lead to compatibility issues like this, maybe not like this if the problem is on the kernel, but dealing with a deprecated tool is a pain...

**Comment by mKeRix** [comment]
There is nothing built-in and the available libraries don't cover the use case that room-assistant needs - or at least they didn't when I wrote v2 at the beginning of this year. I agree that spawning sub processes to different tools is kind of sub-optimal, but it was the easiest way to get this working. In the future we could also switch to use the DBUS interface for Bluetooth Classic as well, but that's a bit painful to understand/implement. Certainly an idea for the other issue that you linked to though!
