### ISSUE TITLE
Using "not_home" rather than "away" in mqtt_room

### ISSUE THREAD

**Issue by PeteBa** [mKeRix/room-assistant#27]
Heiko, I have a small question about your mqtt_room component. I was wondering if there was a particular reason for using "away" rather than "not_home" in mqtt_room. I think it would be great to see closer alignment with the device_trackers particularly for multi-device presence detection. I have made local changes to do this by exposing "away_state" as a config option and was thinking of submitting as a PR on the HA github. Would that make sense ? Appreciate your thoughts and thanks again for a great solution. Pete

**Comment by mKeRix** [comment]
No particular reason, that was just an oversight on my part honestly. A consistent approach would probably be smart, but to reach this we would introduce a breaking change. I don't think we really need to make the away state configurable.

It's a simple change at https://github.com/home-assistant/home-assistant/blob/ac256d594325ffaf02807e7b7b552869e7bceb71/homeassistant/components/sensor/mqtt_room.py#L42 - if you want either you or me can submit a change pull request to change this to "not_home" and let the maintainers of home-assistant decide if this warrants a breaking change.

**Comment by PeteBa** [comment]
Great. I think that is the best solution and keeps the config manageable. I'll get the PR in and many thanks. Pete
