### ISSUE TITLE
Unable To Get iPhone Presence Unless Searching For BT Devices

### ISSUE THREAD

**Issue by jdude226** [mKeRix/room-assistant#270]
I am only able to get my iPhone's room presence to be detected when my phone is actively searching for bluetooth connections via the bluetooth menu on my iPhone. closing the menu makes room presence stop working and I am set to "Not_Home"

opening the bluetooth menu instantly restores the connection and presence is detected once again for my current room

**logs**

this was with BT scanning menu not open on my phone:

8/18/2020, 05:02:15 - debug - BluetoothClassicService: Querying for RSSI of MAC using hcitool
8/18/2020, 05:02:20 - debug - BluetoothClassicService: Command failed: hcitool -i hci0                                                                                                                          cc "MAC" && hcitool -i hci0 rssi "MAC"
Can't create connection: Input/output error
Get connection info failed: No such file or directory

8/18/2020, 05:02:21 - debug - BluetoothClassicService: Querying for RSSI of  MAC using hcitool
8/18/2020, 05:02:26 - debug - BluetoothClassicService: Command failed: hcitool -i hci0                                                                                                                          cc "MAC" && hcitool -i hci0 rssi "MAC"
Can't create connection: Input/output error
Get connection info failed: No such file or directory

8/18/2020, 05:02:27 - debug - BluetoothClassicService: Querying for RSSI of MAC using hcitool
8/18/2020, 05:02:32 - debug - BluetoothClassicService: Command failed: hcitool -i hci0                                                                                                                          cc "MAC" && hcitool -i hci0 rssi "MAC"
Can't create connection: Input/output error
Get connection info failed: No such file or directory

As soon as I opened the BT menu on my iPhone

8/18/2020, 05:02:33 - debug - BluetoothClassicService: Querying for RSSI of MAC                                                                                                       using hcitool
8/18/2020, 05:02:34 - debug - BluetoothClassicService: Received RSSI of 0 for MAC from Basement_Bedroom
8/18/2020, 05:02:34 - debug - EntitiesService: Adding new entity bluetooth-classMAC

8/18/2020, 05:02:34 - info - HomeAssistantService: Device tracker requires manual setu                                                                                                                         p in Home Assistant with topic: room-assistant/device_tracker/bluetooth-classic-MAC-tracker/state
8/18/2020, 05:02:34 - debug - EntitiesService: Adding new entity bluetooth-classic-MAC
8/18/2020, 05:02:34 - debug - HomeAssistantService: Registering entity room-assistant-                                                                                                                         bluetooth-classic-MAC under homeassistant/sensor/room-assistant/bluetoot                                                                                                                         h-classic-MAC/config
8/18/2020, 05:02:34 - debug - HomeAssistantService: Sending new state true for room-as                                                                                                                         sistant-bluetooth-classic-MAC-tracker
8/18/2020, 05:02:34 - debug - HomeAssistantService: Sending new state Basement_Bedroom                                                                                                                          for room-assistant-bluetooth-classic-MAC
8/18/2020, 05:02:34 - debug - HomeAssistantService: Sending new attributes {"distance"                                                                                                                         :0,"lastUpdatedAt":"2020-08-18T04:02:34.506Z"} for room-assistant-bluetooth-classic-MAC
8/18/2020, 05:02:39 - debug - BluetoothClassicService: Querying for RSSI of MAC using hcitool
8/18/2020, 05:02:44 - debug - BluetoothClassicService: Command failed: hcitool -i hci0                                                                                                                          cc "MAC" && hcitool -i hci0 rssi "MAC"
Can't create connection: Input/output error
Get connection info failed: No such file or directory

8/18/2020, 05:02:45 - debug - BluetoothClassicService: Querying for RSSI of MAC using hcitool
8/18/2020, 05:02:45 - debug - BluetoothClassicService: Received RSSI of 0 for MAC from Basement_Bedroom
8/18/2020, 05:02:45 - debug - HomeAssistantService: Sending new attributes {"distance"                                                                                                                         :0,"lastUpdatedAt":"2020-08-18T04:02:45.395Z"} for room-assistant-bluetooth-classic-MAC
8/18/2020, 05:02:51 - debug - BluetoothClassicService: Querying for RSSI of MAC using hcitool
8/18/2020, 05:02:56 - debug - BluetoothClassicService: Command failed: hcitool -i hci0                                                                                                                          cc "MAC" && hcitool -i hci0 rssi "MAC"
Can't create connection: Input/output error
Get connection info failed: No such file or directory

**Relevant configuration**
Paste the relevant parts of your configuration below.

global:
  instanceName: Basement_Bedroom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://172.30.3.149:1883'
  mqttOptions:
    username: roomassistant
    password: PASS
bluetoothClassic:
  minRSSI: -20
  hciDeviceId: 0
  addresses:
#iPhone_Josh
    - 'MAC'
#Watch_Josh
    - 'MAC'

I used to have this functioning quite well with my Huawei P20 Pro and my fiance's iphone 8. I am now using her iphone 8 and she a 11. both don't seem to work

the devices in my config are my apple watch and iphone 8.

**Environment**
 - room-assistant version: Just ran a fresh install, should be on latest release, but at least 2.0
 - installation type: NodeJS
 - hardware: Raspberry Pi 4 & Raspberry Pi 3
 - OS: IOS 13.5.1

**Comment by jdude226** [comment]
So an update on this.

today I was working at home and paired my bluetooth headphones to my iphone to listen to music. After some time I noticed home and room assistant were detecting my presence properly. 

I tried pairing my headphones to my apple watch (had no idea that was even possible) and to my fiances iphone 11 as well. All 3 devices seem to work normally now with room assistant. 

Prior to this, all devices (minus my iphone 8 which was connected to my apple watch) were not paired with any bluetooth devices. I think having a device paired may affect how the iphone responds to room assistant.

I have no idea how all of that works. But I am just sharing my observation and how it seems to be working almost instantly after I had done that. I will update here if I notice an issue tomorrow after returning home after an extended period of being away. but as of tonight it works just like it did before.

**Comment by mKeRix** [comment]
Unfortunately I don't have any hard documentation proof for this, but on some devices (e.g. Apple ones) you do need to have paired some kind of Bluetooth device at least once already before it can be tracked. The pairing can be removed afterwards afaik, it is just important that you did it once so that the chip starts listening to our Bluetooth requests. I assume this is done for security reasons. The same seems to apply after you factory reset the device.

I'm glad you were able to figure it out by yourself rather quickly though and thanks for reporting back with more information. :)
