### ISSUE TITLE
set state of inquiries switch at boot

### ISSUE THREAD

**Issue by MarpleA** [mKeRix/room-assistant#275]
**Is your feature request related to a problem? Please describe.**
I only activate the bluetooth inquiries switch if it has been triggered by a door contact sensor. And I deactivate it 2 minutes later.
That works great but there is one minor hick up. If any of the raspberry pi's reboot for some reason, the inquiries switch is 'on' by default and stays 'on' forever.

**Describe the solution you'd like**
I'd love to see an option where I could set the state of the requires switch after booting. Maybe directly in the configuration file.

**Describe alternatives you've considered**
An alternative could be to preserve the last state before reboot but this could lead to a non desired behavior in case the reboot happens the same time the trigger for activation fires.

**Comment by mKeRix** [comment]
In theory you can still set the switch state even when room-assistant is down and it will be preserved in MQTT. That could be used to build a switch that preserves the state. I don't think Home Assistant lets you adjust switches that are marked as unavailable though, so I guess you could indeed run into non-desirable behavior.

Either way, a default value is easy enough to implement. I'll look at this for the next version. 👍

**Comment by MarpleA** [comment]
Great. thx!
