### ISSUE TITLE
is it working with google home?

### ISSUE THREAD

**Issue by sunsgs** [mKeRix/room-assistant#283]
Is it working with google home inside home assistant?

**Comment by mKeRix** [comment]
I'm not sure I understand what you mean/what you're trying to achieve. Could you elaborate a bit further? Do you want to use Google Home devices instead of Raspberry Pis? Or do you want to run room-assistant alongside the Google Home voice integration?

**Comment by sunsgs** [comment]
Can I use iOS ble and connection to the google home to use as room presence?

**Comment by gbdavidx** [comment]
Why are you asking that here?

**Comment by mKeRix** [comment]
I'm still not entirely sure what you're after, but I'm pretty sure that room-assistant does not support it. room-assistant runs entirely independent from Google Home and iOS devices can't be tracked well using BLE in room-assistant.
