### ISSUE TITLE
Provide a "Rolling 5 minute" Average Device Tracker Entity

### ISSUE THREAD

**Issue by morethanunpopular** [mKeRix/room-assistant#285]
**Problem**
In my multi-story home, my room assistant deployment struggles to determine between a room and the room directly above it. My devices will frequently bounce between them. I do observe that on average, however, where room assistant thinks my devices are is correct --  but at any given moment, it might be wrong.

**Solution**
I think if rolling 1, 5, and 10 minute averages were also available (I.E. The closest room assistant node  on average over the last 1, 5, and 10 minute), a person could make automations based off of this information with a higher degree of reliability. 

**Alternatives**
For my deployment I actually built a second MQQT app in Python that queries the the Room Assistant API, and generates a rolling 5 minute average. This is working well for me, but I have very limited skills in JS, so I am not best suited to implement a similar feature directly into room assistant. 

**Additional context**
I have tried various position of the room assistant nodes in the two rooms, but I have not been able to find a position that significantly reduces this problem. 

A point of detail about the Python app I built, I weight the 4th and 5th minute more heavily in the average than the first three in an attempt to capture changing positions more quickly. That said, this is obviously not useful data for determining when a room is entered, I find motion detectors/door contact sensors are better suited to that specific task either way.

**Comment by Migz93** [comment]
Would really appreciate such a feature, I live in a fairly small cottage and with 3 devices dotted around, my location is correct 90% of the time but that 10% makes me hesitant to set up any automations. I tried to see if there was a way to lower the bluetooth power as that might help but it seems not, so an average would be the next best thing
