### ISSUE TITLE
Add support for MiFlora Sensors

### ISSUE THREAD

**Issue by frdbonif** [mKeRix/room-assistant#286]
**Describe the solution you'd like**
I'd like the ability to add Xiaomi MiFlora and related devices to Room Assistant, as they are BLE devices it is the only practical way to add them to Home Assistant if I already run Room Assistant. 

**Describe alternatives you've considered**
The sensors are already supported in mitemp_bt which gives visibility of the message format used.

**Additional context**
I can try to look in to adding support myself but have never used TypeScript so may not be successful.

I see that the code already has a moisture function.  I will get hold of a device in the next few weeks and see what results I can get.

**Comment by andrelung** [comment]
I think this works already: 
![image](https://user-images.githubusercontent.com/4161059/94367965-09165700-00e2-11eb-893a-d7815e32522f.png)

**Comment by frdbonif** [comment]
> I think this works already:
> ![image](https://user-images.githubusercontent.com/4161059/94367965-09165700-00e2-11eb-893a-d7815e32522f.png)

Thanks, after I posted I looked through the code and thought it might.  I've got one on the way from China in the next month so I'll definitly report back when it arrives.

**Comment by PeteBa** [comment]
Hey, can I get confirmation that this works for the Xiaomi Mi Flora plant monitor. I have a dozen of these monitoring plants in Home Assistant via the Plant Gateway solution. Unfortunately, my Mi Floras dont work with Room Assistant as suggest by the posts above. Tracing through the code, my devices never announce moisture/illuminance/temp/etc events. They only announce their presence and mac address. To get the sensor readings you need to establish a connection and query the respective services directly. Now, my Mi Flora units are about 2 years old so perhaps it needs never firmware. Can someone confirm ?

**Comment by PeteBa** [comment]
Just as a follow-up to the previous. I have the Mi Floras now working. It seems that in newer firmware (I'm now running 3.2.2) Xiaomi devices rotate through multiple announcements that correspond to each the various sensor readings. Magic.

**Comment by mKeRix** [comment]
Thanks for checking this @PeteBa! I will add this note to the docs.

**Comment by frdbonif** [comment]
> Just as a follow-up to the previous. I have the Mi Floras now working. It seems that in newer firmware (I'm now running 3.2.2) Xiaomi devices rotate through multiple announcements that correspond to each the various sensor readings. So if it doesnt look to be working then check the firmware version and use the Flower Care App to update.

@PeteBa can you share a link to the sensor and config that you have working, I'm not having any luck with mine at all.
