### ISSUE TITLE
error - BluetoothClassicService: RSSI update for empty address requested (HASSIO and iPhone / Apple Watch)

### ISSUE THREAD

**Issue by gionaf** [mKeRix/room-assistant#288]
**Describe the bug**
After some time that room-assistant is running, I start getting this error in the logs:
`error - BluetoothClassicService: RSSI update for empty address requested`
and my device's room is no longer updated.
A reboot _sometimes_ fixes the problem for a while.

**To reproduce**
I've 2 room-assistant instances on HASSIO, one rPi 3B+ and one rPi 4B.
The two Pis also have a USB bluetooth adapter each, which I was hoping would solve the problem (freeing up the internal receiver). Unfortunately, the problem occurs using both.
I'm trying to track 4 devices: iPhone X, XS; Apple Watch 3 and 6.

**Relevant logs**
After some time that room-assistant is running, the logs gets filled with:
`error - BluetoothClassicService: RSSI update for empty address requested`

And occasionally I also get:
`error - BluetoothClassicService: Command failed: hcitool -i hci0 cc "[MAC]" && hcitool -i hci0 rssi "[MAC]"`

**Relevant configuration**
Main instance:

```global:
  instanceName: xxxx
  integrations:
    - homeAssistant
    - bluetoothClassic
cluster:
  weight: 0
  autoDiscovery: false
  peerAddresses:
    - 'xxx.xxx.xxx.xxx:xxx'
homeAssistant:
  mqttUrl: 'mqtt://xxx.xxx.xxx.xxx:xxx'
  mqttOptions:
    username: xxx
    password: xxx
bluetoothClassic:
  hciDeviceId: 0 # i also get the error when using the external adapter "1"
  minRssi: -89
  interval: 10
  addresses:
    - 'xxx'
    - 'xxx'
    - 'xxx'
    - 'xxx'
```
Secondary instance (and mqtt server):
```global:
  instanceName: xxxx
  integrations:
    - homeAssistant
    - bluetoothClassic
cluster:
  weight: 1
  autoDiscovery: false
  peerAddresses:
    - 'xxx.xxx.xxx.xxx:xxx'
homeAssistant:
  mqttOptions:
    username: xxx
    password: xxx
bluetoothClassic:
  hciDeviceId: 0 # same as above: i also get the error when using the external adapter "1"
  minRssi: -99
  interval: 10
  addresses:
    - 'xxx'
    - 'xxx'
    - 'xxx'
    - 'xxx'
```

**Expected behavior**
I'ld expect room-assistant to track and update which room my device is in.

**Environment**
 - room-assistant version: 2.9.0
 - installation type: Hass.io
 - hardware:  RaspberryPi 3B+ and 4B (using both the internal and an external adapter)
 - OS: HassOS 4.13 (on rPi 3B+) and HassOS 5.2 (on rPi 4B)

**Comment by mKeRix** [comment]
If the `hcitool` error is only happening periodically it may not be a big issue. The empty address issue is certainly annoying and something that I still haven't been able to pinpoint. Do you see a lot of cluster connects/disconnects by any chance? I've been wondering if that could be related.

**Comment by gionaf** [comment]
> Do you see a lot of cluster connects/disconnects by any chance?
No, i didn't see any actually. Sometimes the wrong leader gets elected, not sure if it's related.

I have a feeling (but I don't know how to test it) that this it what happens:
- i arrive home with device A, which gets tracked by instance 1
- when I then move out of instance 1's range with device A, the "empty address" error starts to appear
- device A, after being paired with instance 1 first, doesn't connect to instance 2, and its room is no longer updated

The same happens if I connect to instance 2 first (as soon as I go out of its range, the "empty address" error starts to appear and the room is no longer updated).

Any idea on how to debug it? Sorry but i'm a noob with python (and hass.io too).

Anyway thanks a lot for your efforts, the idea behind room-assistant is great!

**Comment by mKeRix** [comment]
I added a line of logging that should hopefully generate some more output for debugging this issue! Would be great if you could update to the latest version and then check the logs of the leader instance when this happens again. The relevant line should start with "Trying to request inquiry without MAC!" and contain some information about the current application state afterwards.

**Comment by gionaf** [comment]
Hi, thanks for taking the time to debug this issue!

Here are the logs:

```
10/6/2020, 9:46:23 AM - info - HomeAssistantService: Device tracker requires manual setup in Home Assistant with topic: room-assistant/device_tracker/bluetooth-classic-[IPHONE MAC]-tracker/state
10/6/2020, 9:46:52 AM - error - BluetoothClassicService: Trying to request inquiry without MAC! Current index: 1. Addresses in this round: [WATCH MAC]. Nodes in this round: [object Object],[object Object].
10/6/2020, 9:46:52 AM - error - BluetoothClassicService: RSSI update for empty address requested
```

I'm also now experiencing a lot of reboots of the cluster leader.

I've also done a simple custom sensor for tracking which room i'm in, by simply comparing the rssi from the 2 instances (when connected to both). I get some temporary wrong results, but it's pretty accurate, just need to filter for 30/60 seconds

**Comment by mKeRix** [comment]
I put up a new beta version which also includes some fixes for the BT Classic device rotation logic. As I wasn't able to reproduce this specific issue in a test locally yet I'm not certain that this will fix it for you, but could you please check?

If the problem persists I also updated the log message again, this time to expose some other details.

**Comment by alastaid** [comment]
Hi, I am getting the same error, have just upgraded using the @beta and still only get:
10/18/2020, 10:10:46 - error - BluetoothClassicService: RSSI update for empty address requested
when running room-assistant -v, not seeing the extended logs.  Am I doing something wrong to not see the extended logs to help resolve?

**Comment by mKeRix** [comment]
@alastaid The extended log will be available on the leader instance - make sure to run that one with `-v` as well.

**Comment by alastaid** [comment]
@mKeRix , thanks! So just finished upgrading all 8 nodes to @beta, and run it for a few minutes and dont see the error at all now, which I doubt helps, I will let it run for a few hours and if it shows I will post it

**Comment by gionaf** [comment]
@mKeRix no errors for me too, after 6 hours of testing. Great, thank you so much!
