### ISSUE TITLE
Bluetooth crashes after start of Room-Assistant

### ISSUE THREAD

**Issue by AdmiralRaccoon** [mKeRix/room-assistant#295]
**Describe the bug**
When starting room-assistant, the bluetooth commands are failing. Before I start room-assistant, I use hciconfig and it reports that bluetooth is up, after i quit room-assistant, it reports bluetooth is down.

**To reproduce**
Rebooting and start room-assistant again

**Relevant logs**
master@ra-floor:~$ hciconfig
hci0:   Type: Primary  Bus: USB
        BD Address: 00:1A:7D:DA:71:10  ACL MTU: 310:10  SCO MTU: 64:8
        UP RUNNING
        RX bytes:1220 acl:0 sco:0 events:72 errors:0
        TX bytes:2788 acl:0 sco:0 commands:72 errors:0

master@ra-floor:~$ room-assistant -v -c ~/room-assistant/config/
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
10/7/2020, 12:51:19 PM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-classic
10/7/2020, 12:51:19 PM - info - NestFactory: Starting Nest application...
10/7/2020, 12:51:19 PM - info - InstanceLoader: AppModule dependencies initialized
10/7/2020, 12:51:19 PM - info - InstanceLoader: ConfigModule dependencies initialized
10/7/2020, 12:51:19 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
10/7/2020, 12:51:19 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
10/7/2020, 12:51:19 PM - info - InstanceLoader: HttpModule dependencies initialized
10/7/2020, 12:51:19 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
10/7/2020, 12:51:19 PM - info - InstanceLoader: ClusterModule dependencies initialized
10/7/2020, 12:51:19 PM - info - InstanceLoader: TerminusModule dependencies initialized
10/7/2020, 12:51:19 PM - info - InstanceLoader: ScheduleModule dependencies initialized
10/7/2020, 12:51:19 PM - info - InstanceLoader: EntitiesModule dependencies initialized
10/7/2020, 12:51:19 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized
10/7/2020, 12:51:19 PM - info - InstanceLoader: BluetoothClassicModule dependencies initialized
10/7/2020, 12:51:19 PM - info - InstanceLoader: StatusModule dependencies initialized
10/7/2020, 12:51:20 PM - info - RoutesResolver: EntitiesController {/entities}:
10/7/2020, 12:51:20 PM - info - RouterExplorer: Mapped {/entities, GET} route
10/7/2020, 12:51:20 PM - info - RoutesResolver: StatusController {/status}:
10/7/2020, 12:51:20 PM - info - RouterExplorer: Mapped {/status, GET} route
10/7/2020, 12:51:20 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.1.99:1883
10/7/2020, 12:51:20 PM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, /home/master/room-assistant/config/local.yml
10/7/2020, 12:51:20 PM - debug - EntitiesService: Adding new entity bluetooth-classic-inquiries-switch
10/7/2020, 12:51:20 PM - debug - HomeAssistantService: Registering entity room-assistant-unten-bluetooth-classic-inquiries-switch under homeassistant/switch/room-assistant/unten-bluetooth-classic-inquiries-switch/config
10/7/2020, 12:51:20 PM - debug - HomeAssistantService: Sending new state true for room-assistant-unten-bluetooth-classic-inquiries-switch
10/7/2020, 12:51:20 PM - debug - EntitiesService: Adding new entity status-cluster-size
10/7/2020, 12:51:20 PM - debug - HomeAssistantService: Registering entity room-assistant-unten-status-cluster-size under homeassistant/sensor/room-assistant/unten-status-cluster-size/config
10/7/2020, 12:51:20 PM - debug - EntitiesService: Adding new entity status-cluster-leader
10/7/2020, 12:51:20 PM - debug - HomeAssistantService: Registering entity room-assistant-unten-status-cluster-leader under homeassistant/sensor/room-assistant/unten-status-cluster-leader/config
10/7/2020, 12:51:20 PM - debug - HomeAssistantService: Sending new state 1 for room-assistant-unten-status-cluster-size
10/7/2020, 12:51:20 PM - debug - HomeAssistantService: Sending new state none for room-assistant-unten-status-cluster-leader
10/7/2020, 12:51:20 PM - info - ClusterService: Starting mDNS advertisements and discovery
10/7/2020, 12:51:20 PM - info - NestApplication: Nest application successfully started
10/7/2020, 12:51:20 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["unten"]} for room-assistant-unten-status-cluster-size
10/7/2020, 12:51:20 PM - debug - HomeAssistantService: Sending new attributes {"quorumReached":true} for room-assistant-unten-status-cluster-leader
10/7/2020, 12:51:21 PM - info - ClusterService: unten has been elected as leader
10/7/2020, 12:51:21 PM - debug - HomeAssistantService: Sending new state unten for room-assistant-unten-status-cluster-leader
10/7/2020, 12:51:21 PM - info - EntitiesService: Refreshing entity states
10/7/2020, 12:51:21 PM - debug - HomeAssistantService: Sending new state true for room-assistant-unten-bluetooth-classic-inquiries-switch
10/7/2020, 12:51:21 PM - debug - HomeAssistantService: Sending new state 1 for room-assistant-unten-status-cluster-size
10/7/2020, 12:51:21 PM - debug - HomeAssistantService: Sending new state unten for room-assistant-unten-status-cluster-leader
10/7/2020, 12:51:21 PM - debug - HomeAssistantService: Sending new attributes {} for room-assistant-unten-bluetooth-classic-inquiries-switch
10/7/2020, 12:51:21 PM - debug - HomeAssistantService: Sending new attributes {"nodes":["unten"]} for room-assistant-unten-status-cluster-size
10/7/2020, 12:51:21 PM - debug - HomeAssistantService: Sending new attributes {"quorumReached":true} for room-assistant-unten-status-cluster-leader
10/7/2020, 12:51:26 PM - debug - BluetoothClassicService: Querying for RSSI of 20:39:56:78:EA:0A using hcitool
10/7/2020, 12:51:28 PM - debug - BluetoothClassicService: Query of 20:39:56:78:EA:0A reached scan time limit, resetting hci0
10/7/2020, 12:51:32 PM - debug - BluetoothClassicService: Querying for RSSI of F0:5C:77:F0:B8:A0 using hcitool
10/7/2020, 12:51:32 PM - error - BluetoothClassicService: Command failed: hcitool -i hci0 cc "F0:5C:77:F0:B8:A0" && hcitool -i hci0 rssi "F0:5C:77:F0:B8:A0"
Invalid device: Network is down

10/7/2020, 12:51:38 PM - debug - BluetoothClassicService: Querying for RSSI of 20:39:56:78:EA:0A using hcitool
10/7/2020, 12:51:38 PM - error - BluetoothClassicService: Command failed: hcitool -i hci0 cc "20:39:56:78:EA:0A" && hcitool -i hci0 rssi "20:39:56:78:EA:0A"
Invalid device: Network is down

10/7/2020, 12:51:38 PM - error - BluetoothClassicService: Command failed: hciconfig hci0 reset
Can't init device hci0: Connection timed out (110)

^C10/7/2020, 12:51:41 PM - debug - HomeAssistantService: Marking room-assistant-unten-bluetooth-classic-inquiries-switch as unavailable

master@ra-floor:~$ hciconfig
hci0:   Type: Primary  Bus: USB
        BD Address: 00:1A:7D:DA:71:10  ACL MTU: 310:10  SCO MTU: 64:8
        DOWN
        RX bytes:1226 acl:0 sco:0 events:73 errors:0
        TX bytes:2807 acl:0 sco:0 commands:74 errors:0

```text
```

**Relevant configuration**

global:
  instanceName: flur
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.99:1883'
  mqttOptions:
    username: mqttuser
    password: mqttuser
bluetoothClassic:
  hciDeviceId: 0
  addresses:
    - '20:39:56:78:EA:0A'
    - 'F0:5C:77:F0:B8:A0'

```yaml
```

**Environment**
 - room-assistant version: 2.10.0
 - installation type: NodeJS
 - hardware: Generic PC with Bluetooth Dongle
 - OS: Vmware esxi 6.7 U2 with ubuntu 20.04.1 LTS VM, Bluetooth passthrough

**Additional context**
This is my first try with room-assistant. Should it be working within a VM`or isn´t that supported?

Thanks,
Philipp

**Comment by mKeRix** [comment]
room-assistant should work in a VM, but this adds a bunch of other factors into play which might break something. To me it looks like the reset is causing your Bluetooth adapter to go down. A simple thing you could try is to get your Bluetooth adapter running again and then set the `scanTimeLimit` option of the `bluetoothClassic` integration to `6`. If that doesn't work you can also try increasing it to `10`, but then you also need to increase the `interval` to at least `10`.

If you want some more in-depth info you can also launch `hcidump` in another terminal and then start room-assistant afterwards. That should give you debug info from the Bluetooth adapter.

**Comment by AdmiralRaccoon** [comment]
I tried several settings and sticks, everytime the same error. i read somewhere esxi doesn´t pass through bluetooth really good.
don´t bother, that was just a test. I´ll stick to another PI for this area
