### ISSUE TITLE
How can i use room-assistant with BLE and Apple Devices

### ISSUE THREAD

**Issue by zazu-sf** [mKeRix/room-assistant#296]
**Describe the bug**
With BT Classic and the MAC-Address as xx:xx:xx:xx:xx:xx everything works as ecpected.
But i like to use BLE. With the MAC-Address for my Apple-Devices in lovercase and without : it doesn't work.
And i can't find a UUID ibeacon Address for my Apple Devices.
What can i do to use room-assistant with Apple Devices and BLE?

**Expected behavior**

**Environment**
 - room-assistant version: 2.10.0
 - installation type: Hass.io
 - hardware: Raspberry Pi Zero W

**Comment by mKeRix** [comment]
iOS devices don't emit a consistent BLE ID that you could use to track them easily. This is exactly why the Bluetooth Classic integration exists - to track devices where you don't have luck with BLE.
