### ISSUE TITLE
Question on Mixing Classic and Lowenergy on different PIs

### ISSUE THREAD

**Issue by bleitchhk** [mKeRix/room-assistant#298]
Hi;

I am a very very big fan of room assistant.  I have / have had both bluetoothclassic and bluetooth lowenergy versions work well.  The whole cluster architecture and nomination of a leader to send the MQTT state is simply brilliant.

I want to combine them.  I am however, using pi 0w s which are great for this task.  It seems they only have one hci (0) so it is not possible to do both on single pi 0w ... please correct me if I am wrong here.

Now, I am thinking of running dual pi 0ws at each point with one running bluetoothclassic and another running bluetoothlowenergy.

I am think to put them in the same cluster, just with different instance names.

It would be something like
- 5x Pi 0w - running classic
- 5x pi 0w - running lowenergy

will this function as a 10 node cluster with both classic MAC addresses being reported and BLE iBeacons being reported to the MQTT broker from the single cluster ?

If so, any special configs ?

Best;

Brendan

**Comment by mKeRix** [comment]
It's not yet possible to run both from the same adapter, there is an open issue about this here: #209. The setup as you describe it won't work exactly like that, you need at least one device that runs both integrations at the same time, which should then be the preferred leader. This is a limitation of the leader mechanisms I've used... I left this to improve on in the future in the hopes of not many people running into this issue.

BUT you can achieve this in a different and most likely even cheaper way! Just get yourself some USB OTG adapter and cheap Bluetooth USB sticks. You can then stick those into your Pi 0Ws and run both integrations at the same time, from different adapters. If you need to place these relevant Pis for each integration in different spots you can also do that and use this tactic only for the leader instance.

**Comment by bleitchhk** [comment]
Hi;

Thanks for this.

I bought a “plugable" USB adaptor based on web advice it works well on a PI.

I installed it, did a full update + upgrade of the PI, followed by a reboot.

The USB dongle is not taking at the linux level (room assistant not yet seeing it as a result).

- I run “lsusb” and I can see the device at the USB level report, so it is there
- I run "hcitool dev” and see only hci0, the built in bluetooth on the Pi 0w itself

Is there some secret to binding the USB dongle to a bluetooth hci1 ?

Thanks;

Brendan

**Comment by mKeRix** [comment]
None that I know of unfortunately - it's possible that an additional driver package is required, but that depends on the USB dongle model.

Apart from that: I actually put out a new beta version (2.11.0-beta.1) yesterday that supports running BT Classic and BLE off the same Bluetooth adapter! So if you can't figure out the dongle issue you could also give the new beta a try.

**Comment by bleitchhk** [comment]
Hi;

It is a better solution !

Brendan

**Comment by bleitchhk** [comment]
Hi;

For “npm", use "room-assistant@2.10.0” as opposed to just "room-assistant" ?

Looking on github, I see your beta is 2.10.0, so just checking

It is easy enough to save my “local.yaml” file and just start from scratch by reflashing the SD card and going through whole process.

Cheers;

Brendan

**Comment by mKeRix** [comment]
GitHub is showing 2.10.0 as the latest release on the main repository page because it is the latest version marked as stable, if you look into the releases page you will see the beta versions as well. You can just install it by typing `sudo npm i --global --unsafe-perm room-assistant@beta` - this should work like any other upgrade, without requiring you to re-flash. If you do want to start fresh you can of course just copy the `local.yaml` though.

**Comment by bleitchhk** [comment]
Hi;

I think it is all working, but the room assistant logs don’t really completely confirm via advice on setting a device tracker topic, The HA mqtt debug (HA logger for mqtt set to debug) does not really show the topic messages coming in for the sensor or manually set device tracker. However, the MQTT integration shows a sensor being auto discovered and the mqtt messages in the integration show a recent mqtt state.

So, I think it is working ... ? :)

Thanks for the tips !

Brendan
