### ISSUE TITLE
Clarification: entity ID to use for behaviours

### ISSUE THREAD

**Issue by Alfiegerner** [mKeRix/room-assistant#299]
Hi,

What is the entity id used for behaviours? I'd like to apply the rolling average option to a couple of RA instances.

Is it the instance name? Home-assistant entity_id?

Thanks!

**Comment by mKeRix** [comment]
It refers to the room-assistant internal ID of the entity, which is set by the integrations. Currently the easiest way to figure this out is to look at the JSON in `http://<your-room-assistant-ip>:6415/entities` and look at the `id` property of the entity you want to customize. I would like to make this information more visible somehow in the future, maybe in the HA UI.

For Bluetooth Classic it would for example be: `bluetooth-classic-xx-xx-xx-xx-xx-xx` (sensor) and `bluetooth-classic-xx-xx-xx-xx-xx-xx` (device tracker).

**Comment by Alfiegerner** [comment]
Thanks!
