### ISSUE TITLE
Mac Adress from BLE Device

### ISSUE THREAD

**Issue by sebastianapw** [mKeRix/room-assistant#3]
Just a quick question concerning room assistant. 
Is it possible to track a devices bluetooth MAC-Adress? 
This would be really helpful for tracking devices such as an iPhone. 
At the moment I'm facing the problem that the iPhone doesn't have a static UUID so that it can't get tracked in a reliable way. 
Cheers.

**Comment by mKeRix** [comment]
Sorry for the long radio silence! I will try to implement an option for this this weekend. Would you use the iPhone with an virtual iBeacon app or are there other ways of making the iPhone broadcast BLE packages?

**Comment by sebastianapw** [comment]
If I'm right the iPhone is broadcasting the Bluetooth MAC-ID if once connected to another Bluetooth Device. At the time my iPhone is broadcasting its MAC steady and connects every 15 minutes to the computer. If this shouldn't work the virtual Beacon would be my second option. 
Thanks in forward

**Comment by mKeRix** [comment]
I addressed this issue with the `use_mac` option of the BLE component in version 0.2.0. I am going to close this issue, but please do try with the updated version (`git pull` & `npm install`) and let me know if it works for you. If it doesn't I'll reopen the issue and we'll investigate it further.
