### ISSUE TITLE
Heads up with multiple BT adapters (RPI Issue not Room-Assistant)

### ISSUE THREAD

**Issue by ghzgod** [mKeRix/room-assistant#300]
**Describe the bug**
When using multiple BT adapters, after reboot, RPI selects USB as HCI0 and HCI1 seizes to exist.

**To reproduce**
Boot RPI with no USB BT adapter and you see HCI0 from the onboard BT.  Plug USB adapter in and you see HCI1 as the dev id for that.  Check these using the command `hcitool dev` Now reboot with both devices and HCI0 becomes the BT device and the onboard BT stops working.

I am using the latest raspbian lite.  8-20-2020. Linux Kernel 5.4  

I am using the latest room-assistant 2.10.0.

I just want people to be aware of this.  I've been banging my head against the wall for a few days trying to see why my onboard BT for 2 devices doesnt work after the BT dongle is plugged in.

More info here: https://www.raspberrypi.org/forums/viewtopic.php?t=282948

Ultimately, if we can get BT Classic and BLE to work from a single device, everybody would win.  I understand the dev is busy.

**Comment by ghzgod** [comment]
Update:  I downgraded to [Raspbian Lite July 10 2019](http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-07-12/2019-07-10-raspbian-buster-lite.zip) and that kernel version allowed me to use both USB BT and onboard BT.  I will not upgrade distros as it looks like the current linux kernel is going through some bluetooth hardships.

**Comment by mKeRix** [comment]
Thanks for leaving this hint complete with a solution (even if it's a downgrade for now)! I will pin this issue for more visibility until we can work off a single adapter.

**Comment by ghzgod** [comment]
Thank you dev!
