### ISSUE TITLE
Error: EALREADY, Operation already in progress

### ISSUE THREAD

**Issue by Robbilie** [mKeRix/room-assistant#302]
**Describe the bug**
I am running room-assistant via ansible on a raspi zero w and the service sometimes crashes with the reason shown in the logs section.

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```
Oct 14 15:55:22 diningroom room-assistant[9109]: /opt/nodejs/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100
Oct 14 15:55:22 diningroom room-assistant[9109]:     this._deviceId = this._socket.bindRaw(deviceId);
Oct 14 15:55:22 diningroom room-assistant[9109]:                                   ^
Oct 14 15:55:22 diningroom room-assistant[9109]: Error: EALREADY, Operation already in progress
Oct 14 15:55:22 diningroom room-assistant[9109]:     at Hci.init (/opt/nodejs/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100:35)
Oct 14 15:55:22 diningroom room-assistant[9109]:     at Hci.pollIsDevUp (/opt/nodejs/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:115:14)
Oct 14 15:55:22 diningroom room-assistant[9109]:     at ontimeout (timers.js:436:11)
Oct 14 15:55:22 diningroom room-assistant[9109]:     at tryOnTimeout (timers.js:300:5)
Oct 14 15:55:22 diningroom room-assistant[9109]:     at listOnTimeout (timers.js:263:5)
Oct 14 15:55:22 diningroom room-assistant[9109]:     at Timer.processTimers (timers.js:223:10)

```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
all:
  hosts:
    'bedroom.local':
    'diningroom.local':
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothClassic
          - bluetoothLowEnergy
      homeAssistant:
        mqttUrl: mqtt://192.168.178.62:1883
        mqttOptions:
          username: room-assistant
          password: RgCLBj5qADsLzZnb
      bluetoothClassic:
        addresses:
          - 'xxxxx'
      bluetoothLowEnergy:
        maxDistance: 5
        whitelist:
          - xxxx

```

**Expected behavior**
The service should run without interrupt.

**Environment**
 - room-assistant version: [e.g. 2.0.0]
 - installation type: ansible (nodejs)
 - hardware: raspi zero w
 - OS: raspios

**Comment by mKeRix** [comment]
This error is caused by the BLE library that room-assistant uses and the way it handles these low level issues. While looking at similar issues in the past I couldn't find a good way to catch such errors without something hacky - but to be fair, this specific exception is new. I suppose it's worth the effort to check if it can be prevented. Until then the automatic restart of the systemd service (or the HA add-on watchdog) should make this issue less annoying.

**Comment by fidonet** [comment]
I'm running 2.11.2 on a Pi Zero W (installed using the scripts from your FAQS - thank you!) and still periodically seeing this error

Oct 28 20:45:16 raspberrypi room-assistant[15829]: /opt/nodejs/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100
Oct 28 20:45:16 raspberrypi room-assistant[15829]:     this._deviceId = this._socket.bindRaw(deviceId);
Oct 28 20:45:16 raspberrypi room-assistant[15829]:                                   ^
Oct 28 20:45:16 raspberrypi room-assistant[15829]: Error: EALREADY, Operation already in progress
Oct 28 20:45:16 raspberrypi room-assistant[15829]:     at Hci.init (/opt/nodejs/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100:35)
Oct 28 20:45:16 raspberrypi room-assistant[15829]:     at Hci.pollIsDevUp (/opt/nodejs/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:115:14)
Oct 28 20:45:16 raspberrypi room-assistant[15829]:     at ontimeout (timers.js:436:11)
Oct 28 20:45:16 raspberrypi room-assistant[15829]:     at tryOnTimeout (timers.js:300:5)
Oct 28 20:45:16 raspberrypi room-assistant[15829]:     at listOnTimeout (timers.js:263:5)
Oct 28 20:45:16 raspberrypi room-assistant[15829]:     at Timer.processTimers (timers.js:223:10)
2Oct 28 20:45:16 raspberrypi systemd[1]: room-assistant.service: Main process exited, code=exited, status=1/FAILURE
Oct 28 20:45:16 raspberrypi systemd[1]: room-assistant.service: Failed with result 'exit-code'.
fg

with -v enabled

10/28/2020, 8:56:54 PM - debug - BluetoothService: Querying for RSSI of 80:BE:05:74:19:14 using hcitool
10/28/2020, 8:56:54 PM - debug - BluetoothClassicService: Received RSSI of -17.7 for 80:BE:05:74:19:14 from bedroom
10/28/2020, 8:56:54 PM - debug - HomeAssistantService: Sending new state true for room-assistant-bluetooth-classic-80-be-05-74-19-14-tracker
10/28/2020, 8:56:54 PM - debug - HomeAssistantService: Sending new state bedroom for room-assistant-bluetooth-classic-80-be-05-74-19-14
10/28/2020, 8:56:54 PM - debug - HomeAssistantService: Sending new attributes {"distance":17.7,"lastUpdatedAt":"2020-10-28T20:56:54.896Z"} for room-assistant-bluetooth-classic-80-be-05-74-19-14
noble warning: unknown handle 11 disconnected!
10/28/2020, 8:57:00 PM - debug - BluetoothService: Querying for RSSI of 18:55:E3:96:96:D4 using hcitool
10/28/2020, 8:57:00 PM - debug - BluetoothClassicService: Received RSSI of -13.8 for 18:55:E3:96:96:D4 from bedroom
10/28/2020, 8:57:00 PM - debug - HomeAssistantService: Sending new attributes {"distance":13.8,"lastUpdatedAt":"2020-10-28T20:57:00.922Z"} for room-assistant-bluetooth-classic-18-55-e3-96-96-d4
noble warning: unknown handle 11 disconnected!
10/28/2020, 8:57:06 PM - debug - BluetoothService: Querying for RSSI of 8C:86:1E:61:36:43 using hcitool
10/28/2020, 8:57:06 PM - debug - BluetoothClassicService: Received RSSI of -11.5 for 8C:86:1E:61:36:43 from bedroom
10/28/2020, 8:57:06 PM - debug - HomeAssistantService: Sending new attributes {"distance":11.5,"lastUpdatedAt":"2020-10-28T20:57:06.596Z"} for room-assistant-bluetooth-classic-8c-86-1e-61-36-43
noble warning: unknown handle 11 disconnected!
10/28/2020, 8:57:12 PM - debug - BluetoothService: Querying for RSSI of 78:7B:8A:37:A1:D7 using hcitool
10/28/2020, 8:57:13 PM - debug - BluetoothClassicService: Received RSSI of 0 for 78:7B:8A:37:A1:D7 from bedroom
10/28/2020, 8:57:13 PM - debug - HomeAssistantService: Sending new attributes {"distance":0,"lastUpdatedAt":"2020-10-28T20:57:13.491Z"} for room-assistant-bluetooth-classic-78-7b-8a-37-a1-d7
noble warning: unknown handle 11 disconnected!
10/28/2020, 8:57:18 PM - debug - BluetoothService: Querying for RSSI of 80:BE:05:74:19:14 using hcitool
10/28/2020, 8:57:19 PM - debug - BluetoothClassicService: Received RSSI of -18.6 for 80:BE:05:74:19:14 from bedroom
10/28/2020, 8:57:19 PM - debug - HomeAssistantService: Sending new attributes {"distance":18.6,"lastUpdatedAt":"2020-10-28T20:57:19.076Z"} for room-assistant-bluetooth-classic-80-be-05-74-19-14
noble warning: unknown handle 11 disconnected!
10/28/2020, 8:57:22 PM - info - BluetoothLowEnergyService: Discovered new BLE peripheral 54cbd4be8fe1 with ID 54cbd4be8fe1 and RSSI -87
10/28/2020, 8:57:24 PM - debug - BluetoothService: Querying for RSSI of 18:55:E3:96:96:D4 using hcitool
10/28/2020, 8:57:26 PM - debug - BluetoothService: Query of 18:55:E3:96:96:D4 reached scan time limit, resetting hci0
/opt/nodejs/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100
    this._deviceId = this._socket.bindRaw(deviceId);
                                  ^

Error: EALREADY, Operation already in progress
    at Hci.init (/opt/nodejs/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100:35)
    at Hci.pollIsDevUp (/opt/nodejs/lib/node_modules/room-assistant/node_modules/@abandonware/noble/lib/hci-socket/hci.js:115:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by mKeRix** [comment]
Yeah, I'm sorry about that. This version did not actually fix this issue completely, I'm currently tracking it in #316.

It drastically reduced the issues in my test setup, which is why I thought it was fixed. Currently I'm trying out different other ideas to fix this, but since I have to wait at least half a day for each idea to be sure it's fine now it takes some time.
