### ISSUE TITLE
Inconsistent Scan Results

### ISSUE THREAD

**Issue by teshiburu2020** [mKeRix/room-assistant#305]
I am fairly new to room-assistant, so far I have it set up using 1 new pi-zero, and it works wonderfully, if I'm sitting next to the device. 

However, currently in testing, my son who is in his room less than 5m away from the pi-zero constantly flits between "Living Room" and "not_home" 

![image](https://user-images.githubusercontent.com/65967646/96228836-00e96300-0f8e-11eb-894f-af860a12c225.png)

I read the troubleshooting section about the incorrect not_home states, and increased that timeoutCycles to 10 as below 

![image](https://user-images.githubusercontent.com/65967646/96228952-31c99800-0f8e-11eb-8aad-a028ed0191b0.png)

But it doesn't seem to have had a positive effect?

**Comment by mledford** [comment]
It sounds like you need to set the `minRssi`. In particular you might set a default value to only pick up devices so they are reported for that node when it is considered in that room. You would then want other Pis for other rooms so you know which room a device is in.

**Comment by teshiburu2020** [comment]
Seems to be mainly linked to one device in particular, as you can see on the 6p often drops out more. 

Can I set a minrssi per device? 
![Screenshot_20201016-193700](https://user-images.githubusercontent.com/65967646/96296375-1ccd2300-0fe7-11eb-9e48-127fa78699c2.png)
![Screenshot_20201016-193653](https://user-images.githubusercontent.com/65967646/96296378-1d65b980-0fe7-11eb-9454-6cbd358be08a.png)

**Comment by mledford** [comment]
According to the documentation, yes.

https://www.room-assistant.io/integrations/bluetooth-classic.html#requirements

See the sample config files at the bottom.

**Comment by teshiburu2020** [comment]
Cool thanks, now to under how it worked

**Comment by keesdd** [comment]
Hi all,

iam having the exact same issue's. Using 2 rpi's zero w. When changing the minRssi "to high" the rpi from downstairs is also picking up my iPhone when iam upstairs. So the room reporting is incorrect. I need to use a low minRssi (-10), if i set it to -15 i get the wrong rooms reported.

Placed my iPhone 1 meter away with minRssi -10. For a few hours it works good, then after 2:33 am it starts reporting not_home and in the room on and off.

![image](https://user-images.githubusercontent.com/13919434/96686374-bea19680-137e-11eb-8c78-0d843d1b6ef3.png)

Dont know how to get it more accurate without mixed room presence reporting.

**Comment by mKeRix** [comment]
@keesdd Looking at your state visualization I would recommend to give first give debouncing a try, and if that doesn't work try out the averaging. You can define these behaviors per entity in room-assistant, check out the [entities docs](https://www.room-assistant.io/guide/entities.html#settings). That should clean up these random not_homes and hopefully make your automations run more reliably without much more effort.

**Comment by teshiburu2020** [comment]
@mKeRix I've set my minRssi fairly low, like -3 and such as my house isnt the largest and can also have the issues that @keesdd mentioned. 

I was looking at averages but I'm confused by how it should be added? Is it added as a new section after bluetooth classic,

What about the bluetooth-classic-xx-tracker should that be changed to my devices?

**Comment by mKeRix** [comment]
@teshiburu2020 You add the options to the config just like the other ones, the config examples in the docs always start at the top level. So you would e.g. have:

```yaml
global:
  integrations:
    - bluetoothClassic
bluetoothClassic:
  addresses:
    - AB:CD:XX:XX:XX
entities:
  behaviors:
    bluetooth-classic-ab-cd-xx-xx-xx-tracker:
      rollingAverage:
        window: 300
```

You can also view all available room-assistant entity IDs by going to http://<room-assistant-ip>:6415/entities in your browser and looking at the JSON.

**Comment by teshiburu2020** [comment]
OK - Cool thanks, I'll take a look. 

Just need to do some finer work on my minRssi settings I feel. 

As last night, my phone was on my night stand, next to the "Bed Room" device, and look how inconsistent things are! 

![image](https://user-images.githubusercontent.com/65967646/97797981-9d139b00-1c19-11eb-9c3d-4ed68f9b3c05.png)

I'm still struggling to get my head around how the minRssi should be configured.

**Comment by mKeRix** [comment]
Configuring the `minRssi` just right can be a bit tedious. I did it by setting some values, letting it run for a while and checking periodically if the value matches the reality. If it didn't I checked the current distances via the API and adjusted the settings so it would make the system reflect reality. This way I could step by step get closer to what works for me.

**Comment by keesdd** [comment]
tnx for the response and i will tryout the debounce settings.

and also for clarifying how the classic entitie needed to be set in the config (_bluetooth-classic-ab-cd-xx-xx-xx-tracker:_)

**Comment by teshiburu2020** [comment]
@mKeRix Thanks for that, I've added the following to my local.yml on each of my pizeros, lets see what happened 
```

entities:
  behaviors:
    bluetooth-classic-a0-10-81-03-bc-c3-tracker:
      rollingAverage:
        window: 300
    bluetooth-classic-74-a5-28-69-90-0f-tracker:
      rollingAverage:
        window: 300
    bluetooth-classic-f8-0f-f9-ce-40-80-tracker:
      rollingAverage:
        window: 300

```
hopefully this is now correct?

**Comment by teshiburu2020** [comment]
Seems to take real issue with my Pixel 4 lol!! even triggered a swap and the duration between swaps wasnt 300 seconds lol 

![image](https://user-images.githubusercontent.com/65967646/98044033-272c5100-1e1e-11eb-9f75-042cf84f65b6.png)

any ideas?

**Comment by teshiburu2020** [comment]
Yeah, it has some real distaste for my pixel 4 ignoring all the rolling averages seemingly as well?

```
3 November 2020
21:52:11
Changed to not_home
21:51:15
Changed to Office
21:44:45
Changed to Bed Room
21:28:40
Changed to Living Room
21:13:54
Changed to Living Room
```

**Comment by mKeRix** [comment]
Could you update your configuration to use `bluetooth-classic-a0-10-81-03-bc-c3` and so on (without `-tracker` at the end) for the entity keys and then restart room-assistant?

When I copied the example into the thread here I was thinking of the device tracker, but what you want to have the average on is the sensor.

**Comment by teshiburu2020** [comment]
Just changed this over, so lets see what it does :)

**Comment by teshiburu2020** [comment]
Mkay, so changed that over and it seems more consistent which is nice. 

However, I think I'm now at the point where the minRSSI is going to matter? 

take these 2 from the API for example 

This is from the pi in the "bed room"

`    "id": "bluetooth-classic-a0-10-81-03-bc-c3",
    "name": "Galaxy S8 Room Presence",
    "distributed": true,
    "distances": {
      "Bed Room": {
        "lastUpdatedAt": "2020-11-06T13:28:37.935Z",
        "distance": 3.7,
        "outOfRange": false
      },
      "Office": {
        "lastUpdatedAt": "2020-11-06T13:27:14.392Z",
        "distance": 10.1,
        "outOfRange": false
      },
      "Living Room": {
        "lastUpdatedAt": "2020-11-06T13:27:56.003Z",
        "distance": 0,
        "outOfRange": false
      },
      "Joshes Room": {
        "lastUpdatedAt": "2020-11-06T13:28:32.407Z",
        "distance": 16.1,
        "outOfRange": false`

and this is from the living room 

`    "id": "bluetooth-classic-a0-10-81-03-bc-c3",
    "name": "Galaxy S8 Room Presence",
    "distributed": true,
    "distances": {
      "Living Room": {
        "lastUpdatedAt": "2020-11-06T13:27:54.733Z",
        "distance": 0,
        "outOfRange": false
      },
      "Bed Room": {
        "lastUpdatedAt": "2020-11-06T13:28:38.212Z",
        "distance": 3.7,
        "outOfRange": false
      },
      "Office": {
        "lastUpdatedAt": "2020-11-06T13:27:14.417Z",
        "distance": 10.1,
        "outOfRange": false
      },
      "Joshes Room": {
        "lastUpdatedAt": "2020-11-06T13:28:32.420Z",
        "distance": 16.1,
        "outOfRange": false`

But the phone is reporting that its in the bedroom to home-assistant? 

![image](https://user-images.githubusercontent.com/65967646/98371766-9d0a0580-2034-11eb-9eba-6b40f0a062df.png)

**Comment by mKeRix** [comment]
Indeed, the distance is showing as closer in the living room. The state itself is now affected by the rolling average though, so it won't immediately switch to the living room. It will only switch after it has been in the living room for some time (or more specifically, after living room is the state that the entity spent the longest time in in the last 300 seconds).

**Comment by teshiburu2020** [comment]
Yeah time to play with minRssi then as that device hasn't moved all day lol and the bedroom is a whole floor between it lol

**Comment by teshiburu2020** [comment]
So getting there with minRssi to do as i want, but any idea how i can combat this reporting distance 0 on 2 rooms that are physically 10 metres away... 


```
"id": "bluetooth-classic-74-a5-28-69-90-0f",
    "name": "Nexus 6P Room Presence",
    "distributed": true,
    "distances": {
      "Living Room": {
        "lastUpdatedAt": "2020-11-07T09:50:00.510Z",
        "distance": 0,
        "outOfRange": false
      },
      "Office": {
        "lastUpdatedAt": "2020-11-07T08:02:07.198Z",
        "distance": 13.4,
        "outOfRange": false
      },
      "Joshes Room": {
        "lastUpdatedAt": "2020-11-07T09:49:48.653Z",
        "distance": 0,
        "outOfRange": false
      },
      "Bed Room": {
        "lastUpdatedAt": "2020-11-07T09:49:36.506Z",
        "distance": 13.3,
        "outOfRange": false
      }
```

**Comment by mKeRix** [comment]
These values come from a system level, not sure if there is much you can do by configuring the Pi differently (but if you find something do let us know!). Something that you could try is somehow limit the signal quality of the instances that report closely together, just enough to bring them out of the "golden range", which is what you see as 0. This can be achieved by e.g. hiding the Pi behind some furniture or putting it on a different height.
