### ISSUE TITLE
Cluster nodes unreliable and stop reporting presence

### ISSUE THREAD

**Issue by RichEsq** [mKeRix/room-assistant#315]
**Describe the bug**
I am having difficulty getting reliable presence reports from my nodes.

I am running 4 nodes, each on Raspberry Pis:

1. Raspberry Pi 4 - Ethernet, Home Assistant plugin
2. Raspberry Pi 3 - Ethernet, NodeJS
3. Raspberry Pi Zero W - Wifi, NodeJS
4. Raspberry Pi Zero W - Wifi, NodeJS

Only the Raspberry Pi 4 reliably reports presence. The remaining will inevitably stop reporting presence to Home Assistant after a few hours. It's not clear to me what is causing this, but a reset of the pi will temporarily resolve it. 

I reinstall the whole system about a week ago (with a fresh Home Assistant install) and followed the quick start guide. 

**To reproduce**
Start configuration, wait.

**Relevant logs**

```
● room-assistant.service - room-assistant service
   Loaded: loaded (/etc/systemd/system/room-assistant.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-10-26 18:24:05 AEDT; 11min ago
 Main PID: 5626 (node)
   CGroup: /system.slice/room-assistant.service
           ├─5626 node /opt/nodejs/bin/room-assistant
           ├─5857 hcitool -i hci0 cc XX:XX:XX:XX:XX:XX
           ├─5861 hcitool -i hci0 cc XX:XX:XX:XX:XX:XX
           ├─5865 hcitool -i hci0 cc XX:XX:XX:XX:XX:XX
           ├─5869 hcitool -i hci0 cc XX:XX:XX:XX:XX:XX
           ├─5873 hcitool -i hci0 cc XX:XX:XX:XX:XX:XX
           ├─5877 hcitool -i hci0 cc XX:XX:XX:XX:XX:XX
           ├─5881 hcitool -i hci0 cc XX:XX:XX:XX:XX:XX
           ├─5885 hcitool -i hci0 cc XX:XX:XX:XX:XX:XX
           └─5925 hcitool -i hci0 cc XX:XX:XX:XX:XX:XX

Oct 26 18:24:30 RoomAssistantKids room-assistant[5626]: 10/26/2020, 6:24:30 PM - info - NestApplication: Nest application successfully started
Oct 26 18:24:32 RoomAssistantKids room-assistant[5626]: 10/26/2020, 6:24:32 PM - info - HomeAssistantService: Device tracker requires manual setup in Home Assistant with topic: room-assistant/device_tracker/bluetooth-classic-xx
Oct 26 18:28:54 RoomAssistantKids room-assistant[5626]: 10/26/2020, 6:28:54 PM - info - ClusterService: bedroom has been elected as leader
Oct 26 18:33:11 RoomAssistantKids room-assistant[5626]: 10/26/2020, 6:33:11 PM - info - ClusterService: Removed 192.168.1.207:6425 from the cluster with id bedroom
Oct 26 18:33:12 RoomAssistantKids room-assistant[5626]: 10/26/2020, 6:33:12 PM - info - ClusterService: Removed 192.168.1.207:6425 from the cluster with id bedroom
Oct 26 18:33:12 RoomAssistantKids room-assistant[5626]: 10/26/2020, 6:33:12 PM - info - ClusterService: Removed 192.168.1.207:6425 from the cluster with id bedroom
Oct 26 18:33:18 RoomAssistantKids room-assistant[5626]: 10/26/2020, 6:33:18 PM - info - ClusterService: Added 192.168.1.207:6425 to the cluster with id bedroom
Oct 26 18:33:18 RoomAssistantKids room-assistant[5626]: 10/26/2020, 6:33:18 PM - info - ClusterService: bedroom has been elected as leader
Oct 26 18:33:19 RoomAssistantKids room-assistant[5626]: 10/26/2020, 6:33:19 PM - info - ClusterService: kitchen has been elected as leader
Oct 26 18:33:44 RoomAssistantKids room-assistant[5626]: 10/26/2020, 6:33:44 PM - info - HomeAssistantService: Device tracker requires manual setup in Home Assistant with topic: room-assistant/device_tracker/bluetooth-classic-xx

```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  instanceName: Kitchen
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://xxx:xxx:xxx:xxx:1883'
  mqttOptions:
    username: homeassistant
    password: xxx
bluetoothClassic:
  addresses:
    - 'XX:XX:XX:XX:XX:XX'
    - 'XX:XX:XX:XX:XX:XX'
cluster:
  networkInterface: eth0
  quorum: 3
  port: 6425
  peerAddresses:
    - 'xxx:xxx:xxx:xxx:6425'
    - 'xxx:xxx:xxx:xxx:6425'
    - 'xxx:xxx:xxx:xxx:6425'
  weight: 5
```

**Environment**
 - room-assistant version: 2.11.0
 - installation type: NodeJS, Hass.io
 - hardware: Raspberry Pi 4, Raspberry Pi 3, Raspberry Pi Zero W
 - OS: Linux, Mac

**Comment by embcla** [comment]
mKeRix told me that every node should have the HomeAssistant integration running, maybe you can try that too?

**Comment by mKeRix** [comment]
Are the `hcitool -i hci0 cc XX:XX:XX:XX:XX:XX` all for the same address or different ones? In theory there should only be maximum one of those subprocesses at a given time.

Apart from that, do you see the same issue when you raise the `interval` in the `bluetoothClassic` settings to e.g. 15?

**Comment by RichEsq** [comment]
@mKeRix They're two different mac addresses, which alternate (my phone and my partner's phone). I'll try raising the interval.

@embcla They all do - all of the configs are identical, with the only change being the name and peer addresses.

**Comment by RichEsq** [comment]
I increased the interval and the output is the same on at least one of my nodes. It's by far the least reliable one though, and might be the source of the problems. 

```
● room-assistant.service - room-assistant service
   Loaded: loaded (/etc/systemd/system/room-assistant.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-10-27 09:56:27 AEDT; 1h 13min ago
 Main PID: 262 (node)
   CGroup: /system.slice/room-assistant.service
           ├─ 262 node /opt/nodejs/bin/room-assistant
           ├─2715 hcitool -i hci0 cc 54:33:CB:9A:XX:XX
           ├─2719 hcitool -i hci0 cc B8:5D:0A:79:XX:XX
           ├─2723 hcitool -i hci0 cc 54:33:CB:9A:XX:XX
           ├─2727 hcitool -i hci0 cc B8:5D:0A:79:XX:XX
           ├─2732 hcitool -i hci0 cc 54:33:CB:9A:XX:XX
           ├─2740 hcitool -i hci0 cc B8:5D:0A:79:XX:XX
           ├─2781 hcitool -i hci0 cc 54:33:CB:9A:XX:XX
           ├─2785 hcitool -i hci0 cc B8:5D:0A:79:XX:XX
           └─2789 hcitool -i hci0 cc 54:33:CB:9A:XX:XX

Oct 27 09:56:27 RoomAssistantBedroom systemd[1]: Started room-assistant service.
Oct 27 09:57:18 RoomAssistantBedroom room-assistant[262]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Oct 27 09:57:18 RoomAssistantBedroom node[262]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Oct 27 09:57:18 RoomAssistantBedroom room-assistant[262]: *** WARNING *** Please fix your application to use the native API of Avahi!
Oct 27 09:57:18 RoomAssistantBedroom room-assistant[262]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Oct 27 09:57:18 RoomAssistantBedroom room-assistant[262]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in 
Oct 27 09:57:18 RoomAssistantBedroom room-assistant[262]: *** WARNING *** Please fix your application to use the native API of Avahi!
Oct 27 09:57:18 RoomAssistantBedroom room-assistant[262]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Oct 27 09:57:18 RoomAssistantBedroom node[262]: *** WARNING *** Please fix your application to use the native API of Avahi!
Oct 27 09:57:18 RoomAssistantBedroom node[262]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Oct 27 09:57:18 RoomAssistantBedroom node[262]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple 
Oct 27 09:57:18 RoomAssistantBedroom node[262]: *** WARNING *** Please fix your application to use the native API of Avahi!
Oct 27 09:57:18 RoomAssistantBedroom node[262]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Oct 27 09:57:22 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:22 AM - info - IntegrationsModule: Loading integrations: bluetooth-classic, home-assistant
Oct 27 09:57:28 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:28 AM - info - NestFactory: Starting Nest application...
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: AppModule dependencies initialized
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: ConfigModule dependencies initialized
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: NestEmitterModule dependencies initialized
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: IntegrationsModule dependencies initialized
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: HttpModule dependencies initialized
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: DiscoveryModule dependencies initialized
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: ClusterModule dependencies initialized
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: TerminusModule dependencies initialized
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: BluetoothModule dependencies initialized
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: ScheduleModule dependencies initialized
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: EntitiesModule dependencies initialized
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: HomeAssistantModule dependencies initialized
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: BluetoothClassicModule dependencies initialized
Oct 27 09:57:29 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:29 AM - info - InstanceLoader: StatusModule dependencies initialized
Oct 27 09:57:33 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:33 AM - info - RoutesResolver: EntitiesController {/entities}:
Oct 27 09:57:33 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:33 AM - info - RouterExplorer: Mapped {/entities, GET} route
Oct 27 09:57:33 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:33 AM - info - RoutesResolver: StatusController {/status}:
Oct 27 09:57:33 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:33 AM - info - RouterExplorer: Mapped {/status, GET} route
Oct 27 09:57:34 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:34 AM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.1.206:1883
Oct 27 09:57:35 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:35 AM - info - ConfigService: Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dis
Oct 27 09:57:35 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:35 AM - info - NestApplication: Nest application successfully started
Oct 27 09:57:44 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:44 AM - info - HomeAssistantService: Device tracker requires manual setup in Home Assistant with topic: 
Oct 27 09:57:44 RoomAssistantBedroom room-assistant[262]: 10/27/2020, 9:57:44 AM - info - HomeAssistantService: Device tracker requires manual setup in Home Assistant with topic: 
```

**Comment by vincentwolsink** [comment]
Same issue here. Multiple instances of `hcitool` running for my two devices.
Reboot of Pi Zero W does not fix the issue for me.

If I run one of the hcitool commands by hand it returns:
```
Can't create connection: Input/output error
```

**Comment by mKeRix** [comment]
Version 2.11.1 should prevent two inquiries (= two hcitool instances) running at a same time in theory. This might lead to some other issues, but at least we'd gain visibility. Can you see the same issues on that version as well?

**Comment by RichEsq** [comment]
Upgraded, and can confirm that Version 2.11.1 does prevent the duplicate inquiries. Unfortunately, I'm no longer getting any presence detection from the device. 

I'm also getting the same errors that @vincentwolsink describes. 

```
● room-assistant.service - room-assistant service
   Loaded: loaded (/etc/systemd/system/room-assistant.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-10-27 22:09:46 AEDT; 13h ago
 Main PID: 281 (node)
   CGroup: /system.slice/room-assistant.service
           └─281 node /opt/nodejs/bin/room-assistant

Oct 27 22:09:46 RoomAssistantBedroom systemd[1]: Started room-assistant service.
Oct 27 22:10:15 RoomAssistantBedroom room-assistant[281]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Oct 27 22:10:15 RoomAssistantBedroom node[281]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Oct 27 22:10:15 RoomAssistantBedroom room-assistant[281]: *** WARNING *** Please fix your application to use the native API of Avahi!
Oct 27 22:10:15 RoomAssistantBedroom room-assistant[281]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Oct 27 22:10:15 RoomAssistantBedroom room-assistant[281]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Oct 27 22:10:15 RoomAssistantBedroom room-assistant[281]: *** WARNING *** Please fix your application to use the native API of Avahi!
Oct 27 22:10:15 RoomAssistantBedroom room-assistant[281]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Oct 27 22:10:15 RoomAssistantBedroom node[281]: *** WARNING *** Please fix your application to use the native API of Avahi!
Oct 27 22:10:15 RoomAssistantBedroom node[281]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Oct 27 22:10:15 RoomAssistantBedroom node[281]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Oct 27 22:10:15 RoomAssistantBedroom node[281]: *** WARNING *** Please fix your application to use the native API of Avahi!
Oct 27 22:10:15 RoomAssistantBedroom node[281]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Oct 28 09:43:42 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:43:41 AM - info - IntegrationsModule: Loading integrations: bluetooth-classic, home-assistant
Oct 28 09:43:58 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:43:58 AM - info - NestFactory: Starting Nest application...
Oct 28 09:44:00 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:00 AM - info - InstanceLoader: AppModule dependencies initialized
Oct 28 09:44:00 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:00 AM - info - InstanceLoader: ConfigModule dependencies initialized
Oct 28 09:44:00 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:00 AM - info - InstanceLoader: NestEmitterModule dependencies initialized
Oct 28 09:44:00 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:00 AM - info - InstanceLoader: IntegrationsModule dependencies initialized
Oct 28 09:44:01 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:01 AM - info - InstanceLoader: HttpModule dependencies initialized
Oct 28 09:44:01 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:01 AM - info - InstanceLoader: DiscoveryModule dependencies initialized
Oct 28 09:44:01 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:01 AM - info - InstanceLoader: ClusterModule dependencies initialized
Oct 28 09:44:01 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:01 AM - info - InstanceLoader: TerminusModule dependencies initialized
Oct 28 09:44:01 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:01 AM - info - InstanceLoader: BluetoothModule dependencies initialized
Oct 28 09:44:01 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:01 AM - info - InstanceLoader: ScheduleModule dependencies initialized
Oct 28 09:44:01 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:01 AM - info - InstanceLoader: EntitiesModule dependencies initialized
Oct 28 09:44:01 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:01 AM - info - InstanceLoader: HomeAssistantModule dependencies initialized
Oct 28 09:44:01 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:01 AM - info - InstanceLoader: BluetoothClassicModule dependencies initialized
Oct 28 09:44:01 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:01 AM - info - InstanceLoader: StatusModule dependencies initialized
Oct 28 09:44:08 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:08 AM - info - RoutesResolver: EntitiesController {/entities}:
Oct 28 09:44:09 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:08 AM - info - RouterExplorer: Mapped {/entities, GET} route
Oct 28 09:44:09 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:09 AM - info - RoutesResolver: StatusController {/status}:
Oct 28 09:44:09 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:09 AM - info - RouterExplorer: Mapped {/status, GET} route
Oct 28 09:44:15 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:15 AM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.1.206:1883
Oct 28 09:44:15 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:15 AM - info - ConfigService: Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml
Oct 28 09:44:16 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 9:44:16 AM - info - NestApplication: Nest application successfully started
Oct 28 10:40:49 RoomAssistantBedroom room-assistant[281]: 10/28/2020, 10:40:49 AM - info - ClusterService: Added 192.168.1.206:6425 to the cluster with id kitchen

```

**Comment by vincentwolsink** [comment]
This doesn't look like a room-assistant issue to me. It only seems room-assistant is triggering this by doing a lot of bluetooth scans.

When I reboot or power off/on my Pi Zero W without starting room-assistant, the first time I run `hcitool` manually it directly fails.
```
pi@pi:~ $ hcitool -i hci0 cc XX:XX:XX:XX:XX:XX
Can't create connection: Input/output error
```

So for me it is now permanently broken somehow..

**Comment by mKeRix** [comment]
If a reboot doesn't fix the issue there are a couple troubleshooting steps you can try:

- ensure Bluetooth is on on the device you want to track and it is close to the room-assistant instance
- try to restart the device you are tracking (if possible)
- update all packages using `sudo apt-get update && sudo apt-get upgrade`
- update the Raspberry firmware using `rpi-update`
- backup your config and refresh the SD with a fresh version of Raspbian

**Comment by RichEsq** [comment]
@mKeRix do you have a known good SD card image for a Raspberry Pi Zero W? Would be nice if we could reduce some variability.

Also, I should take this opportunity to say that Room Assistant is a fantastic project, and I really appreciate your attention and hard work on it.

**Comment by RichEsq** [comment]
I think this is probably related to issue #314

**Comment by vincentwolsink** [comment]
> If a reboot doesn't fix the issue there are a couple troubleshooting steps you can try:

I tried everything except a clean install. This might fix it for now, but is not sustainable.
I cleanly installed 3 Raspberry Pi Zero W's earlier and all three of them had this issue after running for about a day.

**Comment by mKeRix** [comment]
@RichEsq There isn't one, at least not yet. I played with the thought a while ago but ultimately didn't need it since ansible allows a pretty repeatable setup. With that resetting a Pi is just re-flashing, setting up WiFi and SSH and then running the ansible command again.

@vincentwolsink I get that this is frustrating and I'm sorry that the steps above don't help. At the same time it's tricky to debug these things with them being in system dependencies and not reproducible. If you want to get some more information you can run `hcidump`, then execute the `hcitool` command in a different terminal. That should show you exactly what is happening with the Bluetooth adapter.

If you say that this always happens after a while you could try to make room-assistant use the adapter more carefully by increasing the `interval` as mentioned above and in addition also increasing the `scanTimeLimit` to something above 6 seconds. This should make it so that room-assistant doesn't need to reset the adapter anymore.

**Comment by vincentwolsink** [comment]
@mKeRix I am not frustrated :) Was just trying to provide you with some information about the situation.

I will debug some more myself and will report back if I have found something usefull.

**Comment by vincentwolsink** [comment]
Ok. When I increase `interval` and `scanTimeLimit` things are stable. Detection is just slow. So I guess now its a case of tweaking those settings until things are stable and detection as good as possible.

@mKeRix 
Can you maybe tell me how the detection algorithm works? Will the nodes communicatie RSSI values and only report the node with the highest RSSI value for a device, or will the latest detection of a device on any node always report? Or will the nodes only report when the previous node lost a device (which makes the timeoutCycles setting important)?

**Comment by mKeRix** [comment]
The Bluetooth Classic detection has this workflow:

- leader instance does a 1:1 mapping of available room-assistant instances and tracked devices (based on local config)
- leader instance sends out requests for RSSI inquiry to these mapped instances
- each instance performs its inquiry task and broadcasts findings to *all* nodes it is connected to
  - the inquiry is forced to run at max `scanTimeLimit` long
- instances received inquired values and save them into a local cache along with the current timestamp
  - each node has its own cache and is capable of making a state decision on its own
  - this decision may be different (depending on the state of the cache), but will at most times be the same on all nodes
- state updates determine the current value by checking who is closest, not out of range (`minRssi`) and within the timeframe of `timeoutCycles`
  - state update is performed on each received measurement and every second (e.g. for when a device is not in reach, as then there wouldn't be any reported RSSIs)
  - only a leader instance reports its state to MQTT/Home Assistant
- this flow is repeated every `interval` seconds

Does that answer your questions?

**Comment by RichEsq** [comment]
@vincentwolsink can you share your settings, I'm going to try again

**Comment by vincentwolsink** [comment]
@RichEsq 

```
global:
  instanceName: 'Keuken'
  integrations:
    - homeAssistant
    - bluetoothClassic
cluster:
  weight: 2
  autoDiscovery: false
  networkInterface: wlan0
  port: 6425
  peerAddresses:
    - x.x.x.x:6425
    - x.x.x.x:6425
homeAssistant:
  mqttUrl: 'mqtt://x.x.x.x:1883'
  mqttOptions:
    username: 'xx'
    password: 'xx'
bluetoothClassic:
  interval: 10
  scanTimeLimit: 7
  timeoutCycles: 3
  addresses:
    - 'xx:xx:xx:xx:xx:xx'
    - 'xx:xx:xx:xx:xx:xx'
```

This is my complete config for one of the nodes. If I lower `timeoutCycles` then presence will start flapping a lot between the nodes for the devices. I feel detection is still too slow now, but it is kinda stable.

Also, first I relied on mDNS for the nodes to discover each other. Although that seemed to work, some DNS errors started to show up in the logs once in a while, so I switch to manually specifying them.

**Comment by Larsaeaeae** [comment]
Hi,
i think i got the same problem.
My impression is, that the cluster stops reporting when no device is around for a few hours, but as soon as i restart the room-assistant service everythings fine again. 
I'll test tonight by leaving a phone at home and will report back tomorrow.

**Comment by Larsaeaeae** [comment]
Didn't work, after 18 hours it stopped reporting the phone i left at home and didn't report the presence of any other phones.

**Comment by mKeRix** [comment]
Are you only restarting room-assistant or the whole Pi? Do you see anything notable in the logs when it stops reporting? It may also help to run room-assistant in verbose mode to debug this.

**Comment by Larsaeaeae** [comment]
I am only restarting room-assistant, then it starts working again. 
Nope not really, how do i run it in verbose mode? I would love to help you!

**Comment by mKeRix** [comment]
Running room-assistant in verbose mode is just running it like normal, but with the `-v` flag added. So e.g. `room-assistant -v`. If you use the systemd service you can add that to your unit file and then do `systemctl daemon-reload` before restarting the service.

**Comment by Larsaeaeae** [comment]
okay, did that, will report back tomorrow!

**Comment by Larsaeaeae** [comment]
I think I solved my problem, when running in verbose mode i saw something suspicious:

```
Nov 18 09:22:19 pi-arbeitszimmer room-assistant[382]: 11/18/2020, 09:22:19 - debug - HomeAssistantService: Received message off on room-assistant/switch/arbeitszimmer-bluetooth-classic-inquiries-switch/command for room-assistant-arbeitszimmer-bluetooth-classic-inquiries-switch
Nov 18 09:22:40 pi-arbeitszimmer room-assistant[382]: 11/18/2020, 09:22:40 - debug - HomeAssistantService: Received message off on room-assistant/switch/arbeitszimmer-bluetooth-classic-inquiries-switch/command for room-assistant-arbeitszimmer-bluetooth-classic-inquiries-switch
```

I think my Home-Assistant automation to turn everything connected to it off when i leave home turned off the room-assistant tracking of bluetooth devices.
I didn't even know you could do that since i had to manually setup the mqtt device-trackers and that log-entry wasn't in the normal non verbose log..  
Still testing, but looking good at the moment!

**Comment by Larsaeaeae** [comment]
This was definitely my problem, now its working like should, thank you!

**Comment by RichEsq** [comment]
@mKeRix I tried your instructions to use version 2.10.1 (pre-bluetooth changes), and so far that seems to have helped. I'm still keeping an eye on it though. 

One of my nodes is the HomeAssistant Add-on - is there any way revert that to 2.10.1 as well?

**Comment by mKeRix** [comment]
That's too bad. :(

That message may also appear when the device is not in reach, or when the adapter cannot reach it for some reason. You can run `hcidump` when you see that message appear to get deeper insights into what is happening on the actual Bluetooth adapter.

Another idea could be to try and restart the adapter only when you see this occurring by running `hciconfig hci0 down && hciconfig hci0 up`.
