### ISSUE TITLE
RSSI Distance Positive / Negative

### ISSUE THREAD

**Issue by Veldkornet** [mKeRix/room-assistant#319]
**Describe the bug**
I’ve been watching my MQTT trying to figure out what a good minimum RSSI would be for each room, but I’ve noticed that the RSSI jumps between positives and negatives often... Why is this? I was under the impression that it can’t go above zero.

Below are the MQTT events of my phone while sitting on the charger.

![6D03A0CC-E748-4D1D-A38E-709B3192734C](https://user-images.githubusercontent.com/10297361/97238643-29712880-17ea-11eb-9a30-3ff7f740a153.jpeg)

**Comment by mKeRix** [comment]
Is this the Bluetooth Classic or the Bluetooth Low Energy integration?

**Comment by Veldkornet** [comment]
BluetoothClassic. 

Device in event screenshot is a Google Pixel phone. 

I wasn't aware I could use BLE with the phones, is that a better option?

**Comment by mKeRix** [comment]
For Androids you can install an app that emits beacon signals in the background - I don't have a direct recommendation as I haven't had an Android in a while, but plenty of people posted about what they use online. On iOS devices this doesn't work, as those cannot broadcast with a static ID. I'm trying to work around this in #309.

What is better depends on the circumstances, BLE will update more frequently and reliably but also requires an extra app to be installed and running in the background. 

But, to answer your original question: BT Classic can go negative indeed! 0 is the "golden range" of signal quality, but the signal quality can get even better than that. In those cases the RSSI value will be positive, and the distance being the inverse of the RSSI for BT Classic will be negative.

**Comment by grove825** [comment]
@mKeRix At my setup I also have the distance mostly on negative distance. Ihave issues with setting the minRssi. It only works when I give a positive number at the minRssi. Or do I do something wrong there?

**Comment by mKeRix** [comment]
Positive minRssi makes sense if the distances you see reported are mostly negative - is there something that you'd expect to work, but doesn't? You can imagine the formula for BT Classic to be `maxDistance * -1 = minRssi`.
