### ISSUE TITLE
Reduce number of Events (option) - Change "debounce" to fire on the "Leading Edge" (option)

### ISSUE THREAD

**Issue by yonz2** [mKeRix/room-assistant#329]
**To Many duplicate events fired towards Home Assistant**
We discussed the issue of multiple events in Node-Red  See closed issue #(326) .

However, Home Assistant is flooded with events originating from Room Assistant. I've been running RA with a Gigaset G-Tag for now 24 hours. They are both sitting right next to each other (distance = 10 cm). Nothing has moved at all.
But, I get over 1000 events per hour in my Home Assistant Logs, even though there has been no change at all.

```text
Id	State		Attributes			Time_Fired	
114419	"raspi1"	"{""distance"": 0, ""last_updated_at"": ""2020-11-01T17:26:48.325Z"", ""friendly_name"": ""OrangeTag"", ""icon"": ""mdi:bluetooth""}"	"2020-11-01 17:26:48.487022+00"
114418	"raspi1"	"{""distance"": 0, ""last_updated_at"": ""2020-11-01T17:26:47.311Z"", ""friendly_name"": ""OrangeTag"", ""icon"": ""mdi:bluetooth""}"	"2020-11-01 17:26:47.376656+00"
114417	"raspi1"	"{""distance"": 0, ""last_updated_at"": ""2020-11-01T17:26:37.268Z"", ""friendly_name"": ""OrangeTag"", ""icon"": ""mdi:bluetooth""}"	"2020-11-01 17:26:46.394539+00"
114416	"not_home"	"{""distance"": 0, ""last_updated_at"": ""2020-11-01T17:26:37.268Z"", ""friendly_name"": ""OrangeTag"", ""icon"": ""mdi:bluetooth""}"	"2020-11-01 17:26:38.482335+00"
114415	"raspi1"	"{""distance"": 0, ""last_updated_at"": ""2020-11-01T17:26:37.268Z"", ""friendly_name"": ""OrangeTag"", ""icon"": ""mdi:bluetooth""}"	"2020-11-01 17:26:37.426404+00"
114414	"raspi1"	"{""last_updated_at"": ""2020-11-01T17:26:35.453Z"", ""friendly_name"": ""OrangeTag"", ""icon"": ""mdi:bluetooth""}"	"2020-11-01 17:26:35.484437+00"
114413	"raspi1"	"{""distance"": 0, ""last_updated_at"": ""2020-11-01T17:26:29.212Z"", ""friendly_name"": ""OrangeTag"", ""icon"": ""mdi:bluetooth""}"	"2020-11-01 17:26:29.856777+00"
114412	"raspi1"	"{""distance"": 0, ""last_updated_at"": ""2020-11-01T17:26:28.201Z"", ""friendly_name"": ""OrangeTag"", ""icon"": ""mdi:bluetooth""}"	"2020-11-01 17:26:28.226712+00"
114411	"raspi1"	"{""distance"": 0, ""last_updated_at"": ""2020-11-01T17:26:26.199Z"", ""friendly_name"": ""OrangeTag"", ""icon"": ""mdi:bluetooth""}"	"2020-11-01 17:26:26.221151+00"
```
It would be great to add an option to Room Assistant to reduce the number of events fired when there is little or no change in the measured values (Add some "Fuzzy-ness").

Then there is the issue of the false event "not_home" (see log above) this is intermittent, somtimes few times an hour, or sometimes every 2-3 hours (I found no logic in this). For this you have implemented the **debounce** feature. If I now set the debounce variable to say :
```json
entities:
  behaviors:
    ble-589ec6203f0a:
      debounce:
        wait: 4
        maxWait: 8
```
Then in the case of a REAL event, I might wait up to 8 seconds before the event is fired. To compensate it, would be good to have **debounce** fire on the _leading edge_ (See: https://css-tricks.com/debouncing-throttling-explained-examples/#leading-edge-or-immediate )
This could of course just be an option, set in the config file. Such an option would allow us to _tune_ RA to fire the events when required.

Yonz

**Comment by mKeRix** [comment]
Regarding the amount of events: do you use the entity attributes for anything? Instead of introducing logic to handle fuzziness I wonder if it would be enough to provide an option for not sending the attribute updates. This should eliminate 99% of the events you're seeing I think.

I like your proposal for adding another option to the debounce settings so it can be made a leading edge, especially since it shouldn't be too much additional effort to implement.

Apart from that, you could try raising the `timeout` setting of the `bluetoothLowEnergy` integration a bit to get rid of the random wrong `not_home` states. If you have `maxDistance` configured on all instances it could also be beneficial to raise that on some instances.

**Comment by yonz2** [comment]
Hi,

No All I  am interested in is the presence. So if the number of messgaes is reduced by not sending some attributes, that would be fine.

I'm working on the tuning of the timeout setting, lets see what that brings.

But to have thge "Leading Edge" Option would be a really good.

Best regards
Yonz
