### ISSUE TITLE
No devices being detected

### ISSUE THREAD

**Issue by accelle17** [mKeRix/room-assistant#33]
I have installed on rpi 3 with Jessie image (9.2.1 node-js) and rpi 0w with stretch image (6.11.5 node-js) and it was able to start without any issue using root account. However, it cannot detect any devices after initializing. THe logs doesn't help either. WHat's odd is that on the console, the text color "BLE scanner was initialized" is only on white compared to the rest of the display (starting...  started..  and iBeacon scanner was initialized). I'm not sure if that means something.
I'm not sure what else am I missing.

**Comment by mKeRix** [comment]
Just to be sure: you have a publisher (console and/or MQTT) setup correctly, right?

Does ``sudo hcitool lescan`` on the command line find anything?

**Comment by accelle17** [comment]
Yes, i'm using a blank user and password on mqtt.
the hcitool lescan shows BLE devices around me.

**Comment by mKeRix** [comment]
Interesting, technically it should work. If you enable the console publisher in the config does it not list anything either? Last time someone reported this it was an issue with the MQTT connection/permissions.

**Comment by accelle17** [comment]
![room-assistant issue](https://user-images.githubusercontent.com/20294546/34206912-477d14b2-e5c3-11e7-8732-e98dcf3b81bc.PNG)

that's the only output from console. I'm using below mqtt config, I don't have security configured for the my mosquitto. 
```

 "mqtt": {
    "enabled": false,
    "url": "mqtt://192.168.1.157:1883",
    "username": "",
    "password": "",
    "reject_unauthorized": true,
    "topic": "room/living"
  },

```

**Comment by accelle17** [comment]
Well, I just realized that the mqtt was not yet enabled. So I reconfigured it, and then configured mosquitto with username/pw and added that to the room-assistant config but it still encounter the same issue.

**Comment by accelle17** [comment]
Strange, i added the mac of my mi band 2 on the whitelist and it fixed the issue. I thought using [""] or blank on the whitelist enables it to detect all ble devices?

**Comment by accelle17** [comment]
crap, should have used "" instead of [""] on the whitelist. im closing this issue :)

**Comment by mKeRix** [comment]
I'm glad you were able to figure it out on your own! :)

Just for any possible people coming here from Google in the future: to have no whitelist you have to put the option as `[]` or as `""` (like you mentioned).
