### ISSUE TITLE
Having problems getting Radbeacon to work.

### ISSUE THREAD

**Issue by julianrinaldi** [mKeRix/room-assistant#339]
I bought the suggested Radius Radbeacon and have it set up on one of my nodes. I have the mac address and ibeacon UUID I setup added to my whitelist. The entity shows up in my mqtt broker, but unlike my Bluetooth Classic devices, it only shows up as "status=online" and never publishes a state or any attributes. I've been trying to get this working for a week now. Is there any advice you can give?

**Comment by mKeRix** [comment]
Do you see the beacon being mentioned while starting room-assistant? A log message beginning with something like "Discovered new BLE peripheral". And: can you check what the room-assistant API says about your entity? You can view it by browsing to http://<room-assistant-ip>:6415/entities and then looking for your beacon ID. It should have some additional attributes available in the JSON.

**Comment by julianrinaldi** [comment]
This is the output I'm getting:

[{"attributes":{"nodes":["master-bedroom","office-desk","guest-bedroom-north","office","guest-hall","living-room-south","kitchen","garage","kitchen-south","front-vestibule","kitchen-west","gym","media-room","entry-hall","living-room","garbage-bins"]},"id":"status-cluster-size","name":"Garbage Bins Cluster Size","distributed":false,"state":16},{"attributes":{"quorumReached":true},"id":"status-cluster-leader","name":"Garbage Bins Cluster Leader","distributed":false,"state":"guest-bedroom-north"},{"attributes":{},"id":"ble-00112233445566778899aabbccddeeff-1-1-tracker","name":"00112233445566778899aabbccddeeff-1-1","distributed":true,"state":true},{"attributes":{"distance":0,"lastUpdatedAt":"2020-11-09T23:10:37.925Z"},"id":"ble-00112233445566778899aabbccddeeff-1-1","name":"00112233445566778899aabbccddeeff-1-1 Room Presence","distributed":true,"distances":{"Garbage Bins":{"lastUpdatedAt":"2020-11-09T23:10:37.925Z","distance":0,"outOfRange":false}},"timeout":5,"measuredValues":{"Garbage Bins":{"rssi":-23.361308475693633,"measuredPower":-61}},"state":"Garbage Bins"}]

I didn't see it mentioned when I started Room Assistant, but it looks like it's finding it from that output.

**Comment by julianrinaldi** [comment]
I added a second Radbeacon and still have the same issue. Not publishing state or attributes to my MQTT broker. The Room Presence sensor in Home Assistant shows up as "unknown".

[{"attributes":{"nodes":["kitchen-west","living-room","gym","garage","guest-hall","office","master-bedroom","kitchen","office-desk","front-vestibule","entry-hall","guest-bedroom-north","living-room-south","kitchen-south","media-room","waste-bins"]},"id":"status-cluster-size","name":"Waste Bins Cluster Size","distributed":false,"state":16},{"attributes":{"quorumReached":true},"id":"status-cluster-leader","name":"Waste Bins Cluster Leader","distributed":false,"state":"guest-bedroom-north"},{"attributes":{},"id":"ble-00112233445566778899aabbccddeeff-1-1-tracker","name":"Garbage Bin","distributed":true,"state":true},{"attributes":{"distance":1.5,"lastUpdatedAt":"2020-11-10T01:23:02.919Z"},"id":"ble-00112233445566778899aabbccddeeff-1-1","name":"Garbage Bin Room Presence","distributed":true,"distances":{"Waste Bins":{"lastUpdatedAt":"2020-11-10T01:23:02.919Z","distance":1.5,"outOfRange":false}},"timeout":5,"measuredValues":{"Waste Bins":{"rssi":-54.854125197898654,"measuredPower":-52}},"state":"Waste Bins"},{"attributes":{},"id":"ble-00112233445566778899aabbccddeeff-1-2-tracker","name":"Recycling Bin","distributed":true,"state":true},{"attributes":{"distance":0.5,"lastUpdatedAt":"2020-11-10T01:23:02.928Z"},"id":"ble-00112233445566778899aabbccddeeff-1-2","name":"Recycling Bin Room Presence","distributed":true,"distances":{"Waste Bins":{"lastUpdatedAt":"2020-11-10T01:23:02.928Z","distance":0.5,"outOfRange":false}},"timeout":5,"measuredValues":{"Waste Bins":{"rssi":-48.32368333069955,"measuredPower":-52}},"state":"Waste Bins"}]

**Comment by julianrinaldi** [comment]
It also doesn't publish the state to the device tracker topic for either Radbeacon.

**Comment by mKeRix** [comment]
The internal state of the room-assistant instance you posted actually has a state for these BLE entities - which leads me to another question: Have you enabled the bluetoothLowEnergy integration on all your room-assistant instances or only some?

In the case it is only some: do you have an instance which runs both bluetoothClassic and bluetoothLowEnergy? This instance should then ideally be the [preferred leader](https://www.room-assistant.io/guide/cluster.html#usage-tips). For distributed entities (such as the ones created by the Bluetooth integrations) that state will only be managed from leader nodes.
