### ISSUE TITLE
Rename whitelist to allowlist

### ISSUE THREAD

**Issue by domoritz** [mKeRix/room-assistant#347]
The racially insensitive terms "whitelist" and "blacklist" are discouraged in favor of "allowlist" and "denylist". It would be good for room assistant to take a stance and rename those properties as well.

**Comment by mKeRix** [comment]
Good point! I will put this on my todo list. I think I'll leave the old terms in tact for compatibility reason (at least until I have collected enough stuff to warrant a breaking change release), but of course remove them from the docs entirely in favor of the new terms.
