### ISSUE TITLE
BT Disconnection raspberry PI 3 

### ISSUE THREAD

**Issue by Merangle** [mKeRix/room-assistant#358]
**Describe the bug**
RA installed yesterday (latest version) on a brand new PI 3 (fully updated from scratch). 
HA 0.118.0 Synology DS718+ + Docker + Mosquitto (separated Synology module)

I have set up BT BLE to detect a nut3 and my amzfit GTR watch. Both are well detected. 
But every xx minutes (< 10 minutes) there is a disconnection from one or the other or both of the beacon. 
One or two seconds later, both are reconnected. 

I have disabled Wifi on the RPI 3 (dtoverlay=disable-wifi in /boot/config.txt) to avoid any conflict between BT BLE and Wifi.
 
Both beacons are less than 2m from Raspberry. 
Here is the set up 

I have tried without  success to increase updateFrequency and option entities:debounce 
   
`global:
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.10:1883'
  mqttOptions:
    username: xxx
    password: xxx
bluetoothLowEnergy:
  whitelist:
    - ddd399162dba
    - 24bf234e11d9
#  maxDistance: 10
#  updateFrequency: 5
  tagOverrides:
    ddd399162dba:
      name: Amazfit
    24bf234e11d9:
      name: Nut`

I'm not sure it's a bug, but I don't know what to check.
Any help would be appreciated.
regards 

**To reproduce**
Steps required to reproduce the issue. Too specific

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
```

**Expected behavior**

**Environment**
 - room-assistant version: [e.g. 2.0.0]
 - installation type: [e.g. NodeJS, Docker, Hass.io]
 - hardware: [e.g. Raspberry Pi Zero W, NUC]
 - OS: [e.g. Linux, Windows, macOS]

**Additional context**

**Comment by mKeRix** [comment]
If it's only about false `not_home` states I think you should try to increase the `timeout` option to however long these inaccurate states usually are. The `updateFrequency` option is more so there for throttling the amount of messages that room-assistant produces, because some users wish to not put as much load on their MQTT servers.

**Comment by grinco** [comment]
Not sure if it's related, but detection of my Amazfit GTR on an RPI 3 B+ stopped working entirely. I'm using WiFi though - connected to a 5ghz network. I'll try playing with it and will keep you posted if I discover anything. I'm suspecting a recent kernel update to cause it. 

# grep Model /proc/cpuinfo 
Model		: Raspberry Pi 3 Model B Plus Rev 1.3
# node -v
v14.15.1
# room-assistant -h | grep room-assistant
room-assistant 2.12.0
#  lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
# uname -r
5.4.79-v7+
