### ISSUE TITLE
Xiaomy sensor reports incorrect miflora data

### ISSUE THREAD

**Issue by alexbell62** [mKeRix/room-assistant#361]
Xiaomi sensor reports incorrect miflora data:
- moisture incorrectly called humidity
- soil fertility / conductivity is missing in home assistant, but when look at http://192.168.86.37:6415/entities there is following:
`{"attributes":{},"id":"avocado-null","name":"avocado null","distributed":false,"state":338}`
which is (338) the same as soild fertility when looking at the app.
- battery level is missing

**To reproduce**
Install miflora sensor like that one: https://www.google.com/search?sxsrf=ALeKk01rwYVimarlcLpKctYy1WiXBiLDmw%3A1606235465771&ei=STW9X965LoPBgQaQ84zwDA&q=mi+flora&oq=mi+flora&gs_lcp=CgZwc3ktYWIQAzIECCMQJzIFCAAQkQIyBggAEAcQHjIGCAAQBxAeMgYIABAHEB4yBggAEAcQHjIICAAQBxAKEB4yBggAEAcQHjIGCAAQBxAeMgIIAFDnbljnbmCQcGgAcAB4AIABd4gBrQKSAQMxLjKYAQCgAQGqAQdnd3Mtd2l6wAEB&sclient=psy-ab&ved=0ahUKEwiegvOyzZvtAhWDYMAKHZA5A84Q4dUDCA0&uact=5

Is there an easy way to replace `avocado-null` with `avocado-fertility`, rename `humidity` with `moisture` and get the `battery level` readings?

**Comment by PeteBa** [comment]
Yeah, I bumped into this with my mifloras. I have a local patch for this that I will push up so it can be considered. Note that mifloras dont include battery level in the advertisement data so that is not possible in the current implementation.
