### ISSUE TITLE
DHT11/22

### ISSUE THREAD

**Issue by RaZer0r** [mKeRix/room-assistant#38]
Hey,

Thank you for this great project, i'm one step closer to integrating my rPI-Zero in my house ;-).

Could you tell me how i would add the DHT11 sensor value from the gpio pin into play?
The motion sensor works perfectly and i'm looking to extend some basic temperature/humidity sensing ;-). As i've already got the DHT11 working (with a basic python script) i'm thinking to add it to the node ;-). Any suggestions (besides using a script and pushing the data that way)?

**Comment by mKeRix** [comment]
I think your best option right now is just to execute the script and get the data from there, room-assistant provides a component for that. I use it with my Temper USB sensors and the cmd line utility provided for those.

The GPIO component we have is very basic, it can just read the state of a single pin - which is fine for motion sensors, but I assume the DHT11/22 ones require a bit more complex setup. If you want you can extend room-assistant with the necessary component, but generally a script should work just fine. :)

**Comment by RaZer0r** [comment]
cool, i've made it work with the script function, which indeed works fine :-)?

Thank you for this great project ;-).
