### ISSUE TITLE
Add Bluetooth Support

### ISSUE THREAD

**Issue by dshanske** [mKeRix/room-assistant#40]
Home Assistant's bluetooth tracker component allows you to use bluetooth devices for presence detection. Being as the range of bluetooth can be limited, I was wondering if Room Assistant can optionally report back on all bluetooth devices it sees, not just beacons.

**Comment by mKeRix** [comment]
The BLE component does not require the devices to be beacons, but it still requires them to follow the low energy protocol. There currently is no implementation for "normal" Bluetooth yet.

I think we should be able to create a scanner based on a fitting library, e.g. [node-bluetooth](https://www.npmjs.com/package/node-bluetooth). Unfortunately I'm not sure when I'll get around to doing this myself. Sorry :(

**Comment by dshanske** [comment]
If you could leave the idea open...maybe someone will be interested. I understand you have to prioritize your time. Regrettably, while I do program, not in JS. If I ever take the time to learn...

**Comment by mKeRix** [comment]
Added with the release 2.0!
