### ISSUE TITLE
max_distance for iBeacon doesn't work

### ISSUE THREAD

**Issue by ikbensuper** [mKeRix/room-assistant#41]
Like the title states the max distance limit for BLE doesn't prevent messages (from longer distances) from being sent to the MQTT server.

**Comment by mKeRix** [comment]
Will investigate - this should not be happening, see [here](https://github.com/mKeRix/room-assistant/blob/master/components/ble.js#L63). My local instances also have not shown this bug (at least to my knowledge).

Could you post the BLE part of your config and make sure the detected distances that are being sent along are at least somewhat accurate?

**Comment by ikbensuper** [comment]
Sorry, I made a mistake, its the iBeacon mechanism that is nog being limited by max distance.. The BLE mechanism works fine. I emptied the whitelist and f

My iBeacon config
  },
  "ibeacon": {
    "enabled": true,
    "channel": "home/room_presence",
    "max_distance": 3.5,
    "whitelist": [],
    "system_noise": 0.01,
    "measurement_noise": 3,
    "major_mask": "0xFFFF",
    "minor_mask": "0xFFFF"
  },

{"id":"74278bdabXXXXXXXXXc720eaf059935-XXXXXX-XXXXX","uuid":"74278bdabXXXXXXXXXc720eaf059935","major":XXXXX,"minor":XXXXX,"rssi":-69,"distance":6.630811503366006,"accuracy":1.8809104243859365,"measuredpower":-59,"proximity":"near"}

**Comment by mKeRix** [comment]
Fixed in 0.4.1 (thanks to you!).
