### ISSUE TITLE
Add MQTT discovery for device tracker

### ISSUE THREAD

**Issue by B-Hartley** [mKeRix/room-assistant#424]
It looks like 2021.1.0 will bring MQTT discovery for device trackers.
Would be good to add this.

https://rc.home-assistant.io/blog/2020/12/30/release-20211/
Add discovery for MQTT device tracker (@PeteBa - #42327) (mqtt docs)

**Comment by PeteBa** [comment]
You can see the room-assistant side of this in PR #425. If you have the HA beta then I would appreciate any test feedback, Thanks.

**Comment by mKeRix** [comment]
This is now available in v2.13.0. :)
