### ISSUE TITLE
Support MQTT Room Presence in v2.x

### ISSUE THREAD

**Issue by mKeRix** [mKeRix/room-assistant#432]
**Is your feature request related to a problem? Please describe.**
Users should be able to mix different software/hardware for BLE detection by leveraging the Home Assistant MQTT Room Presence integration.

**Describe the solution you'd like**
This should only be an additional thing and not replace our own logic for pure room-assistant sensors. It may also make sense to put this behind a setting that is disabled by default (so that people don't complain about the mass of MQTT messages).

**Describe alternatives you've considered**
- Downgrading to v1.x of room-assistant -> no updates anymore
- Write an adapter from HTTP API to MQTT Room Presence -> a lot of effort and slower

**Comment by LordNex** [comment]
Just adding my vote for this. Need support for ESP32 BLE as most of us already have these as sensors in each of our rooms. Would be perfect to leverage these as well!
