### ISSUE TITLE
Generic MQTT integration

### ISSUE THREAD

**Issue by mKeRix** [mKeRix/room-assistant#434]
**Is your feature request related to a problem? Please describe.**
Using room-assistant directly with NodeRED (or a different tool that goes directly to MQTT) is cumbersome, as the Home Assistant integration splits the information across multiple topics. There is no easy way to have all relevant information in a single message.

**Describe the solution you'd like**
A separate integration that offers a more plain and generic MQTT integration than the Home Assistant one. This integration should emit a new message as soon as something changed in the entity (state, attribute, other property...). The message should include the complete new state, and optionally the old state as well.

**Describe alternatives you've considered**
- See #413 

**Additional context**
This requires a bit of reworking of the entity registry.

**Comment by dflvunoooooo** [comment]
Great, thank you for the update and your work! 
Now I can see the MQTT-messages in Node-Red with the distance, but how do I get to know which room-assistant instance send the distance. I get an MQTT-message like the following:

`object
topic: "room-assistant/sensor/bluetooth-classic-XX-XX-XX-XX-XX-XX/attributes"
payload: object
distance: 0
last_updated_at: "2021-03-04T19:49:35.014Z"
qos: 0
retain: false
_msgid: "e42c249e.4ce658"`

**Comment by mKeRix** [comment]
If you configure the `mqtt` integration (it's different from the `homeAssistant` integration!) you will see new topics appear under `room-assistant/entity`. They are grouped by instance name, entity type and entity id. These then contain all entity attributes and a diff, like described in the format section of the [integration docs](https://www.room-assistant.io/integrations/mqtt.html#message-format). For the overall entity state you could look at `entity.state` and `entity.attributes.distance` for example. Or you could look at all measured distances under `entity.distances`.

**Comment by ljmerza** [comment]
I think this is a great start but it still requires me to subscribe to every RA instance to find where a device is. So if I have 5 RA instances and want to track where my phone is I have to subscribe to all five instances and figure out which one has the latest data for my phone.

What would be great is subscribing to say `room-assistant/entity/bluetooth-classic-xxx` and this will tell me what room the device is in but also the distance from that device. I'd only have to subscribe to one topic to know everything I need to know about one device.

**Comment by mKeRix** [comment]
@ljmerza If you have a stable cluster you can just determine an instance to use for your subscription, alternatively you can subscribe to e.g. `room-assistant/entity/+/bluetooth-low-energy-presence-sensor/ble-some-id` and filter out any messages that have `hasAuthority` set to `false`. Either of those will give you all distance values in the message, the former from a manually chosen viewpoint, the latter from the room-assistant determined cluster leader. Or am I missing a use case with that?

The distances from all instances are under `entity.distances`, the `entity.attributes.distance` is always the distance from `entity.state`.

**Comment by dflvunoooooo** [comment]
> I think this is a great start but it still requires me to subscribe to every RA instance to find where a device is. So if I have 5 RA instances and want to track where my phone is I have to subscribe to all five instances and figure out which one has the latest data for my phone.
> 
> What would be great is subscribing to say `room-assistant/entity/bluetooth-classic-xxx` and this will tell me what room the device is in but also the distance from that device. I'd only have to subscribe to one topic to know everything I need to know about one device.

No you don't have to subscribe to every RA instance. I have a `mqtt in` node with the topic `room-assistant/entity/#` and after that a switch node which filters by devicename.

**Comment by dflvunoooooo** [comment]
My problem now is, that I do not get updates to devices which are not reachable by any RA instance. If I create a sensor in Node Red for the room occupancy, I will not be able to switch it to unavailable.

**Comment by mKeRix** [comment]
@dflvunoooooo That would be because the entity data doesn't really change in room-assistant though. You should still get a state change to `not_home` after a while (when the internal timeout hits). If you want to do a custom timeout of some sorts I would suggest to have a flow running on an interval that checks the timestamps of the last recorded measurements.

**Comment by dflvunoooooo** [comment]
Thanks for your answer. Yes, it changes to `not_home` but if my created sensor is only using the distances I've got a problem. I created some crude type of trilateration with the distances from mqqt and a function node, wich tells the sensor in which room I am. 
My solution is a trigger node which waits one minute for new distances and wehen non appear the sensor will be set to unavailable.
