### ISSUE TITLE
Apple Watch detection possible?

### ISSUE THREAD

**Issue by vswraith** [mKeRix/room-assistant#44]
Since i have my iWatch on me all the time..is it possible to use that via BLE protocol? I know Apple randomizes the UUID...is anyone using Apple Watch to track room presence?

**Comment by mKeRix** [comment]
This is something I've been trying to figure out myself since I also own an Apple Watch. I have gotten it to work on OS X devices signed in to my account - maybe the connections are synced via iCloud, so that I can see the actual ID of the watch there too. But trying to pair the watch with my Raspberries didn't yield the same results sadly. If anyone has more insight on this I'd love to hear it!

**Comment by vswraith** [comment]
I tried to reuse this code- https://github.com/ewenchou/bluetooth-proximity but could not get it to fully work

**Comment by ikbensuper** [comment]
Nope, won't work.. Been looking for months for cheats an stuff like that. The Bluetooth Mac address changes for privacy matters, just like the iPhone does.

**Comment by mKeRix** [comment]
Which of course makes sense - it’s just a little annoying for us.

When reading through the SDKs I noticed it might be possible by reversing the pattern. So the Apple Watch keeps track of the beacons it sees and then sends the data to an endpoint on a location change. This would require a dedicated iOS app though, which I haven’t worked on before.

Might also not work at all. I didn’t grasp the SDK enough to give a qualified comment 😅

**Comment by mKeRix** [comment]
Btw: another interesting approach is querying the bluetooth device name.

https://community.home-assistant.io/t/reliable-multi-user-distributed-bluetooth-occupancy-presence-detection/50674

The solution described there is just for house occupancy due to the inaccuracy, but maybe we can time the response to get results on a room level?

**Comment by mKeRix** [comment]
Re: name scans for detecting the Apple Watch

I had a prototype of this running, but unfortunately my idea of timing the response does not help with measuring the estimated distance. The timings (and pings) seem a bit arbitrary and are definitely not distinguishable sadly. I also have not found a way of pairing the watch with my raspis yet.

There is [a paper on circumventing MAC randomization](https://arxiv.org/abs/1703.02874v1), but the described methods seem a bit out of scope for this tool. Another method I have in mind is watching the manufacturer data, which could at least work if only one Apple Watch is in the household... but I still have to figure out how much of that is consistent.

**Comment by mKeRix** [comment]
I've tinkered with solutions for this again the last two days and figured out that you can extract the Identity Resolution Key used for making these seemingly random addresses trackable from MacOS devices, as they are synced via iCloud. Digging deeper into the Bluetooth core spec you will see that the last 3 bytes should be encrypted with the IRK using AES 128, if the result matches the first 3 bytes (the hash) then you can be reasonably sure you are seeing the correct device.

Unfortunately I got stuck when trying this out, I can't seem to get the correct hash generated from my Apple Watch samples. Debugging this is very hard, as the nature of AES allows a ton of combinations. The iOS Bluetooth implementation is also not published anywhere, so I can't look into their way of resolving the address.

If anyone wants to try their luck, under High Sierra you can find the keys you need with `sudo defaults read /private/var/root/Library/Preferences/com.apple.bluetoothd.plist`.

**Comment by Martinvdm** [comment]
Is there any news on this issue? It has been a year ago. But a watch as tracking device seems very ovious to me.

**Comment by mKeRix** [comment]
@Martinvdm I haven't continued with my approach of trying to decrypt the Bluetooth privacy mechanism that Apple uses, so no news on that front.

I have recently stumbled across another interesting solution that might work for Apple Watches as well though. Don't have an implementation yet, but will try it out soonish. Stay tuned!

**Comment by mKeRix** [comment]
Hey all,

I have just pushed my code for a component that supports tracking Apple Watches, phones and really any kind of Bluetooth device, find it here: https://github.com/mKeRix/room-assistant/blob/thesis/services/bluetooth-inquiries.service.js

Do note that the stuff in that branch is still very much experimental and the code is not cleaned up yet. I am currently trying out and measuring some presence detection mechanisms. Once I am done with that I will remove what doesn't work and bring the rest into a nice shape.

I've been testing this with my Apple Watch a bit and it seems to work fairly well if you can live with a slower reaction speed. No long term tests yet though, so not sure how it affects the battery life. Will check that in the future.

**Comment by squirrel289** [comment]
That’s serendipitous timing!  I just started digging into this myself so you’ve saved me a TON of time.  Can you comment the code /or explain how to use the service (i.e., how to get the addresses to be tracked)?

**Comment by mKeRix** [comment]
@squirrel289 no documentation on this yet unfortunately - first I will refactor the code in that branch a bit, then I'll write a bit of documentation. I think an official release will still take some time, but I will start with the Bluetooth stuff as it seems to have the most community interest.

First I'll have to finish some other stuff though. I'll let you know again in this thread once the refactored code version is online together with some documentation.

**Comment by DConcord** [comment]
Excited to learn more! I'm trying to decipher the code, but don't quite have the chops to parse it out myself. Are you somehow extracting the IRK so that you can then know which iOS device you're looking at?

**Comment by gmalbert** [comment]
Grateful for your continued great support, @mKeRix . I'm happy to help with any testing as you're able to make some updates. I have an iPhone but no Apple Watch (yet!) so I can at least test the iPhone piece of things.

**Comment by mKeRix** [comment]
It's been a while, but I'm finally at a point where I can share my efforts! I've been rewriting the project in Typescript and ended up running into some limits with the framework that I used, so I ended up building a new version based on a different framework.

Note that this is still a beta - it doesn't have the same feature set of the previous versions just yet and some things may still change. There is also no documentation yet (and the old one doesn't apply for the most part). You can install the [beta version of room-assistant](https://www.npmjs.com/package/room-assistant) with:

```bash
sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev libavahi-compat-libdnssd-dev
sudo npm i --global --unsafe-perm room-assistant@2.0.0-beta.1
```

Switch to some working directory (e.g. your home dir), create a new file `config/local.yml`:

```yaml
global:
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: mqtt://localhost:1883
  mqttOptions:
    username: <mqtt-user>
    password: <mqtt-pass>
bluetoothClassic:
  addresses:
    - <bluetooth-mac>
```

This will enable updates to Home Assistant and room presence tracking for any Bluetooth Classic device (iPhone, Androids, Apple Watch...). If you enabled auto discovery for your MQTT integration in Home Assistant you're done - room-assistant will register itself accordingly with some devices and sensors. :)

**Comment by gmalbert** [comment]
@mKeRix thanks so much for the work! One simple question: am I creating the local.yml file on the room-assistant rpi or in Home Assistant?

**Comment by mKeRix** [comment]
@gmalbert The local.yml is for the room-assistant Pi. On the Home Assistant side of things you shouldn't need to setup anything anymore, just have it connected to MQTT with the discovery turned on. :)

**Comment by gmalbert** [comment]
@mKeRix that worked, thanks. Do we have the ability to run it as a service at this point? I could copy the code from the earlier version, but I don't know what the Workingdirectory would be.

Also, should we do a separate topic for these questions or do you want it all on this issue?

**Comment by mKeRix** [comment]
@gmalbert For stuff regarding Bluetooth I would keep the content here, for more generic beta questions I guess we can make use of #102. I don't have a hard preference though.

You can run it as a service, the service file should look something like this:

```
[Unit]
Description=Room Assistant service

[Service]
ExecStart=/usr/bin/room-assistant
WorkingDirectory=/home/pi
Restart=always
RestartSec=10
User=root

[Install]
WantedBy=multi-user.target
```

The working directory should be relative to where you put your config. Let's say you have your config in `/home/pi/config/local.yml` - that means the working directory should be `/home/pi`. I will make this a bit more intuitive in the near future. Also note that the service file example has user set to root, if you want to run it from a different user (cleaner approach) you would need to run `sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)` first to setup the permissions.

**Comment by gmalbert** [comment]
@mKeRix this didn't seem to work for me. I looked at the /usr/bin directory, and room-assistant does not appear. I don't know if that matters or not, but I thought I'd let you know. Happy to test out anything as I set up a new RPI Zero just for the beta.

**Comment by mKeRix** [comment]
@gmalbert In that case: npm might have linked it to a different place when installing via the command above, you can get the installation path with `which room-assistant`. If that comes up empty something may have gone wrong during installation.

**Comment by gmalbert** [comment]
@mKeRix that was the issue, thanks. I'll put remaining comments over on the beta topic.

**Comment by mKeRix** [comment]
Added with the release of 2.0!

**Comment by macguy81** [comment]
Hi i have setup roomaisstant on hassio and it works great for my iPhone but for some reason it is not able to detect my Apple Watch 5, do i have to do anything special settings?

**Comment by gionaf** [comment]
> Hi i have setup roomaisstant on hassio and it works great for my iPhone but for some reason it is not able to detect my Apple Watch 5, do i have to do anything special settings?

Try pairing the watch (not your iPhone, but your Watch itself! ) to any bluetooth device, e.g. some headphones, near your room-assistant's bluetooth receiver.

**Comment by rcpilotp51** [comment]
> > Hi i have setup roomaisstant on hassio and it works great for my iPhone but for some reason it is not able to detect my Apple Watch 5, do i have to do anything special settings?
> 
> Try pairing the watch (not your iPhone, but your Watch itself! ) to any bluetooth device, e.g. some headphones, near your room-assistant's bluetooth receiver.

This worked for me and i can see the watch in HASS. interesting...
Thank you
