### ISSUE TITLE
Unreliable tracking results with Classic Bluetooth

### ISSUE THREAD

**Issue by pszewello** [mKeRix/room-assistant#471]
**Describe the bug**
I have 2 sets of devices, a Galaxy Phone and Watch and Apple Watch and IPhone, room-assistant can distinguish them and ping them, but the results of presence detection are unreliable. Please see attached image of 1hour of tracking, where the Samsung things are next to another and the apple things are next to another, yet room-assistant is showing them in different places...

**To reproduce**
Setup a cluster, take 2 devices to one room and track, go to another after some time and track, etc...

**Relevant configuration**
Paste the relevant parts of your configuration below.

all:
  hosts:
    '192.168.1.49':
      ansible_user: ***
      ansible_password: ***
      room_assistant_config: 
        global:
          instanceName: livingroom
          integrations:
            - homeAssistant
            - bluetoothClassic
            - omronD6t
          cluster:
            autoDiscovery: false
            port: 6425
            quorum: 3
            peerAddresses:
              - 192.168.1.50:6425
              - 192.168.1.51:6425
              - 192.168.1.52:6425
              - 192.168.1.53:6425
    '192.168.1.50':
      ansible_user: ***
      ansible_password: ***
      room_assistant_config: 
        global:
          instanceName: bedroom
          integrations:
            - homeAssistant
            - bluetoothClassic
            - omronD6t
          cluster:
            autoDiscovery: false
            port: 6425
            quorum: 3
            peerAddresses:
              - 192.168.1.49:6425
              - 192.168.1.51:6425
              - 192.168.1.52:6425
              - 192.168.1.53:6425
    '192.168.1.51':
      ansible_user: ***
      ansible_password: ***
      room_assistant_config: 
        global:
          instanceName: oliwia_room
          integrations:
            - homeAssistant
            - bluetoothClassic
            - omronD6t
          cluster:
            autoDiscovery: false
            port: 6425
            quorum: 3
            peerAddresses:
              - 192.168.1.49:6425
              - 192.168.1.50:6425
              - 192.168.1.52:6425
              - 192.168.1.53:6425
    '192.168.1.52':
      ansible_user: ***
      ansible_password: ***
      room_assistant_config: 
        global:
          instanceName: krzys_room
          integrations:
            - homeAssistant
            - bluetoothClassic
            - omronD6t
          cluster:
            autoDiscovery: false
            port: 6425
            quorum: 3
            peerAddresses:
              - 192.168.1.49:6425
              - 192.168.1.50:6425
              - 192.168.1.51:6425
              - 192.168.1.53:6425
    '192.168.1.53':
      ansible_user: ***
      ansible_password: ***
      room_assistant_config: 
        global:
          instanceName: entrance
          integrations:
            - homeAssistant
            - bluetoothClassic
            - omronD6t
          cluster:
            autoDiscovery: false
            port: 6425
            quorum: 3
            peerAddresses:
              - 192.168.1.49:6425
              - 192.168.1.50:6425
              - 192.168.1.51:6425
              - 192.168.1.52:6425
  vars:
    room_assistant_version: latest
    room_assistant_global_config:
      global:
        integrations:
          - homeAssistant
          - bluetoothClassic
          - omronD6t
      homeAssistant:
        mqttUrl: mqtt://***:1883/
        mqttOptions:
          username: ***
          password: ***
      bluetoothClassic:
        minRssi: -10
        interval: 30
        scanTimeLimit: 20
        timeoutCycles: 6
        addresses:
          #Galaxy S9
          - ***
          #Gear s3
          - ***
          #IPhone
          - ***
          #Apple Watch
          - ***
      omronD6t:
        deltaThreshold: 2
        heatmap:
          minTemperature: 16
          maxTemperature: 30
          rotation: 90    

**Expected behavior**
If both devices are next to another I expect to see the same in tracking. So if I am for 20min in living room than go to bedroom for another 15min then step to bathroom for 5 min with my phone in my pocket and my watch on the hand I expect to see that.

**Environment**
 - room-assistant version: latest
 - installation type: NodeJs via Ansible
 - hardware: Raspberry Pi Zero W x 5
 - OS: Linux

**Additional context**
![room-assistant](https://user-images.githubusercontent.com/40065024/105841848-9bb5fc80-5fd5-11eb-87a3-0afe49d6d8e6.png)

**Comment by mKeRix** [comment]
I'd be interested to see the data that is leading to the presence decisions. Could you get the detailed entity data from the entities endpoint of the [room-assistant API](https://www.room-assistant.io/guide/api.html) for an example like above (two devices next to each other, different rooms)?

**Comment by pszewello** [comment]
Hi, 

I will that data back to you, I had to switch bluetooth enquiry off for now, just waiting for a new switch, as with room-assistant running on the RPI Zerow W it chokes my Orbi mesh, I will try to eliminate one of the satelites to make sure RPIs don't have a problem chosing which WIFI to connect to, and then turn on bt again and update this issue.

**Comment by dflvunoooooo** [comment]
My readings vary for one room and one mobile phone from 0 to -20 and for a different mobile phone in the same room from 0 to -6. It does strongly depend on the device! 
And apparently on the raspberry pi as well. I installed a rasperry pi 4 yesterday and the others are raspberry pi 3's and the results from the 4 are far more stable, I don't know why. I have the same config for room-assistant for every raspberry pi. (I use the measured distance via mqtt to "triangulate" in Node-Red).

![Screenshot_20210430_134224](https://user-images.githubusercontent.com/32816598/116691671-74e3d980-a9bb-11eb-8102-1c12e48a37dd.png)
There are three Raspberry Pi's and the first three values are for one mobile phone and the other three are for a different one.

**Comment by dflvunoooooo** [comment]
Never mind, it turns out the readings where wrong! Apparently the Raspberry Pi 4 has problems if USB 3 and bluetooth are used at the same time :(
