### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by jeubanks** [mKeRix/room-assistant#48]
For "distance" it's not documented if that is in meters or feet.  I'm curious as what is being reported by home assistant from readings "looks" like feet.  But the parameter in room-assistant doesn't specify.  I know it's not 10 meters from one side of my room to the other where the rpi is sitting :)

**Comment by mKeRix** [comment]
The units are supposed to be metric - I will update the documentation to reflect this better. Do note that the distance calculation is heavily dependent on the "measured power" value of the beacons (can be configured on some, it is the measured signal strength when the beacon is exactly 1 meter away) and surroundings. Radio waves and obstructions may have a big impact on the estimation.
