### ISSUE TITLE
deny creation (or discovery) of device_trackers in home assistant (mqtt)

### ISSUE THREAD

**Issue by balonchiks** [mKeRix/room-assistant#488]
**Describe the bug**
room assistant now creates device_tracker that are autodiscovered by homeassistant, creating a mess with similar names i.e. device_tracker.phone_name_1, device_tracker.phone_name_2, device_tracker.phone_name_3 etc,etc,etc in home assistant.

**To reproduce**
just start latest room assistant

**Expected behavior**
this seems to be a new feature in 2.13.0 and i can't see any option/config parameter of sticking to the old format where i had to create mqtt sensors for home assistant myself. Can we have some sort of a config option for room-assistant for the ones that prefer it to be the old way instead of the new one?

**Comment by mKeRix** [comment]
Just so that I'm clear on this: you want to have an option in the config that would allow you to disable auto discovery messages for some entity types (e.g. device_tracker)? Or do you want something that would disable entity auto discovery messages all together?

**Comment by balonchiks** [comment]
> disable auto discovery messages for some entity types (e.g. device_tracker)

sorry for not being clear enought, but i'd be happy to see this implemented. thank you

**Comment by PeteBa** [comment]
If you need an immediate solution then you can limit discovery on the HA side. You can go to "Configuration -> Integrations -> MQTT Devices" and select the specific device. You can then click on the device_tracker and toggle the "Enabled Entity" to off. This will hide just that entity from HA so you would need to do it for each device_tracker.

**Comment by xHirscHx** [comment]
I just noticed that 2 the--  room-assistant Configuration--- option is blank and when i try to fill it back in it returns blank after restart  all my settings are gone. I had 3 devices being tracked now they all say  not home.

**Comment by PeteBa** [comment]
@mKeRix , re-reading the OP comments, looks like I missed updating the Classic Integration handling of `device_tracker` and that can lead to less intuitive Entity Names in the case of Classic.

[BLE Integration:](https://github.com/mKeRix/room-assistant/blob/e76a123446a05692b97d91741bf97760e58a28bd/src/integrations/bluetooth-low-energy/bluetooth-low-energy.service.ts#L328)
```yaml
const deviceTracker = this.createDeviceTracker(
      makeId(`${sensorId}-tracker`),
      `${deviceName} Tracker`,
      deviceInfo
);
```

[Classic Integration:](https://github.com/mKeRix/room-assistant/blob/e76a123446a05692b97d91741bf97760e58a28bd/src/integrations/bluetooth-classic/bluetooth-classic.service.ts#L331)
```yaml 
const deviceTracker = this.createDeviceTracker(
    makeId(`${sensorId}-tracker`),
    device.name
);
```

I can raise a PR on this to align the two integrations and ensure consistency.
