### ISSUE TITLE
Disable logs.

### ISSUE THREAD

**Issue by mredone** [mKeRix/room-assistant#49]
Hello 
How can i disable making logs in logs/{year}/{month} folder?

**Comment by mredone** [comment]
I add comment to line #4 and #30. Today i will get more info if it work ok.

**Comment by mKeRix** [comment]
Oh wow - I have the console publisher disabled on my instances, so I never had issues with the log size.

I added an option for disabling the filesystem logs in the newest version (0.4.2). It is disabled by default now, and you can tweak it by changing the "logging" boolean under "app". Try the update and let me know what you think!
