### ISSUE TITLE
Update killed my setup

### ISSUE THREAD

**Issue by xHirscHx** [mKeRix/room-assistant#501]
**Describe the bug**
Loading integrations: none
**To reproduce**
Steps required to reproduce the issue.

Restart  

**Relevant logs**

Log output that correlates to the bug. You can get debug output with `room-assistant -v`.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:38:36] INFO: Setting up Home Assistant configuration
[19:38:36] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2/5/2021, 7:38:37 PM - info - IntegrationsModule: Loading integrations: none
2/5/2021, 7:38:37 PM - info - NestFactory: Starting Nest application...
2/5/2021, 7:38:37 PM - info - InstanceLoader: AppModule dependencies initialized
2/5/2021, 7:38:37 PM - info - InstanceLoader: ConfigModule dependencies initialized
2/5/2021, 7:38:37 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
2/5/2021, 7:38:37 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
2/5/2021, 7:38:37 PM - info - InstanceLoader: HttpModule dependencies initialized
2/5/2021, 7:38:37 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
2/5/2021, 7:38:37 PM - info - InstanceLoader: PrometheusModule dependencies initialized
2/5/2021, 7:38:37 PM - info - InstanceLoader: ClusterModule dependencies initialized
2/5/2021, 7:38:37 PM - info - InstanceLoader: TerminusModule dependencies initialized
2/5/2021, 7:38:37 PM - info - InstanceLoader: ScheduleModule dependencies initialized
2/5/2021, 7:38:37 PM - info - InstanceLoader: EntitiesModule dependencies initialized
2/5/2021, 7:38:37 PM - info - InstanceLoader: StatusModule dependencies initialized
2/5/2021, 7:38:37 PM - info - RoutesResolver: EntitiesController {/entities}:
2/5/2021, 7:38:37 PM - info - RouterExplorer: Mapped {/entities, GET} route
2/5/2021, 7:38:37 PM - info - RoutesResolver: StatusController {/status}:
2/5/2021, 7:38:37 PM - info - RouterExplorer: Mapped {/status, GET} route
2/5/2021, 7:38:37 PM - info - RoutesResolver: PrometheusController {/metrics}:
2/5/2021, 7:38:37 PM - info - RouterExplorer: Mapped {/metrics, GET} route
2/5/2021, 7:38:37 PM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
2/5/2021, 7:38:37 PM - info - ClusterService: Starting mDNS advertisements and discovery
2/5/2021, 7:38:37 PM - info - NestApplication: Nest application successfully started
2/5/2021, 7:38:39 PM - info - ClusterService: 6e66619d-room-assistant has been elected as leader
2/5/2021, 7:38:39 PM - info - EntitiesService: Refreshing entity states

**Relevant configuration**
Paste the relevant parts of your configuration below.

default
+
global:
  instanceName: Den Room-Ass
  integrations:
    - bluetoothLowEnergy
    - bluetoothClassic
    - homeAssistant
weight: 10
bluetoothClassic:
  whitelist:
    - bc-a5-8b-fc-fa-26
  tagOverrides:
    bc-a5-8b-fc-fa-26:
      name: Note-BT
bluetoothLowEnergy:
  whitelist:
    - 10f86430134611e491912caa8e003811-111-111
    - 46692fd7ddfe
    - 10521c65367e
    - 2caa8e00a766
    - 2caa8e40953a
    - 2caa8e003811
    - null
  tagOverrides:
    10521c65367e:
      name: T Watch
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.191:1883'
  mqttOptions:
    username: ###########
    password: ###########
cluster:
  port: 6425
  peerAddresses:
    - '192.168.1.77:6425'
 

**Expected behavior**
After update it wont load any integrations and nothing is discovered

**Environment**
 - room-assistant version: [e.g. 2.13]
 - hardware: Raspi-hassio-bin  and ubuntu with docker both do the same

**Additional context**

Right after update the config file was gone on both setups --blank
unistalled both the repo and everything on hassio.
config disappears after i set it up and restart it.
was working great before update.
tried using default config but same thing happens

**Comment by mKeRix** [comment]
Unfortunately I can't reproduce this on my Home Assistant setup. room-assistant doesn't write to the config at all, it only reads it. The config management is done by the Home Assistant Supervisor entirely. There weren't any changes to the add-on that would affect this either. Do you see this on other add-ons as well?

Only things that I can remark regarding your config are:
- the `bluetoothClassic` options aren't formatted correctly (there is no `whitelist` there and the address format should use colons
- the `bluetoothLowEnergy` whitelist entry that has been turned into null by Home Assistant was likely not escaped correctly - try wrapping it in quotes (e.g. `- 'some-id'`)

**Comment by xHirscHx** [comment]
I tried a lot of different configuration  buts its like its not seeing the configuration file or a bad path way  im more of a copy paste guy most of this is over my head.

**Comment by xHirscHx** [comment]
so i put this config in 
global:
  instanceName: Den-RA
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
 
and get this 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[06:18:37] INFO: Setting up Home Assistant configuration
[06:18:37] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2/6/2021, 6:18:37 AM - info - IntegrationsModule: Loading integrations: none
2/6/2021, 6:18:37 AM - info - NestFactory: Starting Nest application...
2/6/2021, 6:18:37 AM - info - InstanceLoader: AppModule dependencies initialized
2/6/2021, 6:18:37 AM - info - InstanceLoader: ConfigModule dependencies initialized
2/6/2021, 6:18:37 AM - info - InstanceLoader: NestEmitterModule dependencies initialized
2/6/2021, 6:18:37 AM - info - InstanceLoader: IntegrationsModule dependencies initialized
2/6/2021, 6:18:38 AM - info - InstanceLoader: HttpModule dependencies initialized
2/6/2021, 6:18:38 AM - info - InstanceLoader: DiscoveryModule dependencies initialized
2/6/2021, 6:18:38 AM - info - InstanceLoader: PrometheusModule dependencies initialized
2/6/2021, 6:18:38 AM - info - InstanceLoader: ClusterModule dependencies initialized
2/6/2021, 6:18:38 AM - info - InstanceLoader: TerminusModule dependencies initialized
2/6/2021, 6:18:38 AM - info - InstanceLoader: ScheduleModule dependencies initialized
2/6/2021, 6:18:38 AM - info - InstanceLoader: EntitiesModule dependencies initialized
2/6/2021, 6:18:38 AM - info - InstanceLoader: StatusModule dependencies initialized
2/6/2021, 6:18:38 AM - info - RoutesResolver: EntitiesController {/entities}:
2/6/2021, 6:18:38 AM - info - RouterExplorer: Mapped {/entities, GET} route
2/6/2021, 6:18:38 AM - info - RoutesResolver: StatusController {/status}:
2/6/2021, 6:18:38 AM - info - RouterExplorer: Mapped {/status, GET} route
2/6/2021, 6:18:38 AM - info - RoutesResolver: PrometheusController {/metrics}:
2/6/2021, 6:18:38 AM - info - RouterExplorer: Mapped {/metrics, GET} route
2/6/2021, 6:18:38 AM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
2/6/2021, 6:18:38 AM - info - ClusterService: Starting mDNS advertisements and discovery
2/6/2021, 6:18:38 AM - info - NestApplication: Nest application successfully started
2/6/2021, 6:18:40 AM - info - ClusterService: 6e66619d-room-assistant has been elected as leader
2/6/2021, 6:18:40 AM - info - EntitiesService: Refreshing entity states

**Comment by mKeRix** [comment]
Since I can't reproduce it (just tried with exactly your config minus the mqttUrl/mqttOptions part) you will unfortunately have to do some more digging yourself. Can you exec into the container and look at the config/default.json and config/local.json files? You can either do it from the host machine command line using `docker exec` or the Portainer add-on.

**Comment by xHirscHx** [comment]
config/default.json: line 2: homeAssistant:: command not found
config/default.json: line 3: mqttUrl:: command not found
config/default.json: line 4: mqttOptions:: command not found
config/default.json: line 5: username:: command not found
config/default.json: line 6: password:: command not found
config/default.json: line 8: syntax error near unexpected token `}'
config/default.json: line 8: `  }'

**Comment by xHirscHx** [comment]
anyway i can downgrade version

**Comment by mKeRix** [comment]
It looks like you tried to execute the config file as shell script - you would use something like `cat` to read the file.

**Comment by xHirscHx** [comment]
bash-5.1# cat  config/default.json 
{
  "homeAssistant": {
    "mqttUrl": "mqtt://core-mosquitto:1883",
    "mqttOptions": {
      "username": "addons",
      "password": "athukoach1phaoBeD2wiem3iejootae2oey9aif8oemowoome1rai4yeeyu5ooPu"
    }
  }
}

{}bash-5.1# caconfig/local.jsonon
{}bash-5.1# caconfig/local.jsonon
{}bash-5.1# ls
config         entrypoint.sh
bash-5.1# cat entrypoint.sh
#!/usr/bin/env bashio
MQTT_CONFIG=$(bashio::services 'mqtt')
if bashio::var.has_value "${MQTT_CONFIG}"; then
    bashio::log.info "Setting up Home Assistant configuration"
    echo "${MQTT_CONFIG}" | jq '{homeAssistant: {mqttUrl: "mqtt://\(.host):\(.port)", mqttOptions: {username: .username, password: .password}}}' > /room-assistant/config/default.json
fi

bashio::log.info "Starting room-assistant"
exec room-assistant --digResolverbash-5.1# 


So it looks like (I dont know anything) the config file that i filed out is not saving to wheres its supposed to go. right

**Comment by mKeRix** [comment]
Yeah, it's not saving what you want. Maybe you can try running your config copy-pasted through a YAML linter... possibly there is a small error somewhere, which could cause HA to just wipe your config. Either way, HA is saving something to the correct spot... but it's just an empty object.

**Comment by ejl463** [comment]
I'm also having the same error after updating Home Assistant. Running Hassio on a Raspberry Pi 4. I'm planning on rolling back, but I can help test if needed. Log and config posted below

Log:
>  [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:20:24] INFO: Setting up Home Assistant configuration
[19:20:24] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2/8/2021, 7:20:27 PM - info - IntegrationsModule: Loading integrations: none
2/8/2021, 7:20:28 PM - info - NestFactory: Starting Nest application...
2/8/2021, 7:20:28 PM - info - InstanceLoader: AppModule dependencies initialized
2/8/2021, 7:20:28 PM - info - InstanceLoader: ConfigModule dependencies initialized
2/8/2021, 7:20:28 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
2/8/2021, 7:20:28 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
2/8/2021, 7:20:28 PM - info - InstanceLoader: HttpModule dependencies initialized
2/8/2021, 7:20:28 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
2/8/2021, 7:20:28 PM - info - InstanceLoader: PrometheusModule dependencies initialized
2/8/2021, 7:20:28 PM - info - InstanceLoader: ClusterModule dependencies initialized
2/8/2021, 7:20:28 PM - info - InstanceLoader: TerminusModule dependencies initialized
2/8/2021, 7:20:28 PM - info - InstanceLoader: ScheduleModule dependencies initialized
2/8/2021, 7:20:28 PM - info - InstanceLoader: EntitiesModule dependencies initialized
2/8/2021, 7:20:28 PM - info - InstanceLoader: StatusModule dependencies initialized
2/8/2021, 7:20:28 PM - info - RoutesResolver: EntitiesController {/entities}:
2/8/2021, 7:20:28 PM - info - RouterExplorer: Mapped {/entities, GET} route
2/8/2021, 7:20:28 PM - info - RoutesResolver: StatusController {/status}:
2/8/2021, 7:20:28 PM - info - RouterExplorer: Mapped {/status, GET} route
2/8/2021, 7:20:28 PM - info - RoutesResolver: PrometheusController {/metrics}:
2/8/2021, 7:20:28 PM - info - RouterExplorer: Mapped {/metrics, GET} route
2/8/2021, 7:20:28 PM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
2/8/2021, 7:20:28 PM - error - ClusterService: Failed to start mdns discovery (dns service error: unknown)
2/8/2021, 7:20:28 PM - info - NestApplication: Nest application successfully started
2/8/2021, 7:20:30 PM - info - ClusterService: 6e66619d-room-assistant has been elected as leader
2/8/2021, 7:20:30 PM - info - EntitiesService: Refreshing entity states

And this is my config:

> global:
  instanceName: livingroom
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.47:1883'
  mqttOptions:
    username: **
    password: **
bluetoothClassic:
  minRssi: -20
  hciDeviceId: 0
  timeoutCycles: 6
  addresses:
    - '10:F1:F2:F2:05:96'

**Comment by aneetmakin** [comment]
I think I'm experiencing the same issue as the others in this thread. I updated Room-Assistant to 2.13.0 a couple days ago and everything seemed to be working fine. Updated HASSIO to the latest release yesterday and things haywire. 

Of the 4 instances of RA I have running, I'm only experiencing issues with the one installed via HASSIO add-on. The other 3 instances are running on dedicated RPi zeros. I've tried reinstalling the add-on a few times without luck. 

**Describe the bug**
HASSIO instance of RA does not publish MQTT messages or discover devices. Add-on is also not respecting the instanceName provided to it via config. The given instanceName is "Office", but is appearing as "6e66619d-room-assistant" instead. 

I think that there is some level of communication between the add-on and other nodes. Pulling up the API for any instance via 192.168.2.XXX:6415/entities properly shows all nodes, though there are two rivaling clusters. Add-on is showing itself as cluster-leader. Other 3 nodes have properly elected a single cluster-leader. 

**Steps required to reproduce the issue.**
1. Update Room-Assistant latest production release.
2. Update HASSIO to latest production release.
3. Restart Home Assistant

**Relevant logs**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:32:33] INFO: Setting up Home Assistant configuration
[10:32:34] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2/9/2021, 10:32:37 AM - info - IntegrationsModule: Loading integrations: none
2/9/2021, 10:32:37 AM - info - NestFactory: Starting Nest application...
2/9/2021, 10:32:38 AM - info - InstanceLoader: AppModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: ConfigModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: NestEmitterModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: IntegrationsModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: HttpModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: DiscoveryModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: PrometheusModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: ClusterModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: TerminusModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: ScheduleModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: EntitiesModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: StatusModule dependencies initialized
2/9/2021, 10:32:38 AM - info - RoutesResolver: EntitiesController {/entities}:
2/9/2021, 10:32:38 AM - info - RouterExplorer: Mapped {/entities, GET} route
2/9/2021, 10:32:38 AM - info - RoutesResolver: StatusController {/status}:
2/9/2021, 10:32:38 AM - info - RouterExplorer: Mapped {/status, GET} route
2/9/2021, 10:32:38 AM - info - RoutesResolver: PrometheusController {/metrics}:
2/9/2021, 10:32:38 AM - info - RouterExplorer: Mapped {/metrics, GET} route
2/9/2021, 10:32:38 AM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
2/9/2021, 10:32:38 AM - error - ClusterService: Failed to start mdns discovery (dns service error: unknown)
2/9/2021, 10:32:38 AM - info - NestApplication: Nest application successfully started
2/9/2021, 10:32:38 AM - info - ClusterService: Added 192.168.2.151:6425 to the cluster with id livingroom
2/9/2021, 10:32:38 AM - info - ClusterService: Added 192.168.2.153:6425 to the cluster with id kitchen
2/9/2021, 10:32:42 AM - info - ClusterService: Added 192.168.2.154:6425 to the cluster with id masterbedroom
```

**Relevant configuration**

```
global:
..instanceName: Office
..integrations:
....- homeAssistant
....- bluetoothClassic
cluster:
..weight: 5
..quorum: 3
..autoDiscovery: false
..peerAddresses:
....- '192.168.2.151:6425'
....- '192.168.2.153:6425'
....- '192.168.2.154:6425'
bluetoothClassic:
..minRssi: -2
..interval: 10
..timeoutCycles: 4
..addresses:
....- 'mac1'
....- 'mac2'
....- 'mac3'
```

(Leading periods are not present in the actual config. Added here to show formatting/spacing.)

**Environment**
- Room-Assistant Home Assistant add-on: 2.13.0
- Hassio:
    - core-2021.2.2
    - supervisor-2021.02.6
    - Home Assistant OS 5.11
- Hardware: RPi 4B

**Comment by neetorama** [comment]
I think I'm experiencing the same issue as the others in this thread. I updated Room-Assistant to 2.13.0 a couple days ago and everything seemed to be working fine. Updated HASSIO to the latest release yesterday and things haywire. 

Of the 4 instances of RA I have running, I'm only experiencing issues with the one installed via HASSIO add-on. The other 3 instances are running on dedicated RPi zeros. I've tried reinstalling the add-on a few times without luck. 

**Describe the bug**
HASSIO instance of RA does not publish MQTT messages or discover devices. Add-on is also not respecting the instanceName provided to it via config. The given instanceName is "Office", but is appearing as "6e66619d-room-assistant" instead. 

I think that there is some level of communication between the add-on and other nodes. Pulling up the API for any instance via 192.168.2.XXX:6415/entities properly shows all nodes, though there are two rivaling clusters. Add-on is showing itself as cluster-leader. Other 3 nodes have properly elected a single cluster-leader. 

**Steps required to reproduce the issue.**
1. Update Room-Assistant latest production release.
2. Update HASSIO to latest production release.
3. Restart Home Assistant

**Relevant logs**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:32:33] INFO: Setting up Home Assistant configuration
[10:32:34] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2/9/2021, 10:32:37 AM - info - IntegrationsModule: Loading integrations: none
2/9/2021, 10:32:37 AM - info - NestFactory: Starting Nest application...
2/9/2021, 10:32:38 AM - info - InstanceLoader: AppModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: ConfigModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: NestEmitterModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: IntegrationsModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: HttpModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: DiscoveryModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: PrometheusModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: ClusterModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: TerminusModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: ScheduleModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: EntitiesModule dependencies initialized
2/9/2021, 10:32:38 AM - info - InstanceLoader: StatusModule dependencies initialized
2/9/2021, 10:32:38 AM - info - RoutesResolver: EntitiesController {/entities}:
2/9/2021, 10:32:38 AM - info - RouterExplorer: Mapped {/entities, GET} route
2/9/2021, 10:32:38 AM - info - RoutesResolver: StatusController {/status}:
2/9/2021, 10:32:38 AM - info - RouterExplorer: Mapped {/status, GET} route
2/9/2021, 10:32:38 AM - info - RoutesResolver: PrometheusController {/metrics}:
2/9/2021, 10:32:38 AM - info - RouterExplorer: Mapped {/metrics, GET} route
2/9/2021, 10:32:38 AM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
2/9/2021, 10:32:38 AM - error - ClusterService: Failed to start mdns discovery (dns service error: unknown)
2/9/2021, 10:32:38 AM - info - NestApplication: Nest application successfully started
2/9/2021, 10:32:38 AM - info - ClusterService: Added 192.168.2.151:6425 to the cluster with id livingroom
2/9/2021, 10:32:38 AM - info - ClusterService: Added 192.168.2.153:6425 to the cluster with id kitchen
2/9/2021, 10:32:42 AM - info - ClusterService: Added 192.168.2.154:6425 to the cluster with id masterbedroom
```

**Relevant configuration**

```
global:
..instanceName: Office
..integrations:
....- homeAssistant
....- bluetoothClassic
cluster:
..weight: 5
..quorum: 3
..autoDiscovery: false
..peerAddresses:
....- '192.168.2.151:6425'
....- '192.168.2.153:6425'
....- '192.168.2.154:6425'
bluetoothClassic:
..minRssi: -2
..interval: 10
..timeoutCycles: 4
..addresses:
....- 'mac1'
....- 'mac2'
....- 'mac3'
```

(Leading periods are not present in the actual config. Added here to show formatting/spacing.)

**Environment**
- Room-Assistant Home Assistant add-on: 2.13.0
- Hassio:
    - core-2021.2.2
    - supervisor-2021.02.6
    - Home Assistant OS 5.11
- Hardware: RPi 4B

**Comment by xHirscHx** [comment]
Showing up in supervisor logs 



21-02-09 13:31:38 WARNING (MainThread) [supervisor.addons.options] Unknown options instanceName
21-02-09 13:31:38 WARNING (MainThread) [supervisor.addons.options] Unknown options integrations
21-02-09 13:31:41 INFO (SyncWorker_10) [supervisor.docker.interface] Stopping addon_6e66619d_room_assistant application
21-02-09 13:31:41 INFO (SyncWorker_10) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
21-02-09 13:31:41 WARNING (MainThread) [supervisor.addons.options] Unknown options global
21-02-09 13:31:41 WARNING (MainThread) [supervisor.addons.options] Unknown options instanceName
21-02-09 13:31:41 WARNING (MainThread) [supervisor.addons.options] Unknown options integrations

**Comment by srwatson1** [comment]
I have the following in the supervisor logs

21-02-09 16:57:58 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_6e66619d_room_assistant application
21-02-09 16:57:58 WARNING (MainThread) [supervisor.addons.options] Unknown options global
21-02-09 16:57:58 WARNING (MainThread) [supervisor.addons.options] Unknown options bluetoothLowEnergy
21-02-09 16:57:58 WARNING (MainThread) [supervisor.addons.options] Unknown options bluetoothClassic
21-02-09 16:57:58 WARNING (MainThread) [supervisor.addons.options] Unknown options cluster
21-02-09 16:57:58 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-aarch64 with version 2.13.0

And in the room-assistant logs

2/9/2021, 4:58:03 PM - info - NestApplication: Nest application successfully started
2/9/2021, 4:58:05 PM - info - ClusterService: 6e66619d-room-assistant has been elected as leader
2/9/2021, 4:58:05 PM - info - EntitiesService: Refreshing entity states

**Comment by mKeRix** [comment]
Turns out that this is related to a change in the supervisor: home-assistant/supervisor#2540. The change came without warning for me and is something that I instinctively disagree with (but I also don't know the reasons for why they took this feature away).

Only workaround for now is downgrading your supervisor version.

**Comment by mKeRix** [comment]
To downgrade you can use the following command from your SSH add-on:

`ha supervisor update --version=2021.02.1`

**Comment by neetorama** [comment]
@mKeRix thanks for your help figuring this out.

> Only workaround for now is downgrading your supervisor version.

I'm not sure if this is an option or short term solution. I could be wrong, but based on what I've read and experienced Supervisor updates automatically. I tried rolling back to 2021.02.1 a couple times as you suggested and both times Supervisor automatically updated back to 2021.02.6 in under a minute. 

Is there an option to disable Supervisor auto updates buried somewhere?

**Comment by regoras** [comment]
Adding another data point, also experiencing this: 

```
21-02-09 19:58:40 WARNING (MainThread) [supervisor.addons.options] Unknown options global
21-02-09 19:58:40 WARNING (MainThread) [supervisor.addons.options] Unknown options homeAssistant
21-02-09 19:58:40 WARNING (MainThread) [supervisor.addons.options] Unknown options bluetoothClassic
21-02-09 19:58:40 WARNING (MainThread) [supervisor.addons.options] Unknown options entities
```

Current supervisor version is 2021.02.6. I tried the suggested downgrade command and by the time HA reconnected, it had just upgraded supervisor back.

**Comment by mKeRix** [comment]
Yep, you’re right. The downgrade will revert itself fairly quickly (I just didn’t notice it on my test setup before posting). As per my searching there is no option or anything that would allow you to disable or delay these supervisor updates. Only suggestion I found in the forums is blocking the versions domain that they use from your DNS (e.g. via your Router or Pi Hole) if you use that.

I feel like I’m in a tricky position: on the one hand I appreciate all the work and time that people have put into the supervisor and know that open source is hard... but on the other hand I’m frankly a bit annoyed that such a huge change comes with no prior warning and no proper replacement in place. As it stands right now I believe that I cannot provide a good add-on experience.

Maybe we can collect some more comments of affected users in home-assistant/supervisor#2540? That would help show the severity of the situation.

**Comment by mKeRix** [comment]
Another quick update: talked to frenck on Discord quickly, apparently the two layer limitation mentioned in the docs doesn’t really exist and should be interpreted as a recommendation. That would at least make it possible to build something usable. I still expect that you won’t have the same flexibility as with normal installs, and it will take some time to write this schema for the complex format.

**Comment by xHirscHx** [comment]
Thx  for your help.

**Comment by srwatson1** [comment]
I agree - Thanks for all your time and efforts

**Comment by mKeRix** [comment]
Alright, I added a basic schema that should at least allow you to get basic functionality restored again. This is as far as I could go with the current state of the supervisor - any options that are deeper than two levels or have an array on the second level are unsupported. You also have to have all root objects defined, even if they are empty... otherwise the schema validation fails.

To get the partially working version: uninstall the add-on, reload the add-ons (Add-on Store tab -> three dot menu top right -> Reload), install the add-on again.

I will open issues for everything that is unsupported in the supervisor repo.

**Comment by regoras** [comment]
Thanks mKeRix! Just got it reloaded and it appears that basic functionality is restored. Based on the schema you shared in #2559 on the supervisor repo, is the entities item going to be one of the functions that's broken for the moment?

**Comment by mKeRix** [comment]
@regoras Yep, that is broken due to home-assistant/supervisor#2560 and home-assistant/supervisor#2561. In my tests it wasn't wiped from the UI, but it also wasn't mounted as config option into the add-on container. That means you would still see the configuration, but it won't actually do anything. The same applies to any of the other options that aren't in the schema.

**Comment by xHirscHx** [comment]
So your fix/work till HA does something is showing
IntegrationsModule: Loading integrations: home-assistant
but without the BT integrations we can't really  do anything. wright.

**Comment by regoras** [comment]
The bluetooth integrations will still work and load, from my testing. However entity control isn't working so it looks like debounce and rollingAverage don't work. I'm sure there's more, but that's just my use case.

**Comment by xHirscHx** [comment]
Ya Mqtt explore sees it now but no devices.Thanks for all your work.  Got to love updates.

**Comment by franfos** [comment]
What about "whitelist" option in bluetoothLowEnergy?
Regarding Mqtt, if there is no option to specify username and password, what are the current values sent?
I get this warning in mosquitto broker log:

> [WARN] Not found addons on local database
1613042017: Socket error on client <unknown>, disconnecting.

**Comment by outofsight** [comment]
> Alright, I added a basic schema that should at least allow you to get basic functionality restored again. This is as far as I could go with the current state of the supervisor - any options that are deeper than two levels or have an array on the second level are unsupported. You also have to have all root objects defined, even if they are empty... otherwise the schema validation fails.
> 
> To get the partially working version: uninstall the add-on, reload the add-ons (Add-on Store tab -> three dot menu top right -> Reload), install the add-on again.
> 
> I will open issues for everything that is unsupported in the supervisor repo.

Just an idea. Load configuration of RA addon from a suitable "shared/mapped" folder, i.e. /config/room-assistant/ or /raconfig. This is the same that happens on a RPi and allow sharing config files: one can hold all configuration files of all RA instances in that folder as a default.yaml + a series of {hostname}.yaml and auto-copy with simple ssh/scp to all RA instance upon any change and every instance will pickup suitable config file.

**Comment by xHirscHx** [comment]
Did HA revert back with this update today,config file seems to be working again

**Comment by hippydave** [comment]
> Did HA revert back with this update today, config file seems to be working again
> but i can't copy paste my old config file in gives me a boat load of errors in red at the bottom. Does that have something with the workaround you did yesterday.

I'm just playing with this now, to see if I can get it working. Turns out you need to leave in all the options that are in the default config, removing any of them gives the red errors. You can put in any additional options from your old config in between the existing ones and it won't give errors, but I don't know if it means those options will work.

**Comment by mKeRix** [comment]
@outofsight Yeah, or an inline YAML like:

```yaml
roomAssistantConfig: |
  global:
    instanceName: example
    integrations:
      - homeAssistant
```

Since my issues on the supervisor repo haven't received any real reaction I think that we likely won't see any quick fixes there... so I'll consider an alternative option that would allow complete configuration again.

@hippydave Yep, that's a supervisor issue that I reported here: home-assistant/supervisor#2559.

**Comment by mKeRix** [comment]
The latest version of the add-on (2.13.1) fixed this issue - the config was now moved into the Home Assistant config folder. You can use your complete config as you used it before (no limitations) by creating it as e.g. `/config/room_assistant/local.yml` on the file system. If no configuration exists a default file will be created there on first add-on start. You can create/edit the file using the SSH, Samba or File Editor add-ons.

This was the best option that I found for fixing this stuff in a timely manner, even though it makes things a bit more complicated. Everything else won't work until some changes are implemented in the supervisor unfortunately.
