### ISSUE TITLE
TypeError: os.version is not a function

### ISSUE THREAD

**Issue by SamKirsch10** [mKeRix/room-assistant#502]
**Describe the bug**
Looks like there's some js error thrown upon startup on the Raspberry Pi Zero W `TypeError: os.version is not a function`

**To reproduce**
Followed Pi Zero W tutorial with minimal yaml config below.

**Relevant logs**
```text
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2/6/2021, 2:29:20 PM - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-low-energy
(node:3360) DeprecationWarning: You are using a version of Node.js that will reach EOL in April 2021. The support for this version will be dropped in 7.13. Please refer to https://ela.st/nodejs-support for additional information.
2/6/2021, 2:29:26 PM - info - NestFactory: Starting Nest application...
2/6/2021, 2:29:27 PM - info - InstanceLoader: AppModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: ConfigModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: HttpModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: PrometheusModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: ClusterModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: TerminusModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: BluetoothModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: ScheduleModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: EntitiesModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: BluetoothLowEnergyModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: HomeAssistantModule dependencies initialized
2/6/2021, 2:29:27 PM - info - InstanceLoader: StatusModule dependencies initialized
2/6/2021, 2:29:31 PM - info - RoutesResolver: EntitiesController {/entities}:
2/6/2021, 2:29:31 PM - info - RouterExplorer: Mapped {/entities, GET} route
2/6/2021, 2:29:31 PM - info - RoutesResolver: StatusController {/status}:
2/6/2021, 2:29:31 PM - info - RouterExplorer: Mapped {/status, GET} route
2/6/2021, 2:29:31 PM - info - RoutesResolver: PrometheusController {/metrics}:
2/6/2021, 2:29:31 PM - info - RouterExplorer: Mapped {/metrics, GET} route
2/6/2021, 2:29:31 PM - warn - BluetoothLowEnergyService: The allowlist and denylist are empty, no sensors will be created! Please add some of the discovered IDs below to your configuration.
/opt/nodejs/lib/node_modules/room-assistant/node_modules/systeminformation/lib/system.js:124
          if (!result.virtual && os.version().toLowerCase().indexOf('microsoft') >= 0) {
                                    ^

TypeError: os.version is not a function
    at /opt/nodejs/lib/node_modules/room-assistant/node_modules/systeminformation/lib/system.js:124:37
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:610:12)
```

**Relevant configuration**

```yaml
global:
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.10:1883'
  mqttOptions:
    username: someUsername
    password: somePassword
bluetoothLowEnergy:
  timeout: 10
  maxDistance: 5
```

**Expected behavior**
When starting `room-assistant` it should run

**Environment**
 - room-assistant version: 2.13.0
 - installation type: NodeJS @ v11.5.0 (npm @ 6.4.1)
 - hardware: Raspberry Pi Zero W
 - OS: Raspbian (Linux raspberry 5.10.11+ #1399)

**Additional context**
Followed instructions from tutorial [https://www.room-assistant.io/guide/quickstart-pi-zero-w.html#installing-room-assistant](here)

**Comment by SamKirsch10** [comment]
Updating node. Will reopen if that fails... sorry

**Comment by bsmith76s** [comment]
what fixed this problem? I'm having same.

**Comment by mKeRix** [comment]
Short side note: as you can see in the stacktrace this error isn’t caused by room-assistant, but one of its dependencies. It would make sense to search for (or report) this issue over here: https://github.com/sebhildebrandt/systeminformation

**Comment by bsmith76s** [comment]
> Short side note: as you can see in the stacktrace this error isn’t caused by room-assistant, but one of its dependencies. It would make sense to search for (or report) this issue over here: https://github.com/sebhildebrandt/systeminformation
> 
> By just quickly looking over it I suspect the issue is that you need at least NodeJS v12. I’ll try to raise the guides to that in order to avoid issues... v10 that is currently described in the guides is going EOL this year anyway.

Ive tried to bump up to lates version of nodejs but I keep getting this:

wget -O - https://raw.githubusercontent.com/sdesalas/node-pi-zero/master/install-node-v.lts.sh | bash
--2021-02-06 19:25:58--  https://raw.githubusercontent.com/sdesalas/node-pi-zero/master/install-node-v.lts.sh

Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1944 (1.9K) [text/plain]
Saving to: ‘STDOUT’

-                   100%[===================>]   1.90K  --.-KB/s    in 0.005s  

2021-02-06 19:25:59 (384 KB/s) - written to stdout [1944/1944]

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 88  189k   88  167k    0     0   352k      0 --:--:-- --:--:-- --:--:--  353k
curl: (23) Failed writing body (642 != 4220)
mkdir: cannot create directory ‘temp’: File exists
--2021-02-06 19:26:00--  https://nodejs.org/dist/latest-dubnium/node-v10.23.2-linux-armv6l.tar.gz
Resolving nodejs.org (nodejs.org)... 104.20.23.46, 104.20.22.46, 2606:4700:10::6814:162e, ...
Connecting to nodejs.org (nodejs.org)|104.20.23.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19805690 (19M) [application/gzip]
Saving to: ‘node-v10.23.2-linux-armv6l.tar.gz’

node-v10.23.2-linux 100%[===================>]  18.89M  2.63MB/s    in 7.9s    

2021-02-06 19:26:08 (2.40 MB/s) - ‘node-v10.23.2-linux-armv6l.tar.gz’ saved [19805690/19805690]

unlink: cannot unlink '/sbin/node': No such file or directory
unlink: cannot unlink '/sbin/npm': No such file or directory
ln: failed to create symbolic link '/sbin/node': File exists
ln: failed to create symbolic link '/sbin/npm': File exists



Side Note:
I have been having a time installing room assistant on a pi0. I've started from scratch 4 or 5 times. I always have some issue in installation. This is the closes I have come to getting it up and running.

**Comment by SamKirsch10** [comment]
It looks like you somehow are getting `node-v10.23.2` which is super old. Google around installing node on your pi zero. I was able to update to v14.13.0 and it's working now.

**Comment by mKeRix** [comment]
The repo that is used in the docs is a bit outdated, since NodeJS changed their releases for the processor architecture found on Pi Zeros. I will update it soon. Until then you can follow one of the Internet guides to install a more recent version: https://yatil.net/posts/2020/11/07/node-on-pi/

**Comment by SamKirsch10** [comment]
This _should_ do it since the Pi 0 (aka armv6) was deprecated in the official download section

https://gist.github.com/SamKirsch10/7e1081536de0c7d81cb8666cedfdca0c

**Comment by bsmith76s** [comment]
installed 14.13.0 nodejs and installed room-assistant. started room-assistant and I get this error now. 

/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/hci.js:107
        throw e;
        ^

Error: ENODEV, No such device
    at Hci.init (/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/hci.js:102:37)
    at NobleBindings.init (/usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/hci-socket/bindings.js:111:13)
    at /usr/local/lib/node_modules/room-assistant/node_modules/@mkerix/noble/lib/noble.js:60:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: 19,
  code: 'ENODEV',
  syscall: 'bind'

I just can not get this working.

**Comment by mKeRix** [comment]
That error is unrelated to the issue here, so best would be to create a new one... but essentially it just means there is no bluetooth adapter with the ID that you configured. Check what is available using `hciconfig` and only configure those adapter ids.

**Comment by bsmith76s** [comment]
Thank you. I think I just need to step away a bit. Things are just getting to muddy in my head with this right now. Can I run blue tooth classic and BLE on the same HC0 adapter? or do I need another adapter. can't seem to find this info anywhere with Google and other search engines.

**Comment by mKeRix** [comment]
You can run both on the same adapter, performance will be a bit better with separate adapters though. If you are trying to plug a USB Bluetooth dongle into a Raspberry take a look at this discussion: https://github.com/mKeRix/room-assistant/discussions/451

**Comment by bsmith76s** [comment]
Thank you again. I'll try this later today. I am using ethernet on the pi0 so I'm hoping performance is not effected much on the pi0. If I get up and running I hope to see.

**Comment by casaerreti** [comment]
I am getting this after update and node js ver 14.13


during install
npm WARN notsup Unsupported engine for room-assistant@2.13.0: wanted: {"node":">= 10 < 13"} (current: {"node":"14.13.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: room-assistant@2.13.0

executing 

[Nest] 2538   - 07/02/2021, 20:54:19   [ClusterService] The module '/opt/nodejs/lib/node_modules/room-assistant/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

tried 
npm rebuild or npm install with no success

**Comment by mKeRix** [comment]
The warning you can ignore, that will be fixed in upcoming versions and shouldn’t impact functionality. If the rebuild doesn’t work for you can also always uninstall room-assistant using `npm uninstall -g room-assistant` and then install it again as you normally would. That will wipe the wrongly built packages and build them again.

**Comment by bob-gorman** [comment]
SamKirsch10 script worked like a champ, i got node 15.8.0 installed... but I get a fatal error trying to install room-assistant: 

---
pi:~ $ sudo npm i --global --unsafe-perm room-assistant
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'room-assistant@2.13.0',
npm WARN EBADENGINE   required: { node: '>= 10 < 13' },
npm WARN EBADENGINE   current: { node: 'v15.8.0', npm: '7.5.1' }
npm WARN EBADENGINE }
[         .........] / idealTree: timing idealTree Completed in 151864ms
<--- Last few GCs --->

[2080:0x4007750]   320660 ms: Mark-sweep 121.4 (129.1) -> 120.9 (129.1) MB, 6721.7 / 45.4 ms  (average mu = 0.580, current mu = 0.074) allocation failure scavenge might not succeed
[2080:0x4007750]   328900 ms: Mark-sweep 121.5 (129.1) -> 120.9 (129.4) MB, 7673.8 / 45.4 ms  (average mu = 0.383, current mu = 0.069) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
Aborted

**Comment by Erelen-Laiquendi** [comment]
Same problem on RPi Zero W with Node 15.8 - heap out of memory:

```
pi@rpizero-test:~/room-assistant $ sudo npm i --global --unsafe-perm room-assistant
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'room-assistant@2.13.0',
npm WARN EBADENGINE   required: { node: '>= 10 < 13' },
npm WARN EBADENGINE   current: { node: 'v15.8.0', npm: '7.5.2' }
npm WARN EBADENGINE }
[         .........] / idealTree: timing idealTree Completed in 169743ms
<--- Last few GCs --->

[6701:0x3f42750]   329541 ms: Scavenge (reduce) 121.7 (128.9) -> 121.6 (128.9) MB, 116.8 / 0.1 ms  (average mu = 0.975, current mu = 0.968) allocation fa                               ilure
[6701:0x3f42750]   329861 ms: Scavenge (reduce) 121.7 (128.9) -> 121.6 (128.9) MB, 126.4 / 0.1 ms  (average mu = 0.975, current mu = 0.968) allocation fa                               ilure
[6701:0x3f42750]   330075 ms: Scavenge (reduce) 121.7 (128.9) -> 121.7 (128.9) MB, 130.7 / 0.1 ms  (average mu = 0.975, current mu = 0.968) allocation fa                               ilure


<--- JS stacktrace --->

FATAL ERROR: Scavenger: semi-space copy Allocation failed - JavaScript heap out of memory
Aborted
```

**Comment by SamKirsch10** [comment]
Please Open a separate issue so the dev (not me :) ) can help you properly. Looks like I'm on version v14.13.0, so try that

**Comment by Erelen-Laiquendi** [comment]
Yes, with v14.13 it works. Thanks!
New issue: https://github.com/mKeRix/room-assistant/issues/514

**Comment by mKeRix** [comment]
I've updated the [Pi Zero W installation guide](https://www.room-assistant.io/guide/quickstart-pi-zero-w.html#installing-room-assistant) to use the current LTS version of NodeJS now, which is 14.x. Huge thanks to @SamKirsch10 - I forked your script and only made some small adjustments to change it from the latest to LTS.
