### ISSUE TITLE
Immediate disconnections when attempting to discover iOS companion app

### ISSUE THREAD

**Issue by a-metasyntactic** [mKeRix/room-assistant#508]
**Describe the bug**
When connecting to a device to discover companion app, I'm sometimes seeing an immediate disconnect before getting to service/characteristic discovery. It looks like the same issue being reported in abandonware/noble#62.

**To reproduce**
Run with iOS device tracking on a Raspberry Pi, using onboard Bluetooth and WiFi.

**Relevant logs**
```text
2/7/2021, 1:27:04 PM - info - BluetoothLowEnergyService: Attempting app discovery for tag 5e0d747f2583
2/7/2021, 1:27:04 PM - debug - BluetoothLowEnergyService: Tag 5e0d747f2583 seems to broadcast the app with manufacturer data 4c001006311e0259acbd0100000010000000000000000000000000
2/7/2021, 1:27:04 PM - debug - BluetoothService: Connecting to BLE device at address 5e:0d:74:7f:25:83
2/7/2021, 1:27:04 PM - debug - BluetoothService: Locking adapter 0
2/7/2021, 1:27:04 PM - debug - BluetoothService: Stopping scanning for BLE peripherals on adapter 0
2/7/2021, 1:27:04 PM - debug - BluetoothService: Stopped scanning for BLE peripherals on adapter 0
2/7/2021, 1:27:05 PM - debug - BluetoothService: Disconnected from BLE device at address 5e:0d:74:7f:25:83
2/7/2021, 1:27:05 PM - debug - BluetoothService: Unlocking adapter 0
2/7/2021, 1:27:05 PM - debug - BluetoothService: Adapter 0 went into state poweredOn
2/7/2021, 1:27:05 PM - debug - BluetoothService: Starting scanning for BLE peripherals on adapter 0
2/7/2021, 1:27:05 PM - debug - BluetoothLowEnergyService: Tag 5e0d747f2583 should have the companion app, retrying in a minute
```

**Relevant configuration**
```yaml
bluetoothLowEnergy:
  timeout: 60
  updateFrequency: 0.5
  allowlist:
    - guid1
    - guid2
```

**Expected behavior**
Whilst this issue exists in the underlying BLE libraries, being more aggressive with the retry logic for app discovery might be appropriate. I tried tweaking the behaviour in `BluetoothLowEnergyService` to timeout after 5s instead of 15s and banning app discovery for 1s rather than 60s which results in significantly more reliable detection for me - ran for a day without any dropouts whereas before it would frequently fail to detect a device for 10-20+ minutes at a time.

I think this could be further improved upon by trying to detect this false connection/disconnection situation (by a disconnect within 500ms as suggested in the linked issue maybe?) and immediately attempting to connect again rather than waiting for the device ban to expire and next advert from device.

**Environment**
 - room-assistant version: 2.13.0
 - installation type: Docker
 - hardware: Raspberry Pi 3 A+
 - OS: Raspbian

**Comment by mKeRix** [comment]
Thanks for you in-depth research on this topic! I was seeing issues these dropouts you mentioned occasionally as well, but wasn't able to hunt down the cause. I'll look into tuning the params you mentioned and detecting these disconnections.

**Comment by a-metasyntactic** [comment]
No problem - hope it's helpful. Thanks for all the effort you put into this project!
