### ISSUE TITLE
error - ClusterService: getaddrinfo -3008

### ISSUE THREAD

**Issue by gbdavidx** [mKeRix/room-assistant#556]
**Describe the bug**
error - ClusterService: getaddrinfo -3008
error - ClusterService: getaddrinfo -3008

**To reproduce**
Installed room-assistant by scratch on raspberry pi w's

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```
global:
  instanceName: office
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.1.123:1883'
  mqttOptions:
    username: user
    password: passwd
bluetoothLowEnergy:
  addresses:
    - '90:81:2A:1C:6F:27'
bluetoothClassic:
  minRssi: -9
  addresses:
    - '88:64:40:71:67:6E'
    - '90:81:2A:15:72:11'
    - '90:81:2A:1C:6F:27'
cluster:
  autoDiscovery: true
  networkInterface: wlan0
  port: 6425
  peerAddresses:
    - 192.168.1.190:6425
    - 192.168.1.191:6425                                                               
```

**Expected behavior**
No errors, everything else _seems_ to be working..., however I CANNOT detect my apple watch :(

**Environment**

room-assistant version: 2.13.1
installation type: NodeJS
hardware: Raspberry Pi Zero W
OS: Linux

**Additional context**
<img width="981" alt="Screen Shot 2021-02-24 at 8 55 12 AM" src="https://user-images.githubusercontent.com/26369204/109035992-04989f00-767e-11eb-94ff-3c11413ed642.png">

**Comment by gbdavidx** [comment]
<img width="978" alt="Screen Shot 2021-02-25 at 10 01 38 AM" src="https://user-images.githubusercontent.com/26369204/109196362-74775a00-7750-11eb-9809-3494c0792669.png">
i got my apple watch finally detected (after it died) it appeared in home assistant, but now i am getting this

**Comment by mKeRix** [comment]
The geraddrr info error is more informative than an error really, you should only be concerned about it if your instances aren't able to find each other on your network.

The Apple Watch thing could be a number of things, there's a short troubleshooting section in the Bluetooth Classic integration docs for that.

The locking error is also not really something to be concerned about unless you see that a lot of times after another. The constant re-election points to some network troubles, I'd try raising the [cluster](https://www.room-assistant.io/guide/cluster.html#settings) `timeout` if you're concerned about that. Essentially it means that the node keeps dropping out of the cluster and re-joining, which will cause leader changes and possibly some weird entity behavior... but all in all, room-assistant should be able to deal with it.
