### ISSUE TITLE
Running on ESP32

### ISSUE THREAD

**Issue by 1043717432** [mKeRix/room-assistant#56]
Hi, thanks for sharing. Can a room assistant use ESP32+2.4 GHz Wi-Fi and Bluetooth dual mode chips?
![tb2jv 1fdxybenkhfrdxxciuvxa_ 2675241364](https://user-images.githubusercontent.com/22461690/42720593-2a2515b4-875c-11e8-913d-6ebb11a088d6.jpg)
![tb2lv ofycybunkhfccxxchtvxa_ 2675241364](https://user-images.githubusercontent.com/22461690/42720596-2f2ebf7e-875c-11e8-90c8-5ce6aa963480.jpg)

**Comment by mKeRix** [comment]
room-assistant doesn't incorporate or run on ESP32 chips. If you want to do room based presence with these chips you can write your own piece of software that would run on these chips and make it publish data to MQTT in the format described [here](https://www.home-assistant.io/components/sensor.mqtt_room/).

**Comment by jptrsn** [comment]
There's a project called [Open MQTT Gateway](https://github.com/1technophile/OpenMQTTGateway) that is apparently able to provide the same kind of functionality on an ESP32, although I've not tested it yet.

**Comment by mKeRix** [comment]
I just saw that @jptrsn started his own awesome project that does just this, [ESP32-mqtt-room](https://github.com/jptrsn/ESP32-mqtt-room). For room-assistant ESP32 is a bit out of scope, so I’ll close this issue.
