### ISSUE TITLE
Optionally add transmission power to whitelist

### ISSUE THREAD

**Issue by MatsNl** [mKeRix/room-assistant#58]
Hi!

Would be great if I could add transmission power per device, linked to ID in the whitelist. Not all devices are broadcasting that info, and it's not too hard to manually get an estimate (e.g. standing close to scanner and seeing what value comes out). In those cases a workaround would be welcome right?
Especially for fitness trackers that broadcast lower than current working assumption (-70 vs -5x). 

Don't think it is a mayor change right? Currently changing directly in the code for miband myself.
Cheers

**Comment by mKeRix** [comment]
This is now live in version 1.1.0 - sorry that it took me way longer than what I originally hoped for.
