### ISSUE TITLE
BLE is only reporting one distance in MQTT

### ISSUE THREAD

**Issue by dflvunoooooo** [mKeRix/room-assistant#589]
**Describe the bug**
When I set up BLE for two devices on two RA instances in different rooms, I only get MQTT distance messages for one device from one RA instance to which this device is nearest. For example RA kitchen is only reporting the distance for one BLE device and livingroom is reporting the distance for the other and this devices are near to those RA instances.

**Relevant configuration**
The config files are the same, because I copied them, except for the RA instance name.

**Expected behavior**
I would expect that the MQTT message to contain the distance from from all RA instances, like it is happening for Bluetooth classic.

**Environment**
 - room-assistant version: 2.14
 - installation type: NodeJS
 - hardware: Raspberry Pi 3
 - OS: Arch Linux

Is it because BLE signal is too weak to reach the other instance? With Bluetooth classic I get distances from both instances for both devices. That is what I need, because I am using the distances from both instances to "calculate" in which room the devices are. Am I missing something?

**Comment by mKeRix** [comment]
It does sound like the signal doesn't reach at least - the BLE integration should behave exactly like the BT Classic integration. What kind of beacon are you using? Do you still see updates for both devices if you turn off one of your instances?

**Comment by dflvunoooooo** [comment]
All right, my mistake. The signal is to weak to reach both instances, though both rooms are not very far away.

I am using the HA companion app with `transmitting power` set to medium.
