### ISSUE TITLE
iOS companion app BLE tagOverrides and entity setup seems broken

### ISSUE THREAD

**Issue by Angyld-tur** [mKeRix/room-assistant#594]
**Describe the bug**
After having tried many different combinations in my config, I am unable to setup tagOverrides and entity behaviors for BLE / iOS devies using the companion app. 
For tagOverrides, the documentation is stating to use the tag id, however this one is changing periodically on my iPhone 12 Pro. So I tried various combinations of the UUID found in the companion app and also ids stated from the /api/entities response (see below).
For entity behaviors it seems to be based on the internal ids according to the documentation, but the ones found in the /api/entity endpoint does not seem to have effect on it. I also tried different versions.
Side note on that topic, the debug los is logging `HomeAssistantService: Sending new attributes {"distance":0.3,"lastUpdatedAt":"2021-03-11T20:31:03.258Z"} for room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX`, whereas the id in the api endpoint is missing the "room-assistant-" prefix. Is that on purpose?

**To reproduce**
1) install room assistant 2.14.0
2) install companion app on iOS device
3) add UUID from companions app to allowlist in BLE setup
4) add tagOverrides section to BLE with that same UUID, without hypens (lower / uppercase does not seem to have an effect)
5) add entites section to config with a rolling average calculation, tried various variants (see below)

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - info - BluetoothLowEnergyService: Discovered companion app with ID 307A9ED4-D6D5-VVVV-ZZZZ-XXXXXXXXX for tag macadressss
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - info - BluetoothLowEnergyService: Discovered new BLE peripheral 307A9ED4-D6D5-VVVV-ZZZZ-XXXXXXXXX with ID 307A9ED4-D6D5-VVVV-ZZZZ-XXXXXXXXX and RSSI -48
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - debug - EntitiesService: Adding new entity ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX-tracker
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - debug - HomeAssistantService: Registering entity room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX-tracker under homeassistant/device_tracker/room-assistant/ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX-tracker/config
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - debug - EntitiesService: Adding new entity ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - debug - HomeAssistantService: Registering entity room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX under homeassistant/sensor/room-assistant/ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX/config
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - debug - BluetoothService: Disconnected from BLE device at address MA:CA:DR:ES:S0:00
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - debug - BluetoothService: Unlocking adapter 0
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - debug - BluetoothService: Adapter 0 went into state poweredOn
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - debug - BluetoothService: Starting scanning for BLE peripherals on adapter 0
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - debug - BluetoothService: Disconnected from BLE device at address MA:CA:DR:ES:S0:00
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - debug - HomeAssistantService: Sending new state workroom for room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - debug - HomeAssistantService: Sending new state home for room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX-tracker
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - debug - BluetoothService: Started scanning for BLE peripherals on adapter 0
Mar 11 21:29:02 localhost room-assistant[6145]: 11.3.2021, 21:29:02 - debug - HomeAssistantService: Sending new attributes {"distance":0.1,"lastUpdatedAt":"2021-03-11T20:29:02.385Z"} for room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX
Mar 11 21:29:05 localhost room-assistant[6145]: 11.3.2021, 21:29:05 - debug - HomeAssistantService: Sending new attributes {"distance":0.2,"lastUpdatedAt":"2021-03-11T20:29:05.313Z"} for room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX
Mar 11 21:29:08 localhost room-assistant[6145]: 11.3.2021, 21:29:08 - debug - HomeAssistantService: Sending new attributes {"distance":0.2,"lastUpdatedAt":"2021-03-11T20:29:08.350Z"} for room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX
Mar 11 21:29:11 localhost room-assistant[6145]: 11.3.2021, 21:29:11 - debug - HomeAssistantService: Sending new attributes {"distance":0.4,"lastUpdatedAt":"2021-03-11T20:29:11.493Z"} for room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX
Mar 11 21:29:14 localhost room-assistant[6145]: 11.3.2021, 21:29:14 - debug - HomeAssistantService: Sending new attributes {"distance":0.2,"lastUpdatedAt":"2021-03-11T20:29:14.494Z"} for room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX
Mar 11 21:29:17 localhost room-assistant[6145]: 11.3.2021, 21:29:17 - debug - HomeAssistantService: Sending new attributes {"distance":0.4,"lastUpdatedAt":"2021-03-11T20:29:17.506Z"} for room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX
Mar 11 21:29:20 localhost room-assistant[6145]: 11.3.2021, 21:29:20 - debug - HomeAssistantService: Sending new attributes {"distance":0.2,"lastUpdatedAt":"2021-03-11T20:29:20.650Z"} for room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX
Mar 11 21:29:23 localhost room-assistant[6145]: 11.3.2021, 21:29:23 - debug - HomeAssistantService: Sending new attributes {"distance":0.1,"lastUpdatedAt":"2021-03-11T20:29:23.651Z"} for room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX
```

**Relevant configuration**
```yaml
global:
  instanceName: workroom
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://mqtthost:1883'
  mqttOptions:
    username: user
    password: nicepassword
bluetoothLowEnergy:
  timeout: 60
  maxDistance: 2.5
  updateFrequency: 3
  allowlist:
  - '307A9ED4-D6D5-VVVV-ZZZZ-XXXXXXXXX'
  tagOverrides:
    307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX:
      measuredPower: -46.1
    macadressss:
      measuredPower: -46.1
entities:
  behaviors:
    room-assistant-ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX:
      rollingAverage:
        window: 30
    ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX:
      rollingAverage:
        window: 20
    307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX:
      rollingAverage:
        window: 10
    macadressss:
      rollingAverage:
        window: 50
```

**Expected behavior**
I'd expect the UUID to be available as an ID to setup the rollingAverage and tagOverrides, as the tag id is rotating. 

**Environment**
 - room-assistant version: 2.14.0
 - installation type: NodeJS (14.16.0)
 - hardware: Raspberry Pi Zero W
 - OS: Raspbian

Let me know if you need more information of if I am just not able to read the documentation properly :) I really love the idea of this project!

**Comment by mKeRix** [comment]
Yeah, all the ID stuff can get a bit confusing! There's a couple areas that could use improvement there.

The tagOverrides should be based on the tag ID as you read. For a companion app device the tag ID is actually the app ID (as the hardware one is indeed random). Something like this should work (note that the override also has it in uppercase):

```yaml
bluetoothLowEnergy:
  allowlist:
  - '307A9ED4-D6D5-VVVV-ZZZZ-XXXXXXXXX'
  tagOverrides:
    307A9ED4-D6D5-VVVV-ZZZZ-XXXXXXXXX:
      measuredPower: -46.1
```

For the entity behaviors you are looking for the room-assistant internal IDs from the API. The room-assistant prefix you saw in the logs for example is used to have a "namespace" in Home Assistant, essentially it is supposed to ensure that there are no collisions with other tools using the MQTT integration. I have the behaviors set up and working for companion app devices, your second option is the correct one. Note that the device tracker has a different ID though (it's a different entity), so if you want the behavior on both you'd need to have two entries. Here the ID should be all lowercase.

```yaml
entities:
  behaviors:
    ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX:
      rollingAverage:
        window: 20
    ble-307a9ed4-d6d5-VVVV-ZZZZ-XXXXXXXXX-tracker:
      rollingAverage:
        window: 20
```

**Comment by Angyld-tur** [comment]
Hey there,

thanks for your detailed reply!
I've followed your advises and it is indeed working as expected. 

Would you mind if I open a PR for making the docs a bit clearer?

Have a nice sunday!

**Comment by mKeRix** [comment]
Any improvement is welcome, so feel free! :) Since this specific issue is resolved I'll close it now.
