### ISSUE TITLE
Override Behaviour

### ISSUE THREAD

**Issue by C0NTi** [mKeRix/room-assistant#596]
**Is your feature request related to a problem? Please describe.**
BT Classic and BTLE now both have some override behaviour but I would like to see the two integrations have the same available settings.

With BT Classic only 'id' is supported.

With BTLE only 'name' is supported. (id is listed - but as soon as enable this feature I no longer get mqtt messages )

With the BTLE Overrides you get tag ids in the mqtt messages but nice entity names in home assistant using the override

With BT Classic overrides you get nice simple mqtt messages using the override but get mac addresses in the entity id of home assistant.

MQTT Messages
![Screenshot 2021-03-15 100421](https://user-images.githubusercontent.com/29498865/111136608-d5d36180-8575-11eb-90be-cfb05851742b.png)

BTLE Config (using override in name - which ultimately becomes the home assistant entity id)
![Screenshot 2021-03-15 100528](https://user-images.githubusercontent.com/29498865/111136780-fdc2c500-8575-11eb-959d-c8e86d655785.png)

BT Config (just using mac address) 
![Screenshot 2021-03-15 100650](https://user-images.githubusercontent.com/29498865/111136974-2f3b9080-8576-11eb-9233-c08a0a60344d.png)

**Describe the solution you'd like**

I think it would be much more elegant to include both 'id' and 'name' overides for both integrations. (plus get id fixed for BTLE)

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by mKeRix** [comment]
Thanks for the detailed write up. I'll try to spend some time on fixing this feature and bringing feature parity - the current state is a bit confusing indeed.
