### ISSUE TITLE
Mi band 2 detection possible?

### ISSUE THREAD

**Issue by stefanmechelen** [mKeRix/room-assistant#60]
Hi, is this possible?

**Comment by mKeRix** [comment]
Hey there,

I’ve read success stories with the Mi Band 2 on the Home Assistant forums, so it‘s likely, yeah. Don’t have one to test it on my own though.

If you already have one you can try running `sudo hcitool lescan` on your Linux device. Alternatively you can use any other BLE scanning app, not on the phone connected to the band itself though. If you see it there room-assistant will also be able to pick it up.

**Comment by jptrsn** [comment]
I can confirm that this works with my MiBand 2.
