### ISSUE TITLE
Change update interval

### ISSUE THREAD

**Issue by KrisCoder1** [mKeRix/room-assistant#623]
Hi,

I have Room Assistant installed on Home Assistant as a custom Add-On, is there any way I can change the update interval in the config file? I use bluetoothClassic, but could switch to BLE if neccesary.

regards,
Kris :D

**Comment by mKeRix** [comment]
I guess you already figured this out, but: the respective option for the `bluetoothClassic` integration is named `interval` ([docs](https://www.room-assistant.io/integrations/bluetooth-classic.html#settings)).
