### ISSUE TITLE
not sure if this is important or not

### ISSUE THREAD

**Issue by razorface1978** [mKeRix/room-assistant#624]
i get an error every time i start room assistant 
22:39:34 - warn - ConfigService: No configuration found in /home/pi/config

![image](https://user-images.githubusercontent.com/58651991/112736931-ef3cbc00-8f2c-11eb-8bcc-05a305a86177.png)

**Comment by mKeRix** [comment]
room-assistant looks into the config folder within the current working directory for config files by default, i.e. if you start It in /home/pi it will look in /home/pi/config. If you start it in /home/pi/room-assistant (which you probably meant to do) it will look un /home/pi/room-assistant/config. The instance you showed just didn't load any integrations or any other stuff, it uses purely default settings.
