### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by liquidbear99** [mKeRix/room-assistant#627]
After upgrading all my nodes are giving this error. I'm running the Bluetooth LE integration and don't know why they day the address is already in use. Let me know if there is a fix, or this is a bug.

![image](https://user-images.githubusercontent.com/53712660/112745380-a9ecae80-8f6d-11eb-87b6-b11481d7552f.png)

**Comment by riddledaxis** [comment]
Did you re-apply the permissions after the upgrades?
```
sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
sudo setcap cap_net_raw+eip $(eval readlink -f `which hcitool`)
sudo setcap cap_net_admin+eip $(eval readlink -f `which hciconfig`)
```
I've made this mistake more than once and it is an easy fix

**Comment by liquidbear99** [comment]
Ah! That fixed it! Thanks!

**Comment by mKeRix** [comment]
For future reference: this error usually just means you already have an instance of room-assistant running. Make sure to stop the systemd service or Docker container before starting another instance, or do a `killall node` if you don't use either of those.
