### ISSUE TITLE
Mi Band 3

### ISSUE THREAD

**Issue by stefanmechelen** [mKeRix/room-assistant#64]
Does it work? I have a mac address in the app settings, tried it. Nothing. I've a ble scanner on my phone. Tried it, can't find the mi band 3. Can find the old mi band 2 though. Also, what's the correct setup for this (both in the add on config and in configuration.yaml). Some say with : other without, what's the device id in the mqtt room sensor? there's no such variable in the romm assistant add-on setup. Would love it if I could get this to work, but tried multiple times now and failed miserably.

**Comment by mKeRix** [comment]
Device ID is what your device reports via BLE, the easiest way to find this is by leaving the whitelist empty and turning on the console logger. You can then see what devices room-assistant finds with their respective IDs. It should technically work as long as it's BLE. Some devices do not advertise their presence when they're connected to a phone though, maybe that's the issue?

Unfortunately I don't have a Band 3 to test with and only read about people using the Band 2 so far.

(Sorry for long time to reply, was on vacation)

**Comment by MatsNl** [comment]
Miband 3 works, but you should enable discoverable mode in the mifit app. Does have some battery impact, but not too bad actually!
