### ISSUE TITLE
Raspberry pi zero W

### ISSUE THREAD

**Issue by mredone** [mKeRix/room-assistant#65]
Does Room-assistant in newest version work OOtB on Rpi Zero W?
If yes then how install?
Standard installation not working...

**Comment by jptrsn** [comment]
Works on my Pi Zero W without a problem. Where are you getting stuck in the install? Do you have any error messages you can post?

**Comment by mredone** [comment]
`gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.14.62+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/room-assistant/node_modules/bluetooth-hci-socket
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1`

**Comment by mredone** [comment]
Maybe someone teach me how edit and run a docker file?

**Comment by mredone** [comment]
Hello? Anyone?

**Comment by jptrsn** [comment]
What version of nodejs are you using? Did you make sure to install the correct build for armv6l rather than armv7l? The zero uses a different version of nodejs.

I'm also running into problems on a fresh install using node v 9.9.0 for armv6l. It appears that node-gyp builds are failing, for bluetooth-hci-socket, even when using the --unsafe-perm flag.

**Comment by mredone** [comment]
Yesterday i have another try and on latest `raspbian strech lite` and `Nodejs 10.9.0 for arm6l` i have same issue. First `usb` failed to compile, second `bluetooth-hci-socket`.

I try with `--unsafe-perm` and same problem.

**Comment by jptrsn** [comment]
Try with node v 8.13.0 and run both the install and start commands with the --unsafe-perm flag set. That seems to have resolved the issue for my install.

These are the commands I used to install NodeJS:
```
curl -o node-v8.11.3-linux-armv6l.tar.gz https://nodejs.org/dist/v8.11.3/node-v8.11.3-linux-armv6l.tar.gz
tar -xzf node-v8.11.3-linux-armv6l.tar.gz
sudo cp -r node-v8.11.3-linux-armv6l/* /usr/local/
sudo npm install -g npm@latest --unsafe-perm
```

**Comment by mredone** [comment]
Big THX!!! Everything work like a charm when change newest nodes to 8.11.3 version!

**Comment by mKeRix** [comment]
Sorry I'm only replying now, was on vacation. Glad to see you were able to solve the problem! I will update the README to only mention NodeJS 8.x, not higher.

**Comment by mKeRix** [comment]
For anyone finding this in the future, if you don't want to downgrade to Node 8 you can also use [this fix](https://github.com/sandeepmistry/node-xpc-connection/issues/24#issuecomment-398661672).

**Comment by mKeRix** [comment]
Quick update: current version of room-assistant has fixed the ble compatibility with Node 10!

**Comment by getsmokes** [comment]
Is this still working on a Pi Zero? I've tried multiple times but can't seem to get it working, pi 3 and pi2's are fine.

If anyone has clear instructions that would be great.

**Comment by mKeRix** [comment]
@getsmokes I've just recently installed it on 3 Pi Zero Ws and didn't run into any particular issues.

My process was:

1. Flash latest Raspbian onto SD card, setup SSH and WiFi on /boot.
2. Log in via SSH, run apt-get update & apt-get upgrade.
3. Run the LTS installer script from https://github.com/sdesalas/node-pi-zero
4. Download room-assistant via git clone
5. Run npm install
6. Setup config as described in Wiki
7. Optional: if you want to run Bluetooth stuff install the needed libraries as described in the Wiki, also run the setcap command from there
8. Run npm start

Could you maybe provide me with the errors you're receiving?

**Comment by getsmokes** [comment]
> @getsmokes I've just recently installed it on 3 Pi Zero Ws and didn't run into any particular issues.
> 
> My process was:
> 
> 1. Flash latest Raspbian onto SD card, setup SSH and WiFi on /boot.
> 2. Log in via SSH, run apt-get update & apt-get upgrade.
> 3. Run the LTS installer script from https://github.com/sdesalas/node-pi-zero
> 4. Download room-assistant via git clone
> 5. Run npm install
> 6. Setup config as described in Wiki
> 7. Optional: if you want to run Bluetooth stuff install the needed libraries as described in the Wiki, also run the setcap command from there
> 8. Run npm start
> 
> Could you maybe provide me with the errors you're receiving?

I've tried the steps you outlined twice, both ties getting the same error. 

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.66+
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/room-assistant/node_modules/ffi
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.
