### ISSUE TITLE
BluetoothService resetting very often

### ISSUE THREAD

**Issue by corgan2222** [mKeRix/room-assistant#651]
Hello

RA Leader in the Office entrance:
Ra installed as Home Assistant Addon resets every few seconds, if there is now BLE device found.
Is this a normal behavior? Could not find anything about resetting in the wiki?

![grafik](https://user-images.githubusercontent.com/12233951/114854516-31974180-9de5-11eb-9371-ea1a4cd64b86.png)

One Node installed in the front of the building gets all BLE peripherals from all people crossing. Can this be limited to only track our devices?

![grafik](https://user-images.githubusercontent.com/12233951/114854446-204e3500-9de5-11eb-98d3-c6cbe0a28bef.png)

Config 

> global:
>   instanceName: flur
>   integrations:
>     - bluetoothLowEnergy
>     - homeAssistant
> 
> cluster:
>   port: 6425
>   weight: 10
>   peerAddresses:
>     - 192.168.2.xx
>     - 192.168.3.xx
>     - 192.168.2.xx
> 
> bluetoothLowEnergy:
>   timeout: 5
>   updateFrequency: 2
>   allowlist:
>   - '4FD90C36-xx'
>   - '9fc0822c689cxx'
>   - 'xxx'
>   - 'xxx'
>   tagOverrides:
>     4FD90C36-xx:
>       name: BLE_RA_Stefan_Beacon
>     9fc0822c689xx:
>       name: BLE_RA_Steffi_Beacon
>     3C2EFF1F9481:
>       name: BLA_RA_Stefan_iPhone2

**Comment by mKeRix** [comment]
The resetting was introduced as a recovery behavior, as sometimes the Bluetooth adapter stops responding on Linux. room-assistant then catches these by examining of any advertisements were reported, if not it resets the adapter in the hope that it will wake the adapter up again. If you see it spammed like this it suggests that the Bluetooth Low Energy scanning isn't starting properly...usually it does after a little while, but if not a reboot fixes it. Is this a common unrecoverable issue for you?

As for limiting the tracking - RA will log all passing devices, but won't actually do anything with them unless they are on the allowlist. Is that already enough for you, or would you rather not have the log messages for devices not on the allowlist?

**Comment by corgan2222** [comment]
i did not monitor this problem for some time, but actually this seems some kind of broken.
The BT restart comes around every 15 seconds. It looks like the next restart comes before the raspberry bt chip is coming back to life.

Would it be possible to add on option how often the restart could run?

![grafik](https://user-images.githubusercontent.com/12233951/118727707-7a527800-b833-11eb-96ed-57c11c328033.png)

**Comment by corgan2222** [comment]
dmesg error Hardware name: BCM2711

![grafik](https://user-images.githubusercontent.com/12233951/118728111-02d11880-b834-11eb-956c-82986f0693c4.png)
