### ISSUE TITLE
Connection Error in Browser Feature of Companion App

### ISSUE THREAD

**Issue by haltug** [mKeRix/room-assistant#710]
**Describe the bug**
Checking real time updates of entities does not work in Companion App. Opening an instance leads to the error message 'Connection Error' although the API works over any browser and the phone has access over wifi. Click on 'Cancel' returns to list of instances.

**To reproduce**
Add ip address of instance in Companion App (Iphone), ex. '192.168.10.75:6415', and open instance. Error message pops up right away.

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```
![IMG_3F43681B4F28-1](https://user-images.githubusercontent.com/5527934/119120171-3ffffb00-ba2c-11eb-96a9-826831ed3903.jpeg)

```

**Expected behavior**
Values of entities are shown in instance browser

**Environment**
 - room-assistant version: 2.16.0
 - installation type: NodeJS 
 - hardware: Raspberry Pi Zero W
 - OS: Linux

**Comment by haltug** [comment]
Updated to 2.17.0 and works now. A small hint somewhere would have been helpful.

**Comment by mKeRix** [comment]
Glad to see that you were able to figure it out on your own - you are right, this requirements is very hidden and wasn't mentioned anywhere. I've added a note to the documentation now.
