### ISSUE TITLE
Smartwatch support

### ISSUE THREAD

**Issue by deece** [mKeRix/room-assistant#72]
It seems that the Trackers section of README.md was lost during the rewrite.

The documentation mentions smartwatches, but I'm having trouble finding a suitable android wear app. Do you have any recommendations?

**Comment by mKeRix** [comment]
Everything regarding trackers and other configuration has moved to the [wiki](https://github.com/mKeRix/room-assistant/wiki/Configuration). I don't own any Android Wear device, so I can't give any recommendation there - but depending on the watch you might not need an app. Most watches broadcast some sort of BLE signal that room-assistant can pick up on their own - unfortunately some only do it when they are not connected to any phone or do it via a scrambled ID (for good reasons, just not good for room-assistant). What kind of watch are you using?
