### ISSUE TITLE
Dependencies X-Server?

### ISSUE THREAD

**Issue by corgan2222** [mKeRix/room-assistant#735]
Today i wanted to debloat my raspberries with RA running. I was wondering why a X-Server was installed on the headless running pi-zeros.

In the manual i found these Dependencies to install before installing RA. These packages forcing apt to install the complete x-server stack with 
libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

> Die folgenden zusätzlichen Pakete werden installiert:
  fontconfig fontconfig-config fonts-dejavu-core gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-harfbuzz-0.0 gir1.2-pango-1.0 gir1.2-rsvg-2.0 icu-devtools libcairo-gobject2 libcairo-script-interpreter2 libcairo2 libdatrie1
  libfontconfig1 libfontconfig1-dev libfribidi-dev libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgdk-pixbuf2.0-dev libgif7 libgraphite2-3 libgraphite2-dev libharfbuzz-dev libharfbuzz-gobject0 libharfbuzz-icu0
  libharfbuzz0b libice-dev libice6 libicu-dev libjpeg62-turbo-dev liblzo2-2 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpangoxft-1.0-0 libpixman-1-0 libpixman-1-dev libpthread-stubs0-dev librsvg2-2 librsvg2-common libsm-dev
  libsm6 libthai-data libthai0 libx11-6 libx11-data libx11-dev libxau-dev libxau6 libxcb-render0 libxcb-render0-dev libxcb-shm0 libxcb-shm0-dev libxcb1 libxcb1-dev libxdmcp-dev libxdmcp6 libxext-dev libxext6 libxft-dev libxft2
  libxrender-dev libxrender1 pango1.0-tools x11-common x11proto-core-dev x11proto-dev x11proto-xext-dev xorg-sgml-doctools xtrans-dev
Vorgeschlagene Pakete:
  libcairo2-doc libgraphite2-utils libice-doc icu-doc imagemagick libpango1.0-doc librsvg2-bin librsvg2-doc libsm-doc libx11-doc libxcb-doc libxext-doc
Die folgenden NEUEN Pakete werden installiert:
  fontconfig fontconfig-config fonts-dejavu-core gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-harfbuzz-0.0 gir1.2-pango-1.0 gir1.2-rsvg-2.0 icu-devtools libcairo-gobject2 libcairo-script-interpreter2 libcairo2 libcairo2-dev libdatrie1
  libfontconfig1 libfontconfig1-dev libfribidi-dev libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgdk-pixbuf2.0-dev libgif-dev libgif7 libgraphite2-3 libgraphite2-dev libharfbuzz-dev libharfbuzz-gobject0
  libharfbuzz-icu0 libharfbuzz0b libice-dev libice6 libicu-dev libjpeg-dev libjpeg62-turbo-dev liblzo2-2 libpango-1.0-0 libpango1.0-dev libpangocairo-1.0-0 libpangoft2-1.0-0 libpangoxft-1.0-0 libpixman-1-0 libpixman-1-dev
  libpthread-stubs0-dev librsvg2-2 librsvg2-common librsvg2-dev libsm-dev libsm6 libthai-data libthai0 libx11-6 libx11-data libx11-dev libxau-dev libxau6 libxcb-render0 libxcb-render0-dev libxcb-shm0 libxcb-shm0-dev libxcb1 libxcb1-dev
  libxdmcp-dev libxdmcp6 libxext-dev libxext6 libxft-dev libxft2 libxrender-dev libxrender1 pango1.0-tools x11-common x11proto-core-dev x11proto-dev x11proto-xext-dev xorg-sgml-doctools xtrans-dev
0 aktualisiert, 76 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen noch 23,8 MB von 26,2 MB an Archiven heruntergeladen werden.

I searched for these packages, and they are for handling image and font stuff. I can run RA without the x-server and these packages . So what I'm missing here? Do we need these packages for anything?

**Comment by mKeRix** [comment]
They're only needed for rendering heat maps in the thermopile integrations (D6T and Grid-EYE). The dependency used in the current version of RA is a native dependency, which unfortunately provides no pre-compiled binary for the Zero processor architecture (hence the lib packages are needed to compile locally). You can choose to just leave those away, RA will function completely fine without it unless you need that one specific feature.

If you have an idea of how we could handle or document this better feel free to express them here :)

**Comment by corgan2222** [comment]
for me under the latest raspion os RA runs fine with the following
so maybe change to docs to

We need to install some other dependencies as well, do so by running 
`sudo apt-get update && sudo apt-get install build-essential libavahi-compat-libdnssd-dev libsystemd-dev bluetooth libbluetooth-dev libudev-dev `

If needed heat maps in the thermopile integrations (D6T and Grid-EYE):
`apt-get install libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`
