### ISSUE TITLE
Possibility to respond to "name" request?

### ISSUE THREAD

**Issue by frdmn** [mKeRix/room-assistant#74]
I noticed that "[monitor](https://github.com/andrewjfreyer/monitor)" and "[presence](https://github.com/andrewjfreyer/presence)" are able to track (Apple) devices and get around the address randomisation by sending a "name" request.

Is that possible to implement in room-assistant as well?

**Comment by frdmn** [comment]
Hi Heiko, 

thanks for the reply - hope you had a merry christmas! 🎄

This sounds indeed really interesting! If you still have the source laying around for this adjustment I would appreciate if you could release that to tinker around with it a bit more.

The distance part could be a problem for my use-case though, since I have two probe device in two rooms right next to each other so usually both probe devices always see the devices in question to track.

Thank you for working on this 😊

**Comment by mKeRix** [comment]
Just so you know: haven't forgotten about this, January is just full of deadlines for me. Will make a branch to test this available asap and then update in here again.

**Comment by mKeRix** [comment]
Closing in favor of #44 - forgot to update here, but just using name requests turned out to not be a reliable source of determining distance. I've figured out a different way to will allow for the same use case, see the beta posted in the other ticket.
