### ISSUE TITLE
BT Classic distance measurements change too slowly

### ISSUE THREAD

**Issue by mKeRix** [mKeRix/room-assistant#775]
The current Kalman filter configuration for BT Classic acts too slow when moving large distances. This appeared after the filter values were tuned in a recent version.

More info: #774

**Comment by bobonthenet** [comment]
Does this same issue impact Bluetooth Low Energy? I'm experiencing extremely slow changes over long distances. Going from say 20 meters to 1 meter can take several minutes. I'm only using the BLE integration though.

**Comment by W4rthog** [comment]
I was just looking at the data coming from 4 different nodes and they seem to be slowly drifting when the device is moved and it can take the nodes a couple minutes even to stabilise on the correct value.

**Comment by bobonthenet** [comment]
@W4rthog is that for classic or BLE?

**Comment by W4rthog** [comment]
@bobonthenet Sorry, that's BT Classic as per the issue
I had a quick look and yeah it looks like the Kalman filter is just causing said drift.
I moved my phone from one room to another.
RSSI used to be around -6 now it's 4 when read directly.
My distance is falling slowly but steadily and it takes like 5 minutes to stabilize
![image](https://user-images.githubusercontent.com/14827225/145246196-be3a3761-3d6a-4dbf-95c2-33ed6d8756a2.png)
@mKeRix  Any chance we could get some parameters to configure the filter ourselves or at least option disable it? Or maybe just expose the raw RSSI over the API as well?

**Comment by siiiilky** [comment]
Same issue here, any ideas on a fix for this?
