### ISSUE TITLE
Room Assistant Raspberry Pi Zero W and MQTT server on HA via SSL not sending

### ISSUE THREAD

**Issue by gregma** [mKeRix/room-assistant#78]
I am having a heck of a time getting Room Assistant to send to my hassio MQTT server. My MQTT server is at 192.168.1.100 and has SSL turned on. Many things already connect and send things to it successfully. I’ve installed Room Assistant on a Raspberry Pi Zero W and set it all up, but it’s not sending anything to the MQTT server. Here is my config at ~/room-assistant/config/local.json (I’ve also tried mqtt: instead of mqtts: with the same results. Nothing ever appears to be sent. I thought adding the “console” service would display debugging information to the SSH console, but nothing is seen at all. What am I missing? A status gives this:

pi@raspberrypi:~/room-assistant $ systemctl status room-assistant.service
room-assistant.service - Room Assistant service
Loaded: loaded (/etc/systemd/system/room-assistant.service; enabled; vendor preset: enabled)
Active: activating (auto-restart) since Tue 2019-01-22 23:44:49 GMT; 4s ago
Process: 1993 ExecStart=/usr/bin/npm start (code=exited, status=0/SUCCESS)
Main PID: 1993 (code=exited, status=0/SUCCESS)

Here is the config/local.json:

`{
  "services": ["console", "mqtt", "ble"],
  "room": "living-room",
  "autoDiscovery": true,
  "mqtt": {
    "url": "mqtts://192.168.1.100",
    "username": {redacted username},
    "password":{redacted password},
    "rejectUnauthorized": false
  },
  "ble": {
    "channel": "room_presence",
    "useAddress": true,
    "whitelist": [],
    "whitelistRegex": false,
    "txPowerOverride": {},
    "maxDistance": 0,
    "updateFrequency": 0,
    "processIBeacon": true,
    "onlyIBeacon": false,
    "majorMask": "0xFFFF",
    "minorMask": "0xFFFF"
  },
  "d6t": [],
  "gpio": [],
  "shell": [],
  "prometheus": []
}`

**Comment by gbdavidx** [comment]
how do you get npm version higher then 5.6 installed? it keeps saying it's the latest version...

**Comment by BlueBlueBlob** [comment]
@gbdavidx npm install -g npm@latest

**Comment by mKeRix** [comment]
Should this still be an issue (and I'm assuming it's not, but still): could you turn off the service and run room-assistant manually using `npm start` in the installation folder? This should give you the debug output you're looking for, then we'll hopefully have some kind of error to work with

**Comment by ktpx** [comment]
How about a guide to install this? It never works, have tried on many machines.  npm must be the worst installer, ever.
