### ISSUE TITLE
Can Not Run as  a Service

### ISSUE THREAD

**Issue by jrtaaffe** [mKeRix/room-assistant#79]
I get the following error when trying to run room-assistant as a service:

Feb 15 19:10:24 fireball npm[21596]: Now installing: @abandonware/noble@1.9.2-1
Feb 15 19:10:25 fireball npm[21596]: { Error: Method Not Allowed
Feb 15 19:10:25 fireball npm[21596]:     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
Feb 15 19:10:25 fireball npm[21596]:     at /usr/share/npm/lib/cache/add-named.js:120:12
Feb 15 19:10:25 fireball npm[21596]:     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
Feb 15 19:10:25 fireball npm[21596]:     at FSReqWrap.oncomplete (fs.js:135:15)
Feb 15 19:10:25 fireball npm[21596]:   statusCode: 405,
Feb 15 19:10:25 fireball npm[21596]:   code: 'E405',
Feb 15 19:10:25 fireball npm[21596]:   pkgid: 'abandonware/noble',
Feb 15 19:10:25 fireball npm[21596]:   parent: 'room-assistant' }

**Comment by jrtaaffe** [comment]
When started through the terminal, everything is fine.  But as a service, the previous error occurs when running both as pi or as root.

**Comment by mKeRix** [comment]
Are you running room-assistant on a machine where a proxy is required to access the Internet by any chance? This seems like an issue with connection to the npm servers during the install process.

Although technically it shouldn't need to install anything anymore once you've run it successfully once.

**Comment by DieterClaeys** [comment]
Same here - can run everything fine with a manual start, but using the Autorun script gives me below info:
● room-assistant.service - Room Assistant service
   Loaded: loaded (/etc/systemd/system/room-assistant.service; enabled; vendor preset: enabl
   Active: activating (auto-restart) (Result: exit-code) since Sun 2019-08-04 12:43:21 CEST;
  Process: 501 ExecStart=/usr/bin/npm start (code=exited, status=203/EXEC)
 Main PID: 501 (code=exited, status=203/EXEC)

**Comment by mKeRix** [comment]
@DieterClaeys could you provide the logs from `journalctl -u room-assistant`?

**Comment by DieterClaeys** [comment]
-- Logs begin at Sun 2019-08-04 15:17:03 CEST, end at Sun 2019-08-04
20:18:04 CE
Aug 04 15:40:43 raspberrypi systemd[1]: Started Room Assistant service.
Aug 04 15:40:43 raspberrypi systemd[289]: room-assistant.service: Failed to
exec
Aug 04 15:40:44 raspberrypi systemd[289]: room-assistant.service: Failed at
step
Aug 04 15:40:45 raspberrypi systemd[1]: room-assistant.service: Main
process exi
Aug 04 15:40:45 raspberrypi systemd[1]: room-assistant.service: Failed with
resu
Aug 04 15:40:55 raspberrypi systemd[1]: room-assistant.service: Service
RestartS
Aug 04 15:40:55 raspberrypi systemd[1]: room-assistant.service: Scheduled
restar
Aug 04 15:40:55 raspberrypi systemd[1]: Stopped Room Assistant service.
Aug 04 15:40:55 raspberrypi systemd[1]: Started Room Assistant service.
Aug 04 15:40:55 raspberrypi systemd[411]: room-assistant.service: Failed to
exec
Aug 04 15:40:55 raspberrypi systemd[411]: room-assistant.service: Failed at
step
Aug 04 15:40:55 raspberrypi systemd[1]: room-assistant.service: Main
process exi
Aug 04 15:40:55 raspberrypi systemd[1]: room-assistant.service: Failed with
resu
Aug 04 15:41:05 raspberrypi systemd[1]: room-assistant.service: Service
RestartS
Aug 04 15:41:05 raspberrypi systemd[1]: room-assistant.service: Scheduled
restar
Aug 04 15:41:05 raspberrypi systemd[1]: Stopped Room Assistant service.
Aug 04 15:41:05 raspberrypi systemd[1]: Started Room Assistant service.
Aug 04 15:41:05 raspberrypi systemd[412]: room-assistant.service: Failed to
exec
Aug 04 15:41:05 raspberrypi systemd[412]: room-assistant.service: Failed at
step
Aug 04 15:41:05 raspberrypi systemd[1]: room-assistant.service: Main
process exi
Aug 04 15:41:05 raspberrypi systemd[1]: room-assistant.service: Failed with
resu
Aug 04 19:58:24 raspberrypi systemd[1]: room-assistant.service: Service
RestartS
lines 1-23
-- Logs begin at Sun 2019-08-04 15:17:03 CEST, end at Sun 2019-08-04
20:18:04 CEST. --
Aug 04 15:40:43 raspberrypi systemd[1]: Started Room Assistant service.
Aug 04 15:40:43 raspberrypi systemd[289]: room-assistant.service: Failed to
execute command: No such file or directory
Aug 04 15:40:44 raspberrypi systemd[289]: room-assistant.service: Failed at
step EXEC spawning /usr/bin/npm: No such file or directory
Aug 04 15:40:45 raspberrypi systemd[1]: room-assistant.service: Main
process exited, code=exited, status=203/EXEC
Aug 04 15:40:45 raspberrypi systemd[1]: room-assistant.service: Failed with
result 'exit-code'.
Aug 04 15:40:55 raspberrypi systemd[1]: room-assistant.service: Service
RestartSec=10s expired, scheduling restart.
Aug 04 15:40:55 raspberrypi systemd[1]: room-assistant.service: Scheduled
restart job, restart counter is at 1.
Aug 04 15:40:55 raspberrypi systemd[1]: Stopped Room Assistant service.
Aug 04 15:40:55 raspberrypi systemd[1]: Started Room Assistant service.
Aug 04 15:40:55 raspberrypi systemd[411]: room-assistant.service: Failed to
execute command: No such file or directory
Aug 04 15:40:55 raspberrypi systemd[411]: room-assistant.service: Failed at
step EXEC spawning /usr/bin/npm: No such file or directory
Aug 04 15:40:55 raspberrypi systemd[1]: room-assistant.service: Main
process exited, code=exited, status=203/EXEC
Aug 04 15:40:55 raspberrypi systemd[1]: room-assistant.service: Failed with
result 'exit-code'.
Aug 04 15:41:05 raspberrypi systemd[1]: room-assistant.service: Service
RestartSec=10s expired, scheduling restart.
Aug 04 15:41:05 raspberrypi systemd[1]: room-assistant.service: Scheduled
restart job, restart counter is at 2.
Aug 04 15:41:05 raspberrypi systemd[1]: Stopped Room Assistant service.
Aug 04 15:41:05 raspberrypi systemd[1]: Started Room Assistant service.
Aug 04 15:41:05 raspberrypi systemd[412]: room-assistant.service: Failed to
execute command: No such file or directory
Aug 04 15:41:05 raspberrypi systemd[412]: room-assistant.service: Failed at
step EXEC spawning /usr/bin/npm: No such file or directory
Aug 04 15:41:05 raspberrypi systemd[1]: room-assistant.service: Main
process exited, code=exited, status=203/EXEC
Aug 04 15:41:05 raspberrypi systemd[1]: room-assistant.service: Failed with
result 'exit-code'.
Aug 04 19:58:24 raspberrypi systemd[1]: room-assistant.service: Service
RestartSec=10s expired, scheduling restart.
lines 1-23...skipping...
-- Logs begin at Sun 2019-08-04 15:17:03 CEST, end at Sun 2019-08-04
20:18:04 CEST. --
Aug 04 15:40:43 raspberrypi systemd[1]: Started Room Assistant service.
Aug 04 15:40:43 raspberrypi systemd[289]: room-assistant.service: Failed to
execute command: No such file or directory
Aug 04 15:40:44 raspberrypi systemd[289]: room-assistant.service: Failed at
step EXEC spawning /usr/bin/npm: No such file or directory
Aug 04 15:40:45 raspberrypi systemd[1]: room-assistant.service: Main
process exited, code=exited, status=203/EXEC
Aug 04 15:40:45 raspberrypi systemd[1]: room-assistant.service: Failed with
result 'exit-code'.
Aug 04 15:40:55 raspberrypi systemd[1]: room-assistant.service: Service
RestartSec=10s expired, scheduling restart.
Aug 04 15:40:55 raspberrypi systemd[1]: room-assistant.service: Scheduled
restart job, restart counter is at 1.
Aug 04 15:40:55 raspberrypi systemd[1]: Stopped Room Assistant service.
Aug 04 15:40:55 raspberrypi systemd[1]: Started Room Assistant service.
Aug 04 15:40:55 raspberrypi systemd[411]: room-assistant.service: Failed to
execute command: No such file or directory
Aug 04 15:40:55 raspberrypi systemd[411]: room-assistant.service: Failed at
step EXEC spawning /usr/bin/npm: No such file or directory
Aug 04 15:40:55 raspberrypi systemd[1]: room-assistant.service: Main
process exited, code=exited, status=203/EXEC
Aug 04 15:40:55 raspberrypi systemd[1]: room-assistant.service: Failed with
result 'exit-code'.
Aug 04 15:41:05 raspberrypi systemd[1]: room-assistant.service: Service
RestartSec=10s expired, scheduling restart.
Aug 04 15:41:05 raspberrypi systemd[1]: room-assistant.service: Scheduled
restart job, restart counter is at 2.
Aug 04 15:41:05 raspberrypi systemd[1]: Stopped Room Assistant service.
Aug 04 15:41:05 raspberrypi systemd[1]: Started Room Assistant service.
Aug 04 15:41:05 raspberrypi systemd[412]: room-assistant.service: Failed to
execute command: No such file or directory
Aug 04 15:41:05 raspberrypi systemd[412]: room-assistant.service: Failed at
step EXEC spawning /usr/bin/npm: No such file or directory
Aug 04 15:41:05 raspberrypi systemd[1]: room-assistant.service: Main
process exited, code=exited, status=203/EXEC
Aug 04 15:41:05 raspberrypi systemd[1]: room-assistant.service: Failed with
result 'exit-code'.
Aug 04 19:58:24 raspberrypi systemd[1]: room-assistant.service: Service
RestartSec=10s expired, scheduling restart.
Aug 04 19:58:25 raspberrypi systemd[1]: room-assistant.service: Scheduled
restart job, restart counter is at 3.
Aug 04 19:58:25 raspberrypi systemd[1]: Stopped Room Assistant service.
Aug 04 19:58:25 raspberrypi systemd[1]: Started Room Assistant service.
Aug 04 19:58:25 raspberrypi systemd[413]: room-assistant.service: Failed to
execute command: No such file or directory
Aug 04 19:58:25 raspberrypi systemd[413]: room-assistant.service: Failed at
step EXEC spawning /usr/bin/npm: No such file or directory
Aug 04 19:58:25 raspberrypi systemd[1]: room-assistant.service: Main
process exited, code=exited, status=203/EXEC
Aug 04 19:58:25 raspberrypi systemd[1]: room-assistant.service: Failed with
result 'exit-code'.
Aug 04 19:58:35 raspberrypi systemd[1]: room-assistant.service: Service
RestartSec=10s expired, scheduling restart.
Aug 04 19:58:35 raspberrypi systemd[1]: room-assistant.service: Scheduled
restart job, restart counter is at 4.
Aug 04 19:58:35 raspberrypi systemd[1]: Stopped Room Assistant service.
Aug 04 19:58:35 raspberrypi systemd[1]: Started Room Assistant service.
Aug 04 19:58:35 raspberrypi systemd[416]: room-assistant.service: Failed to
execute command: No such file or directory
Aug 04 19:58:35 raspberrypi systemd[416]: room-assistant.service: Failed at
step EXEC spawning /usr/bin/npm: No such file or directory
Aug 04 19:58:35 raspberrypi systemd[1]: room-assistant.service: Main
process exited, code=exited, status=203/EXEC
Aug 04 19:58:35 raspberrypi systemd[1]: room-assistant.service: Failed with
result 'exit-code'.
Aug 04 19:58:45 raspberrypi systemd[1]: room-assistant.service: Service
RestartSec=10s expired, scheduling restart.

**Comment by mKeRix** [comment]
I believe your issue is this one:

`Failed at step EXEC spawning /usr/bin/npm: No such file or directory`

You need to have npm installed globally and linked in `/usr/bin/npm`. Using the official [NodeJS 10](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions) installation you should already have this by default. What is the output of `which npm`?

**Comment by DieterClaeys** [comment]
I’ll start all over from scratch again tomorrow.
