### ISSUE TITLE
Randomly Disconnecting From All of My Devices

### ISSUE THREAD

**Issue by Ben10lightningx** [mKeRix/room-assistant#814]
**Describe the bug**
I will be sitting in my room for a while and then randomly at the exact same time room assistant says my phone and watch are not in the room anymore when they have not moved from when it said they were in the room. This seems to happen after room assistant has been running for more than a few hours and is fixed by rebooting.

**To reproduce**
Steps required to reproduce the issue. Have room assistant running for a few hours

**Relevant logs**
-- Logs begin at Mon 2021-07-12 17:28:13 BST, end at Tue 2021-07-13 05:09:42 BST. --
Jul 12 17:28:31 RoomAssistantBensRoom systemd[1]: Started room-assistant service.
Jul 12 17:28:50 RoomAssistantBensRoom room-assistant[321]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Jul 12 17:28:50 RoomAssistantBensRoom room-assistant[321]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jul 12 17:28:50 RoomAssistantBensRoom room-assistant[321]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Jul 12 17:28:50 RoomAssistantBensRoom room-assistant[321]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Jul 12 17:28:50 RoomAssistantBensRoom room-assistant[321]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jul 12 17:28:50 RoomAssistantBensRoom room-assistant[321]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Jul 12 17:28:50 RoomAssistantBensRoom node[321]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Jul 12 17:28:50 RoomAssistantBensRoom node[321]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jul 12 17:28:50 RoomAssistantBensRoom node[321]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Jul 12 17:28:50 RoomAssistantBensRoom node[321]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Jul 12 17:28:50 RoomAssistantBensRoom node[321]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jul 12 17:28:50 RoomAssistantBensRoom node[321]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Jul 12 17:28:56 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:28:55 - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-classic
Jul 12 17:29:17 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:17 - info - NestFactory: Starting Nest application...
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: AppModule dependencies initialized
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: ConfigModule dependencies initialized
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: NestEmitterModule dependencies initialized
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: IntegrationsModule dependencies initialized
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: HttpModule dependencies initialized
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: DiscoveryModule dependencies initialized
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: PrometheusModule dependencies initialized
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: EventsModule dependencies initialized
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: ClusterModule dependencies initialized
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: TerminusModule dependencies initialized
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: ScheduleModule dependencies initialized
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: BluetoothModule dependencies initialized
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: EntitiesModule dependencies initialized
Jul 12 17:29:18 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:18 - info - InstanceLoader: BluetoothClassicModule dependencies initialized
Jul 12 17:29:19 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:19 - info - InstanceLoader: HomeAssistantModule dependencies initialized
Jul 12 17:29:19 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:19 - info - InstanceLoader: StatusModule dependencies initialized
Jul 12 17:29:22 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:22 - info - RoutesResolver: EntitiesController {/entities}:
Jul 12 17:29:22 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:22 - info - RouterExplorer: Mapped {/entities, GET} route
Jul 12 17:29:22 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:22 - info - RoutesResolver: StatusController {/status}:
Jul 12 17:29:22 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:22 - info - RouterExplorer: Mapped {/status, GET} route
Jul 12 17:29:22 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:22 - info - RoutesResolver: PrometheusController {/metrics}:
Jul 12 17:29:22 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:22 - info - RouterExplorer: Mapped {/metrics, GET} route
Jul 12 17:29:25 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:25 - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://192.168.3.40:1883
Jul 12 17:29:25 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:25 - info - ConfigService: Loading configuration from /opt/nodejs/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/local.yml (Current:
Jul 12 17:29:26 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:26 - error - ConfigService: "global.cluster" is not allowed [Value: {"autoDiscovery":true,"port":6425}].
Jul 12 17:29:26 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:26 - info - ClusterService: Starting mDNS advertisements and discovery
Jul 12 17:29:26 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:29:26 - info - NestApplication: Nest application successfully started
Jul 12 17:58:10 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:58:10 - error - ClusterService: getaddrinfo -3008
Jul 12 17:58:19 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 17:58:19 - error - ClusterService: getaddrinfo -3008
Jul 12 18:06:10 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 18:06:10 - error - ClusterService: getaddrinfo -3008
Jul 12 18:06:39 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 18:06:39 - error - ClusterService: getaddrinfo -3008
Jul 12 18:14:57 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 18:14:57 - error - ClusterService: getaddrinfo -3008
Jul 12 18:22:08 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 18:22:08 - error - ClusterService: getaddrinfo -3008
Jul 12 18:22:20 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 18:22:20 - error - ClusterService: getaddrinfo -3008
Jul 12 18:34:28 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 18:34:28 - error - ClusterService: getaddrinfo -3008
Jul 12 18:34:40 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 18:34:40 - error - ClusterService: getaddrinfo -3008
Jul 12 19:00:40 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 19:00:40 - error - ClusterService: getaddrinfo -3008
Jul 12 19:04:17 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 19:04:17 - error - ClusterService: getaddrinfo -3008
Jul 12 19:17:38 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 19:17:38 - error - ClusterService: getaddrinfo -3008
Jul 12 19:17:42 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 19:17:42 - error - ClusterService: getaddrinfo -3008
Jul 12 19:28:19 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 19:28:19 - error - ClusterService: getaddrinfo -3008
Jul 12 20:54:28 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 20:54:28 - error - ClusterService: getaddrinfo -3008
Jul 12 20:54:35 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 20:54:35 - error - ClusterService: getaddrinfo -3008
Jul 12 21:22:27 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 21:22:27 - error - ClusterService: getaddrinfo -3008
Jul 12 21:22:35 RoomAssistantBensRoom room-assistant[321]: 12/07/2021, 21:22:35 - error - ClusterService: getaddrinfo -3008
Jul 13 00:01:55 RoomAssistantBensRoom room-assistant[321]: 13/07/2021, 00:01:55 - error - ClusterService: getaddrinfo -3008
Jul 13 00:02:06 RoomAssistantBensRoom room-assistant[321]: 13/07/2021, 00:02:06 - error - ClusterService: getaddrinfo -3008
Jul 13 00:27:31 RoomAssistantBensRoom room-assistant[321]: 13/07/2021, 00:27:31 - error - ClusterService: getaddrinfo -3008
Jul 13 00:27:40 RoomAssistantBensRoom room-assistant[321]: 13/07/2021, 00:27:40 - error - ClusterService: getaddrinfo -3008

**Relevant configuration**
Paste the relevant parts of your configuration below.

global:
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://homeassistant.local:1883'
  mqttOptions:
    username: youruser
    password: yourpass
bluetoothClassic:
  addresses:
    - mac address of my watch
    - mac address of phone

**Expected behavior**
I expected it to keep working 

**Environment**
 - room-assistant version: 2.18.4
 - installation type: NodeJS
 - hardware: Raspberry Pi 0W
 - OS: Raspberry Pi OS Lite

**Additional context**
My apple watch is a series 5 and my phone is an iPhone XR.

**Comment by MagicMountainMan** [comment]
I'm on the latest version as well and there seems be general stability issues with it. I have pretty much the same issues and I've seen other people post in the Discussions section about their stability problems lately. 

Hopefully a fix is issued at some point, but until then it's probably best to install an older version that's more stable.

**Comment by MagicMountainMan** [comment]
I've been on the beta for a few days now and it seems like that solved everything. Had to do a ton of updates just to load it on some of my Pi Zero W's but it seems like everything is stable for now.

**Comment by Ben10lightningx** [comment]
This may be a dumb question but how exactly do I upgrade to the beta? I did the update command and that put me on 2.18.4.

**Comment by MagicMountainMan** [comment]
> This may be a dumb question but how exactly do I upgrade to the beta? I did the update command and that put me on 2.18.4.

Try this:
```
sudo npm i --global --unsafe-perm room-assistant@beta
```
