### ISSUE TITLE
Finally got it working!!! However after i ended it and restarted it, it can't find mqtt???

### ISSUE THREAD

**Issue by gbdavidx** [mKeRix/room-assistant#82]
Also, how do you know the topic? is it the pi hostname/room level? so rasberrypi\downstairs?

[2019-03-15T05:35:17.716Z] INFO  raspberrypi-31720/D6T: Waiting for service(s) 'mqtt'...
Unable to find d6t device on any i2c bus
[2019-03-15T05:35:17.745Z] INFO  raspberrypi-31720/REGISTRY: 'mqtt' service is registered.
events.js:183
      throw er; // Unhandled 'error' event
      ^

these are the mqtt settings (its being hosted in a docker, which was working fine with other services)
```

  "options": {
    "services": [],
    "room": "downstairs",
    "mqtt": {
      "url": "mqtt://192.168.1.246:1883",
      "username": "",
      "password": "",
      "rejectUnauthorized": true
    },
    "ble": {

```

i do not have a username or password

**Comment by gbdavidx** [comment]
i definitely tried it without the port number

**Comment by gbdavidx** [comment]
hello???

**Comment by michaelarz** [comment]
Hi! Would this work?

  "mqtt": {
    "url": "mqtt://192.168.1.246",
    "username": "",
    "password": "",
    "reject_unauthorized": false,
    "topic": "home"
  }
