### ISSUE TITLE
Invalid Slug Name

### ISSUE THREAD

**Issue by asknoone** [mKeRix/room-assistant#83]
This is a request to change the slug from "room-assistant" to "room_assistant". It seems that slugs with a hyphen are invalid in Hassio.

Changing this would allow the use of the add-on services, e.g. hassio.addon_start.

The reason I came across this is because sometimes the add-on stops running so it would be useful to have an automation which restarts the add-on if it stops.

**Comment by mKeRix** [comment]
Thanks for the hint & sorry for the inconvenience. Wasn't aware of this guideline on the Hass.io side.

I will put this on my list for the next major release - I believe changing the slug would cause everyone to have to reinstall room-assistant. Not a major issue, but don't want to do require this on a minor upgrade.

**Comment by mKeRix** [comment]
Fixed with the release of 2.0!
