### ISSUE TITLE
WiFi RTT support

### ISSUE THREAD

**Issue by ikrowni** [mKeRix/room-assistant#85]
Could wifi RTT support be added to room assistant? I have plotted out the distances to each of my 3 AP's and now I'm looking for a way to use that data.

**Comment by mKeRix** [comment]
Correct me if I'm wrong, but wouldn't WiFi RTT be something that would need to be tracked via the portable device? So basically an Android app would need to be written that submits the data to somewhere (MQTT, Home Assistant or w/e). If so I would think that this is out of scope for room-assistant.
