### ISSUE TITLE
Cannot unlink errors when installing NodeJS on Pi Zero W

### ISSUE THREAD

**Issue by k41zen** [mKeRix/room-assistant#861]
**Describe the bug**
Getting the following unlink errors when executing the wget command from the documentation for Pi Zero W devices

**To reproduce**
wget command from documentation:

```wget -O - https://gist.githubusercontent.com/mKeRix/88b7b81e9bca044f74de1dc51696efb2/raw/799a20bca44cc61d8f8ae93878f2f28af8365a69/getNodeLTS.sh | bash```

**Relevant logs**
Unlink errors shown on stdout:

```2021-08-09 08:43:23 (2.66 MB/s) - ‘node-v14.17.4-linux-armv6l.tar.gz’ saved [32352925/32352925]

unlink: cannot unlink '/usr/sbin/node': No such file or directory
unlink: cannot unlink '/sbin/node': No such file or directory
unlink: cannot unlink '/usr/sbin/npm': No such file or directory
unlink: cannot unlink '/sbin/npm': No such file or directory
ln: failed to create symbolic link '/sbin/node': File exists
ln: failed to create symbolic link '/sbin/npm': File exists
```

**Relevant configuration**
N/A not getting that far

**Expected behavior**
The command to complete without errors so that I can continue through the documentation

**Environment**
 - installation type: NodeJS
 - hardware: Raspberry Pi Zero W
 - OS: Raspberry Pi OS (Lite)

**Additional context**
N/A

**Comment by mKeRix** [comment]
On initial installation these messages are completely normal, since the binary links don't exist yet. The installation should still continue and finish fine though - is that not the case for you?

**Comment by bigstation17** [comment]
I have the same problem, and i cannot complete install process: "SyntaxError: Unexpected token"
Raspberry Pi Zero W.
