### ISSUE TITLE
Support for long-term statistics

### ISSUE THREAD

**Issue by pmiguelcruz** [mKeRix/room-assistant#869]
**Describe the bug**
Xiaomi Mi Flora sensors don't show up for selection in the new [statistics UI card](https://www.home-assistant.io/integrations/statistics/)

**Environment**
 - room-assistant version: 2.18.4 and 3.0.0-beta.2
 - installation type: Hass.io and NodeJS
 - hardware: 1 Raspberry PI 4 (Hass.io) + 3 Raspberry Pi Zero W (Raspbian + NodeJS)

**Additional context**
Please see [https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)
And note for users: [https://www.home-assistant.io/more-info/statistics/](https://www.home-assistant.io/more-info/statistics/)
Noticed on HAS **core-2021.8.1** and **core-2021.8.5**
Defining state_class through entities customization doesn't seem to work

**Comment by JesusRo** [comment]
Same happening to me with LYWSD03MMC sensors
