### ISSUE TITLE
npm start *always* fails on node-gyp build

### ISSUE THREAD

**Issue by ktpx** [mKeRix/room-assistant#88]
I just cant get away from this: 

                            ^
In file included from ../src/ffi.h:23:0,
                 from ../src/ffi.cc:3:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
ffi_bindings.target.mk:108: recipe for target 'Release/obj.target/ffi_bindings/src/ffi.o' failed
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
make: Leaving directory '/home/thomas/room-assistant/node_modules/ffi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.66-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/thomas/room-assistant/node_modules/ffi
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.

{ Error: ffi@2.2.0 install: `node-gyp rebuild`
Exit status 1
    at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
    at EventEmitter.emit (events.js:198:13)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  cause:
   { Error: ffi@2.2.0 install: `node-gyp rebuild`
   Exit status 1
       at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
       at EventEmitter.emit (events.js:198:13)
       at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
       at ChildProcess.emit (events.js:198:13)
       at maybeClose (internal/child_process.js:982:16)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
     errno: 1,
     code: 'ELIFECYCLE',
     pkgid: 'ffi@2.2.0',
     stage: 'install',
     script: 'node-gyp rebuild',
     pkgname: 'ffi' },
  errno: 1,
  code: 'ELIFECYCLE',
  pkgid: 'ffi@2.2.0',
  stage: 'install',
  script: 'node-gyp rebuild',
  pkgname: 'ffi',
  parent: 'room-assistant' }

Have tried on multiple platforms, multiple versions, this is highly annoying.  Could someone shed some light on this?

Thanks

**Comment by mKeRix** [comment]
Two quick questions to help me understand:

- Are you running Node.js 10 LTS? (If not, which version are you running? v12 may have some issues, it's not officially supported since it's not LTS)
- Did you run the apt-get command from the [README](https://github.com/mKeRix/room-assistant#requirements)?

**Comment by ktpx** [comment]
Thanks was able to *finally* get it installed after trying several versions of nodejs.

**Comment by sanderjonkers** [comment]
> 
> 
> Thanks was able to _finally_ get it installed after trying several versions of nodejs.

I have the exact same issue, but I can't get it resolved. I've tried Nodejs v12, and now trying with Nodejs v10, but still the same failure on node-gyp build.

pi@RPI3Bplus:~/room-assistant $ node -v
v10.16.3
pi@RPI3Bplus:~/room-assistant $ npm -v
6.9.0
pi@RPI3Bplus:~/room-assistant $ sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev libusb-1.0-0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libudev-dev is already the newest version (232-25+deb9u12).
libusb-1.0-0-dev is already the newest version (2:1.0.21-1).
bluetooth is already the newest version (5.43-2+rpt2+deb9u2).
bluez is already the newest version (5.43-2+rpt2+deb9u2).
libbluetooth-dev is already the newest version (5.43-2+rpt2+deb9u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
