### ISSUE TITLE
how to get started

### ISSUE THREAD

**Issue by yajrendrag** [mKeRix/room-assistant#9]
i can't seem to connect all the dots to figure this out.  i have home assistant and an mqtt server running.

i have cell phones and a stack of Bluetooth beacons.

do i configure each cell phone in home assistant as an mqtt_room sensor?

then room-assistant's instructions say to have a user/password for each client/room.  do you duplicate the mqtt config section for each user?  if not, how do you configure multiple users? similarly do you duplicate the ble section for each room and is the whitelist the list of uuid's for beacons in each room?   if not, how do you configure multiple rooms?

then, how does association of the phone with a beacon cause an mqtt message to be sent?  is there another client required on the phone?

i'd like to try this solution, but i can't seem to figure out how all of the components will work together.

**Comment by mKeRix** [comment]
You have to configure each tag/phone as mqtt_room sensor within HASS using their Bluetooth ID. For the phones it's important to make sure they send BLE advertisement packages, otherwise this component may not work. A lot of phones stay hidden unless you download a virtual beacon app.

It's not necessarily needed to have separate users for each room, rather it's just good practice and prevents collision. This only applies for the room-assistant config though, the HASS config stays the same with just a single user. So basic config management is:
1. In HASS, configure MQTT once and the mqtt_room sensor for each beacon you want to track
2. In room-assistant, you can copy most config parts between each RPi/instance. The only party you definitely have to change is the MQTT topic option: this is used to identify which room the updates came from. If you have a lot of Bluetooth traffic the whitelist is nice to reduce the amount of messages being sent to the MQTT server.

The fundamental concept of this is that you have stationary scanners (e.g. Raspberry Pis) in each room, looking for the advertisement packages of the beacons. Then they broadcast the found beacons together with their calculated distance to the MQTT server. HASS picks up all those messages and compares the distances as well as the times the beacons were found. Using this comparison it determines the current location of the beacon.

I posted my basic setup and some example automations based on mqtt_room [here](https://www.reddit.com/r/homeassistant/comments/5jvwew/use_automation_triggers_with_home_zoning/dc5xgmw/?utm_content=permalink&utm_medium=user&utm_source=reddit&utm_name=frontpage), maybe reading that will help you understand this a bit more.

**Comment by yajrendrag** [comment]
thanks for this.  I was thinking stationary beacons, but this makes much more sense now.  (read thru the reddit post too). I have a couple of Intel nucs in several rooms with usb bluetooth so presuming they will be fine.  will an old rpi b work too?  or is that too underpowered to run the node.js app?

**Comment by mKeRix** [comment]
Those should work fine indeed! I have not actually tried this component on a Windows machine, but there is no platform specific code. If you run into issues we can figure them out together and document it for any other people on Windows.

This component only runs somewhat basic calculations, so the performance for the RPi B is more than enough. Pretty sure you could even run this on a Pi Zero, haha. :)

**Comment by yajrendrag** [comment]
actually, am running ubuntu 16.04 on the nucs... so got node.js installed on the nuc - i installed 6.5 - installed room assistant and all of the bluetooth items from your README.  i used the iogear usb 4.0 bluetooth device from table in your referenced post and configured my mqtt server with a new user..  i haven't done anything in home assistant yet.  i just want to see some mqtt traffic.   but am not seeing anything.  i am manually starting room-assistant and it seems to start fine.  logs show that it's connected to my mqtt server and the ble scanner was initialized.

running mosquitto_sub with a user permitted to subscribe to the room topic used by the nuc, am getting no traffic.  

i have a bunch of these:  [https://www.amazon.com/Altbeacon-iBeacon-Replaceable-Battery-Covering/dp/B01I57KMTI/ref=sr_1_1?ie=UTF8&qid=1486173303&sr=8-1-spons&keywords=altbeacon&psc=1](url) and also tried beacon toy on android..

any suggestions on what i may be doing wrong?

**Comment by mKeRix** [comment]
So far so good then! If you don't get any errors that means technically all should be working fine. Have you checked if the whitelist is empty? Apart from that maybe you can enable the console publisher just to see if the events really aren't fired or if they're just getting lost on their way to the server.
Sorry that it took me a while to reply.

**Comment by yajrendrag** [comment]
yes, the whitelist is empty.  enabling the console, i can see that it is working - all of the physical beacons i have activated are being picked up.  the phone app, beacontoy, however is not.  unless i can't decipher it's id.  the id that room-assistant seems to display is a mac address - correct?  i don't see the phone's bluetooth mac in any of the beacon's displayed.  beacontoy allows you to assign a name to the beacon and i don't see that either.

I have an ipad and did a similar thing with that using an app called Locate.  It's beacons are picked up either or again, i don't know how to identify them in the list.

but that issue aside, i should see mqtt traffic from the physical beacons it's finding.  and not seeing those for some reason.  i've got several mqtt apps up and running, so thinking i've either overlooked something really basic, or something else is going on...

any further thoughts?  also, can you suggest what android & ios beacon apps you found to work?

thanks!

**Comment by mKeRix** [comment]
On phones often times you can set the ID yourself in the app, at least on Android you can. The most recent app I used is called "Beacon Simulator", I forgot the other ones I also tried a while ago. But yeah, the ID used by room-assistant is the Bluetooth MAC that is being reported by the device. iOS sometimes randomizes the ID being sent, although I'm not sure of the specifics here. This might not be the case with some apps.

If you can't find it using the ble component you can try using the `ibeacon` component from PR #6, which is currently in the `dev` branch. Just run `git checkout dev` and follow the usual update procedure. The configuration options are similar to the Bluetooth component, you can see them under `ibeacon` [here](https://github.com/kdanthony/room-assistant/blob/db20312c7918069b047b164c79034d91e8012767/config/default.json). This user had a similar problem and his new component worked out for him.

As far as the MQTT traffic goes... if you don't see any errors it should be sent successfully. A key element that many overlook is that you have to subscribe to the **sub**topics of the configured one. Try subscribing to `room_presence/+` to get all of them. The logic here is that every room has its own topic, e.g. `room_presence/bedroom` and `room_presence/livingroom`.

**Comment by yajrendrag** [comment]
first, thanks for all you help and quick replies.  i had to resort to using the ibeacon component as you suggested - all of the virtual beacon apps - including beacon simulator - all randomize the mac address - at least on my galaxy s7.  

as far as the mqtt traffic - glad you pointed out the channel - i misinterpreted/overlooked that completely.  i was looking at only the topic config... once i added that into my mqtt acl properly - channel/topic/#, it all started working great.

one issue i think is a problem though - in the ibeacon component, the id in the whitelist can only be the beacon uuid.  you can't specify the full id of uuid-major-minor (which is what room-assistant reports as id and what shows up in mqtt too) - you can only whitelist the uuid.  easy enough to workaround for me, since i'm only going to use my phone as a beacon, but kind of defeats the purpose of making the id the combination of the 3 of them.

so, i think i'm set for now, thanks again!

**Comment by mKeRix** [comment]
Thanks for the hint with the whitelist, that's a great point. I sadly haven't managed to properly test that component yet so I that's very valuable feedback. I'll try to adjust this in the coming days. :)

Since you figured everything out I'll close this issue for now.

**Comment by mKeRix** [comment]
The whitelist issue regarding the iBeacon component should be fixed in the latest release btw. :)
