### ISSUE TITLE
Error when trying to update

### ISSUE THREAD

**Issue by gmalbert** [mKeRix/room-assistant#92]
I get the following error when I try to update according to the wiki instructions. When I do a git pull, I get the following error:

```
Updating a0eda1e..2dc53cd
error: Your local changes to the following files would be overwritten by merge:
        package-lock.json
Please commit your changes or stash them before you merge.
Aborting

```

**Comment by mKeRix** [comment]
Looks like the `package-lock.json` got changed by something - but no worries, you can just discard those changes without any impact to the software. Run `git checkout package-lock.json` and then you should be able to upgrade following the normal procedure. :)
