### ISSUE TITLE
Room Presence inconsistent - app shows wrong status in relation to reported meters

### ISSUE THREAD

**Issue by JeroenTuinstra** [mKeRix/room-assistant#931]
**Describe the bug**
The companion app will show that the BLE device is 0.0 meters from "office", yet will report not_home in the app and in Home Assistant. 

**To reproduce**
Install the node according to room-assistant.io with a the UART bluetooth enabled and the USB bluetooth enabled. UART is assigned hci1 and USB is assigned hci0. hci1 is used for Bluetooth Classic and hci0 is used for BLE. 

**Relevant logs**
The only errors that are shown are from the Bluetooth Classic. No further errors with the BLE. It discovers the app and reports to the app. The app shows the distance as 0.0 or a little more, yet the app reports not_home. 

```
BluetoothService: Locking adapter 1
27/09/2021, 22:47:34 - debug - BluetoothService: Querying for RSSI of 64:d2:c4:7a:72:c2 using hcitool
27/09/2021, 22:47:39 - debug - BluetoothService: Command failed: hcitool -i hci1 cc "64:d2:c4:7a:72:c2" && hcitool -i hci1 rssi "64:d2:c4:7a:72:c2"
Can't create connection: Input/output error
Get connection info failed: No such file or directory

27/09/2021, 22:47:39 - debug - BluetoothService: Unlocking adapter 1
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```cluster:
  port: 6415
  peerAddresses:
    - 192.168.10.77:6415
    - 192.168.10.78:6415
    - 192.168.10.80:6415
    - 192.168.10.84:6415
  autoDiscovery: true
  weight: 40
global:
  instanceName: office
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
    - bluetoothClassic
homeAssistant:
  mqttUrl: 'mqtt://192.168.10.2:1883'
  mqttOptions:
    username: **********
    password: **********
bluetoothLowEnergy:
  hciDeviceId: 0
  timeout: 60
  allowlist:
    - 354F360F-CBB4-4A37-8009-FB37B810DE47
    - B11C5139-F269-4454-8BCB-A046FB9FF797
  maxDistance: 5
  tagOverrides:
    354F360F-CBB4-4A37-8009-FB37B810DE47:
      name: Iphone Jeroen BLE
    B11C5139-F269-4454-8BCB-A046FB9FF797:
      name: Iphone Isaac BLE	
bluetoothClassic:
  hciDeviceId: 1
  minRssi: -5
  addresses:
    - '64:d2:c4:7a:72:c2'
  entityOverrides:
    '64:d2:c4:7a:72:c2':
      name: Apple Watch Jeroen BTC
```

**Expected behavior**
Expected when in the app distance is reported as "office: 0.0 m" that the app reports to Home Assistant and in its own app as "office" and not "not_home"

**Environment**
 - room-assistant version: 2.19.1 (I believe ... I don't know where to find this information)
 - installation type: NodeJS
 - hardware: Rapsberry Pi 4 & Pi 3 b+
 - OS: Raspberry Pi OS Lite - release date 2021-05-07 (fully updated after install)

**Additional context**
Perhaps I am doing something completely wrong, but it is too often now that lights switch off while I am still in the room/office and then to discover that Home Assistant says I am "not_home", the companion app says the same, yet the meters to the office are 0.0, within range.

**Comment by JeroenTuinstra** [comment]
Just to give an update ... if anyone is reading this ... I am using an Iphone 11 with ios 15.0.1. It seems as soon as the app is closed the status goes to "not-home", even if the entities page shows that the phone is closest to for example the livingroom. 

I've included here the entities status page, so you can see that the iphone distance is 1.4 and out-of-range is false, yet it reports "not-home". 

`
<html><body>
<div id="content"><div class="tabs "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item json is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"></div></div></div></div><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"><div class="devtools-separator"></div><input class="searchBox devtools-filterinput" placeholder="Filter JSON"></div><div class="panelContent">

  |  
-- | --
0 |  
attributes |  
nodes |  
0 | "bedroom"
1 | "office"
2 | "diningroom"
3 | "livingroom"
id | "status-cluster-size"
name | "livingroom Cluster Size"
distributed | false
stateLocked | true
state | 4
1 |  
attributes |  
quorumReached | true
id | "status-cluster-leader"
name | "livingroom Cluster Leader"
distributed | false
stateLocked | true
state | "livingroom"
2 |  
attributes | {}
id | "bluetooth-classic-inquiries-switch"
name | "livingroom Bluetooth Inquiries"
distributed | false
stateLocked | true
state | true
3 |  
attributes | {}
id | "bluetooth-classic-64-d2-c4-7a-72-c2-tracker"
name | "Apple Watch Jeroen BTC Tracker"
distributed | true
stateLocked | true
state | "home"
4 |  
attributes |  
distance | 0.8
lastUpdatedAt | "2021-10-04T20:23:40.505Z"
id | "bluetooth-classic-64-d2-c4-7a-72-c2"
name | "Apple Watch Jeroen BTC Room Presence"
distributed | true
stateLocked | true
distances |  
office |  
lastUpdatedAt | "2021-10-04T20:23:22.754Z"
distance | 25.2
outOfRange | false
livingroom |  
lastUpdatedAt | "2021-10-04T20:23:40.505Z"
distance | 0.8
outOfRange | false
bedroom |  
lastUpdatedAt | "2021-10-04T18:00:51.055Z"
distance | 21
outOfRange | false
diningroom |  
lastUpdatedAt | "2021-10-04T20:23:30.411Z"
distance | 10.6
outOfRange | false
timeout | 80
state | "livingroom"
5 |  
attributes | {}
id | "ble-5bcf9b14-7592-42a7-a2b8-eabb1b80f5c9-tracker"
name | "Iphone Jeroen BLE Tracker"
distributed | true
stateLocked | true
state | "not_home"
6 |  
attributes |  
lastUpdatedAt | "2021-10-04T19:58:54.893Z"
id | "ble-5bcf9b14-7592-42a7-a2b8-eabb1b80f5c9"
name | "Iphone Jeroen BLE Room Presence"
distributed | true
stateLocked | true
distances |  
livingroom |  
lastUpdatedAt | "2021-10-04T19:57:06.895Z"
distance | 1.4
outOfRange | false
office |  
lastUpdatedAt | "2021-10-04T19:36:35.845Z"
distance | 26.3
outOfRange | false
diningroom |  
lastUpdatedAt | "2021-10-04T19:57:06.749Z"
distance | 12.3
outOfRange | false
timeout | 60
measuredValues |  
livingroom |  
rssi | -61.938376423642765
measuredPower | -59
office |  
rssi | -91.37491568808068
measuredPower | -59
diningroom |  
rssi | -82.69722207600223
measuredPower | -59
state | "not_home"

</div></div></div></div>
</body>
</html>`

It seems the companion app is not functioning as it should be, or ios 15 is messing with background polling of bluetooth. 

I hope someone is reading this - i would really like this feature to work. If not I will probably go back to bluetooth classic, even though it is slow. BLE seemed nice and quick, but useless if the app has to be open all the time. .

**Comment by JeroenTuinstra** [comment]
Turned out that somehow once in a while Raspberry Pi resets the hciconfig and renumbers the attached devices: 
`● room-assistant.service - room-assistant service
   Loaded: loaded (/etc/systemd/system/room-assistant.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-10-04 19:59:49 CEST; 2h 30min ago
 Main PID: 350 (node)
    Tasks: 14 (limit: 2059)
   CGroup: /system.slice/room-assistant.service
           └─350 node /usr/bin/room-assistant

Oct 04 22:29:19 livingroom room-assistant[350]: Can't get device info: No such device
Oct 04 22:29:34 livingroom room-assistant[350]: 04/10/2021, 22:29:34 - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
Oct 04 22:29:34 livingroom room-assistant[350]: 04/10/2021, 22:29:34 - error - undefined: Command failed: hciconfig hci0 reset
Oct 04 22:29:34 livingroom room-assistant[350]: Can't get device info: No such device
Oct 04 22:29:49 livingroom room-assistant[350]: 04/10/2021, 22:29:49 - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
Oct 04 22:29:49 livingroom room-assistant[350]: 04/10/2021, 22:29:49 - error - undefined: Command failed: hciconfig hci0 reset
Oct 04 22:29:49 livingroom room-assistant[350]: Can't get device info: No such device
Oct 04 22:30:04 livingroom room-assistant[350]: 04/10/2021, 22:30:04 - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
Oct 04 22:30:04 livingroom room-assistant[350]: 04/10/2021, 22:30:04 - error - undefined: Command failed: hciconfig hci0 reset
Oct 04 22:30:04 livingroom room-assistant[350]: Can't get device info: No such device
`
With these errors I did a hciconfig command with this result: 
`hci2:   Type: Primary  Bus: USB
        BD Address: 00:1A:7D:DA:71:13  ACL MTU: 310:10  SCO MTU: 64:8
        UP RUNNING
        RX bytes:624 acl:0 sco:0 events:37 errors:0
        TX bytes:945 acl:0 sco:0 commands:37 errors:0

hci1:   Type: Primary  Bus: UART
        BD Address: B8:27:EB:1D:A7:88  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING
        RX bytes:94980 acl:452 sco:0 events:3027 errors:0
        TX bytes:21560 acl:452 sco:0 commands:1416 errors:0
`
Normally the UART bus is hci1 and the USB is hci0, but somehow, and this has happened before the devices seemed to have reset and gotten a new hci number. I noticed this as the previous post showed that the last update in the livingroom was "2021-10-04T19:57:06.895Z".  While I posted it at around 22:30  ... so it hadn't received an update for over 2 hours. When i logged into the raspberry pi I saw the above mentioned errors. 
A reboot sorts this most of the time out, but why it moves the hci value up, i don't know. 

If anyone can tell me how to get the logs for this, I am more than willing to get them - just don't know how.

**Comment by JeroenTuinstra** [comment]
So after a reboot and having the right order of hci devices back in the Raspberry pi. The BLE companion app is no longer updating. It seems the app has to be in the foreground in order to give updates. Even though it has been given all rights in the settings of the Iphone.

This is a copy of entities page and it shows again the distance as 1.2 and status "not_home" and an update "2021-10-04T21:00:05.746Z", which is when it got rebooted and then shortly after that no more updates as the app is in the background.

```
<html><body>
<!--StartFragment--><div id="content"><div class="tabs "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item json is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"></div></div></div></div><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"><div class="devtools-separator"></div><input class="searchBox devtools-filterinput" placeholder="Filter JSON"></div><div class="panelContent">

  |  
-- | --
0 |  
attributes |  
nodes |  
0 | "office"
1 | "diningroom"
2 | "bedroom"
3 | "livingroom"
id | "status-cluster-size"
name | "livingroom Cluster Size"
distributed | false
stateLocked | true
state | 4
1 |  
attributes |  
quorumReached | true
id | "status-cluster-leader"
name | "livingroom Cluster Leader"
distributed | false
stateLocked | true
state | "livingroom"
2 |  
attributes | {}
id | "bluetooth-classic-inquiries-switch"
name | "livingroom Bluetooth Inquiries"
distributed | false
stateLocked | true
state | true
3 |  
attributes | {}
id | "bluetooth-classic-64-d2-c4-7a-72-c2-tracker"
name | "Apple Watch Jeroen BTC Tracker"
distributed | true
stateLocked | true
state | "home"
4 |  
attributes |  
distance | 3.3
lastUpdatedAt | "2021-10-04T21:11:40.497Z"
id | "bluetooth-classic-64-d2-c4-7a-72-c2"
name | "Apple Watch Jeroen BTC Room Presence"
distributed | true
stateLocked | true
distances |  
office |  
lastUpdatedAt | "2021-10-04T21:10:34.100Z"
distance | 28.3
outOfRange | false
diningroom |  
lastUpdatedAt | "2021-10-04T21:12:01.133Z"
distance | 10.5
outOfRange | false
livingroom |  
lastUpdatedAt | "2021-10-04T21:11:40.497Z"
distance | 3.3
outOfRange | false
timeout | 80
state | "livingroom"
5 |  
attributes | {}
id | "ble-5bcf9b14-7592-42a7-a2b8-eabb1b80f5c9-tracker"
name | "Iphone Jeroen BLE Tracker"
distributed | true
stateLocked | true
state | "not_home"
6 |  
attributes |  
lastUpdatedAt | "2021-10-04T21:00:05.746Z"
id | "ble-5bcf9b14-7592-42a7-a2b8-eabb1b80f5c9"
name | "Iphone Jeroen BLE Room Presence"
distributed | true
stateLocked | true
distances |  
livingroom |  
lastUpdatedAt | "2021-10-04T20:58:21.976Z"
distance | 1.2
outOfRange | false
diningroom |  
lastUpdatedAt | "2021-10-04T20:58:03.040Z"
distance | 10.8
outOfRange | false
timeout | 60
measuredValues |  
livingroom |  
rssi | -60.29865028815632
measuredPower | -59
diningroom |  
rssi | -81.37917449927619
measuredPower | -59
state | "not_home"

</div></div></div></div><!--EndFragment-->
</body>
</html>
```

Anyone any suggestions as how to get the BLE companion app to keep giving updates despite it being closed? Or is the companion app just not working?

**Comment by PeteBa** [comment]
I use the iOS App and it updates both in the foreground and background. I have been caught out when power cycling the iphone as iOS does not automatically start applications and I have to remember to manually start the companion app.

I have, however, also noticed that sometimes updates from my iPhone unexpectedly stop and the iPhone state goes to `not_home` after the `timeout` period expires. This seems to be down to the companion app "freezing" rather than a problem with the room-assistant service running on the RPis. I am not sure why this happens but a power cycle of the iPhone and restart of the companion app seems to get the updates going again.

> This is a copy of entities page and it shows again the distance as 1.2 and status "not_home" and an update "2021-10-04T21:00:05.746Z", which is when it got rebooted and then shortly after that no more updates as the app is in the background.

Note that it is normal to have a "last known" distance even when status is `not_home`. In this case, the last BLE advertisement that room-assistance received was at 21:00:05 putting you in the livingroom but subsequently the `timeout` period expired and the state switched from the room to `not_home`.

**Comment by JeroenTuinstra** [comment]
The app doesn't freeze with me. It simply doesn't update any longer. Which makes the app completely useless.  
The time I mentioned, I was in the room - meaning it didn't update since that time. 

So basically I think I will switch back to classic, even though BLE is faster, it just doesn't work with an Iphone. And to me it seems, the ones creating the app are no longer supporting it - as no-one seems to respond to the issues.
