### ISSUE TITLE
Unable to install RA  Raspberry Pi 3 Model B Plus Rev 1.3

### ISSUE THREAD

**Issue by Merangle** [mKeRix/room-assistant#949]
**Describe the bug**
When installing RA from a fresh install (debian V11)  I get this message 

sudo npm i --global --unsafe-perm room-assistant
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.

changed 330 packages, and audited 331 packages in 6m

21 packages are looking for funding
  run `npm fund` for details

13 vulnerabilities (9 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

et 
pi@Parents:~ $ sudo npm fund
pi

**To reproduce**
Steps required to reproduce the issue.
follow the installation instructions 

Any advice ?

**Relevant logs**
Log output that correlates to the bug. You can get debug output with `room-assistant -v`.

```text
```

**Relevant configuration**
Paste the relevant parts of your configuration below.

```yaml
```

**Expected behavior**

**Environment**
 - room-assistant version: [e.g. 2.0.0]
 - installation type: [e.g. NodeJS, Docker, Hass.io]
 - hardware: [e.g. Raspberry Pi Zero W, NUC]
 - OS: [e.g. Linux, Windows, macOS]

**Additional context**

**Comment by JeroenTuinstra** [comment]
I think you need to update your raspbian first: 

`sudo apt update && sudo apt upgrade'

Reboot and upgrade NPM:

`sudo npm install -g npm@8.1.2`

And then continue the setup with: `sudo npm i --global --unsafe-perm room-assistant` 

And follow the next steps in the quide.

**Comment by Merangle** [comment]
It works !
Thanks
