### ISSUE TITLE
Home Assistant isn't picking up messages from MQTT from Room Assistant 

### ISSUE THREAD

**Issue by Shaun-Harrison** [mKeRix/room-assistant#95]
I have MQTT set up which is doing some other work which all works fine in Home Assistant

But now when I am trying to get Room Assistant to send messages to MQTT (Which works fine) they are not getting picked up in Home Assistant

I can see from the logs that home assistant is subscribing to the following topic 'room_presence/docker-room/+'
Which doesn't pick any messages up as the actual topic is 
'room_presence/docker-room/' 

I am using room assistant in docker on an rpi4 
This is my docker-compose 

    version: '2'
    services:
      room-assistant:
        image: mkerix/room-assistant:latest-arm32
        restart: always
        network_mode: host
        environment:
          SERVICES: 'console,mqtt,ble'
          ROOM: 'docker-room'
          #BLE
          BLE_WHITELIST: '["DEVICE_ID"]'

**Comment by mKeRix** [comment]
Could you share the sensor configuration you put into Home Assistant?

**Comment by Shaun-Harrison** [comment]
Hello

I managed to get this working after some debugging 

Here is the config that ended up working

    version: '2'
    services:
      room-assistant:
        image: mkerix/room-assistant:latest-arm32
        restart: always
        network_mode: host
        environment:
          SERVICES: 'console,mqtt,ble'
          ROOM: 'Dining Room'
          AUTO_DISCOVERY: 'true'
          #BLE
          BLE_WHITELIST: '["DEVICE_ID"]'
          BLE_CHANNEL: 'room_presence'
          BLE_UPDATE_FREQUENCY: 0

Then the Home Assistant config 

    #Room Presence - Tile Name
     sensor:
      - platform: mqtt_room
        state_topic: "room_presence"
        device_id: 'DEVICE_ID'
        name: 'Shaun Keys'
        away_timeout: '90'
