### ISSUE TITLE
room-assistant after a while stops recognizing any beacons.

### ISSUE THREAD

**Issue by oleggold** [mKeRix/room-assistant#96]
I have two raspberry pi zero w running room-assistant.
One of them works flawlessly. The other works for about an hour or so after reboot and then stops recognizing beacons presence. The units have exactly the same image of stretch with the following changes:
1. Host names are different
2. Room names in local.json are different.

Could you please let me know how I can debug this?

Thank you.

**Comment by mKeRix** [comment]
Two things I can think of that might cause this:

1. room-assistant could still be receiving the BLE advertisements, but not forward them to the MQTT server correctly anymore. You can check this by enabling the console publisher and just checking the output. A while back one of my Pis kept dropping out of the WiFi randomly, which caused intermittent reporting issues like this.
2. A hardware or a system dependency issue - are all the packages up-to-date and so on? The best way to rule out hardware specific issues that I can think of right now would be to fire up a new screen/tmux session with `sudo hcitool lescan --duplicates` and then leave it running for a while. If that continues reporting BLE advertisements long after room-assistant would have usually stopped we would need to look deeper.
