### ISSUE TITLE
Can't detect android with ble

### ISSUE THREAD

**Issue by soloam** [mKeRix/room-assistant#98]
Hello, did anyone had success detecting a android with room assistant ble? I tried several app to emulate a ibeacon, I can detect the ibeacon with other scan apps, but it does not appear on the room assistant feed, I can see other devices, just not my android!

Thank you

**Comment by mKeRix** [comment]
Hey there,

can you see your Android beacons on the Raspberry when you type `hcitool lescan` into the command line? room-assistant should put out the same things you can see with that command. Do you get any other output when turning on room-assistant?

**Comment by soloam** [comment]
Hello, I'll try that out on Friday at the moment I'm away from home! On my room assistant I can see several other devices, like my tv and my Google Home for example! I can't see my android phone beacon, but if I pick up other phone with a beacon scanner I can see it there! I'll try the command line and report back on Friday! Thank you

**Comment by soloam** [comment]
Hello, I tested out and yes, I can detect the mobile beacon with the command "hcitool lescan", I can see the mobile mac address appearing up in the console! (I used other mobile to show me the mac address and UUID, but yes, it appears!

**Comment by mKeRix** [comment]
Alright, thanks for checking! Could you maybe post your config here (just the services and the ble part should be enough). And just out of interest: do you have the console publisher enabled as well, just for debugging?

**Comment by soloam** [comment]
this is my local.json


```
{
    "services": [
        "mqtt",
        "ble",
        "shell",
        "console"
    ],
    "room": "garage",
    "autoDiscovery": false,
    "mqtt": {
        "url": "mqtt://mosquitto.local:1883",
        "rejectUnauthorized": false
    },
    "console": {
        "enabled": true
    },
    "ble": {
        "channel": "room_presence",
        "useAddress": false,
        "whitelist": [],
        "whitelistRegex": false,
        "txPowerOverride": {},
        "maxDistance": 5,
        "updateFrequency": 5,
        "processIBeacon": true,
        "onlyIBeacon": false,
        "majorMask": "0xFFFF",
        "minorMask": "0xFFFF"
    }
}
```

**Comment by mKeRix** [comment]
Since you're seeing other devices on room-assistant my last guess would be that your phone advertisements are received, but just not recognized as iBeacons. The check for this currently is [here](https://github.com/mKeRix/room-assistant/blob/master/services/ble.service.js#L79) in the code. In that case you would see the device, but not with the configured iBeacon id. It also may not show a name. On Linux you would most likely see it with its Bluetooth MAC address.

**Comment by Shaun-Harrison** [comment]
Hi there

Having the same issue on RPI4 although when doing hcitool lescan i don't see my phones mac - I have a pixel 3 which does support ble

Any suggestions?

**Comment by soloam** [comment]
I also have a Pixel 3, try the app BeaconScope from play store!

**Comment by Alfiegerner** [comment]
> I also have a Pixel 3, try the app BeaconScope from play store!

I use beaconscope too! Have you found a way to reliably restart it or keep it running? My galaxy S10 kills it from time to time and I have a kludge tasker restart task that reopens the app.

**Comment by Shaun-Harrison** [comment]
> I also have a Pixel 3, try the app BeaconScope from play store!

Hello! Don't come across many other pixel users!
Do you have an example of how you've set up the app? 
For Room assistant I use whitelist, what would go inside there?



> > I also have a Pixel 3, try the app BeaconScope from play store!
> 
> I use beaconscope too! Have you found a way to reliably restart it or keep it running? My galaxy S10 kills it from time to time and I have a kludge tasker restart task that reopens the app.

Unsure on how samsung does it, but for pixel there is an option to stop the phone optimising apps with regards to battery, essentially if optimising is enabled for the app if its not in use it will get killed off
