### ISSUE TITLE
Running room-assistant for the first time after install on rpi- zero 2W produces following error

### ISSUE THREAD

**Issue by AbhiOommen** [mKeRix/room-assistant#987]
When starting room assiatnt for the first time after install on rpi zero 2W it errors out.

```
pi@office:~/room-assistant $ room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
07/12/2021, 19:10:15 - info - IntegrationsModule: Loading integrations: home-assistant, bluetooth-classic, bluetooth-low-energy
07/12/2021, 19:10:16 - info - NestFactory: Starting Nest application...
07/12/2021, 19:10:16 - error - ExceptionHandler: Cannot find module '@mkerix/noble'
Require stack:
- /opt/nodejs/lib/node_modules/room-assistant/dist/integration-support/bluetooth/bluetooth.service.js
- /opt/nodejs/lib/node_modules/room-assistant/dist/integrations/bluetooth-classic/bluetooth-classic.service.js
- /opt/nodejs/lib/node_modules/room-assistant/dist/integrations/bluetooth-classic/bluetooth-classic.module.js
- /opt/nodejs/lib/node_modules/room-assistant/dist/integrations/integrations.module.js
- /opt/nodejs/lib/node_modules/room-assistant/dist/app.module.js
- /opt/nodejs/lib/node_modules/room-assistant/dist/main.js
- /opt/nodejs/lib/node_modules/room-assistant/bin/room-assistant.js
```

```global:
  instanceName: office
  integrations:
    - homeAssistant
    - bluetoothClassic
    - bluetoothLowEnergy
homeAssistant:
  mqttUrl: 'mqtt://homeassistant.local:1883'
  mqttOptions:
    username: mqtt
    password: mypasswd
bluetoothClassic:
  addresses:
    - 1stdevice
    - 2nddevice
bluetoothLowEnergy:  
```

**Comment by AbhiOommen** [comment]
Bump - anyone?

**Comment by townsmcp** [comment]
I found following the RPI 3 install and using NodeJS 14 rather than 16 worked

**Comment by AbhiOommen** [comment]
Thanks. But how did you switch the versions. I am using the wget and piping into bash for the pi zero install.

`wget -O - https://gist.githubusercontent.com/mKeRix/88b7b81e9bca044f74de1dc51696efb2/raw/799a20bca44cc61d8f8ae93878f2f28af8365a69/getNodeLTS.sh | bash`

Do I copy and edit the shell script file and change something in there?

**Comment by townsmcp** [comment]
@AbhiOommen i rebuilt my RPI zero w 2 last night. I found the following thread very helpful:

https://github.com/mKeRix/room-assistant/discussions/967

Basically, follow the normal RPI zero w install procedure but instead of doing
`sudo npm i --global --unsafe-perm room-assistant ` to install RA, replace it with:
`sudo npm i --global --unsafe-perm --verbose --foreground-scripts room-assistant `

**Comment by AbhiOommen** [comment]
> @AbhiOommen i rebuilt my RPI zero w 2 last night. I found the following thread very helpful:
> 
> #967
> 
> Basically, follow the normal RPI zero w install procedure but instead of doing `sudo npm i --global --unsafe-perm room-assistant ` to install RA, replace it with: `sudo npm i --global --unsafe-perm --verbose --foreground-scripts room-assistant `
> 
> But to answer your question, when performing the RPI 3 install, replace: `curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash - ` with `curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - `

THANK YOU! I believe this worked for me as well. Appreciate the help, very interesting that verbose made it work.

One for question what is the right format to enter bluetooth mac addresses in the config for RA - I entered them in small letters and without the colon signs, but getting this error now when I start room-assistant

```
21/12/2021, 16:57:35 - error - undefined: "bluetoothClassic.addresses[0]" does not match the required MAC address format [Value: "ab12cd34efg7"].
21/12/2021, 16:57:35 - error - undefined: "bluetoothClassic.addresses[1]" does not match the required MAC address format [Value: "xyd6sfa5h42h"].
```

**Comment by AbhiOommen** [comment]
Never mind - figured it out. Thank you again.
